### ISSUE TITLE
RL10-B2 Issues

### ISSUE THREAD

**Issue by VenomousRequiem** [CobaltWolf/Bluedog-Design-Bureau#100]
It seems the gimbal doesn't work, and the engine's thrust seems to be offset somehow.

**Comment by CobaltWolf** [comment]
Honestly I might not include it in the upcoming update - the extension mechanism needs to be remodeled. Thoughts? @VenomousRequiem  @jsolson

**Comment by jsolson** [comment]
Keep it.

I just noticed the Isp is wrong in the cryo version of this engine.

**Comment by CobaltWolf** [comment]
The engine doesn't work though

**Comment by jsolson** [comment]
Worked fine for me yesterday.

**Comment by Cowboy-WY** [comment]
Thrust seems centered, but gimbal animation is not functional
![gimbal](https://cloud.githubusercontent.com/assets/20691292/17340635/4b7e65a0-58ae-11e6-8ba2-1fff0d9eea74.PNG)

**Comment by CobaltWolf** [comment]
I'm still not sure why. I still don't want to include this part in the next release anyways.

**Comment by VenomousRequiem** [comment]
Did this ever get looked at?

**Comment by CobaltWolf** [comment]
Oh fuck you

-----Original Message-----

**Comment by CobaltWolf** [comment]
^ Where do we stand on this? We can hide it so it doesn't cause issues. The engine bell texture needs to be played with anyways.
