### ISSUE TITLE
Mariner 10 Solar Panels track sun internally but not externally

### ISSUE THREAD

**Issue by GoldForest383** [CobaltWolf/Bluedog-Design-Bureau#1005]
Internally - Right-Click Menu
Externally - Model does not move. 

https://i.imgur.com/8oPdjTV.jpg

**Comment by jsolson** [comment]
They work just fine for me.

![screenshot8](https://user-images.githubusercontent.com/16825376/100292830-985bb180-2f4f-11eb-9bed-b680d12dd759.png)

**Comment by GoldForest383** [comment]
I'll update/fresh install BDB, but the model wasn't turning for me when I took that screenshot.

**Comment by GoldForest383** [comment]
Huh, well, it's working now after updating. It definitely wasn't working before though.

**Comment by GoldForest383** [comment]
The issue is still there. I found out the issue though. 

The angled solar panels will model track, but the straight panels won't model track.

**Comment by zorg2044** [comment]
I need to rearrange some of the hierarchy.
