### ISSUE TITLE
OAO-WEP Ultraviolet Instrument Package showing Deploy/Retract option twice.

### ISSUE THREAD

**Issue by computercat04** [CobaltWolf/Bluedog-Design-Bureau#1006]
![screenshot8](https://user-images.githubusercontent.com/59670938/99916634-a3a9a580-2ce1-11eb-8c76-eded6c15de0c.png)
![screenshot9](https://user-images.githubusercontent.com/59670938/99916637-aad0b380-2ce1-11eb-8c61-d79f3877a1c0.png)

**Comment by zorg2044** [comment]
Unfortunately this is a side effect of having 2 science experiment modules on an animated part. no workaround I know of.

**Comment by computercat04** [comment]
@zorg2044 Ok
