### ISSUE TITLE
Fatal Showstopper Errors When Using BD Parts with Tweakscale

### ISSUE THREAD

**Issue by DomPrice** [CobaltWolf/Bluedog-Design-Bureau#1009]
From the log:
-----------------------------------------------------------
[EXC 16:44:59.142] NullReferenceException: Object reference not set to an instance of an object
	InfernalRobotics.Gui.UIAssetsLoader.LoadBundleAssets () (at <c6483ccff18e4212baa08bf3e44d5da6>:0)
	InfernalRobotics.Gui.UIAssetsLoader+<LoadBundle>d__14.MoveNext () (at <c6483ccff18e4212baa08bf3e44d5da6>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
[LOG 16:44:59.249] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.LR87.mod1 (Prometheus-I-640 "Perses" Liquid Engine).
[LOG 16:44:59.249] [TweakScale] ERROR: **FATAL** Part bluedog.LR87.mod1 (Prometheus-I-640 "Perses" Liquid Engine) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.249] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.LR87.mod2 (Prometheus-II-675 "Pallas" Liquid Engine).
[LOG 16:44:59.249] [TweakScale] ERROR: **FATAL** Part bluedog.LR87.mod2 (Prometheus-II-675 "Pallas" Liquid Engine) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.249] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.LR87.mod4 (Prometheus-IV-700 "Astreous" Liquid Engine).
[LOG 16:44:59.250] [TweakScale] ERROR: **FATAL** Part bluedog.LR87.mod4 (Prometheus-IV-700 "Astreous" Liquid Engine) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.254] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.LR91.mod1 (Prometheus-I-200 "Leto" Liquid Engine).
[LOG 16:44:59.254] [TweakScale] ERROR: **FATAL** Part bluedog.LR91.mod1 (Prometheus-I-200 "Leto" Liquid Engine) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.254] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.LR91.mod2 (Prometheus-II-250 "Lelantos" Liquid Engine).
[LOG 16:44:59.254] [TweakScale] ERROR: **FATAL** Part bluedog.LR91.mod2 (Prometheus-II-250 "Lelantos" Liquid Engine) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.254] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.LR91.mod4 (Prometheus-IV-300 "Asteria" Liquid Engine).
[LOG 16:44:59.254] [TweakScale] ERROR: **FATAL** Part bluedog.LR91.mod4 (Prometheus-IV-300 "Asteria" Liquid Engine) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.258] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan1.15mDecoupler (Prometheus-I-15 Stack Decoupler).
[LOG 16:44:59.258] [TweakScale] ERROR: **FATAL** Part bluedog.Titan1.15mDecoupler (Prometheus-I-15 Stack Decoupler) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.259] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan1.FuelTank1 (Prometheus-I-4000 Liquid Fuel Tank).
[LOG 16:44:59.259] [TweakScale] ERROR: **FATAL** Part bluedog.Titan1.FuelTank1 (Prometheus-I-4000 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.259] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan1.FuelTank2 (Prometheus-I-1300 Liquid Fuel Tank).
[LOG 16:44:59.259] [TweakScale] ERROR: **FATAL** Part bluedog.Titan1.FuelTank2 (Prometheus-I-1300 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.259] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan1.BigAdapterMedium (Prometheus-I-340 Liquid Fuel Tank).
[LOG 16:44:59.259] [TweakScale] ERROR: **FATAL** Part bluedog.Titan1.BigAdapterMedium (Prometheus-I-340 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.259] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan1.BigAdapterShort (Prometheus-I-140 Structural Adapter).
[LOG 16:44:59.259] [TweakScale] ERROR: **FATAL** Part bluedog.Titan1.BigAdapterShort (Prometheus-I-140 Structural Adapter) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.259] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan1.SmallAdapter (Prometheus-I-160 Structural Adapter).
[LOG 16:44:59.259] [TweakScale] ERROR: **FATAL** Part bluedog.Titan1.SmallAdapter (Prometheus-I-160 Structural Adapter) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.260] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan1.NoseProbe (Prometheus-I "Crius" Anterior Probe Core).
[LOG 16:44:59.260] [TweakScale] ERROR: **FATAL** Part bluedog.Titan1.NoseProbe (Prometheus-I "Crius" Anterior Probe Core) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.261] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan2.1875mDecoupler (Prometheus-II-875 Stack Decoupler).
[LOG 16:44:59.261] [TweakScale] ERROR: **FATAL** Part bluedog.Titan2.1875mDecoupler (Prometheus-II-875 Stack Decoupler) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.261] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan2.FuelTank1 (Prometheus-II-3000 Liquid Fuel Tank).
[LOG 16:44:59.262] [TweakScale] ERROR: **FATAL** Part bluedog.Titan2.FuelTank1 (Prometheus-II-3000 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.262] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan2.FuelTank2 (Prometheus-II-1900 Liquid Fuel Tank).
[LOG 16:44:59.262] [TweakScale] ERROR: **FATAL** Part bluedog.Titan2.FuelTank2 (Prometheus-II-1900 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.262] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan2.FuelTank3 (Prometheus-II-1100 Liquid Fuel Tank).
[LOG 16:44:59.262] [TweakScale] ERROR: **FATAL** Part bluedog.Titan2.FuelTank3 (Prometheus-II-1100 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.262] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan2.FuelTank4 (Prometheus-II-600 Liquid Fuel Tank).
[LOG 16:44:59.262] [TweakScale] ERROR: **FATAL** Part bluedog.Titan2.FuelTank4 (Prometheus-II-600 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.265] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan4.FuelTank1 (Prometheus-IV-2800 Liquid Fuel Tank).
[LOG 16:44:59.265] [TweakScale] ERROR: **FATAL** Part bluedog.Titan4.FuelTank1 (Prometheus-IV-2800 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.266] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan4.FuelTank2 (Prometheus-IV-3300 Liquid Fuel Tank).
[LOG 16:44:59.266] [TweakScale] ERROR: **FATAL** Part bluedog.Titan4.FuelTank2 (Prometheus-IV-3300 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.266] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan4.FuelTank3 (Prometheus-IV-1700 Liquid Fuel Tank).
[LOG 16:44:59.266] [TweakScale] ERROR: **FATAL** Part bluedog.Titan4.FuelTank3 (Prometheus-IV-1700 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.267] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.SRB2seg (Prometheus-III-2 "Los" Solid Rocket Booster).
[LOG 16:44:59.267] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.SRB2seg (Prometheus-III-2 "Los" Solid Rocket Booster) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.267] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.SRB3seg (Prometheus-IV-3 "Selene" Solid Rocket Booster).
[LOG 16:44:59.267] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.SRB3seg (Prometheus-IV-3 "Selene" Solid Rocket Booster) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.268] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.SRB5seg (Prometheus-III-5 "Eos" Solid Rocket Booster).
[LOG 16:44:59.268] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.SRB5seg (Prometheus-III-5 "Eos" Solid Rocket Booster) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.269] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.SRB7seg (Prometheus-III-7 "Helios" Solid Rocket Booster).
[LOG 16:44:59.269] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.SRB7seg (Prometheus-III-7 "Helios" Solid Rocket Booster) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.269] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.SRB7segStack (Prometheus-III-7S "Lios" Solid Rocket Booster).
[LOG 16:44:59.270] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.SRB7segStack (Prometheus-III-7S "Lios" Solid Rocket Booster) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.270] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.SRBnose (Prometheus-III Separatron Nosecone).
[LOG 16:44:59.270] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.SRBnose (Prometheus-III Separatron Nosecone) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.270] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.SRBseparator (Prometheus-III Separatron XL).
[LOG 16:44:59.271] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.SRBseparator (Prometheus-III Separatron XL) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.271] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.TranstageEngine (Prometheus-T-51 "Metis" Liquid Engine).
[LOG 16:44:59.272] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.TranstageEngine (Prometheus-T-51 "Metis" Liquid Engine) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0
[LOG 16:44:59.272] [TweakScale] WARNING: **FATAL** Found a showstopper problem on bluedog.Titan.TranstageTank (Prometheus-T-400 Liquid Fuel Tank).
[LOG 16:44:59.272] [TweakScale] ERROR: **FATAL** Part bluedog.Titan.TranstageTank (Prometheus-T-400 Liquid Fuel Tank) has a fatal problem due having duplicated properties - see issue [#34]( https://github.com/net-lisias-ksp/TweakScale/issues/34 ). at error:0

**Comment by zorg2044** [comment]
These so called showstopper errors are usually due to more than 1 MM patch trying to configure a part. The tweakscale configs within BDB do not have any duplicate patching issues so this is most likely caused bu some 3rd party mod or patch. I would suggest following up with the tweakscale dev to identify the issue and a solution.
