### ISSUE TITLE
Nimbus-ITHIR Scanning Infrared Radiometer: The Retract button seems useless. Only the Deploy one works.

### ISSUE THREAD

**Issue by computercat04** [CobaltWolf/Bluedog-Design-Bureau#1014]
![screenshot18](https://user-images.githubusercontent.com/59670938/103561192-75e27f80-4e8f-11eb-8703-d38045c4041c.png)

**Comment by zorg2044** [comment]
I think this is the case for animations where the end point is the same as start point. I think its just how it works. Doesnt affect the usage so I think its fine.
