### ISSUE TITLE
Titan IIIC fairing is broken. (.craft file.)

### ISSUE THREAD

**Issue by computercat04** [CobaltWolf/Bluedog-Design-Bureau#1016]
![screenshot16](https://user-images.githubusercontent.com/59670938/104138939-311e8300-537e-11eb-87ce-b984ca92f97a.png)

**Comment by zorg2044** [comment]
github or release?

**Comment by computercat04** [comment]
> github or release?

GitHub.

**Comment by zorg2044** [comment]
I didnt see a problem. The craft file has been updated regardless.
