### ISSUE TITLE
Titan CT3 and IV need additional Engine variant

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1018]
For consideration;  Both the Titan CT3 and Titan IV flew on LR87-AJ-11A and LR91-AJ-11A engines.   
These engines are both lighter than their predecessors.   This was done by removing the man rating items that were originally designed into these engines for MOL.   

This results in an approximate 150kg mass reduction on the LR87 and a 50kg mass reduction on the LR91 at ksp scale.   

The LR87-11A has 13% more thrust at the same isp.    The LR91-11A has 5% more thrust and a +2 to its Vacuum ISP.   The Thrust change is partially a result of removing man-rating from the engines.   This can also be seen in the LR87-AJ-7 for the Titan II GLV...  the AJ-7s were of a lower thrust than the AJ-5s they were modified from.    The rest of the thrust change came from a slight re-design to the Turbopump machinery to improve reliability which had the benefit of increasing fuel flow slightly.

I suggest the appropriate upgrades be unlocked at the same time as the Titan IV upper stage tanks.

If these added modes are added to the engines, I suggest they would need to propagate to both LR91-AJ-11 engines (single and 4 vernier) as well as the LR87-AJ-11 single bell engine.

**Comment by zorg2044** [comment]
@Pappystein do you have a reliable source you can share for these engine stats? If so we can add this in.

**Comment by Pappystein** [comment]
I will have to dig it up again (I have a LOT of pdfs on Titan.)   I will try to post them up on my next work weekend (So Thursday - Saturday)

**Comment by Pappystein** [comment]
I am missing a PDF that I think I re-named to be "System and Structural Design Improvements for the Titan Rockets"   It is not a primary source, but is well cited.  That one covered the lightening of the structure by ripping out all the old avionics and interfaces and upgrading both the CT3 and Titan IV to new interfaces (with the launch tower) as well as newer Avionics in each stage.

However, I do have the following:
https://www.researchgate.net/profile/Btc_Zandbergen/publication/279711349_Simple_mass_and_size_estimation_relationships_of_pump_fed_rocket_engines_for_launch_vehicle_conceptual_design/links/5598039308ae99aa62ca1d65/Simple-mass-and-size-estimation-relationships-of-pump-fed-rocket-engines-for-launch-vehicle-conceptual-design.pdf

The Above PDF matches the numbers I have in my notes and quoted above mostly, They cite Janes reference books,  as well an ESA article on foreign launch vehicles.   

http://www.b14643.de/Spacerockets/Specials/U.S._Rocket_engines/engines.htm

Spacerockets b14643.de actually has data for 3 different production lots of LR87 and LR91-AJ-11As, but both list them weirdly and give credit to most of them flying on Titan 23s and latter.

Of course, Space Launch Reports lists the Thrust of the 11A engines on the Titan IV and CT3 cards. However, Ed has a different thrust listed for the LR91-AJ-11A than most sources I have seen.

I will still be looking for the documents on mass reduction per stage (which I am suggesting be applied directly to the engine to prevent odd or "over-optimized" legoing in-game.

**Comment by Pappystein** [comment]
So I need to correct a mistake... If I am using the right scale factor for the upper stage engines I did not catch the Turbopump exhaust in looking at the LR91 thrust profile.   The 5% jump in performance is now a 1 or 2% jump for the LR91 but that does not include the +2 ISP gain at vacuum.   

Also I found the new Avionics used by both the CT3 and IV.   It was called WASS and it replaced every controller on the entire rocket. reducing the number of fault censors and overall reducing complexity.   Between the two stages, it was estimated to save a lot of mass when compared to a 34D, however a firm number eludes me ATM.

**Comment by Pappystein** [comment]
I started a RFI on NASASpaceflight.com....

https://forum.nasaspaceflight.com/index.php?topic=52981.0

**Comment by Pappystein** [comment]
As near as I can tell, the below data is correct.   Please note that the LR87-AJ-11 #14 and #15 are test engines and met the full design spec.   the quoted thrust of the AJ-11 is exactly 100KN higher.  I think THAT is an error (someone miss-typed and everyone after quoted the wrong data) but I can't prove it as every USAF document states the AJ-11 performed to specification (which is that of #14 and #15)     And every document that quotes max thrust quotes the higher number.



LR87-AJ-9 Titan IIIC:                2107kn
YLR87-AJ-11 #14 and #15              2313kn    
LR87-AJ-11 production on Titan 23B:  2353kn    
LR87-AJ-11 production on Titan 23D:  2413kn
LR87-AJ-11A on CT3 and Titan IV:     2429kn



Data on the LR91 is a lot easier...


LR91-AJ-5/7/9  444.8kn  @309.2 ISP(VAC)
LR91-AJ-11       444.8kn @318 ISP(VAC)
LR91-AJ-11A     467kn    @318 ISP(VAC)

**Comment by Pappystein** [comment]
And, sorry I never left the sources here....

PDF documents from USAF:   Titan IIIM 1st stage Propulsion Development, Titan 23D and Titan 34D users Guide

PDF Documents AIAA:  AIAA-86-1631

PDF Documents NASA: Titan IIIE and Centaur Summary

PDF Documents Lockheed Martin:  THIS IS COMMERCIAL TITAN INC (Martin Marietta 1991)

With the exception of the AIAA document, all are available in either L2 or on the USAF DCIT (?)server or the NTRS server for NASA.
