### ISSUE TITLE
Titan I LR87-AJ-3 appears to have minor textureing issues when the "Titan 3" SRM skirt is chosen as it's B9PS option

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1019]
Two pictures from the same launch.  The "stand" attachment points in the first image are glowing red (this is with the Titan 3 SRM skirt on the Titan I LR87 engine!)   
https://i.imgur.com/Wbr3phX.jpg

and at a slightly different angle, the same 4 points are glowing white

https://i.imgur.com/UrekXgU.jpg

This is on the Dev build (about 2 weeks old now, not the most current as I post this.)

**Comment by Pappystein** [comment]
Here is the same set of parts in the VAB with a pretty extreme closeup

https://i.imgur.com/GZARah3.jpg

**Comment by CobaltWolf** [comment]
Looks like those were some old meshes that accidentally got included in the export... easy fix I hope! :)

**Comment by zorg2044** [comment]
Verified its ok now
