### ISSUE TITLE
Saturn S-IC Slightly Inaccurate Texture

### ISSUE THREAD

**Issue by TCORPStudios** [CobaltWolf/Bluedog-Design-Bureau#1027]
The S-IC in the mod has a black ring on the tank above the stripes, seemingly modeled after the S-IC on the SA-500F Test Article rather than the later S-IC, which doesn't have a black ring.
If you are aiming for accuracy, please consider updating the textures a bit.
If I'm just talking out of my ass or the current design was intended for kerbalisation, then this isn't an issue.

**Comment by zorg2044** [comment]
These parts are being complete remade for the next major update. The level of fidelity and accuracy will be much higher :)
