### ISSUE TITLE
Thor Engine mount forced clipping???

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1031]
The Thor engine mount has no visible top node.

This picture is where the models say they should attach (I have left a tiny space so you can see the node on the tank is in the correct place
https://i.imgur.com/xnJCiMI.jpg

and here is the engine right before it actually attachs to the node... you can see the overall pretty easily here:

https://i.imgur.com/p0liqfW.jpg

**Comment by biohazard15** [comment]
Cannot confirm that on 1.10.1 and latest build.

This looks like a "bug" that appeared some months ago, when Cobalt fixed Thor tank lengths. This led to same exact clipping in all old Thor-based crafts, which had to be rebuild (partially, at least). Try to rebuild 1st stage from scratch.

**Comment by zorg2044** [comment]
yeah as far as I can see the parts are fine. might need a fresh install maybe?

**Comment by Pappystein** [comment]
I did a fresh install the day of the report.  I am deleting my BDB folder again and downloading the dev version will apprise in an hour or 3

**Comment by Pappystein** [comment]
I don't know what happened.   Like every time I update I delete my BDB folder and copy the new dev one in.   Everything is OK after this copy in.   Who knows!
