### ISSUE TITLE
1.11.1 - Lights not functional/stuck

### ISSUE THREAD

**Issue by beny873** [CobaltWolf/Bluedog-Design-Bureau#1032]
It appears the new lights that in 1.11.1 have bugged out the old lights. 

Animated lights are no longer functional. They appear to get stuck in a position and do not provide any illumination. 

Probably just a matter of updating the .cfgs to whatever format squad has set as the new standard. 

Edited by Zorg:

Affected parts

- [ ] bluedog_Apollo_Block2_DockingLight
- [ ] bluedog_Apollo_Block2_DockingLight2

**Comment by zorg2044** [comment]
Yes but the annoying thing is this would not be backwards compatible with 1.8 to 1.10 with which BDB is fine in all other areas. Looking at some possibilities though.

**Comment by beny873** [comment]
I'm not familiar with how module manager works exactly, but does it have the ability to detect the game version, or just installed mods?

I was just thinking it would be cool if there was a kind of MM patch that detected the build ID and patched the light CFGs based on those.

Short of that a whole new branch for pre 1.11.1 would have to be made. 

Come to think of it, the new inventory system isn't in 1.10 either which is another backwards compatibility issue. :/

**Comment by zorg2044** [comment]
MM cannot do version checking unfortunately. But I am looking into the possibility of testing for the presence of a stock part that would only be present in a specific version. Its hacky but I've seen some other modders resort to that.

**Comment by zorg2044** [comment]
Lights animated using ``ModuleLight`` are no longer functional. Lights using ``ModuleAnimateGeneric`` seem to work fine.

affected parts

bluedog_Apollo_Block2_DockingLight2

bluedog_Apollo_Block2_DockingLight

**Comment by zorg2044** [comment]
This fix should be backwards compatible
