### ISSUE TITLE
Need new craft files

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#1034]
- [x] Hexagon
- [x] Mariner 10
- [x] Strawman

**Comment by OrbitalManeuvers** [comment]
Looks like Mariner 10 was created on 1.11.1, while all the rest are 1.10.1 - so it shows as incompatible and won't load. Changing the version tag at the top allows it to load in 1.10.1.

**Comment by friznit** [comment]
Hexagon and Strawman done.

I'm in the process of scrubbing all my old craft files on the latest release of KSP so can share them once done, though they'll all be tagged 1.11.1 (I don't have a vanilla 1.10 install).  Easy enough to mass update to 1.10 though.

**Comment by zorg2044** [comment]
Everything should be set to 1.10.1 now.
