### ISSUE TITLE
Issues with LDC adapters

### ISSUE THREAD

**Issue by biohazard15** [CobaltWolf/Bluedog-Design-Bureau#1035]
These are not bugs per se - more like oversights.

1) Part description states that decoupler is disabled by default - this is not the case; it is actually enabled.

2) More serious problem - these parts have fuel crossfeed set to ON and no way to disable it. This effectively prevents their use as interstages if both stages use the same fuel.

**Comment by zorg2044** [comment]
I cant really test this today, but I believe both the above issues should be resolved now.
