### ISSUE TITLE
Dev Branch as of 23/02 Titan III LR-97 Plumes are.....gone

### ISSUE THREAD

**Issue by beny873** [CobaltWolf/Bluedog-Design-Bureau#1036]
Assuming it's got to do with the work being done on Waterfall. May even be intended for the time being, but just in case it isn't I thought I'd drop a note.

**Comment by zorg2044** [comment]
Whoops my bad, I was using it as a test bed for a UDMH+NTO plume being developed for Waterfall core. Fixed now
