### ISSUE TITLE
Kane-11 LIB EVA Floodlight not moving

### ISSUE THREAD

**Issue by Atomic-Thunder** [CobaltWolf/Bluedog-Design-Bureau#1042]
As the title says the light is stationary and will not move when turned on.
![Screenshot (73)](https://user-images.githubusercontent.com/80572093/111024533-32cefa80-8444-11eb-834f-0f8b2ae92ef7.png)

**Comment by zorg2044** [comment]
Is this with the current release? It should be fixed on the github master, will be included the next release. This was caused by KSP changing the light module.

**Comment by Atomic-Thunder** [comment]
This is the current version available through CKAN.
