### ISSUE TITLE
RL10 textures & Centaur interstage attachment

### ISSUE THREAD

**Issue by cmheisel** [CobaltWolf/Bluedog-Design-Bureau#1048]
Fresh install of BDB 1.72 on KSP 1.11 and everything seems to be working great, except for two Centaur issues:

1. RL-10s (all three parts) are missing textures and appear as gray models
2. The Centaur interstage will attach to the Centaur mounting plate only if no RL-10s were attached. If you attach the interstage, then attach engines, then unattach the interstage it will not re-attach.

Adding a screenshot of the RL-10s and [a link to the video of the attachment bug](https://www.dropbox.com/s/zgpw17qkn3g3r6r/Blue%20Dog%20Design%20-%20RL10%20texture%2C%20centaur%20interstage%20attachment.mp4?dl=0).
![Screenshot 2021-03-29 211458](https://user-images.githubusercontent.com/34786/112919444-1fbf5a00-90d5-11eb-8d69-04376dec9a72.png)

**Comment by zorg2044** [comment]
Please download the latest update v1.7.2 hotfix in which this was fixed.
