### ISSUE TITLE
Mercury Launch Escape System Rotation

### ISSUE THREAD

**Issue by Invaderchaos** [CobaltWolf/Bluedog-Design-Bureau#1049]
I was just fooling around with the Mercury parts today when I noticed something. This is the default rotation, straight from the part window.

![screenshot1731](https://user-images.githubusercontent.com/4949484/113753557-d920bf80-96d3-11eb-9b0c-0c19f5a18976.png)

Looks about fine. However, when rotated 180 degrees, this is what the LES looks like on the Mercury nose unit:

![screenshot1732](https://user-images.githubusercontent.com/4949484/113753568-db831980-96d3-11eb-9e47-bfd6faad1f2a.png)

As can be seen, the LES has a "plug" that covers the hole on the starboard side of the nose unit. I'm not 100% sure, but I would venture to assume this is supposed to be the correct orientation.

**Comment by zorg2044** [comment]
Fixed in a6a7bc1cc49271ba7ae0158f42407b75413efd04
