### ISSUE TITLE
I really don't want to call this an issue (or series of issues) so much as a list of things left incomplete and not on a roadmap

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1050]
Most of these things I am listing are Agena related:
1) Agena SOT (real size not the thin bois ) has no fairing or base to support it (2.5m diameter parts)
https://i.imgur.com/bAt4YgJ.png
I am guessing this was because there was no interstage similar to the Centaur one available in 2.5m that Agena could fit in

2) Agena B and D are missing their "Forward Rack"   This is between the fuel tank and TRU/GCU.   On Agena B this is where the extra analog clocks go to perform commands.  It is the Forward rack size that makes Agena B 4" longer than Agena D for what it is worth.  On Agena D it was present but empty except for the GATV (which got a battery there that is in BDB.)   Simple solution.   Re Use the Battery model as an empty spaceer for Agena B and Agena D and ignore the 4" lenght difference.  Apply correct colorschemes to both the Battery Module as well as the new "Forward Rack" part.

As the tankage is set up currently, it most closely resembles the ASCENT Agena which did away with the forward Rack as well as the TRU for a much simpler Guidance Interface (AKA hookups and a minimal ammount of Avionics to allow the payload to control Agena.) 

3) Agena A (this is probably a waste of time on this one given that really none were used except for KH sats...)  Missing Forward rack (half the thickness of B/D) and TRU/GCU is part cylindrical and part conical.   The early Keyhole cameras were mounted in the TRU, not in a separate part.   

Part 1 is problem causing because unless you are launching your SOT equiped Agena in a Titan CT3/IIIE/IV fairing you are not going to have a nice way to stack this stage.

Part 2 is a nusicance if you are looking for accurate Rocket stages.   PArt 3 is negligable but put here incase someone else asks why the AGena A TRU is not setup correctly.

**Comment by zorg2044** [comment]
``I am guessing this was because there was no interstage similar to the Centaur one available in 2.5m that Agena could fit in``

We have Delta III interstages. I think the length is sufficient. I'll see what we can do about a 2.5m skirt.

**Comment by Invaderchaos** [comment]
I do love Agena and would definitely consider doing a part or two to cover what’s missing. Personally, I’m not terribly interested in doing the 2.5m SOT and a forward rack for Agena A would be out of the picture as according to my understanding, it tapered inwards, meaning it would lead to a non-stock stack diameter, which I definitely want to avoid. However, a forward rack part is something I might have interest in doing.

While I do love Agena, I’m a little confused with some of the terminology surrounding Agena. Is Ascent Agena just an Agena D optimized for lifting separate payloads (OGO, Mariner, etc.) without a forward rack, and non-ascent Agena’s would launch with something like a Keyhole, and those would use a forward rack. For a while, I always thought the “rack” was represented by how the Agena tank extends a little above the top of its raceway

**Comment by Invaderchaos** [comment]
Also apologies for accidentally closing this issue, i misclicked.

**Comment by Pappystein** [comment]
Well see that is a problem.    I can find descriptions of the forward rack,   including written lengths..   however, no DIAGRAMS are easily findable.   

I will re-consult my sources and try to provide more information as I can

**Comment by Pappystein** [comment]
So, since data is sparse on the Forward rack sizes I will leave this note for data I have...   some may be contradictory.   I will clean it up in a later post:

Source: Agena Payload Users Handbook:   GCU + Forward rack is 40" tall (from drawing on pg 2-2) for "standard Agena (IIRC this is Agena B)  Forward rack starts at the joint of the Hemispherical endcap and the cylinder for the fuel tank!  This is under the cable raceway by a few inches.


Compilation of all produced Agena (gross descriptions):
https://ntrs.nasa.gov/search?q=19720013179     (drawings all depict Agena D except for lacking electronics)

**Comment by Invaderchaos** [comment]
So from what I understand the forward rack was present on all Agena D? Again, from at least what I can tell, I think that the forward rack might already be included in a way in our current part set, as part of the Agena tankage.

![5ABF4A6D-5980-400D-AA48-6A20A8770096](https://user-images.githubusercontent.com/4949484/155859617-e23761ee-8fa0-4255-bf35-2f4ca01e1e63.jpeg)
 
This image from one of your documents appears to show the raceway extending slightly into the forward rack. In our part set, we can see there is a small section above what would be considered the actual “fuel tank” that the raceway also similarly extends into:

![B8552FA9-04AC-40E7-B3D3-E9924AC2F542](https://user-images.githubusercontent.com/4949484/155859648-c9a25398-3168-40e9-a275-77c797288115.jpeg)

In many illustrations, the end of the tank is depicted right at the end of the raceway, or even right before it, as seen from one of the diagrams you sent: 

![9D4FD7B5-ED75-4035-8275-4712ACC98665](https://user-images.githubusercontent.com/4949484/155859789-34bebe5e-744d-4b84-bc87-4b0e59b9eedf.jpeg)

As seen in the BDB Agena D, the tankage extends noticeably above the raceway, in fact it does to a length almost as long as the TRU itself. I’ll have to check the length of the models to confirm, but I believe this might be the forward rack we are discussing. There might be some slight inaccuracies associated with this, including the extra 4” Agena B has, but if this truly is a stand in for the forward rack, I’d be happy to leave it at that.

**Comment by Invaderchaos** [comment]
In other news, I have found more info on the Agena Horizon Sensor. 
![2CCCCF3F-C4A7-4ABB-8E1C-10BB7A062CF6](https://user-images.githubusercontent.com/4949484/155860361-cd0454a8-bd3f-4c40-bea1-6e6bca313a4f.jpeg)
![A0AEB82C-9CEA-46F6-8C3E-AE18F88041DB](https://user-images.githubusercontent.com/4949484/155860363-eaa9a5ac-fe88-4ec6-865a-4163e7f0ec85.jpeg)
![65D592C7-05C1-4779-B5D5-3D2858423C33](https://user-images.githubusercontent.com/4949484/155860368-383d8f92-4e81-4d39-ba3b-a47c0e9b416d.jpeg)
![8298AEBE-62E1-4E3F-A128-C0162100DD7A](https://user-images.githubusercontent.com/4949484/155860366-c3c64d92-bdd5-4d98-b88f-f3e26528a55f.jpeg)
 The last image is from a Seasat document so I’m a little unsure if it’s something that would be on Agena or Seasat. Regardless, this might be something worth making. If you happen to have any additional info on it, please let me know.

**Comment by Invaderchaos** [comment]
Some more stuff on the Horizon Sensors:
![CCBED6C7-7983-423F-8381-208682206526](https://user-images.githubusercontent.com/4949484/155860880-d551598d-18fe-4f27-91eb-b4c09ef6d03b.png)
![42C17B72-9CE0-4461-9107-7C706734FB57](https://user-images.githubusercontent.com/4949484/155860936-6d38c13f-d162-4315-bb3c-b9da6d59d9e1.jpeg)
![010BC9B7-5C94-47C7-BF10-16D081FBD696](https://user-images.githubusercontent.com/4949484/155860938-e6760b47-1abb-4989-9eaf-0de4da0ba9e9.jpeg)
