### ISSUE TITLE
RL10 Textures Not Working

### ISSUE THREAD

**Issue by Jeronimo-GeoFS** [CobaltWolf/Bluedog-Design-Bureau#1052]
Hello, I recently uninstalled and reinstalled to get the latest version of the mod, and for some reason, the RL10 engine textures stopped working. The engines are gray now and this is the only engine affected. I've attached a screenshot showing what the textures look like. 
![image](https://user-images.githubusercontent.com/68471494/114475799-f4edff00-9bc6-11eb-8c9d-d75eecbcbdbe.png)

**Comment by zorg2044** [comment]
Did you download from github? I noticed for some reason the most recent hotfix (which fixes this issue specifically ) is below the older release. 

https://github.com/CobaltWolf/Bluedog-Design-Bureau/releases/tag/v1.7.2-hotfix

Alternatively you can also get it here.

https://spacedock.info/mod/442/Bluedog%20Design%20Bureau
