### ISSUE TITLE
SystemHeat patch for Lumber Gust 45 engine doesn't work

### ISSUE THREAD

**Issue by aristurtle** [CobaltWolf/Bluedog-Design-Bureau#1053]
The patch at https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/BD_Extras%20(No%20Warranty)/GameData/Bluedog_DB_Extras/BDB_nuclearEngines_systemHeat/NuclearEngines_SystemHeat.cfg tries to modify the part named "bluedog_STNP_45", but the part in question is named "bluedog_SNTP_45", so the patch does nothing.

The patch _does_ work on the other nuclear engine because it actually is named STNP_75; the acronym isn't consistent between the two.

**Comment by zorg2044** [comment]
Alrighty will fix that. STNP is incorrect but changing that would break craft for no real reason so just have to be careful when patching.
