### ISSUE TITLE
Apollo/Kane Lights Screen Flickering

### ISSUE THREAD

**Issue by Lodkins** [CobaltWolf/Bluedog-Design-Bureau#1054]
KSP - 1.8.1
BDB - v1.7.3
Lights - Apollo Docking Floodlight, Apollo EVA Floodlight, CSM Light
Visuals - EVE, Distant Object, Planetshine, Scatterer, JNSQ
Launch Vehicle - Saturn 1B
Paint Skin - BDBNIC's Skylab White

ADF & AEVAF Lights don't seem to flicker when activating manually, 
but CM's Interior Light screen flickers when pressing the Light action group

[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/6368646/KSP.log)

**Comment by zorg2044** [comment]
I can't reproduce this issue in my KSP 1.11 test install. This might be related to how we had to update them to deal with new lights module in KSP 1.11 (and might be causing problems in 1.8)

Unfortunately this means we cant change them and in any case all of these parts are currently being completely remade.
