### ISSUE TITLE
Having difficulties with B9 parts loader (Missing items)

### ISSUE THREAD

**Issue by Cypher39** [CobaltWolf/Bluedog-Design-Bureau#1055]
I'm currently running version 1.8.1 of KSP and I've been having a lot of trouble getting the mod to run fully for me after I saw it on CKAN. It seems as if some parts are not loading correctly, I was unable to build certain components nor use the blueprints for any of the base-rockets the mod includes. (I.E Titan II)

![image](https://user-images.githubusercontent.com/83116492/115955081-924c0b80-a4c2-11eb-9e89-1515358f7a6c.png) Upon booting I get two warnings.
![image](https://user-images.githubusercontent.com/83116492/115955164-0be3f980-a4c3-11eb-939a-85cf6e575202.png)
![image](https://user-images.githubusercontent.com/83116492/115955577-5c5c5680-a4c5-11eb-9a99-0e41ec35f107.png)

I've tried uninstalling all of my mods beforehand and installing only the items BDB and it's co-dependents and I had the same issue upon start up and attempting to load any of the base rocket blue prints and I can notice some items seem to be missing. I have also tried installing it on version 1.11.1 as well with roughly the same problem.

Here's my KSP log, I'd appreciate any suggestions or advice as to how to fix the problem as I really love this mod's historical relation. 

[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/6369396/KSP.log)

**Comment by zorg2044** [comment]
Which version of BDB do you have installed? And did you install via CKAN or manually through github releases/Spacedok?

That craft file you're trying to load looks really old. Containing parts removed from the mod since 2019.

**Comment by Cypher39** [comment]
> 
> 
> Which version of BDB do you have installed?
> 
> That craft file you're trying to load looks really old. Containing parts removed from the mod since 2019.

1.7.3 latest from CKAN.
Yeah that was the issue it seems I had older blueprints from Kerbal-X and it was the problem all along, part of the issues that led me to think it was a mod problem was the errors I got on start up (as in the first two images) the parts have Kerbal styled names instead of their real life counterparts so I had mistakenly assumed they were absent from the mod. I just installed the newer blue prints directly from the mod and it seems to have fixed all the issues I was having.

I suppose my only remaining question is what's causing the two start up error messages, other than that nothing else seems to be causing any trouble now. Sorry if I looked like a goof.

**Comment by zorg2044** [comment]
> I suppose my only remaining question is what's causing the two start up error messages, other than that nothing else seems to be causing any trouble now. Sorry if I looked like a goof.

So the B9 startup error is mostly harmless. It just means some solar panels which are supposed to get slightly lower output on a variant subtype will instead get the default output. This is a conflict with Kopernicus. The current release of BDB has resolved this issue but ONLY for the most recent versions of Kopernicus. I suppose since you are on 1.8.1 you have a version of Kop that our patch does not fix it for, its not possible to do both. I would just ignore it.

Re tweakscale I have no idea, I would follow up with the Tweakscale author.
