### ISSUE TITLE
Able rocket engine WaterfalFX fix

### ISSUE THREAD

**Issue by Araym-KSP** [CobaltWolf/Bluedog-Design-Bureau#1057]
There is a typo error in the WaterfallFX for the Able and Ablestar engine (_Bluedog_DB\Compatibility\WaterfallFX\Able.cfg_)

line 26 and line 157, under EFFECTS, both for the engage sound situation situation:

clip = Waterfall/Sounds/KW/**vsound_liq9**

should be

clip = Waterfall/Sounds/KW/**sound_liq9**

**Comment by zorg2044** [comment]
Thanks

**Comment by Araym-KSP** [comment]
No prob...
... it's nice to be back in KSP and, sometime, be helpful ;)
