### ISSUE TITLE
Abort modes?

### ISSUE THREAD

**Issue by joey-lg** [CobaltWolf/Bluedog-Design-Bureau#1058]
When you have free development time, could you add more abort modes for Mercury, Gemini, and apollo? Like abort mode 1C or II for apollo (or Kane, if the fake names are applied.)

**Comment by jsolson** [comment]
Sorry, no. I know it sounds like a simple thing, but deactivating whatever auto pilot you're using and turning the capsule around using RCS is beyond the scope of this mod. The Mercury and Gemini towers only have one possible mode. They have one of the three engines angled so it always will pitch over.

For an Apollo Mode 1C abort do a Mode 1B abort and turn around manually. The tower will jettison on it's own when you get turned around. Mode 1B, where the pitch motor does not fire, is the default abort mode over 3000 meters.

Mode II and beyond occur after the LES is gone so they're nothing we can do.

**Comment by joey-lg** [comment]
Oh, ok.
