### ISSUE TITLE
a patch for RO?

### ISSUE THREAD

**Issue by pi-maaster1337** [CobaltWolf/Bluedog-Design-Bureau#1060]
are they planning to release a patch for realism overhaul or is there someone who has?

**Comment by zorg2044** [comment]
Like most mods, compatibility with RO for most stockalike mods is handled by RO itself. The patches are in the RO repository and contributed by users who play with both BDB and RO.

The BDB authors do not make these configs. Please check with RO itself for the status of BDB compatibility. I believe they havent been updated in several months but the majority of parts are covered.

In addition several BDB assets are provided for use in RO capsules and RO engines.
