### ISSUE TITLE
Tweakscale compatibility bug

### ISSUE THREAD

**Issue by NaleshSA** [CobaltWolf/Bluedog-Design-Bureau#1062]
The patch for tweakscale seems to be out of date or something, when you change the size of a tank and then duplicate it, it reverts to its original fuel max values.

Can be reproduced just with tweakscale, bluedog, and their dependencies.

**Comment by zorg2044** [comment]
If you can change the size of the tank that means the part is covered by a tweakscale config. If the behavior is buggy following the scaling it sounds like a tweakscale issue (unless the entire syntax for tweakscale patches have changed recently which I don't think is the case.

I would suggest following up with the tweakscale developer as the BDB author's only involvement here is merging patches provided by community members who use it with tweakscale.

**Comment by NaleshSA** [comment]
There was a pretty bad bug introduced in stock in 1.9 (This is why tweakscale requires ksp-recall nowadays), it's most likely related to this bug and would require some changes on your side. Touching base with Lisias might be a good idea, both for figuring out which side the problem is on, and maybe moving tweakscale support over to their Tweakscale Companion Program.
