### ISSUE TITLE
Gemini internal

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#1065]
Unverified.

From MisterBluSky on the forum:

"Hi! Made an account to post this, I don't actually use this mod for the full rockets, but for the probes and crew modules. I was messing about with the 'Dona' Miniature lander can and noticed a bug regarding the IVA. If you EVA and re-enter the can, the IVA switches backwards. Quicksaving fixes it though."

**Comment by CobaltWolf** [comment]
Isn't that the one that's always been backwards..? Or did we manage to somehow fix it

**Comment by jsolson** [comment]
Yeah it's fixed with the plugin, but it might need another look.

https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Source/VisualStudio/BDB/BDB/RotateInternal.cs

**Comment by OrbitalManeuvers** [comment]
I just tested this today with a github download from 7/1/21. It's definitely borked.

Just launch the can and click Interior Overlay:

https://i.imgur.com/6NP72km.jpg  Just launched
https://i.imgur.com/PrtOyRU.jpg  After first toggle
https://i.imgur.com/ENQ2Bpu.jpg  After first IVA, then toggling

**Comment by jsolson** [comment]
The model flipped around,  but the IV remained pointing in the same direction? ugg.

**Comment by zorg2044** [comment]
More feedback on this issue https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/1202

**Comment by zorg2044** [comment]
Fixed permanently by rotating the IVA model [4d29628](https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/4d2962858880b11a46d105e286a0bd1459596b5d)
