### ISSUE TITLE
LMSS-IAM "Expanse" Inflatable Airlock mesh bug 

### ISSUE THREAD

**Issue by TomFancy** [CobaltWolf/Bluedog-Design-Bureau#1066]
After extension there is visible buggy part of mesh that is flickering and has inverted normals.

**Comment by Rodg88** [comment]
Can't replicate, closing. If you can still replicate please do reopen with a screenshot and a KSP.log

**Comment by CobaltWolf** [comment]
I may have actually fixed this one.
