### ISSUE TITLE
OSO / Early Delta SAF fairings off in size

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1070]
https://i.imgur.com/QPm9rMD.png
https://i.imgur.com/51w4Aio.png

I discovered a scaling issue either in the Orbiting Solar Observatory or the Able/Delta SAF fairings.  
OSO was initially orbited by Delta C rockets.   Using the Delta C + SAF fairings leaves 3 points of the OSO experiment exposed on the SAF fairing.

Could we either get a slightly wider diameter to the bulbous SAF fairings for the Able/Delta?  Alternatively, could the OSO Experiments be scaled down by 5 to 10%?

I hope the pix and info are helpful.

**Comment by zorg2044** [comment]
bleh. thats annoying. But unfortunately due to the geometry enlarging these fairings is none trivial. will see what can be done at some point in the future.

**Comment by Pappystein** [comment]
Would it just be easier to scale down the model?   I am guessing that this is 100% due to scale difference between the parts and the fairings.   A simple Scale factor change to the 2 or 3 parts in question would be easier than messing with new geometry I would think.

**Comment by zorg2044** [comment]
Im not sur that its worth breaking craft files for this.

**Comment by Invaderchaos** [comment]
I do not believe you are using the correct fairing?

![screenshot1399](https://user-images.githubusercontent.com/4949484/133482865-9fb62a7a-df4e-4e33-88f4-40e5fe72b8be.png)

I believe OSO 1 was actually first launched on the DM-19 Thor-Delta rocket, not the Delta C. This rocket launched with two types of fairing, the conical fairing and the "Able Bulbous 3", OSO using the latter. This fairing fits OSO just fine as seen in the attached picture. This rocket was also used to launch OSO 2-5 was launched on Delta C1 (which used the Able Bulbous 3 fairing). Here is a picture that I believe is used in launching OSO 2:

https://images.squarespace-cdn.com/content/v1/5439a3d0e4b0dedc218f23b9/1586281565002-S4JBI39IPLRQ8HRCQDEN/image-asset.png

As you can see, it appears to be the Able Bulbous 3 fairing. Hope this helps!

**Comment by zorg2044** [comment]
Im going to close this issue then
