### ISSUE TITLE
Poppy-2: Broken "Toggle Antenna" action (oversight?)

### ISSUE THREAD

**Issue by biohazard15** [CobaltWolf/Bluedog-Design-Bureau#1071]
According to cfg, Poppy-2 is supposed to have a built-in toggleable antenna. This is not the case - instead there is a button in PAW labeled as "Toggle", which doesn't do anything.
Since its antenna is a separate part, my best guess is oversight\leftover from Poppy-1 cfg.

**Comment by Invaderchaos** [comment]
No idea how I missed this, thanks for pointing it out. Just fixed
