### ISSUE TITLE
Apollo

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#1074]
CM:

- [x] Command Pod
- [x] Main Chute
- [x] Drogue Chute
- [x] Parachute Cover
- [x] Docking Probe
- [x] Heatshield
- [x] Block 1 nose
- [x] Launch Escape System

SM:

- [x] Decoupler
- [x] Service Module (Block2)
- [x] Engine Plate
- [x] Service Propulsion System
- [x] Docking Spotlight
- [x] EVA Floodlight
- [x] Scimitar Antenna
- [x] HGA Assembly

AAP:

- [x] Block 3 SM
- [x] Block 3 HGA
- [x] Block 3+ Mission Module
- [x] Block 4 SM?
- [x] Block 4 Mission Module
- [x] Block 5 HGA
- [x] Block 5 engine plate switch
- [x] Block 5 solar panels
- [x] VFB dual engine plate switch
- [x] AARDV Control Core
- [x] AARDV Block 1 Cargo module
- [x] AARDV Block 1 top plate
- [x] AARDV Block 1 nose adapter
- [x] AARDV Block 2 cargo module
- [x] AARDV Block 2 unpressurized module
- [x] R-4D block variants

LM:

- [x] Ascent Stage
- [x] Ascent Engine
- [x] Docking Cone
- [x] Docking Cone Black variant (for skylab)
- [x] LM Separator
- [x] Descent Stage
- [x] Descent Engine
- [x] Landing Legs
- [x] EVA Antenna
- [x] MESA Materials Bay
- [x] RTG Cask Mystery Goo
- [x] Cosmic Ray Detector
- [x] Separate VHF antenna 

SIM bay

- [x] Apollo SIM bay variants (Historical shelves, Universal Storage nodes and mounting rack, Empty)
- [x] Mapping camera
- [x] Panaromic camera
- [x] Apollo 15/16 Mass spec boom
- [x] Apollo 15/16 Gamma Ray spec boom
- [x] Apollo 15/16 Alpha and X-ray spectrometer
- [x] Apollo 15/16 Subsatellite and dispenser (decoupler)
- [x] Apollo 17 Radar and Radar optical recorder
- [x] Apollo 17 UV spectromer
- [x] Apollo 17 scanning IR radiometer
- [x] #1132

**Comment by jsolson** [comment]
Day 0 issues:

- Apollo's rotation is off by 180 degrees.
- The LES CoM, CoP, and CoL need to be moved back to 3 meters above the attach node. The entire LES dance is very weight and balance sensitive. Otherwise the LES seems to work.
- The drogue chute has either no drag or not enough drag.
- The drogue must be manually cut right now. I don't know how we're going to deal with this. Previous drogue/main arrangements have jettisoned the drogue on main chute deployment. That won't work here.
- The capsule does not hang at the correct angle from the chutes.

**Comment by CobaltWolf** [comment]
Solved bullets 1 and 5

**Comment by CobaltWolf** [comment]
Solved bullet 2

**Comment by CobaltWolf** [comment]
RL / Kerbal parachute values:
Cover release: 24,000 ft / 5850 m
Drogue deployment: Cover release +2 seconds
Drogue reefing: deployment + 10 seconds
Main deployment: 10,000 ft / 2440 m
Main reefing: +10 seconds

**Comment by WVAG** [comment]
Apollo LM CSD? It seems like it'd be crazy fun [http://www.astronautix.com/a/apollolmcsd.html](url)

**Comment by Gordon-Dry** [comment]
Is this known or taken care of in dev?

```
[LOG 21:23:45.403] PartLoader: Part 'Bluedog_DB/Parts/Apollo/bluedog_Apollo_Subsatellite_Core/bluedog_Apollo_Subsatellite_Core' has no database record. Creating.
[LOG 21:23:45.403] [DragCubeSystem]: Drag cubes not found or cannot be read for part Part. Generating New drag cubes.
[WRN 21:23:45.415] DragCubeSystem: Part 'bluedog.Apollo.Subsatellite.Core' has more than two IMultipleDragCube part modules. You should consider procedural drag cubes.
[LOG 21:23:45.415] DragCubeSystem: Creating drag cubes for part 'bluedog.Apollo.Subsatellite.Core'
[EXC 21:23:45.420] NullReferenceException: Object reference not set to an instance of an object
	ModuleDeployablePart.AssumeDragCubePosition (System.String name) (at <cd473063d3a2482f8d93d388d0c95035>:0)
	DragCubeSystem+<RenderDragCubes>d__34.MoveNext () (at <cd473063d3a2482f8d93d388d0c95035>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<RenderDragCubesCoroutine>d__31:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<SetupDragCubeCoroutine>d__46:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CompileParts>d__56:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

```

**Comment by WVAG** [comment]
When LM truck/rover carrier?

**Comment by JovietUnion** [comment]
You mean the LRV cabin?
Might be around the time that the Apollo revamp is done. Not sure

**Comment by WVAG** [comment]
No, the unmanned LM, I remember seeing the 3d model a month or two ago on one of the dev's twitters

**Comment by CobaltWolf** [comment]
I'm planning on doing the AES/AAP LM stuff in the next dev cycle, once this initial revamp pass is done. With that said, the timing might work out such that I start working on them sooner. Still probably not in the main Saturn/Apollo update.

**Comment by WVAG** [comment]
> I'm planning on doing the AES/AAP LM stuff in the next dev cycle, once this initial revamp pass is done. With that said, the timing might work out such that I start working on them sooner. Still probably not in the main Saturn/Apollo update.

Alright, thanks for the clarification, cause landing a rover with the current LEM is a PITA

**Comment by CobaltWolf** [comment]
I have some ideas for the LM-Truck to be something like a platform that goes on top of the descent stage. Maybe a version with extendable ramps...

**Comment by WVAG** [comment]
Can't wait to see it, I just used robotics for mine, sounds like it'll be a hell of a lot easier

**Comment by WVAG** [comment]
On a side note, will there be anything from Journeys of the saturn?

**Comment by CobaltWolf** [comment]
Never heard of it, had to look it up. It seems like it's mostly historical proposals so probably yeah.

**Comment by WVAG** [comment]
Look forward to it, its a really good read

**Comment by subadabadar** [comment]
Would you consider a 3-crew LEM cabin?

**Comment by Gordon-Dry** [comment]
Actually I'm confused about this one:
https://github.com/Kerbalism/Kerbalism/issues/788

**Comment by JovietUnion** [comment]
Would you consider Tantares to be a soviet clone of BDB?

**Comment by WVAG** [comment]
> Would you consider a 3-crew LEM cabin?

Seconding this

**Comment by JovietUnion** [comment]
Lunar escape system?
Packable LRV?

**Comment by Gordon-Dry** [comment]
The "Apollo 2.5m Heat Shield" clips inside the "Apollo Command Module" and so the heat conduction is very high.
![Screen-2021-12-09_20-47-50](https://user-images.githubusercontent.com/29145213/145466267-3f2fc70f-fa39-400f-9bd6-3146b2a502fa.jpg)
![Screen-2021-12-09_20-47-53](https://user-images.githubusercontent.com/29145213/145466283-4ba8d994-ceed-42b1-9e15-9e5205b38780.jpg)


see as well https://forum.kerbalspaceprogram.com/index.php?/topic/122020-181-112-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v181-%D0%BC%D0%BE%D1%80%D0%BE%D0%B7-11jul2021/&do=findComment&comment=4063549

**Comment by Gordon-Dry** [comment]
bluedog_Apollo_SIMbay_subSatellite_dispenser got a really wrong description:
`This decoupler is designed to sit between a capsule's heatshield, and the service module. It includes an umbilical to connect the capsule to the service module's systems. The decoupler automatically maps to the abort action group in case of a failure of the launch stack.`

**Comment by Gordon-Dry** [comment]
bluedog_Apollo_RCS_Sideways got an offset module.
When attaching it on the surface of a part, the nozzle points inwards the part.

**Comment by Gordon-Dry** [comment]
bluedog_Apollo_RCS_3Way got the same issue.

bluedog_Apollo_RCS_Quad is NOT affected.

**Comment by Gordon-Dry** [comment]
bluedog_Apollo_Block3_highGain antenna got wrong angle and/or animation order when radially attached  (there was no way for proper attachment at bluedog_Apollo_EngineMount).

Retracted:
![Screen-2021-12-11_22-33-34](https://user-images.githubusercontent.com/29145213/145692455-21361fb5-8672-4f8f-befd-297c0f2038de.jpg)

Deployed:
![Screen-2021-12-11_22-33-25](https://user-images.githubusercontent.com/29145213/145692456-6d06845a-4e34-4987-aced-70c4d99c21cc.jpg)

If it's not meant to be radially attached but explicitly attached to the engine mount at the nodes, then this needs to be fixed because it cannot be attached to the nodes at the engine mount actually.

**Comment by WVAG** [comment]
![image](https://user-images.githubusercontent.com/87865203/153302555-bc47b453-f9b8-4818-898e-3a969ab4ee4b.png)
Even a slight possibility?
