### ISSUE TITLE
Saturn

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#1075]
S1C (6.25m):
- [x] Engine Mount
- [x] Tank
- [x] Decoupler
- [x] Fins

S2 (6.25m):
- [x] Tank
- [x] Engine Mount
- [x] Engine Mount (7x)
- [ ] Engine Mount (4x)
- [x] Interstage
- [x] Ullage Motor
- [x] INT-17 engine skirt
- [x] INT-17 fins
- [x] INT-21 IU

S4B (4.25m):
- [x] Tank
- [x] Engine Mount
- [x] Engine Mount Switch (LASS)
- [x] Engine Mount Switch (Dual)
- [ ] Engine Mount Switch (Quad)
- [x] Interstage
- [x] Instrument Unit
- [x] Saturn-LM Adapter
- [x] Wide SLA
- [x] Capped SLA with nose 
- [x] Ullage Motor
- [x] 200 series APS
- [x] 500 series APS
- [x] J-2A2 (J-2 with solid extending nozzle)

S4 (3.75m):
- [x] Tank
- [x] Upper tank
- [x] Instrument Unit
- [x] Engine Mount
- [x] Interstage
- [x] 3.75m Instrument Unit

S1 (4.25m):
- [x] Tank
- [x] Retro Motor
- [x] Engine Mount
- [x] Engine Mount (4x, for E-1s)
- [x] Engine Mount (5x, for E-1s or something)
- [x] Large Fin
- [x] Small Fin
- [x] Advanced Fin

S1D (6.25m):
- [x] Central Mount
- [x] Booster Skirt
- [x] Recovery parachutes
- [x] Airbrake fins

S1E (4.25m)
- [x] Long Tank
- [x] 1x mount for S-1B 

LRB (4.25m)
- [x] Dual F-1 mount
- [x] Tank (separate part for the AJ-260 extension?)
- [x] Nose cone
- [x] Separation Motors
- [x] Radial Decoupler

AJ-260 (4.25m):
- [x] AJ-260 (radial)
- [x] AJ-260 (inline)

Structural Bits:
- [x] 4.25m > 1.875m adapter (Juno V)
- [x] 4.25 > 3.125m adapter
- [x] 4.25 to 3.75
- [x] 5m > 4.25m adapter
- [x] 6.25m > 5m adapter
- [x] 2.5m > 1.875m adapter (we don't have one in the saturn style)
- [x] Short 2.5m interstage (for Apollo on S4)

**Comment by jsolson** [comment]
The S4B wide adapter is off by 45 degrees. The retros should be inline with the first stage fins.

https://www.nasa.gov/sites/default/files/apollo_4_at_pad-full.jpg

**Comment by jsolson** [comment]
Now rotate that 90 clockwise and I think we're good.

**Comment by subadabadar** [comment]
Small request: B9-based upgrades to make the S-IVB IU and tankage cheaper. IIRC these were upgrades described in Eyes/by e of pi and would make sense for long-term use of the stage (surely there are cheaper ways to insulate than hand-applied tiles).

**Comment by CobaltWolf** [comment]
Mass upgrades to represent a switch from analogue to digital electronics is definitely something I think a lot of the cores could use.

**Comment by JovietUnion** [comment]
Just asking, are you going to do rockets that didnt make it off the drawing board like Nova, Saturn IV, or even the ~~Infamous sea dragon~~

**Comment by spacefacey** [comment]
> Just asking, are you going to do rockets that didnt make it off the drawing board like Nova, Saturn IV, or even the ~Infamous sea dragon~ There is already a mod for sea dragon

No, there are simply way too many Nova variants and barely any of them are more than paper drawings. With Nova, you would also need a bunch of new part diameters that don't have any other uses in the game. Not really sure about sea dragon but I seriously doubt it, again comes with the same issues as the first one.

**Comment by WVAG** [comment]
> > Just asking, are you going to do rockets that didnt make it off the drawing board like Nova, Saturn IV, or even the ~Infamous sea dragon~ There is already a mod for sea dragon
> 
> No, there are simply way too many Nova variants and barely any of them are more than paper drawings. With Nova, you would also need a bunch of new part diameters that don't have any other uses in the game. Not really sure about sea dragon but I seriously doubt it, again comes with the same issues as the first one.

What about Nova F? Or perhaps the "Nova" Saturn C-8.

**Comment by CobaltWolf** [comment]
Nah, I'm more interested in adding uprated Saturn V stuff that can be lego'd together a bit.

**Comment by WVAG** [comment]
That'll be neat to see, can't wait (on a side note [Where's the HG-3? Not done?])

**Comment by CobaltWolf** [comment]
After looking into it, we discovered that HG-3... doesn't really exist. See this post by Zorg on our forum thread, goes into all the details: https://forum.kerbalspaceprogram.com/index.php?/topic/122020-181-112-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v181-%D0%BC%D0%BE%D1%80%D0%BE%D0%B7-11jul2021/page/872/&tab=comments#comment-4039103

**Comment by WVAG** [comment]
Damn, however, I have hope, if y’all ever incorporate Journeys of the
Saturn parts, the HG-3 is used on the Saturn VB.

**Comment by CobaltWolf** [comment]
See the post I linked. There is no "HG-3". It was basically a placeholder for a set of performance they needed. There's no actual design to base it off of.

**Comment by WVAG** [comment]
Alright, c’est la vie

**Comment by WVAG** [comment]
Also, will there be a higher thrust upper stage engine to take the HG-3’s
place?

**Comment by CobaltWolf** [comment]
Several https://www.reddit.com/r/KerbalSpaceProgram/comments/mxnid0/new_forgotten_cryogenic_engines_coming_to_bluedog/

**Comment by WVAG** [comment]
I'll have to see which ones fit the Rockets

**Comment by zorg2044** [comment]
Both the RL20 and XLR129 are the closest things to a real HG-3 as mentioned in my post. They are staged combustion designs and the RL20 design existed even before Pratt and Whitney conducted the HG-3 study. The RL20 is less powerful than the study reccomended but was mentioned in some MLV documents so its a good fit. The upgraded XLR129 upgrade fits somewhere in the middle of the thrust range recommended so its a closer fit performance wise.

**Comment by WVAG** [comment]
I’ll have to try em out this afternoon

**Comment by JovietUnion** [comment]
Saturn Heavy, anyone?
-Random idea I got

**Comment by JovietUnion** [comment]
Also, Are you gonna do reusable S-IC?
![image](https://user-images.githubusercontent.com/62820134/145113140-435ba35f-8282-4982-acb4-ea693e50054a.png)

**Comment by JovietUnion** [comment]
Nevermind, i found some parts to make reusable Saturn

**Comment by JovietUnion** [comment]
Saturn I S-V?
