### ISSUE TITLE
New Skylab Parts on Loading

### ISSUE THREAD

**Issue by Lodkins** [CobaltWolf/Bluedog-Design-Bureau#1077]
so, downloaded new Skylab parts and booted KSP up and just stopped loading at Skylab Solar wing
log says warning of 

"[WRN 15:40:46.471] PartLoader Warning: Variable useKopernicusSolarPanels not found in Part"

[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/6987179/KSP.log)

**Comment by zorg2044** [comment]
The problem appears limited to KSP 1.8 probably some kind of drag cube problem and not Kopernicus related. Works fine with and without kop in 1.12. Not tested in 1.9, 1.10 or 1.11. 

Needs further investigation.

**Comment by zorg2044** [comment]
was caused by an incorrect pivot name in the config. ksp 1.12 lets you load it but older KSP versions would not.
