### ISSUE TITLE
Transtage Tank RCS ports borked.

### ISSUE THREAD

**Issue by Sgt-Shutesie** [CobaltWolf/Bluedog-Design-Bureau#108]
Transtage tank RCS are broken. 1 is functional, 1 is half functional and the other 2 don't work.

**Comment by CobaltWolf** [comment]
I fixed this but have not committed the changes.

**Comment by CobaltWolf** [comment]
This was actually still broken but I think I fixed it now.

**Comment by CobaltWolf** [comment]
I've tried several times to fix this but now it seems that the parts are completely broken. :/ The RCS flat out will not work.

**Comment by CobaltWolf** [comment]
What is the current status of this RCS block?

**Comment by jsolson** [comment]
They're separate parts instead of part of the tank. I miss that. It made this tank interesting.

The aft facing thruster doesn't work on the ports.

**Comment by CobaltWolf** [comment]
I had to remove them so you could use the RCS blocks elsewhere. 

I'll look into the aft thruster. Hopefully it's an easy fix.

**Comment by CobaltWolf** [comment]
finally figured this out
