### ISSUE TITLE
Daleth SSR-27a Darkah Engine - Only one vernier engine firing creating big torque

### ISSUE THREAD

**Issue by rasta013** [CobaltWolf/Bluedog-Design-Bureau#109]
Discovered this one tonight and I didn't see this posted anywhere.  Attached are images where you can see one vernier firing and the other not with Real Plume installed.  Under stock of course you don't see this but the torque data from Engineer shows it in the second screen shot.  Tried a few config tweaks to see if I could get it working right but no joy.  I'm not very good with thrust transforms so I may just not know what to change.

![ssr-27a_realplume](https://cloud.githubusercontent.com/assets/12317827/17012471/96f55fbe-4edd-11e6-8918-0efaeae4c711.jpg)
![ssr-27a_torque data no real plume](https://cloud.githubusercontent.com/assets/12317827/17012472/970523d6-4edd-11e6-8cc3-ea2f7cc8150a.jpg)

**Comment by jsolson** [comment]
Confirmed. It's not going to be a config file thing. There's a broken/missing/whatever thrust transform in the model. The non-functioning vernier doesn't move with the gimbles either. It's totally dead.

**Comment by CobaltWolf** [comment]
I probably misnamed the transforms when I re-exported it recently.

**Comment by CobaltWolf** [comment]
I fixed this but the line endings thing pissed me off too much

**Comment by Cowboy-WY** [comment]
- Thrust now works in a balanced manner
- Vernier gimbals work
- Real plumes work on all 3 exhaust
- Stock  only shows main engine exhaust, but all thrust and gimbals work - I think that is normal

**Comment by CobaltWolf** [comment]
uhh it should work with stock modules
