### ISSUE TITLE
Gemini Station CLS Compatibility 

### ISSUE THREAD

**Issue by birdog357** [CobaltWolf/Bluedog-Design-Bureau#1092]
A large chunk of the GMSS parts that should have Connected Living Space compatibility, don't. Almost none of the GMSS tubes and adapters do nor does the inflatable airlock. Semi related, the Skylab radial attach node does not have CLS, since Skylab is currently being redone, this should be a moot issue.

**Comment by zorg2044** [comment]
CLS patches have always been community contributed. Please make a pull request if you wish to expand compatibiltiy.

**Comment by zorg2044** [comment]
I believe we had a bunch of CLS patches that covered most of these.
