### ISSUE TITLE
Make sure parts have correct 'bulkead profiles'

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#11]
This has not been paid attention to. Many parts likely have incorrect bulkhead profiles.

**Comment by CobaltWolf** [comment]
eh
fuggit

**Comment by jsolson** [comment]
We have many off sizes. Already out there in other mods is size00 for 0.3125 and size1p5 for 1.875.

size1p5 can probably be read as 1 point 5, as in halfway between 1.25 and 2.5. Maybe we should follow that convention.

**Comment by Cowboy-WY** [comment]
I would like to start verifying and updating all of the bulkhead profiles.  I just need to be sure of what you want to use for each size.  Here is what I assume you want to use based on the parts I have looked through.

size00 - .3125
size0 - .625
size0.5 - .9375 (or do you prefer size0p5)
size1 - 1.25
size?? - 1.5 (based on the other numbers size1.2 seems proper for this)
size1.5 - 1.875
size2 - 2.5
size3 - 3.75
srf - surface attachable

Let me know what you want to go with and I will get started.

**Comment by jsolson** [comment]
You've got the idea. Use a "p" in place of a decimal point. We want to avoid special characters, it could cause problems down the road.

size00 for anything under 0.625. Use common sense here. A 0.5 part might be a size0 depending on context. I don't think we should add more sub size0 sizes. size00 is in wide use in other mods.
size0p5 for 0.9375.
size1p2 looks right for 1.5m.
size1p5 for 1.875 (introduced by HGR I think)

**Comment by Cowboy-WY** [comment]
Thanks, I will get started today.

**Comment by Cowboy-WY** [comment]
updated all files through Mercury folder and submitted pull request #120 

I see the Saturn lower stages seem to be a different size, maybe 2p5?

**Comment by jsolson** [comment]
Saturn stages are still on the drawing board.

**Comment by Cowboy-WY** [comment]
OK, I'll leave the Saturn ones alone for now.  Thanks for getting the bulk of these merged in.  I'm still learning/experimenting with the best way to do changes.

Still to do:
Apollo - again :)
Probe Expansion
Saturn - Later
Science
Shared
Titan

**Comment by jsolson** [comment]
Thank you!

**Comment by Cowboy-WY** [comment]
All done except for Saturn

Few Gemini Fixes - #121 
Apollo - #125 
Probe Expansion - #122  
Science - #123 
Shared - No config files
Titan - #124 

You can probably close this and open a issue for Saturn.  So I remember to go back and do it in the future when Saturn is ready.

**Comment by jsolson** [comment]
Wow. Thank you very much for knocking this out!

**Comment by Cowboy-WY** [comment]
No problem.  This is easy stuff and I learn a bit from looking through the config files.
