### ISSUE TITLE
HLR-ZAP Rechargeable Battery Pack (bluedog_rangerBattery.cfg) - Appears to surface attach in the wrong direction

### ISSUE THREAD

**Issue by Cowboy-WY** [CobaltWolf/Bluedog-Design-Bureau#110]

**Comment by CobaltWolf** [comment]
No. It's supposed to be a battery mounted behind a dust cover. Thank you very much for logging an issue after noticing it! :) 

You can see them arranged around the hexagonal bus in this picture:
http://photojournal.jpl.nasa.gov/jpeg/PIA04594.jpg

**Comment by Cowboy-WY** [comment]
Then it is working as intended.
