### ISSUE TITLE
J15-D Communications Dish (bluedog_mariner4Dish) is missing RemoteTech compatibility in remotetech_Antennas.cfg

### ISSUE THREAD

**Issue by Cowboy-WY** [CobaltWolf/Bluedog-Design-Bureau#111]
Example attached
[J15-D.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/387298/J15-D.txt)

**Comment by CobaltWolf** [comment]
Added it. In the future, it'd be ever better if you could make pull requests if you've already fixed the configs. That way I just have to approve the change and it will get merged in :)

**Comment by Cowboy-WY** [comment]
Sorry, I am unsure of how to do that, first day using github.  I'll see if I can figure that out next time :)

**Comment by CobaltWolf** [comment]
(I am not sure if I know either, I just know other people have submitted them :P )

**Comment by Cowboy-WY** [comment]
looks like this needs an edit.  Range is set to 30Mm (30000000) instead of 30Gm (30000000000).  won't reach anywhere near Duna at current setting :(

Not sure if you have guidelines for your antenna ranges, but I think 30Gm will not always cover Duna.  Might need 40Gm to be sure.

**Comment by Cowboy-WY** [comment]
Lets try the 30Gm to start, I'll play around with distances when I can.

**Comment by CobaltWolf** [comment]
Thanks!

**Comment by jmrd98** [comment]
Quick PR on github can be made by hitting the edit 'pencil' when viewing a file in the repo, and it will ask you want you want to do. Most of the time you want to fork it into your own repo, make w/e changes are needed, and (I think) it asks you if you want to send a PR back to the origin at the end of it.

This is clunky for large changes, but for simple additions it is pretty slick.

**Comment by Cowboy-WY** [comment]
Ready to be closed. Pull Request #118 completed
