### ISSUE TITLE
Titan heating up on Ascent

### ISSUE THREAD

**Issue by AdrianDogmeat** [CobaltWolf/Bluedog-Design-Bureau#1119]
The entire stack heats up and can't timewarp because it says can't timewarp while moving on Terrain, idk why it happens on KSRSS or any 2.5x sized solar systems
![Kerbal Space Program Screenshot 2021 10 13 - 18 03 06 55](https://user-images.githubusercontent.com/68912599/137536783-80953b43-5cc4-4719-a40a-52310d71459d.png)

**Comment by FuryFire2004** [comment]
I thought you meant Saturn's moon titan was literally heating up for a sec when seeing the title. but, what's your mod list look like, that would help eliminate a lot of potential factors.
