### ISSUE TITLE
Mercury Lab Ladder bug

### ISSUE THREAD

**Issue by friznit** [CobaltWolf/Bluedog-Design-Bureau#1124]
Bottom half of the ladder appears to be configured upside down.  Repro: place snack in lab to attract kurious kerbal, deploy ladder, observe subject entering EVA and descending ladder.  When kurious kerbal reaches halfway point, subject flips 180 degrees progresses backwards towards pod.  Witness squeaks of indignation as subject repeatedly attempts to reach snacks but to no avail.

**Comment by CobaltWolf** [comment]
@friznit the two ladder colliders had their "up" vector in opposite directions, easy fix.

**Comment by friznit** [comment]
**Squeaks of delight**
