### ISSUE TITLE
Some BDB antennas locked

### ISSUE THREAD

**Issue by lancisman** [CobaltWolf/Bluedog-Design-Bureau#1133]
![Skärmbild 2021-11-03 091711](https://user-images.githubusercontent.com/70746909/140027719-370d853f-b591-45a6-9eb9-bc608cfc78f6.png)
don't know what is causing this

**Comment by Pappystein** [comment]
As was posted in the forums, you have an RT folder in your Gamedata directory.  even with no files in it, the Remote Tech folder triggers patches that lockout your antennas

Solution:   Either fully re-install Remote Tech, or completely delete and remove the Remote Tech folder if you are not using Remote tech anymore.
