### ISSUE TITLE
MOL Docking port parts do not connect to each other's nodes correctly

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1134]
I am using the 1.875m MOL docking port (the awesome "clampotron sr " level one... and want to convert one of them to a Probe and drogue port using the MOL Big Gemini Drogue adaptor:

https://i.imgur.com/lHrNqwB.png

Parts in question:
Gemini Ferry Docking Adaptor
MOL 1.875m Docking Adaptor.    

There appears to be an interstage node that the MOL 1.875m Docking adapter is grabbing instead of the correct Bottom/top node on the Ferry Docking adapter.

**Comment by CobaltWolf** [comment]
Other way around, you're attaching the top node of the docking port to the interstage node on the adapter
