### ISSUE TITLE
Saturn S-IVB RCS system (500 series) has 2 sets of RCS controls and one is disabled

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1135]
https://i.imgur.com/ZbHlRPr.png

Not certain if this is desired by design... But the Ullage RCS feature works fine for basic pitch/roll and yaw but if you use these RCS ports for any sort of active docking they are useless without going into the advanced tweakable and engaging the Pitch/roll/yaw RCS components (Like I did in the picture above)

**Comment by CobaltWolf** [comment]
That is intended behavior I believe, they default to operating in the historical mode.
