### ISSUE TITLE
Mercury-MASD Main Parachute

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1136]
When the chute was attached to (inside) the Mercury Landing and Control Module it's no longer possible to grab it (click it) and so it's also not possible to configure it for RealChute in the Actions UI.

**Comment by Gordon-Dry** [comment]
I know that the mod PartWizard helps, but this should be possible without another mod.

**Comment by CobaltWolf** [comment]
Is that because it's entirely inside the collider of the RCS part?

**Comment by jsolson** [comment]
Can you not right click the icon in the staging list?

**Comment by Gordon-Dry** [comment]
I need to select in inside the Actions editor for RealChute settings.
This only works by left-clicking the part (or the entry in "Part Wizard" mod as the only solution).

**Comment by CobaltWolf** [comment]
Yeah I think I can just extend the collider for the parachute vertically slightly so it can still be interacted with.

**Comment by Gordon-Dry** [comment]
Something else:
Now for the third time the parachute did not auto-arm with RealChute, so never deployed ...
Perhaps RealChute does not like colliders as well?

**Comment by CobaltWolf** [comment]
To that, I have no idea. I thought RealChute2 was supposed to be released by now.

**Comment by CobaltWolf** [comment]
I just made some adjustments to the main chute collider, hopefully it will be selectable.
![image](https://user-images.githubusercontent.com/16356162/142773705-bcee8ff4-cc97-4f89-a63b-1eff41245a10.png)

**Comment by Gordon-Dry** [comment]
It's selectable, yes.

But chute will not deploy. No exception about RealChute or whatever.

So I only can assume it's still a collider issue.

**Comment by Gordon-Dry** [comment]
Addition:
I forget to mention that, but from the top surface of that part only about ~40% are clickable as soon as it's inside the RCS part.
That means not all of it is above the collider.
Perhaps that alone is the culprit?

**Comment by Gordon-Dry** [comment]
Confirmed.
After moving the MASD chute halfway upwards the whole top surface was outside the collider of the RCS part, clickable and finally the chute deployed.

**Comment by CobaltWolf** [comment]
Really? Weird. I guess I'll have to come up with some better colliders for the RCS part then? 

Thanks for looking into this btw

**Comment by Rodg88** [comment]
Should be fixed with latest version of FAR
