### ISSUE TITLE
I would like to update the remotetech antenna config to make the values represent their intended use

### ISSUE THREAD

**Issue by Cowboy-WY** [CobaltWolf/Bluedog-Design-Bureau#114]
Can you help me fit the BDB antenna into a use category below?  

I am willing to adjust the cfg file once the use cases are defined.

Antenna:
A23 - A27-C - A66 - Belle B81 - DP-75 - F21 - Hermes M-SAM - J-15D - KD2 - M17 - MOS-MCL - MSC Dome - N-100 - OVBR-1 - WPT Scimitar

Probe Cores:
HLR-ASTX - HLR-DIA - HLR-E1 - HLR-HEKS - HLR-P1 - HLR-P4 - HLR-POG - HLR-XPL-7 - 

Antenna Use cases:
1. Low Kerbin Orbit - 500km to 1.5Mm
2. High Kerbin Orbit - 1Mm to 2.5Mm
3. Stationary Orbit - 7Mm to 9Mm
4. Mun - 12Mm
5. Minmus - 50Mm
6. Moho - 20Gm
7. Eve - 25Gm
8. Duna - 35Gm
9. Dres - 65Gm
10. Jool - 80Gm
11. Eeloo - 130Gm
12. Sarnus (OPM Saturn) - 150Gm
13. Urlum (OPM Uranus) - 300Gm
14. Neidon (OPM Neptune) - 450Gm
15. Plock (OPM Pluto) - 750Gm

**Comment by CobaltWolf** [comment]
This is complicated a lot by RemoteTech not modeling low gain antennas properly. A lot of those are meant to be used by lunar or interplanetary missions IRL :/ And then some are high gain uplinks for Kerbin orbit.

**Comment by Cowboy-WY** [comment]
Agreed.  I have divided them by type and spread out the distances a bit.  Using Omni antenna for short range communications and dishes for anything further than the Mun.  Here is what I have so far with coverage out to Duna. The stuff that comes with RemoteTech covers the larger distances for now.  

I have a branch ready for a pull request as soon as you are OK with them,

Omni
1.0Mm - Hermes-SAM & M17 Solar Antenna
2.0Mm - KD2
2.5Mm - A23
3.0Mm - F21
5.0Mm - DP-75
8.0Mm - Belle B81
10.0Mm - A27-C
12.0Mm - N100

Dishes
2.5Mm - MOS-MCL
12Mm - WPT Scimitar & A66
50Mm - OVBR-1
25Gm - MSC Dome
35Gm - J-15D

**Comment by Cowboy-WY** [comment]
Added 
50Mm - Kane-11 CDA HGA

Attached updated cfg file in txt format for review .
[remotetech_Antennas_07302016_1119.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/392004/remotetech_Antennas_07302016_1119.txt)

**Comment by Cowboy-WY** [comment]
Found another Antenna 

2.0Mm - Leo-010SM Solar Antenna

Attached updated cfg file in txt format for review .
[remotetech_Antennas_07302016_1208.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/392032/remotetech_Antennas_07302016_1208.txt)

**Comment by Cowboy-WY** [comment]
Updated and tested all antennas.

fixed typo - bluedog_MOL_rackdish to bluedog_MOL_rackDish
Added %MaxQ = 6000 to all deployable antenna
All Omni Antenna set for %Mode0OmniRange = 250000 to allow for use during launch

Pretty sure I am done editing - at least for today
[remotetech_Antennas_07302016_1307.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/392058/remotetech_Antennas_07302016_1307.txt)

**Comment by Cowboy-WY** [comment]
Ready to be closed. Pull Request #118 completed
