### ISSUE TITLE
descriptionDetail = Isp:</b>

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1143]
There are parts in whose the B9PartSwitch descriptionDetail entries lack a leading `<b>`

**Comment by CobaltWolf** [comment]
We have over a thousand parts, Gordon. I'm not checking all of them. Which ones?

**Comment by Gordon-Dry** [comment]
Well, those which contain
`descriptionDetail = Isp:</b>`
in their config.

Quick search (5 seconds search, more time to copy and paste the result and type this):
```
GameData\Bluedog_DB\Parts\Solids\Scout\bluedog_Scout_Algol_Inline.cfg
GameData\Bluedog_DB\Parts\Solids\Scout\bluedog_Scout_Algol_Radial.cfg
```

**Comment by Invaderchaos** [comment]
Should be fixed now. Closing issue

**Comment by CobaltWolf** [comment]
> 
> 
> Well, those which contain `descriptionDetail = Isp:</b>` in their config.
> 
> Quick search (5 seconds search, more time to copy and paste the result and type this):
> 
> ```
> GameData\Bluedog_DB\Parts\Solids\Scout\bluedog_Scout_Algol_Inline.cfg
> GameData\Bluedog_DB\Parts\Solids\Scout\bluedog_Scout_Algol_Radial.cfg
> ```

You're right, I apologize. I've only used mass find-and-replace once or twice and forgot how easy it was.
