### ISSUE TITLE
Spherical probes with surface solar panels have max. sun exposure of 25%

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1144]
ModuleDeployableSolarPanel with panelType[SPHERICAL] - stock or Kerbalism the same - got max 25% sun exposure.
CYLINDRICAL something about ~ 32%.
This should be taken into account when creating the configs, as the chargeRate is too low in some cases.
Now I recognized this especially with the bluedog_Courier_Core.

**Comment by CobaltWolf** [comment]
@Gordon-Dry I think that's a function of most of the part not facing the sun, right? So we need to just compensate for it, not get it to 100%?

**Comment by Gordon-Dry** [comment]
The thing is that the parts need more EC than their own solar panels provide. This means those early and not so early probes are done after a couple of hours at best.

**Comment by CobaltWolf** [comment]
Honestly it feels like it would be easier to just scale down probe EC consumption... ah well.

**Comment by Invaderchaos** [comment]
I've never had an issue with spherical probes running out of EC, especially Courier probes. What sort of situations does it run out of EC in? After all, it's a relay probe which in my career typically uses less power than scientific probes. And with those probes, while transmitting experiments take up a lot of EC, I guess players are supposed to wait for a little for the ec to return before transmitting another experiment. Which spherical probes run out of EC besides courier?

**Comment by Gordon-Dry** [comment]
I guess it's Kerbalism patches not balanced enough. But only those probes which for weird reasons got ModuleDataTransmitter INTERNAL and DIRECT as well, besides built-in solar panels.

**Comment by Invaderchaos** [comment]
> I guess it's Kerbalism patches not balanced enough. But only those probes which for weird reasons got ModuleDataTransmitter INTERNAL and DIRECT as well, besides built-in solar panels.

Ok, so I assume this is then only a problem with Kerbalism patches then?
