### ISSUE TITLE
All engines with SafeSolid™ system lost their action group "Brakes"

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1146]
apollo-saturn-revamp that is.

The following engines:
```
GameData\Bluedog_DB\Parts\Gemini\bluedog_Gemini_RetroMotor.cfg
GameData\Bluedog_DB\Parts\Mercury\bluedog_Mercury_RetroRocket.cfg
GameData\Bluedog_DB\Parts\Mercury\bluedog_mercurySRB.cfg
GameData\Bluedog_DB\Parts\ProbeExpansion\AIMP\bluedog_AIMP_Star13.cfg
GameData\Bluedog_DB\Parts\ProbeExpansion\Explorer\bluedog_Explorer_Star17.cfg
GameData\Bluedog_DB\Parts\ProbeExpansion\JunoProbes\bluedog_Pioneer_1.cfg
GameData\Bluedog_DB\Parts\ProbeExpansion\JunoProbes\bluedog_Pioneer_VernierSolids.cfg
GameData\Bluedog_DB\Parts\Redstone\bluedog_Sergeant_11x.cfg
GameData\Bluedog_DB\Parts\Redstone\bluedog_Sergeant_1x.cfg
GameData\Bluedog_DB\Parts\Redstone\bluedog_Sergeant_3x.cfg
GameData\Bluedog_DB\Parts\Solids\IUS\bluedog_IUS_Orbus21.cfg
GameData\Bluedog_DB\Parts\Solids\IUS\bluedog_IUS_Orbus6.cfg
GameData\Bluedog_DB\Parts\Solids\Peacekeeper\bluedog_Athena_Castor30.cfg
GameData\Bluedog_DB\Parts\Solids\Peacekeeper\bluedog_Athena_Castor30XL.cfg
GameData\Bluedog_DB\Parts\Solids\Peacekeeper\bluedog_Peacekeeper_SR120.cfg
GameData\Bluedog_DB\Parts\Solids\Scout\bluedog_Scout_Antares_Basic.cfg
GameData\Bluedog_DB\Parts\Solids\Scout\bluedog_Scout_Antares_Inline.cfg
GameData\Bluedog_DB\Parts\Solids\UpperSolids\bluedog_UpperSolids_Altair.cfg
GameData\Bluedog_DB\Parts\Solids\UpperSolids\bluedog_UpperSolids_BE3.cfg
GameData\Bluedog_DB\Parts\Solids\UpperSolids\bluedog_UpperSolids_Star37BV.cfg
GameData\Bluedog_DB\Parts\Solids\UpperSolids\bluedog_UpperSolids_Star37FMV.cfg
GameData\Bluedog_DB\Parts\Solids\UpperSolids\bluedog_UpperSolids_Star48BV.cfg
GameData\Bluedog_DB\Parts\Titan\bluedog_Titan2_S2_VernierMotor.cfg
```
Have no more
```
		ACTIONS
		{
			ShutdownAction
			{
				actionGroup = Brakes
			}
		}
```

**Comment by spacefacey** [comment]
Huh, that's weird, I haven't had that issue on my end. But I also don't think all solid were meant to have that system, really only stuff for IUS, and Star series motors.

**Comment by Gordon-Dry** [comment]
Well, those ones who have SafSolid in the description by default should have SafeSolid ShutdownAction working.
And all those listed have it in the description but no ShutdownAction defined, so how do you not have that issue?

**Comment by Gordon-Dry** [comment]
Allright, there is a patch that should do the job:
GameData\Bluedog_DB_Extras\SafeSolid shutdown with AG Brakes\SafeSolid shutdown with AG Brakes.cfg

1. it got a lot of empty spaces in the path
2. by using :AFTER[zzzBluedog_DB] it depends on :FOR[zzzBluedog_DB] to work,  which is only found in GameData\Bluedog_DB_Extras\BDB_RealNames\RealNames.cfg

I suggest changing :AFTER[zzzBluedog_DB] to :AFTER[Bluedog_DB]

**Comment by Gordon-Dry** [comment]
Well, it should even be :FINAL to work in both cases, with and without BDB_RealNames.

**Comment by Gordon-Dry** [comment]
That's weird. MM cache says all is okay, all engines with SafeSolid got the action group, but ingame they don't.
Did something change in the basegame regarding how action groups are appended to modules?

**Comment by Rodg88** [comment]
commit 337d5da should have fixed
