### ISSUE TITLE
P-SSM-3L 0.3125 Payload Separation Mechanism & the 1/4 length Peacekeeper Interstage have a gap

### ISSUE THREAD

**Issue by spacefacey** [CobaltWolf/Bluedog-Design-Bureau#1147]
These two parts have an offset between them and the part they are attached to in the y axis.

**Comment by CobaltWolf** [comment]
Vertical Y axis? A man of taste, I see

**Comment by Invaderchaos** [comment]
Ok, think I fixed this one now
