### ISSUE TITLE
Minor description errors

### ISSUE THREAD

**Issue by Morphisor244** [CobaltWolf/Bluedog-Design-Bureau#1155]
Found some inconsistencies as I scoured the files for text errors, after I noticed a few during play (sorry I'm a nitpick).
Take it as you will of course.

- [x] Able upgrades: Part upgrades do not match the actual change in performance: first upgrade states improved Isp but this is not actually upgraded; 2nd upgrade state slower mass but instead the Isp is upgraded.

No real_description, despite the regular one using Kerbal names instead of real names.
Applies to:
- [x] bluedog_Agena_Engine_XLR81
- [x] bluedog_GATV_NuclearPackage
- [x] bluedog_Agena_SOT_GuidanceArray
- [x] [PARTUPGRADE] bluedog_Atlas1

- [x] bluedog_Agena_MultiPayloadAdapter real_description does not mention the ‘optional extra floating attach node’. Seems useful info to add there too?

- [x] bluedog_Mercury_PosigradeRocket has an odd real_title, being 'Mercury Posigrade'. Surely there's at least one word missing here at the end.

- [x] bluedog_Vega_EngineMount real_description notes cold-gas RCS thrusters, regular description does not. Part cfg does not include RCS modules, so real_description seems in error?

**Comment by CobaltWolf** [comment]
Thank you for this! I will try to make those corrections this afternoon. Keep letting us know if you find more. It's an oft overlooked but important thing to get right for player comprehension

**Comment by Morphisor244** [comment]
Yeah I do intend to go through the rest, I only managed to get to Delta so far, taking it alphabetically... it's a big thing.
The basic errors that don't need further investigation what the intention ought to be I'll put in directly through PR.

**Comment by CobaltWolf** [comment]
Appreciated!

**Comment by Morphisor244** [comment]
I've now run through the whole thing excepting Apollo, Saturn, Skylab; will do those on the Saturn branch. I edited the above post and submitted a PR for all the 'obvious' text fixes that needed doing.

**Comment by Invaderchaos** [comment]
Little confused with what you wrote about the Able engine. You mention two upgrades but there is only the default and one additional upgrade. Both have the correct stats, the second upgrade does appear to have the lower mass as well.

**Comment by Morphisor244** [comment]
> Little confused with what you wrote about the Able engine. You mention two upgrades but there is only the default and one additional upgrade. Both have the correct stats, the second upgrade does appear to have the lower mass as well.

You're right it's not very clear, sorry. I also got a little confused when looking at the actual upgrades vs. the description vs. the basic info in the upgrades file, they all say slightly different things.

For the Able engine, the actual upgrade has improved mass, improved thrust and Isp, but the thrust is not mentioned in the description, only in the detail; the basicinfo in the upgrades file only mentions 50% mass. The descriptionDetail line also mentions a different Vac Isp than the highest actual value in the atmosphereCurve, 270 vs. 272.

For the Ablestar engine, the actual upgrade has the Isp improvement commented out, yet the upgraded values are still noted in the info/description, whereas the mass reduction is not in the details.

**Comment by Invaderchaos** [comment]
Ok, that seems to be everything. Thanks for pointing these issues out! Closing the issue.
