### ISSUE TITLE
Fix RL-10 texture seam.

### ISSUE THREAD

**Issue by FoxxoniusAugustus** [CobaltWolf/Bluedog-Design-Bureau#116]

**Comment by CobaltWolf** [comment]
So, strangeness: This does not show up in Unity, meaning it's not an issue with the part but the exporter. Will investigate further.

**Comment by CobaltWolf** [comment]
Needs to get looked at again, i can't remember if this is still happening.

**Comment by VenomousRequiem** [comment]
It is.

**Comment by CobaltWolf** [comment]
y tho

**Comment by VenomousRequiem** [comment]
Because you SUCK

**Comment by CobaltWolf** [comment]
T.T
