### ISSUE TITLE
Cryogenic Engines overheat while using Real Fuels

### ISSUE THREAD

**Issue by Apollo1298** [CobaltWolf/Bluedog-Design-Bureau#1162]
Cryo Engines overheat far too quickly while using RF stocklike config. I tested this with only BDDB installed with dependencies using CKAN, and the issue didn't occur. Then I installed Real fuels on top of that, again with dependencies, and the issue happened exactly as I encountered it originally. 

KSP 1.12.2.3167 CKAN v1.30.4
List of mods installed to replicate:
B9 Part Switch (B9PartSwitch v2.19.0)
Bluedog Design Bureau (BluedogDB v1.8.1a)
Breaking Ground (BreakingGround-DLC 1.7.1)
Community Resource Pack (CommunityResourcePack 1.4.2)
DMModuleScienceAnimateGeneric (DMagicScienceAnimate v0.23)
Module Manager (ModuleManager 4.2.1)
Real Fuels (RealFuels 1:rf-v13.5.1)
Real Fuels: Stockalike RF Configs (RFStockalike v3.2.6.6)
Simple Adjustable Fairings - Plugin (SimpleAdjustableFairings v1.12.0)
Solver Engines plugin (SolverEngines v3.11.0)
Waterfall Core (Waterfall 0.7.0)

Apologies if this is the wrong place for this, as it could be a RF issue. Cryo engines from other mods, however, do not have this issue.

**Comment by zorg2044** [comment]
Could you let us know which engines specifically? And how long they are taking to overheat?

**Comment by Apollo1298** [comment]
I've been doing some testing. I get the problem on these engines, but that's all i have time to test right now: 
Daleth SSR68
LEH87H2
MBC-1
PL20x3
It seems like if i pick any BDDB engine from the sidebar after I search for "cryo" it will have the problem. The time to overheat seems to vary.

Ive attached a .gif that has the exact timings for overheats and shows what happening: 
[https://gfycat.com/chiefjampackedblackrussianterrier](https://gfycat.com/chiefjampackedblackrussianterrier)
 The last few minutes of the clip are interesting because it shows one engine quickly overheating and exploding, but while doing that the other engines don't seem to overheat, but after the first engine is gone, another one starts to overheat, although it runs out of fuel before it can explode. Again, this is a test instance that ONLY has these mods installed via CKAN:

B9 Part Switch (B9PartSwitch v2.19.0)
Bluedog Design Bureau (BluedogDB v1.9.0)
Breaking Ground (BreakingGround-DLC 1.7.1)
Community Resource Pack (CommunityResourcePack 1.4.2)
DMModuleScienceAnimateGeneric (DMagicScienceAnimate v0.23)
Module Manager (ModuleManager 4.2.1)
Real Fuels (RealFuels 1:rf-v13.5.3)
Real Fuels: Stockalike RF Configs (RFStockalike v3.2.6.6)
Real Plume (RealPlume 2:v13.3.2)
Simple Adjustable Fairings - Plugin (SimpleAdjustableFairings v1.12.0)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.8.14.0)
Solver Engines plugin (SolverEngines v3.12.0)
Waterfall Core (Waterfall 0.7.1)

**Comment by zorg2044** [comment]
hmm, could you try again after deleting Bluedog_DB/Patches/Thermal/engines.cfg ?

**Comment by Apollo1298** [comment]
Still doing the same thing

**Comment by zorg2044** [comment]
Hmm in which case you might need to follow up with RealFuels devs sorry.
