### ISSUE TITLE
Mercury Lab Crew Ladder issue

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1165]
bluedog_MiniLab_Ladder, the upper part (which is folded) is oriented 180° offset, that means as soon as a Kerbal climbs up the lower part and reaches the upper part the Kerbal turns around 180° and is head down. Pressing "W" (to climb up) makes the Kerbal climb down.
As soon as the lower part of the ladder is touched, the Kerbal turns around again, head up.

This results in an endless loop if the player dares.

--

My actual mission is in danger, I use that part below the hatch of a Mun lander... and cannot make a Kerbal get in.

**Comment by CobaltWolf** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/1124
