### ISSUE TITLE
No S3D config in bluedog_Thor_LR79

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1166]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/0c21a1ac819e842ecd7d81e6caabd461a41f17bc/Gamedata/Bluedog_DB/Parts/Thor/bluedog_Thor_LR79.cfg#L203

There is a description, but no Identifier and Data.

**Comment by zorg2044** [comment]
It has identical performance to the default stats. Just a different mesh as per the description

```A variant of the "Baldr" engine used on the Chryslus. While the performance is nearly identical, it can be visually distinguished by the lack of starter tanks.```

**Comment by Gordon-Dry** [comment]
Yes, it does, but it does not show up the same stats in VAB as the priority settings are out of order.
There is a reason for the PR.

**Comment by zorg2044** [comment]
Ok i mean its not a big deal to add that in, but I'm seeing the correct Isp and thrust in the VAB for that variant. What are you seeing?
