### ISSUE TITLE
Apollo Parachutes are crossing when deployed

### ISSUE THREAD

**Issue by Cowboy-WY** [CobaltWolf/Bluedog-Design-Bureau#117]
![apollo chutes](https://cloud.githubusercontent.com/assets/20691292/17267620/0ae4d6e0-55cb-11e6-976e-30c806c7a58d.png)

**Comment by CobaltWolf** [comment]
I rotate + reexported but haven't tested.

**Comment by Cowboy-WY** [comment]
Much better!  

![apolloparachutes](https://cloud.githubusercontent.com/assets/20691292/17464809/b0b7cfc0-5ca4-11e6-91d0-5eb61dd27ed4.PNG)
