### ISSUE TITLE
Lem no fuel in vab

### ISSUE THREAD

**Issue by Adamdroide** [CobaltWolf/Bluedog-Design-Bureau#1170]
When creating a new space ship using the lem module (Sina-MEM-ASC Ascent Stage Cockpit)
It display no fuel inside it.
Same thing with the descent stage
But when i'm using it with the saturn V craft file it shows me fuel inside it.
What can i do to have fuel in it ?
Same i've got texture bug with the gemini pods module it's black white and orange at the same time 
![Capture d’écran 2022-01-10 215558](https://user-images.githubusercontent.com/84043803/148838175-7c7472f4-2784-4429-994d-41c5b1a48ebe.png)
![Capture d’écran 2022-01-10 215706](https://user-images.githubusercontent.com/84043803/148838316-a81c582f-f644-40cc-b477-c647ba7064a0.png)

**Comment by zorg2044** [comment]
Is b9partswitch installed? Looks like it might be missing.

**Comment by Adamdroide** [comment]
I've done a clean reinstall of bdb mod and b9 and still got the problem 
![Capture d’écran 2022-01-11 181318](https://user-images.githubusercontent.com/84043803/148989678-a6ae5a92-7fbc-446b-812a-7312d41b7611.png)

**Comment by zorg2044** [comment]
sounds like a mod conflict

Need to see:

modlist (can be a full screenshot of your gamedata folder)

ksp.log  (Kerbal Space Program top level folder)
moduleManager.log (Kerbal Space Program/Logs/ModuleManager)
ModuleManager.ConfigCache (Kerbal Space Program/Gamedata)

**Comment by Adamdroide** [comment]
With some magic it's currently working so  i'm reinstalling my mod each to see if ther's any problem.
By the way when using your saturnV craft file the rocket is wobbling i don't why if you have a response :)
My mod install i'm installing other mod and telling you if ther's another incompatibility 
![Capture d’écran 2022-01-12 175323](https://user-images.githubusercontent.com/84043803/149185666-03485adf-4f9e-4f45-bc19-cf51ecffd30c.png)

**Comment by zorg2044** [comment]
``By the way when using your saturnV craft file the rocket is wobbling i don't why if you have a response :)``

This is just KSP issues with large rockets. Kerbal Joint Reinforcement takes care of it (I think KJR NEXT is most current).

If you dont want to use KJR I would suggest using editor extensions redux, set autostruts to grandparent for all. Then individually set the abort tower autostrut to heaviest.

**Comment by Adamdroide** [comment]
thanks i'm gonna use the newer version. 
By the way i'm still having issues when installing mod with the bdb mod i'm gonna install one by one to see which one is messing with it

**Comment by CobaltWolf** [comment]
> thanks i'm gonna use the newer version. By the way i'm still having issues when installing mod with the bdb mod i'm gonna install one by one to see which one is messing with it

Did you ever have any luck @Adamdroide ?

**Comment by Adamdroide** [comment]
> Did you ever have any luck @Adamdroide ?

Yes but still have missing part for rocket but not a big deal
