### ISSUE TITLE
Sarnus-SIV-3125 Fairing Base (PF) problem with Test Contract

### ISSUE THREAD

**Issue by maddavo** [CobaltWolf/Bluedog-Design-Bureau#1174]
Test contract requires part to be tested through staging sequence, but staging the fairings doesn't complete test. So seems no way to complete Test Contract.

**Comment by maddavo** [comment]
Also part mentions enabling of decoupler in PF module description but there is no button to enable the decoupler in VAB.

**Comment by zorg2044** [comment]
Im not sure whats going on there but I dont think we can attend to this anyway since the next update which is coming soon replaces this part and related test contracts entirely. Sorry you might just need to let that contract go.
