### ISSUE TITLE
Apollo Capsule Heatshield buoyancy too high

### ISSUE THREAD

**Issue by NatoKerbal** [CobaltWolf/Bluedog-Design-Bureau#1176]
if I land in the water the heatshield's buoyancy causes it to start flipping around and flying in the air, I fixed this by turning down scatterer waves however the capsule still floats too high to the point where it's floating in the air

**Comment by zorg2044** [comment]
is this with the current release of BDB or the development version from github?

**Comment by NatoKerbal** [comment]
Dev version

**Comment by zorg2044** [comment]
were you using a planet pack by any chance?

**Comment by NatoKerbal** [comment]
I'm using rescale

**Comment by CobaltWolf** [comment]
This seems to be an issue with Scatterer, I'm going to close. If need be, players will have to reduce the wave intensity.
