### ISSUE TITLE
LMSS-EX4 Fixed Solar Array has backwards Sun Exposure

### ISSUE THREAD

**Issue by Blu3wolf** [CobaltWolf/Bluedog-Design-Bureau#1177]
Ive launched a Two Room Space Station with the LMSS parts, with two LMSS-EX4 Fixed Solar Arrays. They work when the sun is on the brown rear side of the solar panels, and not when the sun is on the blue PV side of the panels. I've installed using CKAN.

**Comment by Rodg88** [comment]
![image](https://user-images.githubusercontent.com/2611674/184168034-003665b9-00e4-4c4b-8dc5-9684caec3129.png)
![image](https://user-images.githubusercontent.com/2611674/184168234-4381c4d4-ec7f-4423-8249-0b65cfb8458c.png)
Just one of the panels is receiving sunlight, no matter which variant is active. Maybe the BdbSymmetricalPart module isn't behaving correctly? Could possibly re-create the behavior with B9 if needed.

**Comment by Rodg88** [comment]
fixed
