### ISSUE TITLE
Skylab Micrometeoroid Shield not saving when quicksaving & quickloading

### ISSUE THREAD

**Issue by Arthurism** [CobaltWolf/Bluedog-Design-Bureau#1182]
So I've been having this problem, whenever I jettisoned the Hokulani OWS Orbital Workshop's shielding, and then I quicksave & quickload the shielding would come back and there would be no "Jettison Shielding" option.
</br>
![image](https://user-images.githubusercontent.com/80765214/157806977-f1c4c55a-4b7b-4cc9-8966-adadfa13cb4f.png)
↑ Before quicksaving, after jettisoning shielding.
</br>
![image](https://user-images.githubusercontent.com/80765214/157807035-4e52f351-e868-406a-b223-887c7419341e.png)
↑ After quickloading.
</br>

**My GameData Folder:**
![image](https://user-images.githubusercontent.com/80765214/157807407-2d3a6a82-8bc3-4b55-8f0c-9bc97a819f4e.png)

**Comment by zorg2044** [comment]
This is a known issue for which we have no complete solution. Workaround is to ensure the workshop (the part with the shield) is NOT the root part. Ideally the S4B instrument unit should be the root of a skylab build.

https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/1093
