### ISSUE TITLE
Apollo Service Module broken texture

### ISSUE THREAD

**Issue by Arthurism** [CobaltWolf/Bluedog-Design-Bureau#1183]
Why does my Apollo service module look like this sometimes?
![image](https://user-images.githubusercontent.com/80765214/158300643-afc9d723-7125-42b0-8f93-9836ed60c050.png)

The only thing i can do to fix it is by restarting KSP entirely.
Even if I changed the paintjob it still looks like that until I restart KSP.

**Comment by Arthurism** [comment]
![image](https://user-images.githubusercontent.com/80765214/158303614-023456fc-9036-441d-91d2-29e738f643fb.png)

**Comment by zorg2044** [comment]
Please make sure your b9partswitch is up to date and try a clean install of BDB as well.

If that doesnt work please see if removing moduleManagerWatchdog does anything. Not sure about its effects so would like to rule it out.

If the problem still persists please post your moduleManager.log and modulemanager.configcache

**Comment by zorg2044** [comment]
Oh and remove BDB Now In Colours as well. Not sure if thats up to date with the newer parts and there might be some conflicts

**Comment by Arthurism** [comment]
Ah okay, let me try doing that.

**Comment by Arthurism** [comment]
> Oh and remove BDB Now In Colours as well. Not sure if thats up to date with the newer parts and there might be some conflicts
> 
> If thats the culprit you can just go ahead and delete the apollo related patches in BDBNIC if you want to continue using it. All variants are now provided natively in BDB for Apollo.

I've been having this problem before I installed BDBNIC I'm pretty sure.

**Comment by FuryFire2004** [comment]
Rule of Thumb btw when Dealing with broken mods look at the effects of removing sub-mods such as for example bdb extras and bdb  now in colors. usually sub-mods can cause funky behavior more often then other stuff.

**Comment by FuryFire2004** [comment]
although now that i look at it it could be tuFX
