### ISSUE TITLE
Skylab Phase 2

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#1185]
**LM ATM adapter**

- to be made from LM Lab parts

**25kw Power Module**

- [x] solar panels
- [x] radiators
- [x] Power tower service module
- [x] solar array support structure
- [x] extended docking adapter 0.625/0.9375 ports
- [x] berthing ports

**Skylab Reboost - Teleoperator Retrieval System**

- [x] Probe core
- [x] Propulsion kit
- [x] Solar panel
- [x] Omni antenna
- [x] Camera
- [x] Light
- [x] mini docking ports

**EOSS SII interstage version**

- [x] Aft module integrated with SII interstage
- [x] Solar panels
- [x] Telescope module
- [x] Experimental rollout solar panel
- [x] Mass spec
- [x] multispec boom
- [x] microwave spec boom
- [x] scaterrometer
- [x] Radar antenna
- [x] Comm antenna small
- [x] Comm antenna large

**LTEP**
- [ ] LTEP telescope

**Comment by zorg2044** [comment]
Link to phase 1: https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/1059

**Comment by zorg2044** [comment]
![image](https://user-images.githubusercontent.com/39182212/164521107-b32643cc-0fd8-4e8e-b809-c245bf472b97.png)

**Comment by LilBread402** [comment]
Would it be possible to add the ability for solar panels on the ATM to retract?

**Comment by CobaltWolf** [comment]
Should be easy enough, it's just changing a line in the config.

**Comment by Nuggets4321** [comment]
I hate to bug the dev team but is the Radiators for the 25kw power tower expected soon?

**Comment by zorg2044** [comment]
No idea... prob not that soon. Other things on my plate right now.

**Comment by Nuggets4321** [comment]
alright all good

**Comment by zorg2044** [comment]
well its done lol

**Comment by CobaltWolf** [comment]
Going to close this issue. @zorg2044 , feel free to make a new one for LTEP if you ever start on it
