### ISSUE TITLE
Belle Nose Cone decoupler does not work

### ISSUE THREAD

**Issue by Cowboy-WY** [CobaltWolf/Bluedog-Design-Bureau#119]
missing "MODULE" line in config file

I'm fixing it in the bulkheadProfiles update I am working on.

**Comment by CobaltWolf** [comment]
Thanks! Would I be able to make a post on the thread recognizing you for all you've done lately? I know some people prefer to lurk as much as possible. :) 

-----Original Message-----

**Comment by Cowboy-WY** [comment]
I am usually pretty low key, but it wouldn't bother me either way.  Thanks for asking.

**Comment by Cowboy-WY** [comment]
Included this fix in Pull Request #120

**Comment by Cowboy-WY** [comment]
Verified working - Ready for closure
