### ISSUE TITLE
Craft Files for Saturn Update

### ISSUE THREAD

**Issue by friznit** [CobaltWolf/Bluedog-Design-Bureau#1198]
Scrubbed all the old craft file, bumped versions to 1.12.3, renamed a bunch for clarity and removed a few obsolete ones.  Recommend you delete all the old craft in the folder and replace with these (i.e. don't merge them)

[Craft Files.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/8499625/Craft.Files.zip)

Added a bunch of Saturn variants to accompany the Unofficial Wiki guides:

- Super Jupiter
- Saturn Development Concepts (A1, C1, C2, C4)
- Saturn I Blk2 SA-5 & SA-6 AS101 (with Apollo BP13)
- Saturn IB
- Saturn IB MLV (1967 AAP study for Earth Orbital Missions)
- Saturn IB SRM (1966 Study UA - INT-05 to INT-27)
- Saturn V
- Apollo 11 CM
- Apollo 17 CM
- ASTP
- Saturn Intermediate Payload (1966 Intermediate Payload Study INT-17/18/19/20)
- Saturn V MLV (1965-1968 AAP Studies & NASA ELV)
- Saturn V Derivatives (S-ID)
- ETS Saturn IC & MB
- ETS Apollo
- AARDV
- ETS AARDV Block II
- Skylab
- ETS Spacelab
- Venus Flyby
- Pegasus
- Big G (NASA conical concept for Saturn)
- Big G (USAF concept for Titan)

**Known omissions:**

- Agena Horizon Scanner
- Staging is not correct on almost all the builds

Let me know of anything missing/incorrect below

**Comment by Aelfhe1m** [comment]
Thanks for providing these. I haven't had time to flight test most of them, but I did open them all in the VAB to have a look at them and noticed a few errors/omissions slipped through the cracks during the SAF replacement. (I pulled the craft from the main branch using GitHub desktop after the launch of v1.10 and loaded them into a newly created clean sandbox save of 1.12.3)

Craft still with stock style fairing:

- Athena IIcS-4
- Jupiter A (not sure there's a suitable SAF for this one)
- KH-9 Hexagon
- Minotaur
- Minotaur V
- Minotaur VI
- Strawman
- Strawman 4
- Titan 34D IUS

Craft with both stock style and SAF fairings:

- Saturn H03 (ETS)
- Saturn M02 (ETS)
- Saturn M43 (ETS)

**Comment by Aelfhe1m** [comment]
Thanks for providing these. I haven't had time to flight test most of them, but I did open them all in the VAB to have a look at them and noticed a few errors/omissions slipped through the cracks during the SAF replacement. (I pulled the craft from the main branch using GitHub desktop after the launch of v1.10 and loaded them into a newly created clean sandbox save of 1.12.3)

Craft still with stock style fairing:

- Athena IIcS-4
- Jupiter A (not sure there's a suitable SAF for this one)
- KH-9 Hexagon
- Minotaur
- Minotaur V
- Minotaur VI
- Strawman
- Strawman 4
- Titan 34D IUS

Craft with both stock style and SAF fairings:

- Saturn H03 (ETS)
- Saturn M02 (ETS)
- Saturn M43 (ETS)

**Comment by zorg2044** [comment]
Thanks. Will do a cleanup for the next update. Theres also some extraneous nodes on some S4B mounts in some craft that were built before other variants were added.
