### ISSUE TITLE
LM Cockpit facing the wrong way

### ISSUE THREAD

**Issue by Arthurism** [CobaltWolf/Bluedog-Design-Bureau#1202]
![image](https://user-images.githubusercontent.com/80765214/163696787-6cd1478c-5590-4703-976d-45d9fb95854e.png)

How can I fix this? My LM has its cockpit facing backwards.

**Comment by zorg2044** [comment]
Unfortunately this seems to happen from time to time for some people, not sure why. Its correct on our test installs though. Please see if reloading the save fixes it?

![image](https://user-images.githubusercontent.com/39182212/163868168-85280622-b3fa-43af-af75-48eecb477832.png)

**Comment by CobaltWolf** [comment]
I bet it's a root part issue, Zorg.

**Comment by Arthurism** [comment]
> Please see if reloading the save fixes it?

![image](https://user-images.githubusercontent.com/80765214/164128123-b8368319-91e9-4a51-a4dd-56f447a05b9e.png)
Ah ye it's good now thanks

**Comment by Arthurism** [comment]
uhh wait
I noticed that I get that bug every time I dock with the LM using another vessel when I'm in cockpit view

**Comment by zorg2044** [comment]
Unfortunately we are unlikely to be able to fix this in the short term. The IVAs were all made for us by other people ages ago, they didnt match up the orientation of the newer spacecraft we made so JSO wrote a module for our plugin that rotates the IVAs correctly. It seems to bug out under certain conditions and it may not be so easy to fix. The permanent solution is likely remaking the IVAs from scratch to match the new craft models. Which is unlikely to happen soon. Though if time allows lets see.

**Comment by Arthurism** [comment]
Ah okay
Anyways thanks for helping! You can close this issue if you want

**Comment by zorg2044** [comment]
We'll keep this open for now since your feedback here is I think the first we've heard about how to reproduce it (dock in internal view). Might help JSO if they take a second look.

**Comment by zorg2044** [comment]
Referenced in the main issue for this.
