### ISSUE TITLE
The Advanced Heatsheild Textures are Acting Wierd 

### ISSUE THREAD

**Issue by Nuggets4321** [CobaltWolf/Bluedog-Design-Bureau#1205]
![Uploading Kerbal Space Program Screenshot 2022.04.20 - 22.05.22.30.png…]()

**Comment by Nuggets4321** [comment]
![Kerbal Space Program Screenshot 2022 04 20 - 22 05 22 30](https://user-images.githubusercontent.com/99323841/164228117-9934759f-b747-4e60-817c-c1c617d35d1e.png)

**Comment by zorg2044** [comment]
yup this is a known issue, will be fixed very soon.

**Comment by Nuggets4321** [comment]
Oh Thanks
