### ISSUE TITLE
Lem decent stage cross-feed issue

### ISSUE THREAD

**Issue by lsamman** [CobaltWolf/Bluedog-Design-Bureau#1219]
It’s really freaking annoying to have to use fuel ducts to have the lem decent stage have more fuel can it just be able to drain from radial tanks attached to it?

**Comment by CobaltWolf** [comment]
Yeah, easy fix. 

I'm pretty sure it was set to false because the old LM didn't have a decoupler part between the ascent and descent stage, so it was possible for the ascent stage to have its fuel taken during descent. Shouldn't be an issue now.
