### ISSUE TITLE
I don't know if this is BDB or another mod but im having werid glitches

### ISSUE THREAD

**Issue by Nuggets4321** [CobaltWolf/Bluedog-Design-Bureau#1223]
![unknown](https://user-images.githubusercontent.com/99323841/168954703-274a54ec-32ed-4f19-8e78-7d2496ccdc70.jpeg)
![image](https://user-images.githubusercontent.com/99323841/168954745-f737f9be-a56b-4b8d-bdd5-a93ef9241129.png)

**Comment by Nuggets4321** [comment]
It was Textures Unlimited Dev mode

**Comment by Nuggets4321** [comment]
It appears to be just with plumes now

**Comment by Nuggets4321** [comment]
Looks like Z fighting

**Comment by zorg2044** [comment]
What engines are those?

**Comment by Nuggets4321** [comment]
It’s the J-2

**Comment by Nuggets4321** [comment]
i think the newest scatterer has been doing this

**Comment by Nuggets4321** [comment]
Its a issue with the newest scatterer
