### ISSUE TITLE
small gap on the SLA-IU

### ISSUE THREAD

**Issue by Nuggets4321** [CobaltWolf/Bluedog-Design-Bureau#1225]
![Kerbal Space Program Screenshot 2022 05 19 - 21 31 31 56](https://user-images.githubusercontent.com/99323841/169424152-269dd4ee-c1c1-43a8-8a4d-4aeae5be15bf.png)

**Comment by zorg2044** [comment]
Im not seeing this, though I've heard this can be caused by loading sub-assemblies sometimes.
