### ISSUE TITLE
Kane SA MSM boilerplate is the wrong size

### ISSUE THREAD

**Issue by dangerzachattack** [CobaltWolf/Bluedog-Design-Bureau#1228]
I've noticed that the size of this part is not the 2.5m that BDB uses for the kane parts, and it is really anoying (and i cant even use tweakscale to fix it!) Heres some photos. the 1st one shows the gap in question. the 2nd photo shows the part from an overhead veiw along side the Kane Service module. the 3rd photo shows the same situation from the side.

![Screenshot 05_23_2022 04_37_01](https://user-images.githubusercontent.com/106042832/169727569-b5dabb8e-0991-4d3f-82f5-6bc1b8a97ddc.jpg)
![Screenshot 05_23_2022 04_45_42](https://user-images.githubusercontent.com/106042832/169728238-2dc6d6cc-0556-4157-8234-2412f8833bd2.jpg)
![Screenshot 05_23_2022 04_47_17](https://user-images.githubusercontent.com/106042832/169728239-1f8ba4d6-10c2-4961-a242-d1c2946793d2.jpg)

**Comment by dangerzachattack** [comment]
Oh, and the Sarnus-SIV A6BP PAyload adaptor has the same problem.

**Comment by zorg2044** [comment]
Do you have the saturn rescale patch from BDB extras from an older release installed? That is now defunct and should be deleted.

If not its something else external to BDB rescaling those parts.

**Comment by dangerzachattack** [comment]
> Do you have the saturn rescale patch from BDB extras from an older release installed? That is now defunct and should be deleted

Thats exactly it! thanks @zorg2044
