### ISSUE TITLE
Titan SRB nose chute shows deployed diamater in VAB

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1229]
Titan SRB nose chute is showing it's like 16 m wide in the vab engineer's report, causing issues on low level launchpads or KK launchsites. Don't know what would fix it, maybe some tag on the canopy mesh. I've heard of it being fixed just by re-exporting the mu too.

**Comment by MgnfcntBstrd** [comment]
I also have this issue.  I used Sarbian's Debug Stuff to show... stuff.  Hope that helps.

![image](https://user-images.githubusercontent.com/94755111/200416154-755f94c2-236e-4c93-b1de-bed1cc06165a.png)

For comparison:

![image](https://user-images.githubusercontent.com/94755111/200416734-0b278c51-ccca-4771-ae29-2d170d77291e.png)

**Comment by MgnfcntBstrd** [comment]
The Big-G parachute also has a similar issue.
![image](https://user-images.githubusercontent.com/94755111/201001068-287da7f3-0d51-451a-8ce9-41b499e6bd44.png)

**Comment by Rodg88** [comment]
No longer an issue, possibly due to KSPCF
