### ISSUE TITLE
OAO telescope experiments nonfunctional with spacedust installed

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1231]
bluedog_OAO3_PEP_instrument wasn't performing any experiments for me, pretty sure due to having SpaceDust installed. SD also uses the same animation as the DM science modules, and I think that's what was causing the interference. 

This patch fixed it for me, but it isn't ideal as it disconnects the experiments from the animation:
https://gist.github.com/Rodg88/738567807c0f92ea1911506e6f19c3cd

One possible solution is a 2nd duplicate deploy animation with a unique name, so SpaceDust has it's own animation without interfering with DMscienceanimate (or getting DMscienceanimate compatibility added to SD)

**Comment by zorg2044** [comment]
For me at least, even the generic animation module wouldnt play with a SD module on the part. Going to just do a +PART
