### ISSUE TITLE
Surveyor Part Wishlist

### ISSUE THREAD

**Issue by Invaderchaos** [CobaltWolf/Bluedog-Design-Bureau#1232]
Base Surveyor:
- [ ] Default Bus (with landing radars)
- [ ] Default Bus (w/out landing radars)
- [ ] Empty Bus (structural part, no probe core)
- [ ] TD-339 Rocket Vernier Engine (Surveyor Gimbal Mount)
- [ ] TD-339 Rocket Vernier Engine (Fixed, stand-alone)
- [ ] Landing Leg (RCS)
- [ ] Landing Leg (No RCS)
- [ ] HGA/Solar Mast
- [ ] TV Camera
- [ ] Soil Scoop
- [ ] Alpha Scattering Experiment
- [ ] Omni Antenna(s)
- [ ] Canopus Tracker/Control Equipment Platform
- [ ] Surveyor Adapter

Surveyor B/Surveyor Orbiter:
- [ ] Surveyor Bus Variant Stuff(Extended Fuel, smaller diameter solid motor mount, etc.)
- [ ] Surveyor Orbiter Experiment Package (includes camera comparable to Lunar Orbiter)
- [ ] Surveyor Orbiter Solar Panel (includes RCS)
- [ ] Surveyor Orbiter Tracking HGA

Misc Surveyor Proposal Stuff:
- [ ] Flat Triangular Solar Panel
- [ ] Surveyor Landing Leg w/ folding solar panel
- [ ] Surface Sample Drill (includes X-ray/alpha spectrometer experiment and mass spectrometer experiment)
- [ ] Neutron Activator Experiment
- [ ] SNAP-11 radially attachable RTG (for night operations)
- [ ] Upper Thermal Compartment (maybe experiment container)
- [ ] TD-339 Rocket Vernier Engine Extended Nozzle
- [ ] Surveyor Internal Fuel Tank? (LF only/no solid)

Surveyor Rover (UNLIKELY)
- [ ] Surveyor-Rover Attachment Hinge (BG Robotics)
- [ ] Rover Probe Core
- [ ] Rover Aft Section (RTG)
- [ ] Rover Aft Section (Hollow)
- [ ] Rover Tank Tread
- [ ] Rover TV Camera
- [ ] Rover Penetrometer Experiment
- [ ] Rover High Gain Antenna (Tracking)
- [ ] Rover Omni Antenna
- [ ] Rover RF Ranging Antenna

**Comment by FuryFire2004** [comment]
is this a birthday gift list for you?

**Comment by Invaderchaos** [comment]
> is this a birthday gift list for you?

Lol probably should’ve worded it differently than wishlist
