### ISSUE TITLE
Bit of an issue i noticed when trying to dock the 25kw solar array to skylab. 

### ISSUE THREAD

**Issue by FuryFire2004** [CobaltWolf/Bluedog-Design-Bureau#1249]
because the skylab solar telescope panels are not retractable it basically means you have to break the panels via collision to actually dock the 25kw solar array, I'm assuming that's not intended, so um hope this bug report helps.

**Comment by zorg2044** [comment]
Realistically they would be removed on EVA (such as using an Engineer kerbal). But since people kept asking I made them retractable as of 3 weeks ago f06785ac57724921b8d316bde0f2bd5722bdce89
