### ISSUE TITLE
S-IVF collider problem

### ISSUE THREAD

**Issue by biohazard15** [CobaltWolf/Bluedog-Design-Bureau#1256]
See screenshot:
![screenshot47](https://user-images.githubusercontent.com/62663094/179654509-34ea47f2-3506-4ac2-925f-641af96e84e4.png)

**Comment by Rodg88** [comment]
Not sure what's wrong here?

**Comment by CobaltWolf** [comment]
@Rodg88 I think they're saying that the APS clips into the stringers. I need to make the colliders flush with the slightly raised stringer areas and not the smooth tank skin which is the bit that's actually 6.25m
