### ISSUE TITLE
S-IC 6x skirt variant mesh bugs

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1261]
![image](https://user-images.githubusercontent.com/2611674/180022397-9d9a3e02-1fa7-41d5-ba32-18d0715afad8.png)

**Comment by CobaltWolf** [comment]
Wow I hate that.

**Comment by CobaltWolf** [comment]
Silver lining tho - at least someone noticed and mentioned before we released it!
