### ISSUE TITLE
LRV base

### ISSUE THREAD

**Issue by Raqnick** [CobaltWolf/Bluedog-Design-Bureau#1272]
When changing LRV Deployment slider servo angle it's flipping the craft

**Comment by Raqnick** [comment]
Addition:it happens only on the Moon(1km above till surface).Everything is great in the VAB or on the launchpad

**Comment by Rodg88** [comment]
Do you have KJR (RO Branch) installed? It’s incompatible for this reason. If you replace it with KJR:Next it should solve the issue

**Comment by Rodg88** [comment]
KJR: Next is here https://forum.kerbalspaceprogram.com/index.php?/topic/184206-kerbal-joint-reinforcement-next/
