### ISSUE TITLE
S-IVF APS mount panel

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1276]
The S-IVF texture's mounting points for the APS (I presume thats what they are) don't match the profile of the small or large APS 
![image](https://user-images.githubusercontent.com/2611674/182629189-cfdd4a3e-85f6-49da-8716-6469a25bfe0e.png)
![image](https://user-images.githubusercontent.com/2611674/182629397-2a39c4c8-b5a2-45c9-9720-3f87bb0e7202.png)

It might be better to just have the normal paint in the area, though stopping the stringers gives a nice indication for placement. eg:
![image](https://user-images.githubusercontent.com/2611674/182630541-1edf9eb5-1b93-4f5a-a56d-e1d4ef13c2f6.png)

**Comment by CobaltWolf** [comment]
Yeah that's probably best, will have to wait until I have dev time at my home PC
