### ISSUE TITLE
Flying Dish

### ISSUE THREAD

**Issue by Raqnick** [CobaltWolf/Bluedog-Design-Bureau#1277]
The Dish Antennae is flying away from the craft(can be fixed by timewarp,but only for a minute
![Kerbal Space Program_2022 08 01-20 52](https://user-images.githubusercontent.com/95162518/182851140-040660e0-27a8-426f-866e-099df5fa8dca.png)
)

**Comment by Rodg88** [comment]
Can you upload your ksp.log file?

**Comment by Raqnick** [comment]
https://drive.google.com/file/d/1Ldfg7r9479KKuDcYct4iGkDQlwUOWpS2/view?usp=sharing
Sorry,can't load here,file is 2mb off limit

**Comment by Rodg88** [comment]
It might be an issue with Trajectories/Траектория, it's spamming the log a lot in your log. Try uninstalling that and see if that helps?

**Comment by Raqnick** [comment]
I had no such problems on stable verison.But i think i can try this

**Comment by CobaltWolf** [comment]
Worst we eliminate that as a culprit. I've never seen this, at least that I can remember

**Comment by Raqnick** [comment]
Video of spacecraft separation:https://drive.google.com/file/d/13be3U7lF-FHGO2wfCg6RAS5VbhXyQ2Y-/view?usp=sharing

**Comment by Rodg88** [comment]
Haven't been able to reproduce

**Comment by OrbitalManeuvers** [comment]
@Rodg88 as requested

https://drive.google.com/drive/folders/1ylGn38fnhDi_vyQV1d47QsU6J-p1bF1u?usp=share_link

Zipped since the cache file is 23MB
