### ISSUE TITLE
Note for Atlas Revamp

### ISSUE THREAD

**Issue by Sgt-Shutesie** [CobaltWolf/Bluedog-Design-Bureau#1278]
Matt told me to do an issue for this for zorg or whoever gets around to the atlas revamp.

The current atlas tapered section is a straight angle, and is not filleted, like the real thing.

![image](https://user-images.githubusercontent.com/17996283/182949818-e0c56b11-7def-4aac-8bc1-9fe2d2a56e02.png)

![image](https://user-images.githubusercontent.com/17996283/182949864-c97a4681-185b-49c4-8eb9-ae5fe7c0216f.png)

I imagine the best way to implement this is like how it is done on SIV, where the filleted section is part of the tapered section.

**Comment by CobaltWolf** [comment]
Copied to main Atlas revamp issue, closing this
