### ISSUE TITLE
Apollo Feedback

### ISSUE THREAD

**Issue by raveloda** [CobaltWolf/Bluedog-Design-Bureau#128]
- [x] Apollo Engine thrust is rather low for the weight of a loaded CSM and later on also carry the LEM
- [x] Apollo RCS sprite effect is not playing from the nozzles, but rather behind them
- [x] No RCS on the capsule? Not sure if you intended to have some or not
- [x] Not just Apollo, but a number of parts actually say they have Life Support supplies, but there are no LS configs for Snacks, USI-LS, TAC-LS, etc (You're probably working on these for Apollo and MOL, but I wanted to check)

**Comment by raveloda** [comment]
If you're adding LS supplies to things, I can help test the new weight stats. It may need tweaking because some, like USI "Supplies" can weigh a lot, specially for an Apollo-styled Mun mission. USI Supplies for a crew of 3 can be a lot. I think it will be a little over 120 supplies for a week, per kerbonaut

**Comment by jsolson** [comment]
This will all change as we fiddle with things, but based on today's specs:

Kane Command Service Module:
TWR Wet: 0.38
TWR Dry: 0.64
DV: 1629.95

Apollo Command Service Module:
TWR Wet: 0.31
TWR Dry: 0.79
DV: 2919.56

**Comment by CobaltWolf** [comment]
Second and third definitely need to be changed. I don't know what to do
about life support stuff. I don't think any of us play with them.

We'll have to wait until the entire system is in game to balance things
like the TWR.

Matthew Mlodzienski
3D Animation and Visual Effects
Westphal COMAD 2017

**Comment by jmrd98** [comment]
I (Komodo) do use life support, albeit modded a bit. (I use USI, but tweaked the consumption down, as they assume 6hr kerbal days while I prefer 24hr... anyway!...) My short term non-copout suggestion would be to look at MOLE and Habtech, who do ship life support patches, for numbers for similar-ish modules as the ones here.

I haven't used TAC in a very long time, and i've not used Kerbalism at all. SNACKS are easy to support, if it comes to that, though :)

Life support in general would depend on how long you expect them to be in the can for... for the MOL parts, I can see this being significant, with Apollo being right behind in endurance.

**Comment by CobaltWolf** [comment]
Komodo, see #34

**Comment by jmrd98** [comment]
Referencing #147 here for completeness' sake.

**Comment by CobaltWolf** [comment]
all set here
