### ISSUE TITLE
Parts won't appear

### ISSUE THREAD

**Issue by Snappydragon93** [CobaltWolf/Bluedog-Design-Bureau#1286]
I've downloaded the mod but NONE of the parts will appear. Why am I only one having this problem?

**Comment by Rodg88** [comment]
Sounds like it's been installed incorrectly. These are the folders you should have in your gamedata: https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/master/Gamedata

**Comment by Snappydragon93** [comment]
@Rodg88 I checked to files they seem to be ok but the parts still don't appear. It also says a major error or something happened. I don't know if this correlates to my problem.

**Comment by Rodg88** [comment]
If you upload your KSP.log somewhere like here https://gist.github.com/ and link it here I can take a look
