### ISSUE TITLE
Case sensitive folder

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#1291]
When installing on a case sensitive operating system like linux, the `Gamedata` folder in the download doesn't extract into KSP's `GameData` folder, meaning that I have to manually copy it over instead of just unzipping it directly into the KSP folder. I realize this is the most minor of nitpicks but it caused me no end of trouble trying to figure out where the mod went.

**Comment by Rodg88** [comment]
This is surprisingly non-trivial, mainly thanks to GitHub it seems. I'm trying something, but it might not be worth the hassle, or even work.

**Comment by Rodg88** [comment]
Looks like what I tried won't be suitable, so we're actually unable to do this sorry. (git would delete and re-create each file with a new path, destroying all file history.)
