### ISSUE TITLE
Mesh names on LM descent stage and Q3 storage

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1296]
The foil meshes on the LM descent stage tank assembly, and the Q3 storage, need unique mesh names. The LM ascent stages, legs, and MESA are all fine as-is.

**Comment by CobaltWolf** [comment]
@Rodg88 this work for the descent stage? 
![image](https://user-images.githubusercontent.com/16356162/187082844-77698fc6-301d-48ce-b535-8a55acd09063.png)

**Comment by Rodg88** [comment]
just the tank cover on taxi subtype needs a pass too, pCube180 and pCube198 seem to be duplicates too
