### ISSUE TITLE
Are shared assests needed?

### ISSUE THREAD

**Issue by Snappydragon93** [CobaltWolf/Bluedog-Design-Bureau#1297]
Part won't appear wondering if shared assets are needed.

**Comment by Rodg88** [comment]
Not sure what you mean by shared assets. upload and post your KSP.log and I'll have a look.

**Comment by Snappydragon93** [comment]
Sorry Im unsure what a KSP.log is I started KSP a week ago

**Comment by Rodg88** [comment]
Well it seems like an installation issue, You should have this inside your Kerbal Space Program/GameData folder:
![image](https://user-images.githubusercontent.com/2611674/187053582-d553b36d-1731-49fa-90b8-4d000e02dd00.png)

If there's still an issue after making sure it's set up that way, then post the KSP.log file. It is in the main Kerbal Space Program folder. Zip it and upload somewhere and link it here

**Comment by Rodg88** [comment]
@Snappydragon93 closing for now, if you need more help you can also post in the forum thread: https://forum.kerbalspaceprogram.com/index.php?/topic/122020-1123 
But even when posting there, your KSP.log file will still be needed for people to help properly.
