### ISSUE TITLE
KH-9 camera model tweaks

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1300]
The main camera part could use a very minor restructure to fix some b9 specmap switching errors:
![image](https://user-images.githubusercontent.com/2611674/187428279-2ad8ab3d-b172-46de-86d4-daca88d31203.png)
The two highlighted meshes called "Foil" should be replaced with empty transforms with the same name, while the actual meshes should be children of the new "Foil" transforms and renamed to something like "foilmesh"

**Comment by CobaltWolf** [comment]
![image](https://user-images.githubusercontent.com/16356162/192390246-8919c442-b406-4ae9-9dcc-fdbaa56a2f6d.png)

as requested, close the issue when verified w/ new B9 switch

**Comment by Rodg88** [comment]
verified and working without errors now
