### ISSUE TITLE
Long agena tank flag transform mesh maybe too close to tank skin

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1306]
https://forum.kerbalspaceprogram.com/index.php?/topic/122020-1123-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v1104-%D0%BB%D1%83%D0%BD%D0%B0-19july2022/&do=findComment&comment=4172037

**Comment by CobaltWolf** [comment]
I checked, shouldn't be an issue. Maybe something with an FX plugin they were using.
