### ISSUE TITLE
Backwards IVA on Apollo LEM

### ISSUE THREAD

**Issue by blufor878** [CobaltWolf/Bluedog-Design-Bureau#1308]
So an odd issue I noticed with the standard LEM module. The IVA is facing backwards compared to the physical model. I found a temporary fix where you have a kerbal EVA and enter the LEM whenever this happens. Unfortunately the problem gets reset by IVA switch, whereby you have to enter and exit the LEM again. I should also note that the other LEM variants (lab, shelter, and taxi) are not affected. Their IVAs show up in the proper orientation. If you need any more details, I will do the best I can to provide them. I should also note that I am currently running the current version of the devbranch as well (as of 9/8/22).

**Comment by Rodg88** [comment]
Yeah this is a known issue due to the iva models being backwards and using a custom module to correct them, but the module is a little unreliable. It’s on the todo list already afaik

**Comment by blufor878** [comment]
> Yeah this is a known issue due to the iva models being backwards and using a custom module to correct them, but the module is a little unreliable. It’s on the todo list already afaik

Cool beans! As long as it's a known issue then we're good. You guys have produced a really good mod here, and in my opinion have done a really good job of keeping tabs on everything. Thank you so much!
