### ISSUE TITLE
Leo-M-59F Structural Plate has incorrect description (bluedog_Gemini_Structure_A)

### ISSUE THREAD

**Issue by Cowboy-WY** [CobaltWolf/Bluedog-Design-Bureau#131]
It is just a structural adapter 1.875 - 1.5

description  = This orbital service module includes a large supply of mono propellant, as well as large RCS thrusters that double as main engines. It also includes a built in decoupler, which must be manually staged.

**Comment by CobaltWolf** [comment]
ack, that's Beale's doing. We'll have to fix it. I'm at work right now, but I think the new description would be:

description = 18.75m to 1.5m structural adapter for Leo parts.

**Comment by Cowboy-WY** [comment]
Updated description in Pull request #137
