### ISSUE TITLE
LM Problem

### ISSUE THREAD

**Issue by FrostyDog69** [CobaltWolf/Bluedog-Design-Bureau#1310]
I was just wondering why the LM looks like the real thing as far as the decent stage color goes, in the VAB it comes up looking like a reflective gold foil but when in a mission or in space it’s dark and you can’t see any gold even with the sun shining right on it.

**Comment by Rodg88** [comment]
Can you post a screenshot of it in space?

**Comment by zorg2044** [comment]
> I was just wondering why the LM looks like the real thing as far as the decent stage color goes, in the VAB it comes up looking like a reflective gold foil but when in a mission or in space it’s dark and you can’t see any gold even with the sun shining right on it.

Make sure you have reflections turned on in the game settings.

**Comment by FrostyDog69** [comment]
> 

Yes just give me about 10 minutes

**Comment by FrostyDog69** [comment]
I can try yes

**Comment by FrostyDog69** [comment]
Also my reflects are turned on and it is still very dark when in space or sitting on the Mun

**Comment by FrostyDog69** [comment]
>
![image](https://user-images.githubusercontent.com/113146173/189548455-a15c3ddc-6132-438f-9902-e24e2d748c12.jpg)

here it is in the VAB

**Comment by FrostyDog69** [comment]
![image](https://user-images.githubusercontent.com/113146173/189548523-154f28c9-27d7-49db-b8d5-f086cfcf5341.jpg)

here it is outside the VAB-this is what it looks like I’m soace and on the mun

**Comment by Rodg88** [comment]
That is what happens when Reflection Refresh Mode is set to "Off". 
![image](https://user-images.githubusercontent.com/2611674/189592719-253d5cdc-fe2e-412f-a539-e32bf12fdce8.png)
You want to set this to at least Low instead (higher settings than low are fairly performance intensive for not much gain, it's just how often the reflection gets updated)
