### ISSUE TITLE
Big G 0.625m caps

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1316]
The small skylab caps on the conic and cylindrical service modules could be replaced with Apollo endcaps, to place the Apollo active docking ports onto.
![image](https://user-images.githubusercontent.com/2611674/190855243-33dc3f0f-0139-46a0-bc12-0cf68e57fcc3.png)

**Comment by CobaltWolf** [comment]
those are on a different texture sheet tho. I could try copying it over would just take a little bit of work, add it to my to-do list pls? also looks like the inside of the rim is broken on the conic SM
