### ISSUE TITLE
conflict between new BDB dev versions and Extraplanetary Launch Pads

### ISSUE THREAD

**Issue by GusToTheMoon** [CobaltWolf/Bluedog-Design-Bureau#1319]
whenever you boot the game for seemingly a second time with EPLP installed, it creates a resource called "bdbScrapMetal" and it screws over the game in many a weird and wonderful ways.
![image](https://user-images.githubusercontent.com/114694734/193119163-383cd72d-579c-4489-91ec-de084c2097ff.png)
![image](https://user-images.githubusercontent.com/114694734/193119232-a0bac222-b394-4ddc-a684-ca97ab720cc0.png)
removing EPLP seems to fix it, but i have no idea what inside it is actually causing the issue

**Comment by Rodg88** [comment]
Will need to see your KSP.log to find what’s happening

**Comment by GusToTheMoon** [comment]
> Will need to see your KSP.log to find what’s happening

the only offending piece i could find was in the screenshot above, so don't really know if sending my log file would help much.
also, something is spamming my log file with the same thing about "bones" so i think you would go insane trying to find it

**Comment by Rodg88** [comment]
There's plenty of stuff to look for, it will be useful. And don't worry, you can search a log file if you know what to look for. if you zip it it will reduce the size a lot which might help upload it, if it's spam-filled

**Comment by Rodg88** [comment]
And I can't reproduce this, so will need a log to look for culprits

**Comment by Rodg88** [comment]
Feel free to reopen if you can get a log
