### ISSUE TITLE
BDSEP-PSE cannot be deployed

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1321]
This experiment does not show a "place" icon in the inventory slot.

![bdb-pse](https://user-images.githubusercontent.com/43111140/194986942-3432d54d-498d-4c82-95e8-78904842f4db.png)

**Comment by Rodg88** [comment]
Its currently designed as a part you just drop as an engineer with eva construction, and has a normal science module instead of a long term BG experiment, but It can probably still have a deployment module, I'll look into it

**Comment by Rodg88** [comment]
I've changed them to use ModuleGroundPart, like the rest of the ALSEP. There is definitely some KSP based jank this way, but not needing an engineer to deploy is probably worth it. If you only use the parts in the correct way, and don't try to mess with them in EVA construction, it should be fine.
