### ISSUE TITLE
Untextured (?) LEM nibblet

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1322]
![lem-nibblet](https://user-images.githubusercontent.com/43111140/195096484-34e5fb26-93cf-4d24-93ed-efaa6ea979bf.png)

I think this is a regression that appeared around the time of the new LEM variants.

**Comment by Rodg88** [comment]
It's like this on the normal Ascent module and the Lab variant.

**Comment by CobaltWolf** [comment]
ty will fix shortly
