### ISSUE TITLE
Balance: KANE "Yagi" antenna

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1323]
My impression was that this antenna was sort of an Apollo 11-ish component? The first Apollo mission is basically spread out at the 160 level, but this antenna is at the 300 level in Scanning Tech.

Raising issue just in case this _isn't_ on purpose. If it's for later missions then it makes sense where it is.

edit: just noticed the dipole one is in the same place ... so this is probably on purpose.

**Comment by CobaltWolf** [comment]
The yagi antenna is from Apollo 17
