### ISSUE TITLE
B9 Partswitch fatal error

### ISSUE THREAD

**Issue by ArlenGaming** [CobaltWolf/Bluedog-Design-Bureau#1327]
When I try running KSP with the dev version of BDB (the one with shelab and LRV), B9 partswitch has a fatal error and makes me quit the game. Here is my KSP.log
[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/9831518/KSP.log)

**Comment by CobaltWolf** [comment]
What is the error? Usually it shows a list of parts affected

**Comment by ArlenGaming** [comment]
![image](https://user-images.githubusercontent.com/83114089/197011348-1434b571-a780-42fd-a1f7-ec528118663c.png)

**Comment by Rodg88** [comment]
Your log file isn't uploaded properly or something, it just downloads a 0kb file. Maybe try zip it to reduce the size and try uploading it again.

**Comment by ArlenGaming** [comment]
[ksplog.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/9832742/ksplog.zip)
here

**Comment by Rodg88** [comment]
First off, ACK basically needs: https://spacedock.info/mod/3064/Shaddy and the update: http://taniwha.org/~bill/Shabby_v0.3.0.zip to stop spamming the log. Will probably speed up your game load too.
Your KSPCF and Harmony are also out of date: https://github.com/KSPModdingLibs/KSPCommunityFixes/releases/tag/1.23.0

The issue is with a patch for Extraplanetary Launchpads activating when Simple Construction is installed, should be able to fix it, but for now you can remove the file Bluedog_DB/Compatibility/ExtraplanetaryLaunchpads/ELCargo.cfg in your install.

**Comment by ArlenGaming** [comment]
Thanks ill try it tomorrow after I get home from school

**Comment by lucalis023** [comment]
im having the same problem with the "scrapmetal" and B9, im using the dev branch and i have all the mods up to dave

**Comment by Rodg88** [comment]
@lucalis023 if your copy of dev branch is older than a few hours, either try updating to current dev, or the above fix I posted, removing the config file

**Comment by ArlenGaming** [comment]
Ok I did what you told me to now I can't click on any buttons in the VAB.
can't exit, can't launch, can't even move parts.

**Comment by ArlenGaming** [comment]
can't even rotate the camera

**Comment by CobaltWolf** [comment]
Oh wait I've had that happen to me before. Get to the VAB and the game just... breaks, and requires killing from task manager. No idea why, I think I eventually nuked that install.

**Comment by ArlenGaming** [comment]
how can I fix it?

**Comment by ArlenGaming** [comment]
Ok I did some testing and it turns out KSPCF was causing it

**Comment by lucalis023** [comment]
still having the problem even with the newer vertion it says that the resource "screapmetal" doesnt existis (wich i think is true) if i revert to an older vertion of the branches (always master or dev) it fixes and i dont have this problem ![20221022152016_1](https://user-images.githubusercontent.com/116320831/197356825-d4e9b1ac-8e82-4fdc-bee6-c91959889732.jpg)

**Comment by Rodg88** [comment]
Do you have simple construction or not so simple construction installed?

**Comment by Rodg88** [comment]
For now you can remove the file Bluedog_DB/Compatibility/ExtraplanetaryLaunchpads/ELCargo.cfg in your install.

**Comment by Rodg88** [comment]
Latest version of master or dev should fix this
