### ISSUE TITLE
Voyager Mars

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#1330]
Orbiter

- [x] Core
- [x] SM
- [x] Propulsion module
- [x] C1 engine
- [x] Solar annular
- [x] Solar square
- [x] HGA
- [x] HGA upgrade
- [x] MGA
- [x] Relay antenna
- [x] Backshell
- [x] Heat shield
- [x] LGA
- [x] star tracker
- [x] Planetary scan platform
- [x] Planetary scan platform upgrade
- [x] Neutron albedo boom
- [x] Magnetometer boom
- [x] spacecraft adapter
- [x] MM impacts
- [x] solar plasma
- [x] solar x-ray
- [x] atmo mass spec
- [x] cosmic ray

Lander

- [x] Lander core
- [x] descent engine
- [x] Landing leg
- [x] RTG
- [x] command antenna
- [x] passive air sampler
- [x] boom sampler
- [x] HGA dish
- [x] camera
- [x] long range sampler
- [x] radar altimiter
- [x] deorbit motor mount
- [x] deorbit motor (Star 24)
- [x] parachute
- [x] drill

Dual payload adapter

- [x] DPAF base
- [x] DPAF shroud/fairing base

**Comment by OrbitalManeuvers** [comment]
Didn't want to open a new issue for this, since it might be "as designed" but ... the Atmo Analysis experiment is 200 Mits to transmit, and between the 2 RTGs and the battery, transmission only gets to about 70% before you're out of EC.

**Comment by Rodg88** [comment]
Lander HGA partname needs fixing, I’ve warned it’ll break crafts on the thread already

**Comment by Gordon-Dry** [comment]
I place it here; on first boot with actual dev I get:
![Screen-2022-11-02_16-23-12](https://user-images.githubusercontent.com/29145213/199530509-dbf4d537-a852-4e86-bb5c-246c977e1a09.jpg)

**Comment by Rodg88** [comment]
Sounds like it might be due to kerbalism or something messing with the base science modules. Maybe this was why we had to use seperate parts?

**Comment by OrbitalManeuvers** [comment]
The Soil Moisture Sensor Boom has left-over text on the extend/retract action, where it says "Toggle Trapped Radiation Boom"

**Comment by zorg2044** [comment]
> The Soil Moisture Sensor Boom has left-over text on the extend/retract action, where it says "Toggle Trapped Radiation Boom"

Whoops didnt see this. Fixed now
