### ISSUE TITLE
Can't deploy "Burke-OVBR-1 Communications Dish"

### ISSUE THREAD

**Issue by Astro301** [CobaltWolf/Bluedog-Design-Bureau#1333]
I've noticed that in the editor that I can't deploy the "Burke-OVBR-1 Communications Dish". I thought that it might be that It could only deploy in space but when I jettisoned Mariner 2 from the upper stage and right clicked the dish, it didn't show the option to deploy. I've also tried deploying it using action groups but that didn't work either. I'm really hoping this is just a missing dependency because I've noticed some other deployable antennas are experiencing this same issue. BTW I've installed the mod through CKAN so it may have something to do with that.

**Comment by Rodg88** [comment]
Did you work out the issue? What was the cause out of interest?

**Comment by Xenomorph162** [comment]
PS: I haven't even messed with the dependencies' files for months so they were probably updated since then without my knowledge.

**Comment by Astro301** [comment]
Unfortunately this didn't seem to work. I think it may be a mod conflict or something. I'm going to try to pin down what mod it might be.

**Comment by Rodg88** [comment]
If you upload your ksp.log file I can have a look

**Comment by Astro301** [comment]
I'm considering doing that as a last resort if I can't figure it out on my own. I've never uploaded a file before so it might take a while.

**Comment by Rodg88** [comment]
no problem. if you do want to upload, and the log files are large, zipping them can help a lot

**Comment by Astro301** [comment]
https://www.dropbox.com/s/8r885s466tj3s6o/KSP.log?dl=0

**Comment by Astro301** [comment]
I hope this is the right one.

**Comment by Rodg88** [comment]
Looks like another mod 'NCAP' is incorrectly triggering RemoteTech patches to apply, even though you don't have RemoteTech installed. If you remove that it should work fine. If you want to report it to them, the issue is they need to use "NEEDS" instead of "FOR" for their remote tech compatibility patches. Using "FOR[x]" tells modulemanager that x mod exists.

**Comment by Astro301** [comment]
Oh okay. I'll see what I can do. Deleting NCAP won't be to much of a sacrifice anyway. Thanks for your help!

**Comment by Rodg88** [comment]
no problem!
