### ISSUE TITLE
Voyager Mars fuel

### ISSUE THREAD

**Issue by Raqnick** [CobaltWolf/Bluedog-Design-Bureau#1335]
Main engine uses hypergolic fuel,while TC-1 engines use standard LF/O.

**Comment by Rodg88** [comment]
Fixed thanks. The C1 engine will now have an option to switch to hypergolic. You'll need to update the hypergolic patch from the dev version https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/1.11-development/BD_Extras%20(No%20Warranty)/GameData/Bluedog_DB_Extras/Pafftek/HypergolicBDB
