### ISSUE TITLE
Paracutes not working

### ISSUE THREAD

**Issue by RiccRacc** [CobaltWolf/Bluedog-Design-Bureau#1338]
im on the latest version of BDB and the paracutes are broken i have realchute and ive tried it without but it shows the stowed and deployed model and im pretty sure the game dosent recognize them as parachutes

**Comment by Rodg88** [comment]
@RiccRacc if you try upload a zipped version of the log here, it should be fine

**Comment by RiccRacc** [comment]
> @RiccRacc if you try upload a zipped version of the log here, it should be fine

[BDB 1.11 parachutes dont work and rover spazzing out.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/9957702/BDB.1.11.parachutes.dont.work.and.rover.spazzing.out.zip)

heres the log

**Comment by Rodg88** [comment]
I'd try re-installing FAR https://github.com/dkavolis/Ferram-Aerospace-Research/releases
For some reason it's not finding the FAR parachute module, which should exist since you have FAR installed.

**Comment by Rodg88** [comment]
Feel free to reopen if the issue continues
