### ISSUE TITLE
LM Rover Spazzing out then dissapears.

### ISSUE THREAD

**Issue by RiccRacc** [CobaltWolf/Bluedog-Design-Bureau#1339]
im launching right?
its all folded up and its auto strutted ive tried turning off autostrut but it keeps spazzing out and eventually it will dissapear no idea whats wrong

**Comment by RiccRacc** [comment]
[BDB 1.11 parachutes dont work and rover spazzing out.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/9957694/BDB.1.11.parachutes.dont.work.and.rover.spazzing.out.zip)

**Comment by Rodg88** [comment]
For the rover, there's not a lot we can do, it's basically "just KSP things"
However you can try install KSPCF https://github.com/KSPModdingLibs/KSPCommunityFixes/releases and KJR:N https://github.com/meirumeiru/Kerbal-Joint-Reinforcement/releases
KSPCF helps a lot with stock robotics, and KJR:N reinforces joints, without messing up the rover joints.
