### ISSUE TITLE
B9PartSwitch error on bluedog_MB60

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#1340]
![Screen-2022-11-06_15-33-31](https://user-images.githubusercontent.com/29145213/200176983-fa5d8833-a530-453d-97be-110c1edba52e.jpg)

I guess it's the still commented-out entry in
GameData\Bluedog_DB_Extras\MethaloxEngines\Methalox_MB60.cfg on line 39 ?
`			// texture = Bluedog_DB_Extras/MethaloxEngines/bluedog_RL20_methane`

**Comment by Rodg88** [comment]
Ah yep, didn't fully comment out that node. fixed
