### ISSUE TITLE
KH/Corona heatshield auto-jettison / mod interaction

### ISSUE THREAD

**Issue by MgnfcntBstrd** [CobaltWolf/Bluedog-Design-Bureau#1341]
[KSPLogs.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/9954032/KSPLogs.zip)
[ModuleManager.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/9954041/ModuleManager.zip)

https://forum.kerbalspaceprogram.com/index.php?/topic/122020-1123-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v1110-%D0%B2%D0%BD%D0%B5-22oct2022/page/1141/#comment-4196313

This was a fresh KSP install with no cloud settings, fresh CKAN install and CKAN installation of a "minimal" (for me) mod load to test out TAC-LS.

The game crashed, so the MM logs are from the next restart.  MJ2, Atmos Autopilot and Debug Stuff were added from CKAN, the rest of the mods are the same as the load that was running when the heatshield issue happened.

**Comment by MgnfcntBstrd** [comment]
Hmmm.  Also had a stack of three remaining Clementine ISAS adapters deploy fire the attached cores when I switched back to them.  

![image](https://user-images.githubusercontent.com/94755111/200473255-137f2e50-e830-4a51-85d3-41b446d073c0.png)

**Comment by Rodg88** [comment]
From a quick look without finding anything definitive, I'd suggest trying it without ToadicusTools/TweakableEverything. That's basically the only thing that seems like it could be messing with the parts in question.

**Comment by Rodg88** [comment]
Ah, looks like It happens when routineMissionManager is active? Might be able to report it to them after I confirm it

**Comment by MgnfcntBstrd** [comment]
I will do so.   Thank you!

**Comment by MgnfcntBstrd** [comment]
I wonder if RMM is also the reason my stock re-entry modules can't decouple.
