### ISSUE TITLE
@thumbs images going corrupt?

### ISSUE THREAD

**Issue by DJGlitch816** [CobaltWolf/Bluedog-Design-Bureau#1342]
Several images from the @thumbs folder became corrupted today and the game now freezes trying to load them. I don't want to redownload the entire enormous mod file again, but I don't see the @thumbs directory anywhere in the source code on Github. Is it on here?

**Comment by Rodg88** [comment]
The thumbnails in the folder are auto generated, you can safely delete them and ksp will replace them as you need them.

**Comment by DJGlitch816** [comment]
It got even weirder, I went through and reinstalled the mod from scratch and the game still froze on the same part (small fuel tank 1).

**Comment by DJGlitch816** [comment]
Turns out it's something in the game's code. This is what I pulled from the log. I got the same issue even after deleting the mod and reinstalling it from a fresh download:

[LOG 13:55:12.633] Load(Texture): Squad/Parts/@thumbs/fuelTankSmall_icon1
[EXC 13:55:12.708] NullReferenceException: Object reference not set to an instance of an object
	DatabaseLoaderTexture_PNG+<Load>d__0.MoveNext () (at <0435390348b6470d8166bd1c53b4b100>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by Rodg88** [comment]
It’s unlikely to be anything to do with BDB then, but if you post your ksp.log I can have a look anyway

**Comment by Rodg88** [comment]
It might be due to 0kb png files being generated, which will cause issues like that. No idea why that happens though. So just keep deleting problem files/emptying all the thumb folders, like the squad one since it's where an error is happening in that log clip.

**Comment by Rodg88** [comment]
Closed due to not being a bdb issue, if it continues maybe ask on the ksp modded support forum
