### ISSUE TITLE
Missing Texture files

### ISSUE THREAD

**Issue by ThomasWarChild** [CobaltWolf/Bluedog-Design-Bureau#1343]
BDB, Hello and thank you for the work you do.   Sorry about all of these, but thought you should know and this is where it says to report issues.

I'm getting quite a few textures not found for the Apollo and Mercury folders.  Here is what my log says:

[LOG 16:47:02.209] Load(Model): Bluedog_DB/Parts/Mercury/bluedog_mercuryHeatshield
[ERR 16:47:02.210] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop' not found!

[ERR 16:47:02.210] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop_NRM' not found!

[LOG 16:47:02.211] Load(Model): Bluedog_DB/Parts/Mercury/bluedog_mercuryLES
[LOG 16:47:02.213] Load(Model): Bluedog_DB/Parts/Mercury/bluedog_mercuryPod
[ERR 16:47:02.214] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop' not found!

[ERR 16:47:02.214] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop_NRM' not found!

[LOG 16:47:05.299] Load(Model): Bluedog_DB/Parts/Skylab/bluedog_GooLab_Module
[ERR 16:47:05.310] Texture 'Bluedog_DB/Parts/Skylab/bluedog_LM_Ascent' not found!

Also getting these errors as well.

[LOG 16:47:02.711] Load(Model): Bluedog_DB/Parts/MOL/Solar/bluedog_Gemini_SolarWing
[WRN 16:47:02.731] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Gemini_SolarWing/Gemini_SolarWing/pivot/Direction_2/Rotate_A 1/Rotate_B 1/B 1"
[WRN 16:47:02.731] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "Gemini_SolarWing/Gemini_SolarWing/pivot/Direction_2/Rotate_A 1/Rotate_B 1/Rotate_C 1/C 1"

[LOG 16:47:02.957] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Klaw/bluedog_SmallKlaw
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/1.875m/Arm_1.875mLeft/Arm1 1/Arm2 1/GameObject/pCylinder15.012"
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/1.875m/Arm_1.875mLeft/Arm1 1/Arm2 1/pCylinder15.013"
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/1.875m/Arm_1.875mLeft/Arm1 1/group10.006/pCube4.006"
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/1.875m/Arm_1.875mLeft/group20.006/pCylinder9.006"
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/2.5m/Arm_2.5mLeft/Arm1 3/Arm2 3/GameObject/pCylinder15.010"
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/2.5m/Arm_2.5mLeft/Arm1 3/Arm2 3/pCylinder15.011"
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/2.5m/Arm_2.5mLeft/Arm1 3/group10.005/pCube4.005"
[WRN 16:47:02.984] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/smallKlaw/Klaw/2.5m/Arm_2.5mLeft/group20.005/pCylinder9.005"

[LOG 16:47:03.486] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Pioneer/bluedog_Pioneer_RTG
[WRN 16:47:03.521] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Pioneer_RTG/RTG/RTG.002/SNAP19.001/SNAP19.002/Extension.001/Collider3.001"
[WRN 16:47:03.521] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Pioneer_RTG/RTG/RTG.002/SNAP19.001/SNAP19.002/Collider2.001"

[LOG 16:47:03.797] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Transit/bluedog_ANNA

[LOG 16:47:03.808] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Transit/bluedog_POPPY1
[WRN 16:47:03.809] Couldn't create a Convex Mesh from source mesh "" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[LOG 16:47:03.815] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Transit/bluedog_POPPY2
[WRN 16:47:03.816] Couldn't create a Convex Mesh from source mesh "" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[LOG 16:47:03.838] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Transit/bluedog_SOLRAD8
[WRN 16:47:03.839] Couldn't create a Convex Mesh from source mesh "" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[LOG 16:47:03.844] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Transit/bluedog_Transit2A
[WRN 16:47:03.845] Couldn't create a Convex Mesh from source mesh "" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[LOG 16:47:03.886] Load(Model): Bluedog_DB/Parts/ProbeExpansion/Transit/bluedog_Transit5_SNAP9A
[WRN 16:47:03.890] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Transit5_SNAP9A/box_c/box_c|mesh:collider|Dupli|"
[WRN 16:47:03.890] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Transit5_SNAP9A/box_c.001/box_c.001|mesh:collider|Dupli|"
[WRN 16:47:03.890] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Transit5_SNAP9A/box_c.002/box_c.002|mesh:collider|Dupli|"
[WRN 16:47:03.890] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Transit5_SNAP9A/box_c.003/box_c.003|mesh:collider|Dupli|"
[WRN 16:47:03.890] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Transit5_SNAP9A/box_c.004/box_c.004|mesh:collider|Dupli|"
[WRN 16:47:03.890] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/Transit5_SNAP9A/box_c.005/box_c.005|mesh:collider|Dupli|"
[WRN 16:47:05.062] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider"
[WRN 16:47:05.062] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.001"
[WRN 16:47:05.062] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.002"
[WRN 16:47:05.062] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.003"
[WRN 16:47:05.062] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.004"
[WRN 16:47:05.062] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.005"
[WRN 16:47:05.062] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.006"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.007"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.008"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.009"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.010"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.011"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.012"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.013"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.014"
[WRN 16:47:05.063] BoxColliders does not support negative scale or size.
The effective box size has been forced positive and is likely to give unexpected collision geometry.
If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GameObject/ASTP_SLA_Truss/0.9375/0.9375_Colliders/.9375_Collider.015"

**Comment by Rodg88** [comment]
The “BoxColliders does not support negative scale or size.“ are harmless, unless when using any of the listed parts you get unusual behaviour, like trying to srf attach other parts to them and they don’t attach in expected locations.

And all I can really suggest for the missing textures, is perhaps an installation or download error. You may need to redownload the mod and/or try reinstalling it.

**Comment by ThomasWarChild** [comment]
Thank you.  I'll give it a go... I've been reinstalling everything since I bumped up to 1.12.4

**Comment by Rodg88** [comment]
Cool, if the issue persists feel free to reopen with a log
