### ISSUE TITLE
LRV stucked,again

### ISSUE THREAD

**Issue by Raqnick** [CobaltWolf/Bluedog-Design-Bureau#1344]
LRV unfolding at the VAB,but stucking and flipping the craft at actual flight.

![KSP_x64_2022 11 27-14 18_1](https://user-images.githubusercontent.com/95162518/204138335-ea6ee9a6-ee76-414e-8e28-bc4e25cd142f.png)
![KSP_x64_2022 11 27-14 20](https://user-images.githubusercontent.com/95162518/204138340-79d02956-1c5e-4091-ae48-f5a6a83c6f2b.png)
![KSP_x64_2022 11 27-14 18](https://user-images.githubusercontent.com/95162518/204138356-dda53001-32bc-4c46-863c-b5bee8882fbd.png)

**Comment by Rodg88** [comment]
Do you have KJR? If so, replace it with KJR:Next
https://github.com/meirumeiru/Kerbal-Joint-Reinforcement/releases
