### ISSUE TITLE
Gemini Capsule does not get extended lifesupport with TAC-LS

### ISSUE THREAD

**Issue by birdog357** [CobaltWolf/Bluedog-Design-Bureau#1348]
I was trying to load the default craft file for the MOL and the file calls for bluedog_Gemini_Capsule instead of what I am assuming is a deprecated version called bluedog_Gemini_Crew_A?

In the TAC-LS compatibility  folder command.cfg line 59 `// @PART[bluedog_Gemini_Crew_A,bluedog_Apollo_Block2_Capsule]:NEEDS[TacLifeSupport]:AFTER[TacLifeSupport]` the name of the part is wrong it should be bluedog_Gemini_Capsule I would also suggest that the line shouldn't be commented out by default since Gemini set duration records IRL that were unbeaten by US spacecraft until Skylab.  To maintain the same logic as the Apollo extended LS, shouldn't the MOL equipment section have the same switchable fuel cell as the Gemini equipment module? It would have extra 02 as well as producing water as a byproduct of electric generation.

**Comment by CobaltWolf** [comment]
Our TAC-LS compatibility configs haven't been updated in several years. You seem to have found your way around the file pretty well - If you're able, I'd appreciate you making that and whatever other fixes you see fit and making a Pull Request?

**Comment by birdog357** [comment]
I'll have to figure out how to make a pull request on github, but sure.

**Comment by birdog357** [comment]
> Our TAC-LS compatibility configs haven't been updated in several years. You seem to have found your way around the file pretty well - If you're able, I'd appreciate you making that and whatever other fixes you see fit and making a Pull Request?

I think I got a proper pull request in. Let me know if I jacked it up.

**Comment by Rodg88** [comment]
Merged, thanks for the contribution!

Targeting the main branch is probably fine for this kinda bug fix right @CobaltWolf? I pulled it into dev as well already anyway
