### ISSUE TITLE
Node issue with Agena

### ISSUE THREAD

**Issue by birdog357** [CobaltWolf/Bluedog-Design-Bureau#1349]
When snapping the Agena Interstage onto the bottom of the Agena-D engine mount, the parts interphase and bind together and then don't decouple in flight.

**Comment by Rodg88** [comment]
Double check you don’t have a non-single symmetry mode selected in the editor when placing the interstage

**Comment by birdog357** [comment]
> Double check you don’t have a non-single symmetry mode selected in the editor when placing the interstage

It's not. I can not replicate it by pulling new parts off the pallet, but when I load the supplied SLV-3 Atlas, the problem is there if you move the Agena off and then back on.

**Comment by CobaltWolf** [comment]
Yeah that sounds like the craft file is busted. Stuff like part nodes aren't properly updated in .crafts when the part cfgs are changed. Who even maintains the craft files? :P

**Comment by Rodg88** [comment]
I can update it, I think I have an install designed to do it with minimal added modules.

**Comment by Rodg88** [comment]
@birdog357 Can you try again now with the updated craft files: `Atlas SLV-3 Mariner 4.craft` and `Atlas SLV-3B.craft` from here: https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/master/Craft%20Files

They didn't cause any issues for me personally, but there were some minor errors in how the agena interstage was set up in each craft file.
