### ISSUE TITLE
Delta Engine Fairing Node Placement

### ISSUE THREAD

**Issue by Sgt-Shutesie** [CobaltWolf/Bluedog-Design-Bureau#1353]
The node for the top of the delta engine fairing is too low and causes severe clipping.
![image](https://user-images.githubusercontent.com/17996283/220807357-e8cf08d2-aad1-4453-a8cf-588a586e42ee.png)

**Comment by zorg2044** [comment]
Looks fine here? 

![image](https://user-images.githubusercontent.com/39182212/221648377-736a1c92-3f3e-4249-861b-ed6e862651cc.png)

![image](https://user-images.githubusercontent.com/39182212/221648447-73809d3b-6fbb-4b47-939d-80d34a4f3e36.png)

Is this from a craft file or a fresh build?
