### ISSUE TITLE
[Bug] bluedog.Gemini.Resupply.Capsule ModuleB9PartSwitch Duplicate subtype name (LifeSupport) causes severe warning on launch

### ISSUE THREAD

**Issue by GreenKeldeo** [CobaltWolf/Bluedog-Design-Bureau#1357]
More or less what it says on the tin - here's my ksp.log alongside both ModuleManager logs:
[BlueDog_B9Error.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/10949113/BlueDog_B9Error.zip)

Here's my modlist:
`KSP: 1.12.5 (Win64) - Unity: 2019.4.18f1 - OS: Windows 10  (10.0.0) 64bit
000_AT_Utils - 1.10.1
ClickThroughBlocker - 2.1.10.21
Filter Extensions - 3.2.8
Harmony - 2.2.1
Toolbar - 1.8.0.8
USI Tools - 112.0.1
ToolbarControl - 0.1.9.9
CommunityPartsTitles - 0.9.3
KSP-Recall - 0.3.0.12
Ablative-Airbrake - 1.0.3
AbortPacks - 1.0.2
Achievements - 1.10.1.8
AIES_Patches - 0.0.1.3
AirPark - 1.7.1.7
Alarm Enhancements - 1.0.2
AllYAllContinued - 0.11.19.2
Animated Decouplers - 1.5
ASET Consolidated Agency - 2.0.2
ASET Consolidated Avionics Pack - 3.0
ASET Consolidated Props Pack - 2.0.3
ASET_ERS - 0.4.0.4
ASET_PRC - 0.1.0.5
Astrogator - 1.0
MOTHS - 0.0.1
AutoQuickSaveSystem - 0.1.0.6
Aviation Lights /L - 4.2.0.1
B9 Animation Modules - 1.7
B9 Part Switch - 2.20
B9 Aerospace - 6.6
B9 Aerospace - 6.6
B9 Aerospace HX Parts - 6.6
B9 Aerospace Procedural Wings - 0.44
B9 HX Reconfig - 1.1
BD Animation Modules - 0.6.7.1
BAM - 1.3.3.4
BDArmory - 1.5.9.2
Benjee10_MMSEV - 1.0.2
Plume Party - 0.5
Benjee10_sharedAssets - 0.2.2
Mk.X-37B - 0.1.3.3
BetterSRBs - 1.2.6
BetterTimeWarpContinued - 2.3.13
Bluedog Design Bureau - 1.12
BurstAtomicThrustModule - 0.1.0.3
CactEye Telescopes - 1.5.2.8
ChromaWorks - 2.0.0.1
ComfortableLanding - 2.0.2.5
CommNetAntennasExtension - 2.1.7
CommNetAntennasInfo - 3.1.2
Community Category Kit - 0.1.0.112
Community Resource Pack - 112.0.1
CommunityTechTree - 3.4.4
ConfigurableContainers - 2.6.2.1
Connected Living Space - 2.0.2
Contract Configurator - 2.2.2
Contract Pack: Exploration Plus - 2.0.1
Contract Pack: Clever Sats - 1.4
Contract Pack: CommNet Relays - 2.1
Contract Pack: Field Research - 1.2.2
Contract Pack: Kerbal Academy - 1.1.10
Contract Pack: Bases and Stations - 3.7.3
Contract Pack: Research Advancement Division - 1.2.1
Contract Pack: Tourism Plus - 1.5.2
Contract Pack: Tourism Expanded - 1.0.2
Crew Light - 1.20.1.1
CrewRandR - 1.1.11.4
Crowd Sourced Science - 6.0
CryoEngines - 2.0.6
CryoTanks - 1.6.5
Community Terrain Texture Pack - 1.0.5
Custom Asteroids - 1.9
CustomPrelaunchChecks - 1.8.1.1
DaMichel's AeroRadial - 1.1.0.1
DaMichel's CargoBays - 1.1.0.1
DaMichel's Fuselage - 1.1.0.2
DecouplerShroud - 0.8
DSCore - 3.2
ThorTech - 0.9.6.8
DeployableEngines - 1.3.1
DepthMask - 1.1.3
AGExt - 2.4.1.3
Distant Object Enhancement (DOE) /L - 2.1.1.11
DMagic Orbital Science - 1.4.3
Contract Parser - 1.0.9
Contracts Window Plus - 1.0.9.4
Progress Parser - 1.0.11
DockingCamKURS - 1.3.8.5
DockRotate - 1.12.1.55
DynamicBatteryStorage - 2.2.5
Easy Vessel Switch - 2.3.7852.41352
Engine Lighting Relit - 1.6.3.4
Environmental Visual Enhancements - Redux - 1.11.7.1
EVAEnhancementsContinued - 0.1.15.3
ExtraplanetaryLaunchpads - 6.99.3
FarFutureTechnologies - 1.2
FASA - 7.2.7
Firespitter - 7.17
FMRS (Flight Manager For Reusable Stages) - 1.2.9.3
FreeIva - 0.2.10.3
FRS - 0.0.1.1
GasRepairsAndProbablyExpensiveSnacks - 1.0.2
ProgramaticExtensionAndRetraction - 1.0.2
FShangarExtender - 3.6.0.2
FTLDriveContinued - 0.2.5.2
Goo Pumps & Oils' Speed Pump - 1.9.0.11
GravityTurn - 1.8.3
GroundConstruction - 2.7.1
HabTechProps - 0.2
Hangar - 3.6.2.2
HeatControl - 0.6.1
HideEmptyTechTreeNodes - 1.3.2
Hooligan Labs Airships Core - 7.0.1
htRobotics - 1.0
HullcamVDSContinued - 0.2.2
Interstellar Fuel Switch - 3.30
JanitorsCloset - 0.3.7.9
JSIPartUtilities - 0.5.0.5
JSIAdvTransparentPods - 0.1.24
RasterPropMonitor - 0.31.11.1
Kaboom! (BOOM) - 1.4.0.1
Kerbal Aircraft Reactor Experiment - 1.1.1
KAS - 1.12.8285.34332
KAX - Kerbal Aircraft Expansion /L - 2.8.1
KerbalAtomics - 1.3.3
KerbalChangelog - 1.4.2
Kerbal Engineer Redux - 1.1.9
Kerbal Foundries - 2.4.8.18
KerbalGPS - 1.2.1.4
Kerbal Joint Reinforcement - 4.1.19
KerbalKonstructs - 1.8.6
WaterLaunchSites - 1.0.1
Precise Editor - 1.2
Kerbal Renamer - 1.7
Kerbal Reusability Expansion - 2.9.2
HyperEdit - 1.5.8
Feline Utility Rover - 1.3.6
Keridian Dynamics (KDVA) by Eleusis La Arwall - 0.8.99.6
InlineBallutes - 1.2.11.4
Kipard Skylon - 1.3
Kip Docking Ports - 1.0
Kerbal Inventory System - 1.29.8039.40483
Kopernicus - 1.12.1.158
kOS - 1.4
kOS-Astrogator - 0.2.2
kOS-KerbalEngineer - 0.1.1
KRASH - 0.5.33.5
KSP-AVC Plugin - 1.4.1.9
KSPCommunityFixes - 1.24.6
Ksp Craft Organizer - 1.7.2.2
KSPLogger - 0.6.1.1
KSPWheel - 0.16.14.33
KSP_PartVolume - 0.0.3.10
KSTS - 2.0.3
KWRocketryRebalanced - 3.2.7.2
XT Landertron - 1.3
LoadingTipsPlus - 1.9
L-Tech Scientific Industries - 0.5.2.3
Infernal Robotics - 3.1.10
MandatoryRCS Part Pack - 1.4
ManeuverQueue - 0.5.0.2
MarkIVSystem - 3.2
Kerbal Dust Experiment - 2.0.2.14
Mini Sample Return Capsule (MSRC) - 1.4.2.2
Mk1-Cabin-Hatch - 1.0.1
MOARdV's Avionics Systems - 1.3.6
MoarFilterExtensionConfigs - 1.0.5.2
ModularFlightIntegrator - 1.2.10
ModuleAnimateGenericEffects - 0.1.5
Module Manager Watch Dog - 1.1.0.3
ModuleSequentialAnimateGeneric - 0.0.1.1
Moldavite Machines - 1.3
MunarIndustries Fuel Tank Expansion - 0.9.7.1
ZZZRadioTelescope - 1.0.5.1
NavBallDockingAlignmentIndicatorCE - 1.1.1.3
Docking Port Alignment Indicator - 6.10
NearFutureAeronautics - 2.1.1
NearFutureConstruction - 1.3.1
NearFutureElectrical - 1.2.3
NearFutureExploration - 1.1.2
NearFutureLaunchVehicles - 2.2
NearFutureProps - 0.7.1
NearFuturePropulsion - 1.3.5
NearFutureSolar - 1.3.2
NearFutureSpacecraft - 1.4.3
NeatherdyneMassDriver - 1.3.4.2
Lithobrake Exploration Technologies (LET) - 0.5.1
S.A.V.E - 1.11.0.3
NodeHelper - 1.5.1.5
NovaPunch Rebalanced - 0.1.7.3
Oblivion Aerospace (OAP) - 0.2.99
Oh Scrap! - 2.2
On Demand Fuel Cells (ODFC) by Orum - 1.2.99.1
OuterPlanetsMod - 2.2.10
OPT Continued - 3.1.1
OPT Legacy Spaceplane Parts - 3.1.2
OPT Reconfig - 3.4.1
OrbitalTug - 1.3.1.2
PatchManager - 0.0.17.6
Persistent Rotation Upgraded - 1.9.1.7
Radial Experiment Storage Container - 2.5
Photon Sailor - 1.7.4
PhysicsRangeExtender - 1.21
Kerbal Planetary Base Systems - 1.6.16
PlanetShine - 0.2.6.6
Procedural Fairings - 6.3
PWBFuelBalancerRestored - 0.2.1.7
QuickSearch - 3.3.0.9
QuizTechAeroPackContinued - 1.3.15.1
Mk2.5 Spaceplane Parts - 1.5.3.1
RATPack - 0.4.3.4
RCS Build Aid - 1.0.6
RealChute - 1.4.8.3
RealPlume - Stock - 4.0.6
Recovery Controller - 0.0.4.1
ReentryParticleEffectRenewed - 1.9.1.1
RemoteTechRedevAntennas - 0.1.1
AmpYear - 1.5.9
DeepFreeze Continued... - 0.31
ResearchBodies - 1.13
ResonantOrbitCalculator - 0.0.7
ReStock - 1.4.3
ReStockPlus - 1.4.3
RetractableLiftingSurface - 0.2.1.2
RLA_Reborn - 0.15.2
RoutineMissionManager - 0.4.0.2
SCANsat - 1.20.4
ScienceAlert - 1.9.10.2
ScienceLabInfo - 2.0.2
ScrapYard (SYD) - 2.2.99
PicoPort4AllSizes - 0.1.2.3
PicoPort - 0.1.6.4
RecoverableEmergencyKerbalTransport - 0.4.8.2
Ship Manifest - 6.0.6
Simple Adjustable Fairings - Plugin - 1.12
Simple Adjustable Fairings - KW Rocketry Pack - 1.4
SimpleLogistics! - 2.0.5
SmartParts - 1.9.17
SmartStage - 2.9.14.2
Solar Science (SOL) by Snoopy20111 - 1.3.1
SaveOurSettings - 0.0.1.4
SpacedockReBoxed - 0.3.0.4
SpaceDust - 0.4.4
Space Dust Unbound - 1.0.2
RecycledParts - 0.2.3
ButtonManager - 1.0.1.1
SpaceTuxLibrary - 0.0.8.5
VesselModuleSave - 1.0.1.2
Spacetux - 0.3.13.1
SpaceY Lifters (SYL) by NecroBones - 1.9.99
SpaceY Expanded - 1.4
Spectra - 1.6.5
StandardPropulsionSystems - 1.0.6
MicroSat - 0.1.4.1
StageRecovery - 1.9.6.1
StarshipLaunchExpansion - 0.5
StationKeeping - 0.2.3
StationPartsExpansionRedux - 2.0.10
Surface Mounted Lights - 1.19.7854.4854
SXTContinued - 0.3.29.8
SystemHeat - 0.6
TacSelfDestructContinued - 1.7.0.3
TarsierSpaceTechnology - 7.13
TDProps - 1.4
ThrottleControlledAvionics - 3.8.0.1
ThroughTheEyes - 2.0.4.4
TAC Life Support - 0.18
ToggleLadderExit - 0.0.1.2
Tracking Station Evolved - 1.0.7
Trajectories - 2.4.3
Kerbal Alarm Clock - 3.14
TrimIndicators - 0.1.0.4
TrimPlus - 1.4
TexturesUnlimitedFX - 1.0.5
Tundra Exploration - 6.1
Tundra Space Center - 2.0.2
Tundra Technologies - 6.0
TutorialFixes - 0.0.3
TweakScale - 2.4.6.25
TweakScale Companion - 2023.3.4
TweakScale Companion for Airplane Plus - 0.1
TweakScale Companion for Frameworks - 0.3
TweakScale Companion for Firespitter - 1.2
TweakScale Companion for Kerbal Inventory System (KIS) - 1.0.0.2
TweakScale Companion Living Style - 0.0.3
TweakScale Companion Multipass - 0.0.2
TweakScale Companion for Neist Airliner Parts - 0.0.1
TweakScale Companion for Orbit Portal Technologies (OPT) - 0.0.1
TweakScale Companion for Post Kerbin Mining Corporation Add'Ons - 2.2
TweakScale Companion for ReStockPlus - 1.1
TweakScale Companion Rockets - 0.0.1
TweakScale Companion for SMCE - 0.0.1.1
Asteroid Recycling Tech - 112.0.1
USI Exploration Pack - 112.0.10
Freight Transport Tech - 112.0.1
Karbonite - 112.0.1
Konstruction - 112.0.1
Malemute Rover - 112.0.1
MKS - 112.0.1
NuclearRockets - 112.0.1
Sounding Rockets - 112.0.1
USI Core - 112.0.1
Universal Storage 2 - 4.0.0.8
UrgentContracts - 0.1.1
VesselMover - 1.12
VesselViewerContinued - 0.8.8.6
KSP Interstellar Extended - 1.29.6
Waterfall - 0.9
WaterfallRestock - 0.2.3
Waypoint Manager - 2.8.3.5
WildBlueTools - 1.88.2
Kerbal Actuators - 1.8.5
WildBlueCore - 1.2.3
Blueshift - 1.9.4
Buffalo - 2.12
Buffalo2 - 1.5
Deep Space Exploration Vessels - 3.12
Airships - 2.19.1
Mk-33 - 1.3.2
Mark One Laboratory Extensions - 1.27
Kerbal Actuators: More Servos - 1.2
Pathfinder - 1.40.3
Sandcastle - 1.1.1
Kerbal Actuators: Servo Controller - 1.2.1
Snacks - 1.28`

This is on a fresh install of BDB via CKAN v1.31.2

**Comment by Rodg88** [comment]
This is due to having both TAC LS and Snacks installed, two different life support mods. Is there a reason to have both?

**Comment by GreenKeldeo** [comment]
> This is due to having both TAC LS and Snacks installed, two different life support mods. Is there a reason to have both?

Honestly, no - just ended up with both as a result of DeepFreeze Continued

**Comment by Rodg88** [comment]
Yeah, sometimes you need to be careful with CKAN installing too much lol
