### ISSUE TITLE
'AIR' variant for the Castor 120XL

### ISSUE THREAD

**Issue by Starkillerdude** [CobaltWolf/Bluedog-Design-Bureau#1362]
The Castor 120XL doesn't currently feature an air-started variant

I made a patch that includes it, the ISP is the same as the regular AIR variant, the thrust is speculative

@PART[bluedog_Peacekeeper_Castor120]:FOR[Bluedog_DB]
{
	@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[engineSwitch]]
	{
		SUBTYPE
		{
			name = Castor120XL-AIR
	    		title = Minerva-CGR120XL-AIR "Thestius-XL"
	    		descriptionSummary = Stretched Minerva second stage engine. Altitude optmized version of CGR120XL. Regressive thrust curve 100% to 66%
			real_title = CastorXL 120 AIR
			real_descriptionSummary = Streched Athena second stage engine. Altitude optmized version of Castor 120XL. Regressive thrust curve 100% to 66%
			descriptionDetail = <b>Thrust:</b> 484.68 kN ASL / 577 kN Vac.\n<b>Isp:</b> 252 s ASL / 300 s Vac.
			defaultSubtypePriority = 3
			addedMass = 0.12
			addedCost = 10
			transform = Castor120XL
			volumeAdded = 68 //1310
			RESOURCE
			{
				name = SolidFuel
				unitsPerVolume = 1
			}
			NODE
			{
				name = top
				position = 0.0, 2.9375, 0.0
			}
			MODULE
	  		  {
	    		  IDENTIFIER
	    		  {
	    		    name = ModuleEnginesFX
	   		  }

	    		  DATA
	    		  {
	    		    maxThrust = 374
					useThrustCurve = true
					thrustCurve //steadydrop_66
					{
						      key = 0    0.15  0    15
							key = 0.03 0.66  0.5  0.5
							key = 1    1    -0.6    0
					}
	 					}	
							}
								}
									}

**Comment by Starkillerdude** [comment]
*the description details are wrong

**Comment by CobaltWolf** [comment]
Are you sure? I could have sworn we added one for Carrack.

**Comment by Rodg88** [comment]
Added, currently both the air variants have the same isp though

**Comment by CobaltWolf** [comment]
hey so a little belated but @Rodg88 was this ever implemented?

**Comment by Rodg88** [comment]
Yeah it's in the base part cfg now, ill close
