### ISSUE TITLE
1.11 Dev Branch B9 Fatal Error

### ISSUE THREAD

**Issue by JovietUnion** [CobaltWolf/Bluedog-Design-Bureau#1364]
![image](https://user-images.githubusercontent.com/62820134/228402440-80d5758f-90b2-4b1c-bbfc-7be3808c1de2.png)

GameData

![image](https://user-images.githubusercontent.com/62820134/228402480-390d2207-6d2a-46f6-ae13-06295d370abd.png)

KSP.Log File

[KSP.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11095636/KSP.log)

Im just testing the Dev Branch to not just check out features, but to fix bugs

**Comment by JovietUnion** [comment]
Anyways, anyone have an an idea of what's causing the issue?

**Comment by Rodg88** [comment]
You need ModuleManager installed. You also don't need firespitter, all switching is done via B9PS
