### ISSUE TITLE
B9PartSwitcher Serious Warning - Skylab Radiator Modules Missing

### ISSUE THREAD

**Issue by Vatruvius** [CobaltWolf/Bluedog-Design-Bureau#1365]
I have recently been getting B9PartSwticher serious warnings about the skylab radiators; picture attached. I am running many mods, though the ones I believe directly interact with BDB would be Real Fuels and RF Stockalike RF Configs; the mod versions are written below. If there is something I can do to resolve this issue, please let me know what I need to do.

![KSP_BDB_B9PS_Error](https://user-images.githubusercontent.com/44359446/229031179-51cb56f5-8453-4080-8b31-ca274aa59afd.png)

B9 Part Switcher: v2.20.0
Bluedog Design Bureau: v1.12.0
Bluedog Design Bureau Extras - Community Category Kit: v1.12.0
Real Fuels: 1:rf-v15.3.1
Stockalike RF Configs: v3.2.6.6

**Comment by zorg2044** [comment]
Could you please post your moduleManager.log and modulemanager.configcache files? thanks

**Comment by Rodg88** [comment]
This is likely due to KerbalismSystemHeat, they may need to add specific patching on their side to fix

**Comment by Rodg88** [comment]
You can try making a new text file anywhere in GameData, rename it to `KSHBDBFix.cfg`, and paste the following in there:

@PART[bluedog_skylab_powerModule_radiator*]:NEEDS[Kerbalism,Bluedog_DB,SystemHeat,B9PartSwitch,zzzz_KerbalismSystemHeat]:AFTER[zzzz_KerbalismSystemHeat]
{
	@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[meshSwitchSide]]
	{
		@SUBTYPE,*
		{
			@MODULE
			{
				@IDENTIFIER
				{
					@name = SystemHeatRadiatorKerbalism
				}
			}
		}
	}
}

**Comment by Vatruvius** [comment]
Thank you for the replies, @zorg2044 and @Rodg88.

> Could you please post your moduleManager.log and modulemanager.configcache files? thanks

Here is a pastbin of "skylab_powerModule_radiator" search hits in the moduleManager.log file: [https://pastebin.com/sC8wHuJg](url)
I do not know where the modulemanger.configcache file is located.

> This is likely due to KerbalismSystemHeat, they may need to add specific patching on their side to fix

I will open an issue on Kerbalism System Heat's GitHub, except it appears to be dead since there is an open issue since December 2021.

> You can try making a new text file anywhere in GameData, rename it to `KSHBDBFix.cfg`, and paste the following in there:
> 
> @part[bluedog_skylab_powerModule_radiator*]:NEEDS[Kerbalism,Bluedog_DB,SystemHeat,B9PartSwitch,zzzz_KerbalismSystemHeat]:AFTER[zzzz_KerbalismSystemHeat] { @module[ModuleB9PartSwitch]:HAS[#moduleID[meshSwitchSide]] { @subtype,* { @module { @Identifier { @name = SystemHeatRadiatorKerbalism } } } } }

I tried what you recommended above with no change to the B9PartSwitcher serious warnings.

**Comment by Rodg88** [comment]
The actual log is still more useful, you can upload it as a zip if it’s large. Configcache is in the main gamedata folder.

it’s definitely KSH though, as it’s showing in that snippet, not sure why that patch wouldn’t be working though. Could you post the log after launching with my patch installed?

**Comment by Rodg88** [comment]
The dev for KSH is already aware too, next update should include a fix

**Comment by Vatruvius** [comment]
Here is a ZIP of the modulemanager.log file post temporary fix @Rodg88. [ModuleManager.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11155061/ModuleManager.zip)

I still need help finding the ModuleManager.ConfigCache file. I do have a ModuleManager.Physics file and ModuleManager.TechTree file, but no ModuleManager.ConfigCache file in "Kerbal Space Progarm\GameData." I even did a keyword search in File Explorer with nothing coming up in the entire game directory.

**Comment by Rodg88** [comment]
That log isn't showing my patch, maybe there's an issue with a hidden txt file extension? Try this copy:
[KSHBDBfix.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11157425/KSHBDBfix.zip)

If there's no config cache, it's probably due to some patch errors. It only saves the cache when there's been no patch errors. The KSP.log in the main game directory is still the most useful log for general diagnostics, while configcache shows parts post patching.

**Comment by Vatruvius** [comment]
Here is the new ModuleManager.log file @Rodg88 using your version of the KSHBDBfix.cfg configuration file: [ModuleManager.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11165590/ModuleManager.zip) I got the same serious warning message as before.

I even tried putting it in a folder named KSHBDBfix in Game Data just in case Module Manager does not like the configuration file loose in Game Data.

Additionally, it makes sense that there is no ModuleManager.ConfigCache from your explanation because I have four warnings and eighty-two errors with Rational Resources Kerbalism. I have already opened a case on their bug tracker.

**Comment by Rodg88** [comment]
It should be fine having loose cfg files, but either way it looks like the formatting was messed up somehow, and lost the correct capitalization. Try this one:
[KSHBDBfix.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11166300/KSHBDBfix.zip)

**Comment by Vatruvius** [comment]
Hey, that must have worked. I don't see those two serious warnings anymore. I did get a new serious warning when in the VAB messing around building stuff. I will replicate it and get that message to pop up again for a screenshot. Again, it was for a BDB part.

**Comment by Rodg88** [comment]
I've seen that upgrade error with SkyhawkScienceSystem, but since you don't have that I'm unsure what's causing it. Likely Kerbalism, if it's changing the part upgrade system. This is where a configcache would help lol. It's also fairly safe to ignore.

For the second one, try replacing these two files located in Bluedog_DB/Parts/Solids/Scout with these ones:
[bluedog_Scout_RFcompat.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11168283/bluedog_Scout_RFcompat.zip)

**Comment by Vatruvius** [comment]
Wow, @Rodg88, you are quite familiar with these serious warnings. I swapped out CTT for SSS but ended up undoing that change because of the error and not liking the changes. That resolved the first serious warning. Your file replacements fixed the other two serious warnings, so everything seems good now. I appreciate all your help. Now I need to fix these Rational Resources Module Manager patch errors. Thanks again.
