### ISSUE TITLE
Vanguard (Viklun) Insuffecient Delta-V

### ISSUE THREAD

**Issue by Vatruvius** [CobaltWolf/Bluedog-Design-Bureau#1369]
I recently attempted the three Vanguard (Viklun) missions with unfavorable results using the Easton-V1, V2, and V3 probes. I am playing with FAR, JNSQ, and Real Fuels, letting MechJeb remove the human element during my tests. What I have found under these conditions is that the V1 gets into an okay orbit of 85KM to 850KM, the V2 barely orbits at 85KM and 82KM, and the V3 lacks 300m/s to finish circularizing at 85KM. Given that the V3 is supposed to be orbiting at 125KM to 750KM, one-quarter scale to its real-world counterpart, I do not see how to improve this beyond modifying the rocket design.

According to the unofficial guide for BDB, [https://github.com/friznit/Unofficial-BDB-Wiki/wiki/Vanguard](https://github.com/friznit/Unofficial-BDB-Wiki/wiki/Vanguard), I am supposed to be using Easton-100 and Easton-800 fuel tanks. In-game, the tanks are called Easton-60 and Easton-490. I assume this is just a name change and is functionally the same, but if not, why is there no access to these larger tanks? Currently, I do not have the delta-v required to make these orbits. Perhaps a mod I have is negatively affecting my results, but they should not be affected by hundreds of meters per second. Am I doing something wrong?

**Comment by CobaltWolf** [comment]
@Vatruvius 

First, yes I can confirm that the different numbers in the fuel tank names are the result of a balance pass that occurred at some point after the guides were made. 

Second, I think I found the issue. The V2 satellite weighed 5x as much as the V1, and V3 weighed over 11x as much. I reduced them so V2 and V3 weigh slightly more than V1. I just pushed the fix, but you'll have to either replace the .cfg files for those parts with ones from the.... uh, master branch. Or just make the same edits to your local files. 

https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Vanguard/bluedog_Vanguard_Satellite2.cfg
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Vanguard/bluedog_Vanguard_Satellite3.cfg

That might not be enough to get V3 to the exact 125km x 750km orbit, but that's getting a bit in the weeds for how well we can balance out all the factors. You could try using one of the more advanced variants of the 3rd stage if you're still having delta V issues, just shut it down early.

**Comment by Vatruvius** [comment]
I have tested the new mass values and got far better results, all with a periapsis of 125KM and an apoapsis from 500KM to 650KM. Thank you for making the changes.
