### ISSUE TITLE
Kerbalism SystemHeat Conflict

### ISSUE THREAD

**Issue by Coelhomatias** [CobaltWolf/Bluedog-Design-Bureau#1371]
When using this mod with kerbalism SystemHeat I get this warning:
![image](https://user-images.githubusercontent.com/36272416/232913437-4df76b77-8763-45e0-93c5-d251ef0e3a82.png)

Should kerbalism systemheat be used or dropped?

**Comment by Rodg88** [comment]
It should be fixed when it next updated, but for not you can fix it with this patch https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11166300/KSHBDBfix.zip
