### ISSUE TITLE
Hibernation missing in PAW

### ISSUE THREAD

**Issue by MSchalken** [CobaltWolf/Bluedog-Design-Bureau#1373]
I am running into an issue where the Keyhole return capsule is missing the hibernation button in the PAW. Since pod starts in the command state hibernating, I have no way of gaining control of it.

https://i.imgur.com/xNhdhQu.png

I am using BDB with some other mods, most notably Kerbalism, but I can't figure out if any of the other mods is causing this.
[ModuleManager.log](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11314692/ModuleManager.log)

**Comment by Rodg88** [comment]
Does it have the button before you deploy it? And do any other probe cores have the hibernation buttons with kerbalism?

**Comment by Rodg88** [comment]
@MSchalken This patch should fix the issue, you can install it manually by downloading this file:
https://raw.githubusercontent.com/CobaltWolf/Bluedog-Design-Bureau/master/Gamedata/Bluedog_DB/Compatibility/Kerbalism/KerbalismHibernation.cfg

and installing it in: GameData/Bluedog_DB/Compatibility/Kerbalism/ (Kerbalism is a new dir)

And this will be included in the next versions.
