### ISSUE TITLE
Part Suggestion: Orbus-7S

### ISSUE THREAD

**Issue by Starkillerdude** [CobaltWolf/Bluedog-Design-Bureau#1374]
Orbus-7S is an obscure solid kickstage motor which IMO would be really cool to have in BDB.

it is basically an Minuteman III/Minotaur II+ 3rd stage (aka SR-73) but with the gimbal equipment removed (it was likely spin-stabilized). It had the abort holes seemingly painted over which hints at it not having that function. Performance was likely similar, if not exactly the same, to the base model (though with a slight weight reduction due to the loss of gimbaling equipment).

I am not sure if the following images are of SR-73 or Orbus-7S, though I tend towards the latter:
![image](https://user-images.githubusercontent.com/109817308/235153944-5f76a3a6-71ba-4999-815a-e2d0880abb1f.png)
![image](https://user-images.githubusercontent.com/109817308/235154845-957e4f5c-df2a-4d8b-bb88-3fcefb92fd4f.png)

My suggestion is: take the SR-73 already in BDB, paint the greenish color over it (as shown in the pictures), remove the gimbaling equipment and then add a hole cover between the lower tank area and the nozzle (this gap was due to gimbaling beeing used on SR-73).
It was used on a few flights on both shuttle and CT-3 as a kickstage. I suggested it because the minotaur lineup is still in development and a more unique upper stage solid motor would be great to have.

**Comment by Starkillerdude** [comment]
there is a possibility that the greenish paint is actually just a layer under the regular SR-73 paint, so I am not really sure.

**Comment by shakuvendell** [comment]
_Orbit 7S specifications
The orbus 7S was qualified as the PKM for Hughes' HS-393 family of communication satellites.  Derived from CSD's Minuteman 3 stage 3 motor, with the thrust termination and vector control systems removed, it could be stretched mid-cylinder and incorporate a lengthened nozzle.  An Orbus 7 version is available incorporating a liquid injection TVC system.
First flown:  30 Aug 1984 as part of USN/Hughes Leasat 2 milcomsat
Number flown:  8 to end-1995
Applications:  PKM, launcher upper stage
Mass:  3,547 kg fully loaded, 196 kg burnout
Length:  227.3 cm
Maximum diameter:  132 cm
Propellant
...type:  86% solids CTPB ANB-3066; forward end finocyl
...shape:  stepped cylinder
...mass fraction:  0.935
Burn time:  60.1 s
Thrust in vacuum:  153.467 kN average, 191.274 kN max
Total impulse:  12.5 MNs
Specific impulse:  281.9 s
Pressure (atm):  35.3 average, 43.5 max
Nozzle
...throat diameter:  174.7 mm
...length:  90 cm
...exit diameter:  84.76 cm (expansion ratio 23.55)
...materials:  tungsten throat insert, carbon phenolic exit cone, total mass 63.2 kg
Casing materials:  93-94 kg S-901 fiberglass/epoxy with silica-filled Buna-N
Igniter type:  4.54 kg head-end pyrogen, 6-nozzle_

Per a comment by Bob B., Forum Moderator, https://www.thespacerace.com/forum/index.php?topic=677.0

Comment cites "Jane's Space Directory 1996-97" as the original source.

https://space.skyrocket.de/doc_lau_det/titan-3_commercial.htm cites it as as having been used on at least one flight for Skynet 4A and JCSat 2. Specifically, is appears to have been used on the JCSat 2. The launch was on 01/01/1990, Clearly a dual payload flight.

JCSat would be a fun addition, too.
