### ISSUE TITLE
Parachutes don't slow down the craft

### ISSUE THREAD

**Issue by Brimmla** [CobaltWolf/Bluedog-Design-Bureau#1375]
The Gemini and the Mercury parachutes (probably others) don't slow the craft down enough for the crew to survive.

**Comment by Brimmla** [comment]
NVM i didnt read the closed issues

**Comment by Rodg88** [comment]
Likely a mod interaction or patching issue, would need your ksp.log file to look into it

**Comment by Brimmla** [comment]
How do I share my ksp.log?

**Comment by Brimmla** [comment]
Wait, nvm i figured it out
[ksp log.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11519686/ksp.log.zip)

**Comment by Rodg88** [comment]
@Brimmla So it's certainly to do with FAR, so first make sure you have this version:
https://github.com/dkavolis/Ferram-Aerospace-Research/releases/tag/v0.16.1.1_Marangoni

(Sorry for the delay, was ill with a virus)

**Comment by Brimmla** [comment]
No worries, I installed FAR.

**Comment by VioletChan311** [comment]
all parachutes that i tested work except for 'osiris' recovery chute which even at max alt (5000) and minimum pressure, will not slow down the eaglet sounding rocket probe core. i remember this working previously at some point. i tested with limited mods to make sure it wasnt something else. i had BDB + requirements, skyhawk science system + kerbalism and JNSQ + requirements. i also couldnt find any config files at all for the parachute which is odd. logs attached just incase 
[KSP log.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11593716/KSP.log.zip)

**Comment by Rodg88** [comment]
> i also couldnt find any config files at all for the parachute which is odd. logs attached just incase [KSP log.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11593716/KSP.log.zip)

That sounding rocket looks like it's a rescaled patched part from SSSKerbalism, might need to report it to them.

@Brimmla Did the issue persist with that version of FAR?

**Comment by VioletChan311** [comment]
ah, that would make sense. i didnt see any part files and the parts say Bluedog_DB when hovered. il report it there thanks!

**Comment by Brimmla** [comment]
Yeah, the issue still wasn't fixed even when I installed FAR.

**Comment by Rodg88** [comment]
@Brimmla Looks like it's the new drag cube generation from KSPCF. Installing this patch anywhere in your gamedata will disable it, which should fix the chutes.
[KSPCF_DisableCubegen.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11611082/KSPCF_DisableCubegen.zip)

**Comment by Rodg88** [comment]
The root cause however is actually shaddy, messing with KSPCF's new drag cube calc by changing the shaders on parachute canopies, causing drag cube calculation to fail.

**Comment by Brimmla** [comment]
Ok, I will try that

**Comment by VioletChan311** [comment]
just tested. patch worked for me. appreciate the help!

**Comment by Brimmla** [comment]
It works for me now, thanks!

**Comment by Rodg88** [comment]
@Brimmla @VioletChan311  KSPCF v1.29 should fix the issue now too, without needing to disable the faster drag cube generation feature via that patch.
