### ISSUE TITLE
"Disable decoupler staging" doesn't work on many parts with integrated decouplers

### ISSUE THREAD

**Issue by CCBrailov** [CobaltWolf/Bluedog-Design-Bureau#1377]
Apologies in advance for only using the fake names. I'm not playing with RSS right now and I don't know the correct names offhand.

I'll come back and edit this to increase the list as I notice more. The following parts have integrated decouplers, and the button to disable the staging of said decoupler does nothing:

- Etoh-C Guidance Unit
- Etoh-L Guidance Unit
- Belle 0.9375 interstage

**Comment by Rodg88** [comment]
Don’t worry about the names, either is fine. (Btw if you just want realnames anyway, but without installing RO, there’s just an optional  patch in extras to enable them)

unfortunately from a quick check of the config, I’m not sure what might be interfering. This may mean the feature is just incompatible with probe cores with integrated decouplers, I’ll have to test later.

If you can upload a zipped copy of your KSP.log and modulemanager.configcache I can see if there’s any other non-standard modules that may be interfering, but it’s also possible that it may be an issue with KSP itself

**Comment by Rodg88** [comment]
After testing, I'm fairly sure this is a base KSP issue, not something we can change.
