### ISSUE TITLE
RL10-C2 engine B9 subtype

### ISSUE THREAD

**Issue by Starkillerdude** [CobaltWolf/Bluedog-Design-Bureau#1379]
I decided to include the -C2 subtype in the -B2 config. Performance increase is not that much but it would still be nice to have it.

here the whole config (convert to .cfg before use):

[bluedog_CentaurD_RL10B2.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11794987/bluedog_CentaurD_RL10B2.txt)

**Comment by Rodg88** [comment]
The stats irl should be identical, and now the rl10 variants are all merged an extra subtype would really need a good justification to take up space in the switch.
