### ISSUE TITLE
SII WWS only supports two crew members

### ISSUE THREAD

**Issue by rp1-lox** [CobaltWolf/Bluedog-Design-Bureau#1380]
I think there's a bug for me that's only allowed me to have two crew members in the S-II Wet Workshop. I have no idea why. My config cache and KSP.log are attached.
[KSP.zip](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/11839490/KSP.zip)

**Comment by Rodg88** [comment]
Fixed, thanks.
Though I'm slightly concerned about the lab requiring 12 kerbals to function according to your configcache. That might be due to TS, or maybe LRTR. In my testing the lab only requires 2 scientist kerbals to actually run.
