### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1381]
File: Scidef_bd_GeigerCounter.cfg

The following lines each need their "your" changed to "you're." The first one, twice. 

  EveSrfLanded = Even though your relatively close to the sun your detecting no radiation on the surface. The thick atmosphere must be blocking the radiation.

  SunInSpaceHigh = Going further from the Sun your detecting increasing levels of radiation. Maybe some sort of cosmic source?

  SunInSpaceLow = Your detecting higher levels of radiation near the Sun. Maybe you should examine this more closely?

Sorry, I'm guessing a pull request would be easier for typos. I have this cloned in Github Desktop, but not sure how to do a pull request!

**Comment by Rodg88** [comment]
A PR isn’t necessarily easier, I can do tiny fixes like this very quickly. So reports like this are good, thanks!
