### ISSUE TITLE
Better Early Tree makes certain parts inaccessible

### ISSUE THREAD

**Issue by woodb3kmasterSC4** [CobaltWolf/Bluedog-Design-Bureau#1384]
Users of Better Early Tree don't have a node called "Enhanced Survivability" in their tech tree. Consequently, all parts assigned to that node can't be unlocked (and therefore don't show up in the Parts List). This most notably affects the Gemini capsule, and that's how I discovered this issue. Editing Compatibility\CommunityTechTree\CTT.cfg line 14 to make these parts' required node Survivability (which is what Better Early Tree does by default in its own patch file, which applies before BDB's) makes these parts accessible again. I don't know if any other parts are affected by similar issues.

**Comment by zorg2044** [comment]
Renaming another mod's tech node (Enhanced survivability is a CTT node) seems like a terrible way to do things.
