### ISSUE TITLE
Explorer 1 & remote tech

### ISSUE THREAD

**Issue by Gupyzer0** [CobaltWolf/Bluedog-Design-Bureau#1395]
Explorer 1 doesn't have a remote tech antenna in the configs.

Maybe other explorer series of probes suffer from the same problem like Beacon 1, S45, and S46.

Or maybe I'm missing something?

**Comment by Rodg88** [comment]
Remote tech configs are user submitted so may be out of date, and they aren't something the main team actively maintain. If you want to update them and submit a pr or post an updated file here for me to merge, feel free!

**Comment by Gupyzer0** [comment]
Closing issue as I sadly won't have enough time to make a good patch. Still leaving this for anyone who wants to pursuit remote tech and BDB working together.

First It's a good idea to comment  this line at the begginig of remotetechProbes.cfg so you don't need to wait reaching unmaned tech.

`//%TechRequired = unmannedTech`

And here's the sample on Explorer 1
```
// Explorer 1
@PART[bluedog_Juno1_Explorer1]:NEEDS[RemoteTech,!SETIRebalance]:BEFORE[RemoteTech]
{
	%MODULE[ModuleRTAntennaPassive]{
		%OmniRange = 1000000

		%TRANSMITTER {
			%PacketInterval = 0.6
			%PacketSize = 2
			%PacketResourceCost = 1.5
		}
	}
	
	!MODULE[ModuleRTAntenna]{}
}
```
