### ISSUE TITLE
Suggestion: Modular installer

### ISSUE THREAD

**Issue by kkx2754** [CobaltWolf/Bluedog-Design-Bureau#1396]
This mod is insanely good, but it bothers me a bit that there are very many parts in it and it takes up precious RAM. So I'm suggesting making a modular installer which allows for installing individual "modules", for example just the Saturn and Apollo pack. I've found out that manually removing folders from the Parts directory works, but inexperienced modders might find that a bit hard and unintuitive.

**Comment by Invaderchaos** [comment]
We’re not going to make a modular installer. BDB’s folder structure is designed so individual part families can be removed without affecting other parts (like the Saturn, Apollo, Titan, Agena, etc folders) if users only want certain parts.

**Comment by kkx2754** [comment]
Alright, thanks for the quick response!
