### ISSUE TITLE
Coroutine couldn't be started because the the game object 'bluedog.Vanguard.S2.Guidance' is inactive!

### ISSUE THREAD

**Issue by MaximumMatt** [CobaltWolf/Bluedog-Design-Bureau#1398]
No help from google, so I came here. 

The console keeps spitting out these errors for all of the BDB pods when hovering over the preview icon in the VAB. It seems to be only limited to BDB pods and no other mods/parts. 

When I try to leave the VAB, it spits out a huge error (which is in the log) and prevents me from leaving the VAB.

This only happened today, as I was reinstalling all of my mods to update them to the latest version. So every mod I have (including BDB) is updated to the most current version. 

Here is the KSP.log file https://drive.google.com/file/d/1dUuqNID7YyQcdG_8wRD5ZklRRqydwk0u/view?usp=sharing

Any help is appreciated. 

EDIT: It seems the error only happens after reverting craft to VAB.

**Comment by Rodg88** [comment]
I don't have access to that log file link, sharing settings just need to be updated to allow anyone with link.

It sounds like it may be a corrupted download of something though, it's a weird error. Try verifying game files first, or perhaps during your mod updates one of the downloads errored. I'll still check the log when I have access though

**Comment by MaximumMatt** [comment]
Link should be fixed now. I'm currently going through my mods folder enabling things over time to see if there is any conflict between mods.
