### ISSUE TITLE
Duplicate subtype Water on bluedog_Apollo_AARDV_Cargo_Block1 with kerbalism installed

### ISSUE THREAD

**Issue by JonnyOThan** [CobaltWolf/Bluedog-Design-Bureau#1399]
The following patches both add a Water subtype to bluedog_Apollo_AARDV_Cargo_Block1  when kerbalism-default is installed

https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/968487ec5fb243337f995403bc93f4d83b9fccd4/Gamedata/Bluedog_DB/Compatibility/B9PartSwitch/B9PartSwitchTanks.cfg#L61

https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/968487ec5fb243337f995403bc93f4d83b9fccd4/Gamedata/Bluedog_DB/Compatibility/Kerbalism/KerbalismCargo.cfg#L27

**Comment by Rodg88** [comment]
Are two showing up in game? The first patch should require not having kerbalism default patches present.

**Comment by JonnyOThan** [comment]
It creates a b9ps “serious warning” dialog at startup.

**Comment by Rodg88** [comment]
I'll have to double check, I wasn't getting errors last time I checked with default kerbalism.

**Comment by JonnyOThan** [comment]
oh never mind you fixed this since the last release! https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/8b279c0b4bcb85387d08cbeb483061e544679e99
