### ISSUE TITLE
Non SAF 3.125-3.5m Fairing request  LDC Titan

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#1405]
https://forum.kerbalspaceprogram.com/topic/122020-1125-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v1130-%D0%B7%D0%B0%D0%B1%D1%8B%D1%82%D1%8B%D0%B9-13aug2023/?do=findComment&comment=4359557

**Comment by Rodg88** [comment]
Done
