### ISSUE TITLE
Weird Purple sqaures stacked on top of each other during ignition of any engine.

### ISSUE THREAD

**Issue by Vertex-Wanderer08** [CobaltWolf/Bluedog-Design-Bureau#1408]
![screenshot95](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/132978461/03622fab-6dcc-4d4c-9f40-c1f23573d6f2)
![screenshot97](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/132978461/c0e590c1-f615-4cec-9ca4-d8d0c6255ac3)

never had this issue or glitch before, just started recently.

**Comment by zorg2044** [comment]
I don't know what the cause is here but its usually an out of date visual or effects mod that creates these.

**Comment by Vertex-Wanderer08** [comment]
> I don't know what the cause is here but its usually an out of date visual or effects mod that creates these.

ah i see, probably something within my mods that i updated, thanks man!

**Comment by zorg2044** [comment]
Yeah try disabling some of those mod until it goes away which will help you identify it.
