### ISSUE TITLE
Mariner 9 Solar Panels not reliably generating EC

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1411]
https://i.imgur.com/ELAjylU.png

Panels facing directly at sun don't generate EC, or generate very little. (see attached image)

**Comment by Rodg88** [comment]
it's weird, the sunCatchers look correct, but the panels are only generating when the end is facing the sun. Cobalt will have to look into the model

**Comment by Rodg88** [comment]
It seems to be due to the suncatcher being a child of the skinned mesh animation, need to have the sun catcher independent of that

**Comment by Rodg88** [comment]
Looks like the sunCatcher has to be below a transform that can be defined as the pivot, even when it's not a tracking panel. Maybe if it can be a child of "base"

**Comment by Rodg88** [comment]
Fixed, however the panels won't fall apart when broken
