### ISSUE TITLE
Waterfall FX flicker on M-1 engine.

### ISSUE THREAD

**Issue by JacobB094** [CobaltWolf/Bluedog-Design-Bureau#1419]
When a running M-1 is viewed from behind, there's a very noticeable flicker in the Waterfall plume around the nozzle rim.

**Comment by zorg2044** [comment]
I couldn't see any flickering tbh but on the sea level variant I saw a slight gap near the rim. Was your issue on the sea level version? I suppose it might cause some kind of aliasing depending on your screen resolution/anti-aliasing settings. I have fixed the gap in a commit to the dev branch which you can take a look at if you use it.

**Comment by JacobB094** [comment]
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/168674181/55862ab1-ec56-42cb-b49b-baa89e8814fe)
The issue is with the altitude nozzle. I tried to capture the flicker, but like z-fighting, it's hard to catch. It's more obvious in motion.

**Comment by zorg2044** [comment]
Hmm I didnt see this but will check again. Since the waterfall effects are rendered on a plume mesh it might well actually be z-fighting.

**Comment by Rodg88** [comment]
@JacobB094 This is due to TAA, likely from TUFX, possibly Scatterer.
