### ISSUE TITLE
New Atlas Parts not in CCK 

### ISSUE THREAD

**Issue by gitermane6999** [CobaltWolf/Bluedog-Design-Bureau#1424]
All the new and revamped parts are missing in the custom category (Bluedog_DB_Extras)
![Screenshot_145](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/101951007/81d18e81-6bd7-4255-917e-28e8bb2b4b2c)

**Comment by Rodg88** [comment]
fixed, and removed some of the old parts, will update as they get depreciated
