### ISSUE TITLE
Commercial Titan III 2.5m Dual Payload Adapter SAF base flag shader not correct

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1435]
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/19e34411-e822-4cdb-a76f-ad3fc130a4fa)

**Comment by Rodg88** [comment]
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/b132583e-6da6-42b7-8c74-e9d9f5f41da7)
same with bluedog_Spacelab_airlockModule

**Comment by Rodg88** [comment]
on import, the shader is listed as "Standard" for both of these

**Comment by zorg2044** [comment]
c77802eeb55ec0cc52963c5bafdf02273d73ef85
01056df28f85b6cf0eddcdff61ee953f40755fb5
