### ISSUE TITLE
BigG_CylindricalSM using old texture for window

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1441]
In the MOL part folder, BigG_CylindricalSM is using a material with Gemini_Crew_A_psd for one little window, which is the last thing using that texture set. it could maybe be UVd to use the MOL_New set which has another glowing window. (tho its the small endcap one. that texture set already has an Emit map though)

just this window:
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/8adb76c8-26df-4f0b-abd3-b58ad91cf46d)

It could possibly be moved to the Gemini folder instead too, it's the only bigG in MOL, but i think it uses the MOL 3d endcap

**Comment by CobaltWolf** [comment]
That part should be removed. It was replaced by the BigG_CylindricalSM_CargoModule and BigG_CylindricalSM_EquipmentModule parts in the Gemini folder.
