### ISSUE TITLE
Apollo CM lab white paintswitch shiny

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1443]
might be TU patch issue

**Comment by Rodg88** [comment]
Can't really keep the shader swap without having separate meshes for white and grey/silver, disabling TU compat for RCML

**Comment by Rodg88** [comment]
@CobaltWolf if you can add a separate CM mesh to the RCML for the white texture to be applied to, the TU patch can be enabled again. It needs to have a full mesh swap instead of a texture swap as B9PS can't change the shader, so when TU patches apollo to have the PBR shader, it still applies to the white texture variant

**Comment by CobaltWolf** [comment]
Added the other mesh. It is named "Painted" like the other CM variants

**Comment by Rodg88** [comment]
@CobaltWolf looks like the Painted mesh just needs to have a material using the base bluedog_Apollo_CM texture, not bluedog_Apollo_CM_White. Looks like that's how the base CM model is set up too.

seems like there's a quirk where if the default texture of the Painted mesh isn't where it's expecting it to be, it will just break the shader, _even though_ the paint switch module specifies the correct texture later.
