### ISSUE TITLE
Mercury drogue chute offset

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1447]
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/0d8562ee-5797-48c7-8628-e53bf4a37a97)

it also might have some wonky normals in the inner ring
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/8d81bed1-a781-4371-ae1e-f645c1f3e5bb)

**Comment by CobaltWolf** [comment]
This part's animation is fucked but I fixed the worst of it. Uploaded a fix, needs to be checked.

**Comment by Rodg88** [comment]
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/448cccc8-c1b2-410a-a9de-7d990e420ecb)
looks good
