### ISSUE TITLE
bluedog_Taurus_S1_Interstage collider hierarchy 

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1448]
The colliders for the larger segment only toggle on when the upper segment is attached to something, and the colliders for the upper segment are enabled when that part of the mesh isn't visible. Basically, then the small node isn't attached and the smaller cone is hidden, the colliders are inverted from what they should be.

**Comment by CobaltWolf** [comment]
Uploaded a fix, needs to be checked.

**Comment by Rodg88** [comment]
colliders working now, may need to adjust the module setup to be like vanguard or the thor/able interstages where the top is the main part and the bottom is the 'fairing'
