### ISSUE TITLE
SAF fairings heating up too fast

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#1457]
Something thats bugged me for a long time tbh. SAFs seem to heat up faster than other parts, can be quite ugly. Not sure if its a misconfiguration on our end or if its a SAF issue.

**Comment by Rodg88** [comment]
I bet emissiveConstant in the main part could help, the part default is 0.4, while stock engines for example have 0.8, or stock nosecones have 0.7

**Comment by Rodg88** [comment]
Looks like the SAF parts all have 0.8, might try bumping it up to like 0.9

**Comment by Rodg88** [comment]
should be good now with heatConvectiveConstant = 0.9 on all saf parts
