### ISSUE TITLE
Make it so IUS can fit in a 1.875m payload fairing

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#1466]
Might be worth keeping the original as a variant. Not sure how to do it without messing up the mesh.

**Comment by Rodg88** [comment]
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/169d75bc-a1c5-4053-8f8c-9f3547c6f91f)
The 1.875m adapter shroud on the orbus 21, with a 1.875 decoupler, is also clipping into the fairing.
The adapter section of the shroud could be simple to downscale a bit
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/7145c794-a458-4bbb-8205-437bee459f69)

the main issue is the decoupler though, could maybe just add a switch to add a rescaled smooth profile 1.87m decoupler:
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/dcd51a2c-5eff-4478-9724-38f70aab7336)

Or the existing IUS interstage part that fits on top of the orbus 21 could have a variant that is the autoshroud from the orbus 21.

**Comment by Rodg88** [comment]
like so? 
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/97f3e810-7ac3-4254-be98-147487d8e7c3)
