### ISSUE TITLE
QOL suggestion

### ISSUE THREAD

**Issue by McLeggy** [CobaltWolf/Bluedog-Design-Bureau#1473]
Add a "collect all" feature to the Apollo command modules (like on the Corona return capsule) so players won't have to constantly EVA to collect SIM bay payload science experiments. Some of the experiments only give science if recovered and it gets a little tedious having to EVA to grab the data all the time.

**Comment by Rodg88** [comment]
Could look into this, though the Optical Recording Unit bay part should have that functionality too, so could reduce it to one collection, as long as the bay configuration includes it... Having the pod have the same functionality would also kind of make the Optical Recording Unit as its currently set up kind of pointless.

**Comment by McLeggy** [comment]
The optical recording unit is only used on 17 and even then doesn't transfer to the command module so all the science that does get stored is lost on seperation~Kenny PaduchPronouns: They/Them/TheirsOn Jul 4, 2024, at 12:52 AM, Rodg88 ***@***.***> wrote:﻿
Could look into this, though the Optical Recording Unit bay part should have that functionality too, so could reduce it to one collection, as long as the bay configuration includes it... Having the pod have the same functionality would also kind of make the Optical Recording Unit as its currently set up kind of pointless.

**Comment by CobaltWolf** [comment]
Now that I think about it, part of the point is probably to retrieve them via EVA like in real life

**Comment by Rodg88** [comment]
You can use a generic patch like this if wanted https://forum.kerbalspaceprogram.com/topic/139980-130-community-database-of-module-manager-patches-for-stock-ksp/?do=findComment&comment=3190015
