### ISSUE TITLE
Duplicate B9 Part Switch subtype names: "Water" on resupply parts with Kerbalism installed

### ISSUE THREAD

**Issue by ratemisia** [CobaltWolf/Bluedog-Design-Bureau#1474]
With B9 Part Switch, Bluedog Design Bureau, Kerbalism, and Kerbalism Default Config installed, B9 Part Switch throws a "Serious Error" during KSP loading to Main Menu: "Duplicate subtype names found on ModuleB9PartSwitch: Water". KSP's log suggests that the duplicate subtype names are on several Bluedog Design Bureau parts:

- AARDV Cargo Block 1 and 2

- Gemini "Augustus" Capsule

- Gemini "LongFerrySM"

- Agena Resupply Container

- Big Gemini Cylindrical SM

- Gemini Ferry Pressurized Module

- Gemini Resupply Capsule

- and the MOL "KISmodule".
I suspect that they're all caused by the same .cfg as highlighted in #1399.

In the error, B9 Part Switch says that "the game will continue to run, but this should be fixed ASAP." I have been able to reproduce this error by installing the above mods and dependencies into a blank install and loading to Main Menu. I have experienced NullRefExec spam and stutter in the Editor and in flight after receiving this error during loading, but have not been able to reliably reproduce the nullref spam.

**Comment by ratemisia** [comment]
I see this had been mentioned in issue #1399 - however, it doesn't appear fixed with the latest versions of BDB and Kerbalism, and wasn't identified as appearing on all the above parts in that issue.

**Comment by ratemisia** [comment]
Error does not appear when commenting out these lines in [https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/968487ec5fb243337f995403bc93f4d83b9fccd4/Gamedata/Bluedog_DB/Compatibility/B9PartSwitch/B9PartSwitchTanks.cfg](url):
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/103651498/0366d17c-91a0-4248-995b-a0d295a97e66)

**Comment by ratemisia** [comment]
As suspected in that issue, there appear to be 2 water entries in B9PS from checking in the VAB:
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/103651498/e647eccb-6fdb-44bf-af19-5af364d2bd9d)

**Comment by Rodg88** [comment]
Have you installed from Spacedock? The current version on spacedock doesn't have the fix. If you download the zip from github or use CKAN (I think), it should contain the fix

**Comment by ratemisia** [comment]
I'm off my computer now, but I did install from CKAN. When I next have the opportunity, I'll download from Github and see if that fixes it.

**Comment by Rodg88** [comment]
And to be clear I mean from here, not from the "releases" page 
![image](https://github.com/CobaltWolf/Bluedog-Design-Bureau/assets/2611674/8c36ac6c-5abf-4bc2-91d5-c243f8c74b81)

**Comment by ratemisia** [comment]
Can now confirm, the duplicate entries are fixed in the dev branch, as you said. Nice to know, thanks for the help
