### ISSUE TITLE
Mass Discrepancy between Agena Resupply Container and Gemini Resupply Capsule.

### ISSUE THREAD

**Issue by jmrd98** [CobaltWolf/Bluedog-Design-Bureau#148]
I was going through the parts to add to the USI-LS patch (#147), and I noticed this:

The bluedog_Agena_ResupplyContainer has an empty mass of 0.3 tons, and is more or less a pure KIS box, as best I can tell.

The bluedog_Gemini_ResupplyCapsule clocks in at only 0.2 tons dry, by contrast. (This is with all of the hand-wavy computer/radio/etc mass included, before the cargo comes in.)

One of these seems off, but I don't use them often enough to say which. 

Based on the mass of the parent Gemini pod, I think the G_Resup_Cap part is quite a bit under-massed. Any thoughts, gang?

**Comment by jsolson** [comment]
I guess they're structural. We'll have to see what similarly sized structural parts weigh in at. (none of the structural stuff had been balanced)

**Comment by CobaltWolf** [comment]
Why structural? Why not judge the agena on just cargo? And then the Gemini, average the weight of that size probe and that size KIS container, by volume. 

-----Original Message-----

**Comment by jsolson** [comment]
Ok. We can use the tank formula then.

**Comment by jsolson** [comment]
Just from eyeballing a few parts, I'm going to say leave the Agena part alone and make the Gemini part 0.5 tons. A 0.4 base and add 0.1 for the probe stuff.
