### ISSUE TITLE
Smoke point for M55A1

### ISSUE THREAD

**Issue by JacobB094** [CobaltWolf/Bluedog-Design-Bureau#1481]
Currently, the Minotaur booster uses thrustTransform for its FX, which is not ideal, because there are four of them. For thick, gray smoke which more advanced SRB FX use, this results in particles proliferating quickly and not looking particularly good. A single smoke point transform in the middle would make it possible to create a better looking effect with better performance.

**Comment by CobaltWolf** [comment]
Easy enough to add, I'll take care of that next time I'm clearing issues

**Comment by Rodg88** [comment]
Just set the smoke in stock and realplume to use a different transform on the model, which works ok, but a real smoke transform will still be better

**Comment by Rodg88** [comment]
confirmed fixed, and set up
