### ISSUE TITLE
Move to transformMultipliers for AJ-260 inline, GE-405, GE-405H and JPL 45K engine.

### ISSUE THREAD

**Issue by JacobB094** [CobaltWolf/Bluedog-Design-Bureau#1482]
Leaving it here so it's not forgotten. Basically, the aforementioned engines use multiple instances of ModuleEngines for their verniers, which is messy and causes two fuel gauges to appear. Moving them to use transformMultipliers instead would fix the issue and streamline the config somewhat.

**Comment by JacobB094** [comment]
GE-405 and -405H are done, that still leaves AJ-260 inline and JPL 45K.

**Comment by Rodg88** [comment]
All have been converted now
