### ISSUE TITLE
viking orbiter solar panels suncatchers

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1485]
The viking orbiter solar panels need slight reorganization for the suncatcher, like mariner 71 etc.

**Comment by CobaltWolf** [comment]
what change actually needs to be made?

**Comment by Rodg88** [comment]
My current theory as to what is going wrong is the solar panel module does not like it's "pivot" being animated. So just adding a new transform above the current pivot (hinge1), and have the suncatcher a child of that should work. You possibly don't even need to move the suncatcher up in the hierarchy.
![image](https://github.com/user-attachments/assets/41ff3f80-89d7-4c4e-8803-dc801e2d3c4e)

**Comment by Rodg88** [comment]
while you're at it, if you can move the `extrudedSurface2` object under hinge2, or under a new transform that's animated instead, that could fix the antenna variant switch on this part. It re-appears on deployment when it should be hidden
