### ISSUE TITLE
Inline SRMUs don't separate cleanly.

### ISSUE THREAD

**Issue by JacobB094** [CobaltWolf/Bluedog-Design-Bureau#1487]
The when used as an upper stage, the SRMU has serious separation issues. The issue seems to be the nozzle collider, which does not clear a decoupler mounted below. This can lead to the SRMU dragging the lower stage with it, until the whole thing glitches out, or the rocket just spinning out of control on separation.

**Comment by Rodg88** [comment]
Also not seeing this locally. If you post the log in #1488 I'll be able to look into it more
