### ISSUE TITLE
SRMU Inline asymmetrical thrust.

### ISSUE THREAD

**Issue by JacobB094** [CobaltWolf/Bluedog-Design-Bureau#1488]
The thrust of the SRMU appears to be slightly askew. RCS Build Aid reports about 3Nm of torque (more or less depending on SRMU length set) coming from an otherwise perfectly symmetrical stack. This causes the whole stack to oscillate even when it's perfectly rigid. When used in pairs on Titan configurations, this problem does not appear, the torques probably cancel each other out. In single stick applications, this is a serious problem.

**Comment by Rodg88** [comment]
Not seeing it on my end, might need a log.

**Comment by JacobB094** [comment]
[LCLS-A.craft.txt](https://github.com/user-attachments/files/16200514/LCLS-A.craft.txt)
No log for now, but try this .craft file, which exhibits the issue (and the separation one) on my end. In my latest test, the payload I was launching with was 0.5T. This is a fairly straightforward LCLS-A build, nothing fancy.

Did you engine check torque with RCSBuildAid? While it's possible that the separation issue is limited to some subtypes of the motor, for torque, I've cycled through all of them, and not only is the torque always there, it scales pretty directly with the motor's thrust. The oscillation happened under MechJeb control, BTW, I got so used to PVG as the default mode of flying LVs that I forgot to mention it.

**Comment by Rodg88** [comment]
Loading that craft has resulted in this, so something has gone weird:
![image](https://github.com/user-attachments/assets/eff61ca5-68ab-4557-8b39-824fad4a41d0)

If this is how you've set up the decoupler, that'll be the reason for the messy decoupling.
![image](https://github.com/user-attachments/assets/299d548f-f71c-49ed-9247-0937df9d48ed)

There was some mismatch of the COM offset and node positions between the default part cfg and the default subtype, which could cause some odd COM offsets in some cases with tweakscale, but it wouldn't have caused major loss of control. Looks like you don't have TS anyway. And the type switch wasn't set to update drag cubes/FAR calculations, so maybe that could have cause some offset drag with FAR?

The 0.003kNm torque is minimal and won't cause any loss of control. I've tested with a various SRMUs and a titan probe core and nose cone, and it launched straight upwards with no SAS enabled and didn't deviate.

**Comment by Rodg88** [comment]
Maybe try again with that last pushed change to the SRMU

**Comment by JacobB094** [comment]
> But if this is just node pos corruption and just have the decoupler below the fairing that's fine
> 
> The 0.003kNm torque is minimal and won't cause any loss of control. I've tested with a various SRMUs and a titan probe core and nose cone, and it launched straight upwards with no SAS enabled and didn't deviate.
This is node pos corruption. The vehicle looks normal on my end, I haven't even used the offset tool. Did you try a similar build? 1 segment air lit, Titan decoupler below, and 1.5 segment ground lit. Upper composite is 1.875m ring with Delta K and Centaur shroud, but it shouldn't matter (and it seems like that is fine).

Also, it's not loss of control, it's wobble. It does fly, it just constantly wants to correct. Worth noting, this continued outside the atmosphere, so it's not FAR doing it. The separation happens pretty much outside atmosphere, so I don't think it's interfering.

I'll make a new .craft file with updated boosters, but I doubt toggling some FAR switches will fix it.

**Comment by Rodg88** [comment]
Ah the decoupling issue is the decoupler's fault - in short mode there still seems to be some upper shroud colliders active.

And I see PVG is definitely trying to use too much control authority/it's resonating, is this what you're experiencing?
https://github.com/user-attachments/assets/b2997919-fb83-4899-9c93-4c635ee17f12

**Comment by Rodg88** [comment]
Yeah after looking into it for a few hours, it seems this is basically entirely due to how MJ's default guidance works with this particular craft. I can run the upper SRMU stage in orbit with no guidance active and it flies very straight. However with MJ guidance's constant turning to track a moving goal attitude, and the high available torque from the gimbal, it gets itself into a resonating loop. Even if I set the gimbal response speed to be very slow.

However you can change the attitude adjustment method MJ uses, and it seems the "hybrid" one works much better for this particular craft.

![image](https://github.com/user-attachments/assets/1377d1d0-251f-4270-9a7b-873b2237ac5d)

Last thing I can try is adjusting the model positions to be centered at the COM, instead of using the b9ps COM offset feature. I have seen some buggyness with using COM offsets, resulting in the COM being way too high on short SRMU variants on craft load. Probably unrelated, but probably also worth fixing...

**Comment by Rodg88** [comment]
There was also an error with the COM offset, causing it to be too high. fixing this has also seemed to help a lot with the wobble, even with the default MJ controller

**Comment by JacobB094** [comment]
OK, so I'll try a different decoupler. Glad to see the real problem with COM offset could be found. I'll test the fixes and report back.

**Comment by JacobB094** [comment]
LCLS-A flies well, but 2.5 segment inline SRBs are still oscillating. Had the COM offset been fixed for every length? For the record, UA-1205s on Titan SRM-1 and 2 fly perfectly straight under MechJeb. I'll do more testing, but this behavior appears to be specific to SRMUs.

**Comment by Rodg88** [comment]
Interesting, the 2.5 seg boosters dont define com offset in the subtype, so should be using the base part cfg. You could try adding a line within the srmu full subtype (around line 525) - "CoMOffset = 0, 5.5, 0" and see if that helps.

**Comment by Rodg88** [comment]
Looks like it just requires specific MJ settings for this part. For the BetterController, setting the PID Phase Margin Preset to 90deg helps a lot, or using the HybridController works well too.

I could put these notes in the inline subtype description maybe?

**Comment by Rodg88** [comment]
Also try with the latest dev build of MJ, it seems to work better by default https://ksp.sarbian.com/jenkins/job/MechJeb2-Dev/

**Comment by JacobB094** [comment]
I'll try, but my previous experience with KSP modding taught me that if one part misbehaves while a very similar one does not, there's usually some deeper SNAFU behind it. Since UA-1207s work fine and SRMU oscillate, that means there's _something_ different about SRMUs, and since they're supposed to be very similar motors, that something is probably unintended.

I'll try the COM offset thing, if COM position is different between UAs and SRMUs, that'd explain the difference in behavior. IMO it shouldn't be (maybe a little at burnout), since physically they're very much alike.

**Comment by Rodg88** [comment]
The SRMU has one extra degree of gimbal range with the higher thrust, which together probably amplify the issue, so I'm not surprised the 1207 is slightly more stable. And the UA120 has a nozzle that doesn't move when it gimbals which might hide what its doing in flight a little bit. I was still seeing some slight "wagging" of the thrust from UA120s when using mechjeb to show the thrust vector in-flight, with the default controller of main release MJ.

Current dev branch has the com offset respecified in the subtype, but it should be no different to how it behaves without that line, as its the same offset as the base config. If you wanted to test, you could try changing the 5.5 offset to 5 on the "full" variant, which is what the UA1207 has. If you don't see any worsening of the issue with 5 vs 5.5 I'll just change it to 5 anyway, as it's the midpoint between the 2 and 3 segment variant CoMs, and matches the 1207.

But at this point after fixing the main bug of the 2nd b9ps module changing the CoMOffset, and maybe moving the CoM by .5m, I'm pretty sure it's mainly down to MJ's control settings, and individual craft parameters. Definitely try out the hybridController or 90deg button on release build's betterController, or the dev build of MJ. (Dev build doesn't have the phase angle buttons for better controller anymore, but it doesn't seem to need them either)

**Comment by Rodg88** [comment]
Going to close this for now, all the actual bugs are fixed as far as I can tell.
