### ISSUE TITLE
Apollo Texture Problem

### ISSUE THREAD

**Issue by Cowboy-WY** [CobaltWolf/Bluedog-Design-Bureau#149]
All Apollo parts appear to be having a texture problem.
![apollo](https://cloud.githubusercontent.com/assets/20691292/17536580/3226273c-5e53-11e6-9c31-e6346b4a856c.PNG)

Must be related to the conversion to DDS textures as placing the .tga files back in the directory fixes it.  not sure if there is something that references the texture files with their extensions.

**Comment by Cowboy-WY** [comment]
Hmmm. A change, but not fixed :(
![apollo2](https://cloud.githubusercontent.com/assets/20691292/17644524/6155145a-6146-11e6-95ed-649373b2541f.PNG)

**Comment by Cowboy-WY** [comment]
Looks good now.
![apollo](https://cloud.githubusercontent.com/assets/20691292/17644793/1f7a69ba-614e-11e6-9e94-9abae333951b.PNG)

**Comment by VenomousRequiem** [comment]
Good, but there's some awkward seams in it. If you take a close look at the engine bell or the CM, you'll see what a mean.

**Comment by CobaltWolf** [comment]
That's the normal maps acting strange... what the hell...

**Comment by VenomousRequiem** [comment]
Try removing the normal maps for now until you can get it settled.

**Comment by CobaltWolf** [comment]
I'm making a quick commit with another attempt.
