### ISSUE TITLE
Gemini Lunar Recon antenna part costs

### ISSUE THREAD

**Issue by Nolnoc** [CobaltWolf/Bluedog-Design-Bureau#1495]
The part and entry costs for the Lunar Gemini Recon Dish and Antenna are extremely high. The Recon Dish costs 12,000 funds and the Antenna costs 7,500. Both of these seem to be around 10x the cost that would make sense, and are among the most expensive antenna despite their limited use.

**Comment by Rodg88** [comment]
Fixed, thanks
