### ISSUE TITLE
BIG PROBLEM!

### ISSUE THREAD

**Issue by raidernick** [CobaltWolf/Bluedog-Design-Bureau#15]
The chemtrails from your rockets are obviously some sort of biological agent that is causing users to believe in climate change that are being orchestrated by the lizard men that faked the moon landing! I DEMAND AN EXPLANATION AND FIX IMMEDIATELY OR I'LL CALL MY FLAT EARTH BROTHERS TO TAKE YOU DOWN!

**Comment by CobaltWolf** [comment]
Oh.

**Comment by CobaltWolf** [comment]
Just going to close this, so it isn't in the issues list.
