### ISSUE TITLE
AJ260 error

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1502]
There seems to be something wrong with the AJ-260s in real names mode. I'm getting this error: 
`[EXC 14:39:30.923] Exception: Could not find matching module
	B9PartSwitch.ModuleMatcher.FindModule (Part part) (at <a3c2951fc74e4639820ef37d2d29f386>:0)
	B9PartSwitch.ModuleModifierInfo+<CreatePartModifiers>d__10.MoveNext () (at <a3c2951fc74e4639820ef37d2d29f386>:0)
	B9PartSwitch.PartSubtype.Setup (B9PartSwitch.ModuleB9PartSwitch parent, System.Boolean displayWarnings) (at <a3c2951fc74e4639820ef37d2d29f386>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:LogException(Exception)
	B9PartSwitch.PartSubtype:Setup(ModuleB9PartSwitch, Boolean)
	B9PartSwitch.ModuleB9PartSwitch:InitializeSubtypes(Boolean)
	B9PartSwitch.ModuleB9PartSwitch:GetInfo()
	PartLoader:CompilePartInfo(AvailablePart, Part)
	<CompileParts>d__56:PartLoader+<CompileParts>d__56.MoveNext_Patch0(<CompileParts>d__56)
	KSPCommunityFixes.Performance.<FrameUnlockedCoroutine>d__62:MoveNext()
	KSPCommunityFixes.Performance.<PartLoader_CompileAll>d__58:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
`
The gimbal on the inline variant's main nozzle doesn't seem to work.

_Originally posted by @JacobB094 in https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/1493#issuecomment-2241601729_

**Comment by Rodg88** [comment]
@JacobB094 Not happening locally for me, might need to check your Saturn parts folder is completely up to date with dev. then if it persists maybe the modulemanager.configcache, and KSP.log

**Comment by JacobB094** [comment]
[KSP.zip](https://github.com/user-attachments/files/16360708/KSP.zip)
Here you go. Parts are up to date, the whole folder is freshly replaced from Github.

**Comment by Rodg88** [comment]
It's due to FerramAerospaceResearch/stockEngineGimbalIncrease changing the gimbal range (this patch probably also didn't help with the SRMU stability tbh lol)

I'll see if I can use some other module identifier so changing gimbal ranges doesn't break it.

**Comment by Rodg88** [comment]
Try that, just update the AJ260 cfg file
