### ISSUE TITLE
Request for a mesh to be renamed

### ISSUE THREAD

**Issue by Bellabong** [CobaltWolf/Bluedog-Design-Bureau#1505]
The new all in one engine for the Titan rework has overlapping mesh names which makes it difficult to config for when using only TU.

The nozzle mesh for the AJ3 is called "Mesh 1", which overlaps with the titan 1 style shrouds on later AJ's which is also called "Mesh 1"

![image](https://github.com/user-attachments/assets/69456324-fc0a-4702-809c-92d386e23ca9)
![image](https://github.com/user-attachments/assets/794c66d6-4521-4481-9fac-6e6eb6b081fe)

**Comment by Rodg88** [comment]
Done, new name is AJ3Bell
