### ISSUE TITLE
Delta Dual Payload

### ISSUE THREAD

**Issue by McLeggy** [CobaltWolf/Bluedog-Design-Bureau#1510]
The top part of the Delta Dual Payload Adapter is missing the inside node to attach to the bottom part when at extended length

**Comment by Rodg88** [comment]
unable to reproduce, not sure what might be causing this. might need a log/configcache to see what's going on

**Comment by Rodg88** [comment]
fixed by changing the node position switch to the top half, and fixed decouple direction
