### ISSUE TITLE
bluedog_Viking_Orbiter_PropulsionSection has no emissive

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1513]
viking propulsion nozzle has no emissive shader
the mariner 71's propulsion module's nozzle has a shader that reuses the diffuse as the emissive, which works pretty well with the copper coloured nozzle. so can probably get away without a new emissive texture

**Comment by CobaltWolf** [comment]
They are supposed to have an emissive on the same texture sheet, offset by 0.05 or 0.1 on the horizontal UV axis. I've been doing that for a while now, saves having separate texture sheets when I just need a bell emissive. If they're not set up properly I will have to fix it.
