### ISSUE TITLE
Atlas II Core tank Avionic pod length wrong.

### ISSUE THREAD

**Issue by svcino** [CobaltWolf/Bluedog-Design-Bureau#1514]
IRL Atlas II core tank
![eror2](https://github.com/user-attachments/assets/579a2dbe-ec5f-49b2-b1f3-07cd34e9c063)
Should use Existing Atlas D short avionic pods
![error_atlas2](https://github.com/user-attachments/assets/50d70264-da2f-4b34-bed3-c4f70787b09a)

**Comment by zorg2044** [comment]
![image](https://github.com/user-attachments/assets/dd1daeca-ed36-4492-8fa4-5b4e35e67abb)
