### ISSUE TITLE
surveyor orbiter excess mesh

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1524]
Surveyor orbiter has some mesh from the lander that should be removed:
![image](https://github.com/user-attachments/assets/87ef2ab9-4840-416f-8441-f39d3027c83d)

It's this one:
![image](https://github.com/user-attachments/assets/b717c22c-a496-4572-bff6-caa886c65d9e)

**Comment by CobaltWolf** [comment]
Should be fixed.

**Comment by Rodg88** [comment]
confirmed
