### ISSUE TITLE
Mariner 6-9 canopus tracker lacks depth mask

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1533]
![image](https://github.com/user-attachments/assets/ddeb27b8-7f3c-4281-9409-ddedaf52ceb2)

I've set up a node switch on the probe core and on the different startrackers. It should be in about the right place for the cutout in the engine blankets?
![image](https://github.com/user-attachments/assets/2b45584c-4670-4524-93d4-58a71a703287)
If the tracker needs a blanket mesh switch too, these are the node positions I've set already for positioning:

star tracker bottom node = 0.380778, -0.142875, 0
star tracker top = 0.380778, 0.142875, 0
star tracker 8/9 = 0.380778, 0.1, 0

mariner71 star tracker node
node_stack_bottom = 0.090354, -0.034, 0.0

mariner 5 star tracker node
node_stack_bottom = 0.060876, -0.00175, 0.0

mariner 3 star tracker node
node_stack_bottom = 0.011784, 0.003402, 0.0

**Comment by CobaltWolf** [comment]
![image](https://github.com/user-attachments/assets/85aef755-deaa-4a94-bf1f-598d13633de4)
