### ISSUE TITLE
J2A2 fixed extension gimballing weirdly

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#1535]
The fixed J2A2_Extension's gimbal transform acts weirdly for some reason:
https://github.com/user-attachments/assets/a0c4f2bb-79cd-4682-985a-3008ff33b788

I think if J2A2_Extension is just moved to be under the base J2S main gimbalTransform it should fix it.

**Comment by CobaltWolf** [comment]
Oh wtf? It looks like it's fine with only one axis inputs, but pitching and yawing causes it to separate?

**Comment by Rodg88** [comment]
Yep, no idea why the two gimbaltransforms behave differently lol
