### ISSUE TITLE
Apollo/Gemini CoM

### ISSUE THREAD

**Issue by McLeggy** [CobaltWolf/Bluedog-Design-Bureau#1538]
The CoM offset on the Apollo and Gemini capsules is still incorrect. The current offset forces the capsules into a steeper re-entry. In order to be used as lifting bodies the capsules have to re-enter upside down

**Comment by Rodg88** [comment]
Not sure about Gemini, but I think Apollo should be heads-down for upwards lift? https://www.nasa.gov/history/afj/ap11fj/26day9-approach-earth.html

**Comment by JacobB094** [comment]
Both capsules used a heads down attitude for upwards lift. BDB is correct on that account.
