### ISSUE TITLE
SAF fairings rescale (for extras)

### ISSUE THREAD

**Issue by JacobB094** [CobaltWolf/Bluedog-Design-Bureau#1542]
I've long been interested in a simpler way to play RSS (what with how nice visuals it's been getting lately), and in principle, this is not difficult. Mod such as this can do exactly that:
https://forum.kerbalspaceprogram.com/topic/189978-112-less-real-than-realism-rp-1-with-less-r-v206/

However, it runs into a major obstacle: SAF fairings, which I consider an essential part of BDB. So far, I haven't found any way to rescale them through configs. So, I'm asking this: would that be possible to provide "realscale" (scaled up 1.6x) fairing models in the extras folder? I don't know how much effort it actually is to do something like that, but it'd help a lot with making a "lightweight" way to play RSS work well.

If I'm just missing an existing feature of SAF, please enlighten me on its syntax.

**Comment by Rodg88** [comment]
I just checked the source on GH and found this field in the SAF module: 

[KSPField]
        public float scale = 1f;

So maybe try adding "scale = 1.6" to the SAF modules in a patch? I wouldn't put it even in optional patches on BDB's side though, it would be better in a patch in LRTR or a new compatibility mod. People tend to install everything in optional patches without looking into each patch, and we like to keep that not too disruptive when that happens.

**Comment by zorg2044** [comment]
re-exporting resized models is a considerable time investment and like Rodger said something like this (even via patch) shouldn't be in BDB but RO or an RO compatibility mini mod.

**Comment by JacobB094** [comment]
The issue is, the "scale = 1.6" line doesn't appear to do anything. This: 
`MODULE
		{
			name = ModuleSimpleAdjustableFairing
			segmentLength = 0.804672
			maxSegments = 10
			numSlices = 2
			deploySpeed = 5
			shieldingCenter = 0,1.045, 0
			shieldingBaseRadius = 1.165
			editorOpenOffset = 7.5, 0, 0
			stagingToggleEnabledEditor = true
			WALL_BASE
			{
				transformName = wallbase
				mass = 0.004
				CoM = 0.625, 0.31, 0
				rootOffset = 0, 0.122524, 0
				scale = 1.6
			}
			WALL
			{
				transformName = wall
				mass = 0.008
				CoM = 0.625, 0.53, 0
				rootOffset = 0, 0.3234204, 0
				scale = 1.6
			}
			CONE
			{
				transformName = cone
				mass = 0.010
				CoM = 0.625, 1.12, 0
				rootOffset = 0, 0.3234204, 0
				scale = 1.6
			}
		}`
does not change the fairing in the slightest compared to the version without. Just add this line to any random BDB fairing config and you'll see. I agree, reexporting the files is an awful crock that takes me back to the old days of requesting that KOSMOS author (anyone remember the blue TKS?) include a part flipped upside down just because KSP didn't have any part rotation functionality yet. I was surprised that SAF didn't seem to include a working scaling functionality, but it doesn't. I don't know if reexporting the models is more effort than fixing the plugin, but given the lack of recent updates to the latter, I'm not sure there's any hope in asking there. I do not have the skills to fix the code myself.

In fact, I suspect that this parameter is part of the unfinished attempt at supporting TweakScale from a few years ago, and it doesn't actually do anything.

**Comment by Rodg88** [comment]
It works, just put it in the main module, not within the segment definitions. The definitions would need location updates too however by the looks of it.
![image](https://github.com/user-attachments/assets/14caad48-61ff-4c0a-ad97-ef9aa958b918)

**Comment by JacobB094** [comment]
The moral of this story is: documentation, documentation, documentation. There's a reason I included a 40 page PDF guide with my .craft files. Rooting through the code on Github isn't always the best way of figuring things out, so to speak...

Anyway, I guess we can close this one, now that I know that what I want is a fairly straightforward MM config after all.
