### ISSUE TITLE
Questions about RemoteTech

### ISSUE THREAD

**Issue by Aebestach** [CobaltWolf/Bluedog-Design-Bureau#1544]
- The `bluedog_LEM_Ascent_Cockpit` component in [Gamedata/Bluedog_DB/Compatibility/RemoteTech/remotetech_Pods.cfg](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Compatibility/RemoteTech/remotetech_Pods.cfg) seems to have been removed?
- https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/e1725c3401cd9b36de5808137c6b3c42c153058e/Gamedata/Bluedog_DB/Compatibility/RemoteTech/remotetech_Probes.cfg#L5-L24 It seems that it does not work for all Probe components. The following is a list of components that do not work. They should be configured separately.

   1. [Sina-MLEM-SHL Surface Shelter Module](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Apollo/bluedog_LM_Shelter.cfg)
   2. [Sina-MLEM-CSL Laboratory Module](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Apollo/bluedog_LM_Lab.cfg)
   3. [Sina-EMSS-3 Surface Shelter Module](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Apollo/bluedog_EarlyLunarShelter.cfg)
   4. [Dona-LK217 Miniature Lander Can](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Gemini/Lander/bluedog_Gemini_LanderCan.cfg)

**Comment by Rodg88** [comment]
RemoteTech compat is a community maintained patch, so feel free to PR a fix

**Comment by Aebestach** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/e1725c3401cd9b36de5808137c6b3c42c153058e/Gamedata/Bluedog_DB/Parts/Apollo/bluedog_LM_Shelter.cfg#L188
Does this mean a deployable antenna?

**Comment by Aebestach** [comment]
I have completed the adaptation of the Pods and am now re-adjusting the antenna. I noticed that some dishes with a communication range of 100G are even omnidirectional, which seems a bit unrealistic?
Another question is, https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Compatibility/RemoteTech/Remotetech_ProbesNew.bak this file doesn't seem to do anything?

**Comment by Rodg88** [comment]
Looks like it was probably disabled due to being in-progress/unfinished? No idea why tho, maybe the original author is around on the forums still to ask

**Comment by Aebestach** [comment]
It should be the abandoned content, all for the core module to configure the antenna

**Comment by Aebestach** [comment]
Does 1.14 have additional antennas compared to 1.13?

**Comment by Rodg88** [comment]
There'll be some, at least mariner '69, and viking orbiter. then maybe x15 internal transmitters

**Comment by Aebestach** [comment]
#1545 Currently, there is a common configuration for all components with communication modules, but it may need to be adjusted again. When the new version is released, I will submit a PR to fix it again.

**Comment by Rodg88** [comment]
@Aebestach I mentioned in the the PR, which I've already accepted now, but if you can also update for other 1.14 parts before the release that'd be ideal. That way we don't need to wait for another update for it to be included.

**Comment by Aebestach** [comment]
OK, thanks, but I may need to compare which new components have been added to see if they need to be configured separately.

**Comment by Aebestach** [comment]
Can you add a `CrewCapacity` field to all new components?
Because now RT configuration needs to use this attribute, if there is no such attribute, i need to write it separately one by one. If you can add this attribute, the general writing method is applicable to 1.14

**Comment by Rodg88** [comment]
Off the top of my head the main new ones would be:
ProbeExpansion/Viking/bluedog_Viking_Orbiter_highGainAntenna
ProbeExpansion/Viking/bluedog_Viking_Orbiter_lowGainAntenna
ProbeExpansion/Viking/bluedog_Viking_Orbiter_SolarPanel_Relay
ProbeExpansion/Mariner/bluedog_Mariner69_HighGainAntenna
ProbeExpansion/Mariner/bluedog_Mariner69_LowGainAntenna
ProbeExpansion/Mariner/bluedog_Mariner71_HighGainAntenna
ProbeExpansion/Mariner/bluedog_Mariner71_LowGainAntenna
ProbeExpansion/Mariner/bluedog_Mariner71_SolarAntenna

the stats on those haven't really had a balance check yet though, but shouldn't change too much.

Also Surveyor omni antennas just got merged into one part (just visual variants):
ProbeExpansion/Surveyor/bluedog_Surveyor_Omni

And you should be able to check against other fields for crew capacity checks, like
`HAS:[@MODULE[ModuleCommand]:HAS[#minimumCrew[>0]]]` for pods vs 
`HAS:[@MODULE[ModuleCommand]:HAS[#minimumCrew[0]]]` for probes.

Or even check for the INTERNAL key of the stock ModuleDataTransmitter module instead like:
`HAS:[@MODULE[ModuleDataTransmitter]:HAS[#antennaType[INTERNAL]]]`

What exactly do you need the crew capacity check for? If it's for replacing the internal antennas, it's probably best to use the last option and directly check for the module you're replacing.

**Comment by Aebestach** [comment]
The original RT configuration uses `minimumCrew` to check, but I think this method seems not perfect (For example, when checking `minimumCrew`, some manned cabins have `minimumCrew=0`), because it does not perform well when dealing with manned modules with independent antennas (I think that modules with independent antennas will have enhanced communication capabilities after activating the antenna, rather than the default 3km communication range of RemoteTech), so I used `CrewCapacity` to distinguish between unmanned cores and manned modules.

**Comment by Rodg88** [comment]
Also checking `~CrewCapacity[>0]` will match parts that _don't_ have a positive crew capacity too
