### ISSUE TITLE
Apollo Parachutes Broken Again

### ISSUE THREAD

**Issue by VenomousRequiem** [CobaltWolf/Bluedog-Design-Bureau#155]
![screenshot131](https://cloud.githubusercontent.com/assets/19243006/17646665/85d6c6f4-6199-11e6-93af-3a1f6d3156cf.png)
Need I say more?

**Comment by jsolson** [comment]
Fine here.

**Comment by CobaltWolf** [comment]
Yeah I have not changed them at all. Did you accidentally an old version?

**Comment by VenomousRequiem** [comment]
Nope, but I'll try it again. If it's still fucked up I'll just close this and we never have to think about it again. :b

**Comment by CobaltWolf** [comment]
so are they broken?

**Comment by VenomousRequiem** [comment]
Forgot about this. No, they're fine.
