### ISSUE TITLE
minor nit: "empty" CFG

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1563]
Wondering if this could go away if it's not going to be used for something:

[WRN 12:21:17.421] Cannot create config from file 'F:\KSRSS\GameData\Bluedog_DB\Patches\mass_patch.cfg'.

**Comment by Rodg88** [comment]
It's like that to override any older versions of that patch with the empty version, but after two years and with this new version its probably ok to delete now...
