### ISSUE TITLE
GameData folder syntax issues on Linux

### ISSUE THREAD

**Issue by xavthewhovian** [CobaltWolf/Bluedog-Design-Bureau#1567]
When installing BDB on linux, unzipping the files into the KSP folder does not work correctly. Due to a case sensitivity issue, instead of the BDB files going into the proper "GameData" folder, a new folder named "Gamedata" is created and all mod files go into that folder instead, causing the game to leave them completely unloaded. Fixing the issue is as simple as copying the files from the new Gamedata folder into KSP's original GameData, however a fix on the github end would prevent confusion for end users

**Comment by Kemahudson** [comment]
Having issues with the directory structure on windows as well.

**Comment by Rodg88** [comment]
This is not worth the side effects of fixing, as GitHub would basically destroy all file history of every file in the mod if we renamed the base gamedata dir.

We can try manually rename the dir in the release bundle, but this will rely on whoever is doing it remembering to do so.

**Comment by jmrd98** [comment]
Eh? Since when? At worst this should take two commits, git can deal with directory name/case changes via git mv perfectly fine, unless I’ve gone insane (~60% chance tbf)

cf https://stackoverflow.com/questions/3011625/git-mv-and-only-change-case-of-directory#3011723

**Comment by Rodg88** [comment]
Last time I tried, it handled all the moved files as new copies of the files, and didn't seem to have file history visible. But looking again now at some moved files there does seem to be old file history, it's just hidden behind some more links. I'll probably do a test rename in a branch and see how it goes.

**Comment by Rodg88** [comment]
Next update should have renamed GameData
