### ISSUE TITLE
Model Quirks LEM Ascent Stage

### ISSUE THREAD

**Issue by Sgt-Shutesie** [CobaltWolf/Bluedog-Design-Bureau#157]
I haven't done that much looking, but the antenna on the left side of the ascent stage facing the front looks detached from the rest of the model, while both extended and retracted.

**Comment by VenomousRequiem** [comment]
Can confirm, but I assumed he knew what he was doing. :b

**Comment by CobaltWolf** [comment]
fugoff

**Comment by CobaltWolf** [comment]
Also, I figured out what was causing this and I should be able to easily fix it.
