### ISSUE TITLE
Inconsistent category for Sarnus-SIVB-425 Adapters

### ISSUE THREAD

**Issue by JacobB094** [CobaltWolf/Bluedog-Design-Bureau#1571]
The part bluedog_Saturn_4p25m_adapters is missing from the Saturn category in CCK, and not only that, it's in Structural category, while all other interstages are in Coupling. Its bulkhead profiles are also off, all other adapters show up as 4.25m VABO, while this one is 3.125m. All that makes it hard to find. I'd suggest making it consistent with other Saturn adapter parts.

**Comment by Rodg88** [comment]
It's showing up in the Saturn category (as an adapter), and at 4.25m, for me. I can't think why it'd be showing up at 3.125 either. If the part cfg file was outdated it'd be 3.75, and if VABO patches were out of date the other parts wouldn't be 4.25m.

I can probably change it's naming/category/subcat to be an interstage though.
