### ISSUE TITLE
Oscar 1 should have a builtin decoupler

### ISSUE THREAD

**Issue by alex-dev** [CobaltWolf/Bluedog-Design-Bureau#1572]
Similar to P-11 Subsatellite, Oscar-1 should have its own decoupler.

**Comment by Invaderchaos** [comment]
No. Oscar-1 does not decouple from Agena B, it remains attached.

**Comment by alex-dev** [comment]
Unless something is incoherent between sources... Oscar 1 reentered 1962-01-31 while Discoverer 36 reentered 1962-03-08.

> After reaching orbit, OSCAR 1 was jettisoned, using explosive squibs and springs, into a 245 x 474 km altitude orbit with an inclination of 81.2 degrees.

- https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1961-034A
- https://nssdc.gsfc.nasa.gov/nmc/spacecraft/display.action?id=1961-034B
- https://en.wikipedia.org/wiki/OSCAR_1
