### ISSUE TITLE
Nit: Hermes M-DCAM Nose Unit: default chute deploy altitude outside of allowed range

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#1575]
When first instantiated from the part tray, the altitude slider shows 7000, but touching it snaps it back to a range with 5000 as the max.

No chute mods. Tested on JNSQ/KSRSS.

**Comment by Rodg88** [comment]
Oh I guess there's a hard coded max in the stock chute module... unfortunate. I could just set it to 5000 instead then

**Comment by OrbitalManeuvers** [comment]
@Rodg88 I'm having second thoughts about this report. BCS has this issue too. And so does Bumblebee :) My thoughts now are a) this harms nothing, b) it actually works - i.e. the drogue module seems to use the cfg number? c) if one really wants to restore the higher number after touching the slider and getting forced into the lower range, you can just instantiate a new part again.

Maybe this isn't worth changing?
