### ISSUE TITLE
LM Descent module missing

### ISSUE THREAD

**Issue by DiveWhistle** [CobaltWolf/Bluedog-Design-Bureau#1576]
I was building my Saturn V replica and I noticed that I couldn't find the LM descent module in the VAB OR SPH, I am using the latest version of the mod as well as the category extra and real names addon

**Comment by Rodg88** [comment]
The descent tanks are in the fuel tanks category

**Comment by DiveWhistle** [comment]
Its as if the part itself is not in the game, I only have the geminin lander descent tanks 



Edit: I have the ascent module, propulsion and separator, just not the descent assembly

**Comment by Rodg88** [comment]
How did you install the mod?

**Comment by DiveWhistle** [comment]
via Ckan

**Comment by Rodg88** [comment]
It should just be in the fuel tanks section then 
![image](https://github.com/user-attachments/assets/3fc43586-51de-4f7f-a53b-0ed374963176)

**Comment by Rodg88** [comment]
If its not might need a log

**Comment by DiveWhistle** [comment]
let me check and see, i just removed the real names addon

**Comment by DiveWhistle** [comment]
no change, im posting the log now

**Comment by DiveWhistle** [comment]
no change sadly, ill post the log shortly

**Comment by DiveWhistle** [comment]
had to compress it since it wouldn't fit


[KSP.zip](https://github.com/user-attachments/files/17526128/KSP.zip)


edit: I tried copy/pasting the log itself but it wouldn't stop crashing my brother

**Comment by DiveWhistle** [comment]
did I post the correct log?

**Comment by DiveWhistle** [comment]
I've even tried reinstalling it manually but I still don't have the descent module

**Comment by Rodg88** [comment]
That's the correct log. There's a lot of parts failing to be loaded in your log, including the descent tanks. Also parts from other mods.
Not quite sure what other mod may be breaking stuff so badly, though to start with I would highly recommend uninstalling that version of tweakscale (and Recall), and using tweakscale rescaled instead.

**Comment by DiveWhistle** [comment]
ahh ok ok
