### ISSUE TITLE
X15 control surfaces

### ISSUE THREAD

**Issue by Lu15-M4r1** [CobaltWolf/Bluedog-Design-Bureau#1577]
First of all, congratulations on this amazing stockalike parts mod for KSP, it's an amazing job!
I've been testing the parts included in the new update, specifically the X15, and the control surfaces on any of its wings don't work.
There's also no option to configure roll, pitch and yaw in the parts options. They are static parts.
I've tried reinstalling but it doesn't solve the problem. Am I doing something wrong? Is it necessary to install any additional mods for them to work?
Thanks.

**Comment by Rodg88** [comment]
First guess is you've previously installed FAR, but uninstalled it, without also removing the extra cfg file FAR creates in GameData which causes mods to think FAR is still installed.

**Comment by Lu15-M4r1** [comment]
That's exactly what you said.
I have deleted the FAR cfg file that you mention and now it works perfectly.
Thank you very much.
