### ISSUE TITLE
GLV cannot make it to LKO in JNSQ / 2.5x KSRSS

### ISSUE THREAD

**Issue by VioletChan311** [CobaltWolf/Bluedog-Design-Bureau#1581]
the GLV rocket fully built cannot make it to low kerbin orbit in KSRSS (2.5x) or JNSQ without using its OAMS (apologies if this is intentional). the engines im using are the LR87-AJ-5 and LR91-AJ-5.

ive done a fresh install with only BDB and JNSQ + requirements and mechjeb to see if it was another mod messing with the engines or fuel amounts but it can barely get to an 85km orbit using most of its monopropellant.

(sidenote: the GLV could easily make LKO with a patch i had in Bluedog_DB_Extras called 'HypergolicBDB' which added a hypergolic fuel mixture which the GLV used. since the update this patch no longer works so i removed it and noticed that the GLV cannot make LKO. im unsure where i got this patch folder since i cannot find it in the BDB extras on github)

**Comment by Rodg88** [comment]
Hypergolic patch is in here 
https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/master/BD_Extras%20(No%20Warranty)/GameData/Bluedog_DB_Extras/Pafftek

Also can't reproduce the issue, have no issues getting GLV into 100+ square orbit, manual or PVG launch, without any of the SMs fuel.

https://forum.kerbalspaceprogram.com/topic/122020-1125-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v1140-%D0%BC%D0%B5%D1%82%D0%B0%D0%BB%D0%BB-30sep2024/?do=findComment&comment=4426521

Make sure if you're using it that KSPCF is up to date, is the only thing I can really suggest.

**Comment by VioletChan311** [comment]
hm, im not sure what this is but if its just me il work it out. and thanks for the hypergolic patch, i didnt notice it because of the name. thanks for the reply o7

**Comment by Rodg88** [comment]
A random idea is maybe verifying game files via steam, in case physics settings got changed from default somehow. No idea otherwise sorry

**Comment by VioletChan311** [comment]
i will try that and reply with anything that works

**Comment by VioletChan311** [comment]
i switched to KSRSS instead of testing in JNSQ since your video showed KSRSS (i got from [here](https://gitlab.com/ksrss/KSRSS/-/tree/GameData?ref_type=heads))

so watching your video of ascent every stat about dV in the staging panel is nearly the same with small differences (i start off on the pad with 14 more dV). im also only aiming for 85km with PVG and i can make it with around 100m/s left in the second stage (and i couldnt make it in JNSQ)

i did write out all of the info i thought might be relevant to this about the rocket i was using: 

stock fuel {

    dV total: 3898m/s ASL / 5798m/s Vac (including retrorockets/oams)

    stage : fuel (full) : dV (ASL/Vac)
    1 : 1998 LF / 2442 OX : 2314m/s / 2654m/stage
    2 : 522 LF / 638 OX : 1364m/s / 2685m/s

}

hypergolic patch {

    dV total: 3744m/s ASL / 5543m/s Vac

    stage : fuel (80% full) : dV (ASL/Vac)
    1 : 7992 AZ50 / 9768 NTO : 2254m/s / 2584m/s
    2 : 2088 AZ50 / 2552 NTO : 1270m/s / 2500m/s

}

so this seems to be something different about the planet packs, but its quite a significant difference which confuses me

**Comment by JacobB094** [comment]
Is your PVG properly configured? Try using a turn that starts at 75m/s at a rate of 0.4, instead of default 50m/s and 0.5. Optimizing the turn can make a world of difference.

**Comment by VioletChan311** [comment]
its the configuration ive used for basically every rocket so it should be good, but just incase il give that change a try. im several hundred m/s short from what is shown in the video above however so i dont think its PVG (in the video they go to 100km and i cant even get to 81km. the dV seems about the same too which is strange)

**Comment by OrbitalManeuvers** [comment]
@VioletChan311 The link you quoted for KSRSS is not the right version. There are two active branches, Reborn and EarthHomeWorld. I can't really tell you which to get - Reborn is probably more compatible with more mods. It's the one I use, and is compatible with things like Katniss Cape, etc. Anyway, there's a Branch selector at the top of the page - you need to make a selection there. Also, if you use Reborn, don't install any of the 64k folders in there - just the nested KSRSS folder.

**Comment by VioletChan311** [comment]
ah thank you! that would explain a lot

**Comment by Rodg88** [comment]
Doesn't really explain the issue with jnsq though, do still post here if you discover the cause

**Comment by VioletChan311** [comment]
right i forgot! i will post if i find out anything else
