### ISSUE TITLE
Apollo SM Cargo Bay bugs

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#159]
Service Module gives error: [ModuleCargoBay]: Module ModuleResourceConverter is not an IScalarModule

Does not properly shield parts. Install a solar panel inside and try to deploy to test. It should fail with the bay closed.

**Comment by jsolson** [comment]
Added a second ModuleCargoBay and defined the [lookupCenter property](http://wiki.kerbalspaceprogram.com/wiki/Module#ModuleCargoBay)
The cargo bay colliders may need to be adjusted. @CobaltWolf could you read how lookupCenter works and take a peek at the colliders. I noticed some oddities. We don't need or want colliders on the shelves if that's what you were going for.

**Comment by CobaltWolf** [comment]
whoops

**Comment by jsolson** [comment]
That was fast!

**Comment by CobaltWolf** [comment]
All I had to do was open Unity

**Comment by jsolson** [comment]
It works.
