### ISSUE TITLE
LEM crash tolerance

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#160]
[Post](http://forum.kerbalspaceprogram.com/index.php?/topic/122020-114-bluedog-design-bureau-saturn-apollo-development-v011-vaquero-6aug2016/&do=findComment&comment=2732176)

The engines, decent tanks, and ascent cockpit have crash tolerances of 6 and 7 right now. Not sure what's up.

**Comment by jsolson** [comment]
Somewhat related, well not really, but I increased the node sizes on the LEM parts. It keeps collapsing on me, typically at the ascent engine.

**Comment by CobaltWolf** [comment]
you bastard

:P

**Comment by CobaltWolf** [comment]
Do struts help?

**Comment by jsolson** [comment]
This is a[KSP bug](http://bugs.kerbalspaceprogram.com/issues/12024). There's something weird going on with animated parts and crash tolerance. Both the landing tanks and ascent pod are near indestructible.

**Comment by CobaltWolf** [comment]
Anything we can do about this?

**Comment by Modsojoy** [comment]
kerbal space program bugs, Nothing that can be done

**Comment by jsolson** [comment]
Make landing gear parts. I'm fine the way it is on our side.

**Comment by CobaltWolf** [comment]
Eww. I don't know if I could get landing gear to work on the LEM even if I tried.

**Comment by jsolson** [comment]
Closing since this is a squad bug.
