### ISSUE TITLE
LEM IVA

### ISSUE THREAD

**Issue by Modsojoy** [CobaltWolf/Bluedog-Design-Bureau#161]
Will you guys ever Release the source code? Or atleast the source Models, i want to make an IVA For the LM And CM But taniwha's .mu importer seems to take issue with the Built in antennas on the LM's model.

**Comment by CobaltWolf** [comment]
I don't keep it uploaded, it'd be a pain to manage thru Git and the project files for BDB are several gigabytes due to incremental versions.

https://www.dropbox.com/s/hl5q2027qoab1lm/LEM_Ascent_Cockpit.fbx?dl=0

https://www.dropbox.com/s/5y4wzfq5mtqek2x/Apollo_Block2_Capsule.dae?dl=0

**Comment by Modsojoy** [comment]
Thanks For uploading them Cobalt, Hopefully i can get an IVA Done soon With some ASET/FlightSystemsRedux props.

**Comment by CobaltWolf** [comment]
That's lovely news! :)

**Comment by Modsojoy** [comment]
So i got a Very basic Model done with some hackaday 5 minute-or-less textures thrown together by a noob AKA Yours Truly, Annd i cant for the life of me get the Position or the Scale/Rotation right, Can you get a unity screen shot of the Inspector tab in unity of the LEM Ascent cockpit so i can set the scale and rot right, Or just post the values here.

**Comment by CobaltWolf** [comment]
Was it an FBX? Then it is scaled either 100x or 200x, I can't remember. I don't normally use them but I had to in order to get the animations to work.

**Comment by Modsojoy** [comment]
I mean in unity, what is the scale rotation Ect set to.

**Comment by CobaltWolf** [comment]
Can you post a screenshot? I just checked, the LEM_Ascent_Cockpit (which everything else should be grouped under) is set to 1, 1, 1 scale and has no rotation.

**Comment by Modsojoy** [comment]
Got the Loc and Scale set, Just need to fix the Rot because the Up axis for the IVA Is different from the external, Internal is Y Up and External is Z Up

**Comment by CobaltWolf** [comment]
Ah, I didn't know that. Does it seem to be working fine now?

**Comment by Modsojoy** [comment]
Looks like it, Going to Open up KSP And test it now, The textures are horrible But atleast its a start, I want to put a Yellow-ish tint on the windows like the LEM Was IRL But last time i used two Materials/Shaders on  one Mesh Hierarchy it Broke it. So who The Hell knows.

**Comment by CobaltWolf** [comment]
Yeah you have to separate them to a different mesh. Unity (or rather, KSP) only handles one material per mesh. You'll see I did that to the windows on the LEM and Apollo cockpits. Post some pics here or on the thread when you have it working.

**Comment by Modsojoy** [comment]
i said Mesh Hierarchy, Meaning that The Actual Mesh or 3D Object is parented to a game object Named the name of the 3D Model file. The meshes are shown Under it.

**Comment by CobaltWolf** [comment]
Yeah. You cannot have a mesh with more than one material. You can have different ones in the same hierarchy:

Gameobject
    -> Main mesh (with material X)
            -> Window mesh (with material Y)

**Comment by Modsojoy** [comment]
thats what i meant.

**Comment by CobaltWolf** [comment]
:ok_hand:

**Comment by Modsojoy** [comment]
Needs to be scaled up by a tiny bit and moved forward/Up,Other then that Rot is good and it didnt throw any errors.

**Comment by Modsojoy** [comment]
Almost thought i had broke it, Turns out i forgot to set the Layer right so Now its working. Props need Position tweaking and so does the Actual model itself
[Pictures!!] (!http://images.akamai.steamusercontent.com/ugc/439487577740164138/4675E625220A0C94FC4224951034C9B840ABB062/?interpolation=lanczos-none&output-format=jpeg&output-quality=95&fit=inside|1024:575&composite-to%3D%2A%2C%2A%7C1024%3A575&background-color=black)

**Comment by CobaltWolf** [comment]
... what pictures? ;) I don't see any.

**Comment by Modsojoy** [comment]
Try again? i can see them.

**Comment by Modsojoy** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=760237524

**Comment by Modsojoy** [comment]
Kerbal Orientation Corrected and now all i need to do is move it all into place

**Comment by CobaltWolf** [comment]
Looks very, ah, dark :)

**Comment by Modsojoy** [comment]
needs some lights added in, I dont think its TERRIBLY Bad for something that never had an IVA To begin with, That and this is only my second try at making an IVA.

**Comment by Modsojoy** [comment]
Hopefully i can revamp the textures later on, the current ones are just a couple of Solid colors as Placeholder.

**Comment by VenomousRequiem** [comment]
As long as it's there and you can see the Kerbals, it doesn't really matter. A lot of the time it's a matter of just havijg their portraits down there. :b

**Comment by Modsojoy** [comment]
I was going for a Functional IVA With ASET And FlightSystemsRedux Props, And the thing Tbh is Ugly as hell.

**Comment by Modsojoy** [comment]
Something i cant understand - the exterior Model Shakes around but the IVA Stays Still from the IVA View. I'l have to figure it out later..

**Comment by Modsojoy** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=760237524

**Comment by CobaltWolf** [comment]
How goes?

**Comment by Modsojoy** [comment]
Goes like this - http://steamcommunity.com/sharedfiles/filedetails/?id=764301705

**Comment by Modsojoy** [comment]
Oh btw can a tag- Er - Label be added to this Thread that says "IVA" Or Something like that.

**Comment by CobaltWolf** [comment]
Looking good! And yeah, I'll throw it up.

**Comment by Modsojoy** [comment]
Btw - i have the IVA In my HorizonsIVA Mod along with the KAX, Should i separate them?, Also - how did you assign me to this, Im not marked as a Collaborator.(Or i just dont know how Git works(P.S - I dont))

**Comment by CobaltWolf** [comment]
My ideal situation would be that it be included in the BDB download, with you be credited of course. :) However, it is entirely up to you what you wish to do with it. 

And I don't know how I did it. I was surprised too.

**Comment by Modsojoy** [comment]
Lol, Im willing to turn Over the source Files aswell as some More Info about the Unity bits for it, Just as long as i get to work on it and Refine it.

**Comment by Modsojoy** [comment]
Woops. God damnit Git.

**Comment by CobaltWolf** [comment]
I would include it, all you'd need to do is submit a pull request with updated files if you make changes. I have a couple people that I might be able to ask to texture it if that's all you need help with.

**Comment by Modsojoy** [comment]
Tf is a pull request?

**Comment by Modsojoy** [comment]
Do you want me to turn over the source bits or just the Finished bits?

**Comment by CobaltWolf** [comment]
If you try and upload the files to the github repo it will create a pull request that one of us have to approve. I think.

And I'd appreciate being able to hold on to the source files as well as the finished bits. You said it wouldn't be very textured? I'd like to be able to hand off the source files to another volunteer to touch the textures up.

**Comment by Modsojoy** [comment]
I'l upload the files in a few minutes. Just know that its literally just a solid Color for the LEM IVA, And its using an Updated BETA version of ASET props that needs to be downloaded from here - https://www.dropbox.com/s/evzc2zos8g9iecv/ASET_Dev-24-08-2016.zip?dl=0

**Comment by Modsojoy** [comment]
"Uploads require Push Access"

**Comment by CobaltWolf** [comment]
@jsolson HALP

**Comment by Modsojoy** [comment]
Who?

**Comment by CobaltWolf** [comment]
the co-author who handles the cfgs and knows how Github works :P

**Comment by Modsojoy** [comment]
lol.

**Comment by jsolson** [comment]
You rang?

**Comment by Modsojoy** [comment]
@jsolson m8 you l8.

**Comment by Modsojoy** [comment]
Oh BTW @CobaltWolf i will be able to do the textures in time, Its mainly the UV Mapping and Unneeded Laziness Syndrome that's causing the delay.

**Comment by Modsojoy** [comment]
http://s11.postimg.org/7ccsfo2yb/End_my_suffering_cobalt_Plz_halp.png

The entire model Blown apart. 14 objects total, Just to get a usable UV Map... Fml..

**Comment by Modsojoy** [comment]
FYI - You should convert the textures to jpg or .DDS, it would make them alot smaller and less ram intensive.

**Comment by Modsojoy** [comment]
Also - i noticed something with the External model of the LEM, on the side there are a couple of Poly's that need to be Separated into two Tri's(a rule i use is that if the bend Goes above 5 Degrees i separate it into 2 tri's), 
![jews](https://cloud.githubusercontent.com/assets/21351692/18782652/70b1faba-8155-11e6-8b69-e050d228bba6.PNG)

**Comment by Modsojoy** [comment]
Curently Overhauling the LEM's Internal model, Should be done Tomorrow then i can get onto Making some Better textures.

**Comment by Modsojoy** [comment]
Windows Shader/Tint Test.
![tinttest](https://cloud.githubusercontent.com/assets/21351692/18805601/32eb8350-81e0-11e6-8cd5-34ec53fe352e.PNG)

**Comment by Modsojoy** [comment]
Textures in the Works.

**Comment by Modsojoy** [comment]
![hatch_tex_teset](https://cloud.githubusercontent.com/assets/21351692/18805759/0edb63b4-81e4-11e6-9e24-59e4fb68ec67.PNG)

Hatch textures, also i submitted a pull request with the IVA. I'l email you the source bits.

**Comment by jsolson** [comment]
I don't see a pull request.

**Comment by Modsojoy** [comment]
Goddamnt git. - https://github.com/CobaltWolf/Bluedog-Design-Bureau/pull/170

**Comment by jsolson** [comment]
"Props are from MOARdV's Flightsystems redux and the Latest ASET BETA Build - https://www.dropbox.com/s/evzc2zos8g9iecv/ASET_Dev-24-08-2016.zip?dl=0"

How do I get this working, just dump that zip file in gamedata?

You'll have to consider us (well, me anyway) total noobs when it comes to IVAs. Can I get some links to the dependent mods so I know I'm looking at the right thing? License permitting, ideally we would pull out just the props we need and include them rather than have dependencies. Though it looks like ASET has Props packs specifically intended for this purpose.

**Comment by Modsojoy** [comment]
It uses a little bit of both, i'l have to check and pull the Required props. But for the props like the FDAI And DSKY/ARRT To show up you need to have the prop mods.

**Comment by Modsojoy** [comment]
IVA Will still work without.

**Comment by Modsojoy** [comment]
The ASET Thread is dead and the most recent version is through that link Alexutas Put up on a Github issue. And Flightsystems redux is located here - http://forum.kerbalspaceprogram.com/index.php?/topic/60681-10511-flight-systems-redux-aset-props-and-rpm-iva-8-april-2016/&page=1

**Comment by Modsojoy** [comment]
This is part of the reason why i dont want to Have it as part of the main pack yet, Its severely Unfinished, Its missing a seat transform,Textures and a slew of other Minor Details and greebles.

**Comment by Modsojoy** [comment]
FSR is under the https://creativecommons.org/licenses/by-nc-sa/4.0/ and ASET Is under https://creativecommons.org/licenses/by-nc-sa/3.0/ (Both licenses are the EXACT Same.)

**Comment by Modsojoy** [comment]
![hatch_tex_teset](https://cloud.githubusercontent.com/assets/21351692/18808608/92ae79c4-8234-11e6-9b0e-9bc15e243fa6.PNG)
Finalized textures for the Hatch.

**Comment by CobaltWolf** [comment]
I don't care about the textures but we need seat transforms.

**Comment by Modsojoy** [comment]
Alright chill. Its just a quick Cfg edit.

**Comment by Modsojoy** [comment]
Pull #171

**Comment by CobaltWolf** [comment]
Sorrry, reading that in my email I didn't see that you had commented the textures right before. My point was just that we need something functional right now - polish can come later. 

If you want, you can find some texturing tips here:
http://forum.kerbalspaceprogram.com/index.php?/topic/131145-wip-coatl-aerospace-probesplus-dev-thread-v014-beta-9216/&page=34#comment-2751851

**Comment by Modsojoy** [comment]
Like i said earlier - textures are an issue purely because of Laziness, Anyways - should i start now with Finishing the Minor chunks?

**Comment by CobaltWolf** [comment]
Yeah go for it! 

And I don't mean to be a bother, since you're sort of making this for your own mod's uses, but I just wanted some clarification - the IVA still functions with just stock, not all the extra parts? Again, I realize it's your project and you just want to make it for the prop sets you want to use. I just wanted to make sure that it worked without all the extra stuff installed. We try to have no dependencies, but have expanded functionality the more mods are installed.

**Comment by Modsojoy** [comment]
the iva will LOAD. WILL LOAD, Without Aset and FSR, But there wont be ANY Props and the iva will essentially be a placeholder. also both Flightsystemredux and ASET Prop's licences Allow redistribution.

**Comment by Modsojoy** [comment]
@jsolson Sorry i forgot to include the LEM's Cfg, Thanks for fixing it.

**Comment by Modsojoy** [comment]
Im pretty sure i can close this now seeing as the IVA Is in the works.

**Comment by CobaltWolf** [comment]
*shrug* If you want you can leave it open for discussion until you're done.

**Comment by Modsojoy** [comment]
I figured Theres nothing left to discuss, Iva is in the works and i can just submit a pull request with the New/Updated files As i update and Polish it
