### ISSUE TITLE
1.2 RCS Problems

### ISSUE THREAD

**Issue by VenomousRequiem** [CobaltWolf/Bluedog-Design-Bureau#164]
Fixing the RCS to use the new RCSFX system in 1.2, There's some issues I've been having.

I'm going to need @CobaltWolf to look at for rcsTransform position changes:

- Apollo RCS Quad

- LEM RCS

RCS that I can't figure out how to get to work:

- MOS RCS block

- Gemini's TRAILS RCS (The Reentry RCS and the 3 way block by Beale)

**Comment by jsolson** [comment]
So it doesn't get lost, @jmrd98 (komodo) added a possible catchall patch for RCS. #164

**Comment by CobaltWolf** [comment]
Do you still need help for the MOS and TRAILS RCS?

**Comment by jmrd98** [comment]
I don't know about those. Late night testing showed that the lem ascent rcs works, but the effects are reversed. For example, translate forward, reverse thrusters fire visually. Actual control is correct, just reversed visuals (on all axes). I need to check addn craft, and update my build to see if it reoccurs, as it was only the one I was able to test.

**Comment by jsolson** [comment]
Must be something weird in the model (@CobaltWolf??). Just the Ascent Cockpit needs the effect to be rotated +90 instead of -90.

**Comment by jsolson** [comment]
The MOS RCS block won't work with ModuleRCSFX for now due to [this bug](http://bugs.kerbalspaceprogram.com/issues/11785). Despite what's in the Squad configs, there is no runningEffectName property on ModuleRCSFX. Though we should probably continue to use it in the event they correct that bug.

The Gemini reentry rcs and the original 3-way seem to be working ok, as well as all the other's I've looked at (not all of them).

**Comment by CobaltWolf** [comment]
Why does that affect our MOS RCS though? It's a normal RCS block for the most part.

**Comment by jsolson** [comment]
The MOS RCS has three separate thrust vectors (prograde, normal, and radial), so it needs three different EFFECTS nodes since the node references the thrust vector. But we can't change the effect name in the RCS modules.

**Comment by CobaltWolf** [comment]
Oh. Damn, I wanted to keep that functionality tho...

**Comment by jsolson** [comment]
We will. Let's see if they fix it.

**Comment by jmrd98** [comment]
Did this get bug trackered? I haven't seen it but that doesn't mean it's not there. It seems something that they'd try to get fixed this push.

**Comment by jsolson** [comment]
Yes
http://bugs.kerbalspaceprogram.com/issues/11785

**Comment by VenomousRequiem** [comment]
Is there anything we can do with this? I feel it should be moved to 1.2 issues. I'll close it and we can pick up discussion in #166.
