### ISSUE TITLE
General KSP 1.2 update issues

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#166]
List of things we need to worry about, and info on how to deal with them. Links would be great.
[1.2 Pre-release changelog](http://forum.kerbalspaceprogram.com/index.php?/topic/147583-12-prerelease-changelog/)

CoPOffset, CoLOffset, ect changed. Relative to part center now rather than center of mass (I think).
ModuleRCS -> ModuleRCSFX. Issue #164 
Antenna System [link](https://docs.google.com/document/d/1Tu3KnB1alOMn_VXqF31BPDbAu24HdHLiYP2V1I6b6pU/edit?usp=sharing)
New categories. Do we have a list?

**Comment by VenomousRequiem** [comment]
I tried looking into it, but I think your best bet for the antennas is to reverse engineer the stock antennas' configs. 
As for the RCS, I can completely handle the ones that are giving me trouble if I could just know the transform name, as they weren't made by Cobalt and seem to be different; Except however the MOS RCS which I could probably figure out by just looking a little more carefully at it.

**Comment by jsolson** [comment]
We have node strength and auto strut now. Will kjr be obsolete?

**Comment by VenomousRequiem** [comment]
We need to update the parts to use the new 1.2 categories.

**Comment by CobaltWolf** [comment]
So who wants to do the new categories?

**Comment by Modsojoy** [comment]
I could probably do it. For all the parts right?

**Comment by jsolson** [comment]
> So who wants to do the new categories?
Apparently @IronCretin volunteered.

**Comment by IronCretin** [comment]
I'm about halfway through them right now. Do you want the interstages in coupling or structural?

**Comment by jsolson** [comment]
I'd say coupling.

FYI, if you don't have the very latest commits, Saturn engine mounts are no longer tanks.

**Comment by IronCretin** [comment]
Categories are done:
#182

**Comment by IronCretin** [comment]
Do we want any of the antennas to be stackable?

**Comment by jsolson** [comment]
Squad is still figuring thing out. Playing wait and see.

**Comment by CobaltWolf** [comment]
What do you mean stackable? Able to stack attach? Any that had it before should have it now.

**Comment by IronCretin** [comment]
No. I mean the range extends if you put more than one on.

**Comment by CobaltWolf** [comment]
oh. Yeah, no idea there.

**Comment by IronCretin** [comment]
All the stock ones except the dipole stack, FWIW. I'd make at least all the non-antenna ones stack.

**Comment by CobaltWolf** [comment]
Can this be closed now?

**Comment by CobaltWolf** [comment]
Cool.
