### ISSUE TITLE
Apply placeholder IVA from K-P0110

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#172]
Use the placeholder IVA that Araym sent from the old K-P0110 mod.

>  https://www.dropbox.com/s/kosurqsscq14img/More IVAs.zip?dl=0

As the "Read ME" inside states, the only thing to check is if SXT MEM internals could be free redistribuite (I'm not a "genius" about licenses, so check it from SXT release thread).

I added all the directly related IVAs I'm using for your part pack, with relative cfg to copy the internal to have them placed at best I could tweak. (with optional Mercury and Gemini too, not only Apollo CM/LEM)

It is a painful job, not having a 3d program to check them: I add them, run the game, look at the placement, then try-try-try-try values until they fit for those that have different origins in the model (so when I have a decent placement, generally after a dozen of test, I stop to hurt myself rather to hunt decimal values :confused:)

But in the whole, they should be decently placed.

These are the ones related to your mod: I have more old Beale's IVAs, but used by me only for Tantares parts themselves that actually lack of internals (basically Vostok, TKS and Salyut-MIR parts, or for those crewed parts from other mods that need an IVA, rather than leave the blocky "placeholder" by Squad)

SIDE NOTE:
I thought you saw the SXT IVA for your LEM, as since the first release, it has as internal the STX's MEM one and it is pretty perfect in dimension for your model.
In fact, as I have the STX pack itself in my game, I was amused to find directly it working when I downloaded your LEM the first time.
That... or anyone of you (JSO, Venoumous or yourself) added it inconsciously and then it stayed on the cfg by chance...

**Comment by jsolson** [comment]
Pinging @Araym-KSP

Doesn't the name of the INTERNAL need to be changed to avoid collisions if this is installed elsewhere, or has that already been done?

**Comment by CobaltWolf** [comment]
I don't know. Maybe.

**Comment by Modsojoy** [comment]
Ayy @CobaltWolf Im working on the Apollo CSM's IVA Next after i Finish #161

**Comment by CobaltWolf** [comment]
@Modsojoy  Yeah but in the meantime we can use this one :P

**Comment by Modsojoy** [comment]
Lel. Just a heads up m8.

**Comment by CobaltWolf** [comment]
done and done
