### ISSUE TITLE
F1 Gimbal animation issues

### ISSUE THREAD

**Issue by VenomousRequiem** [CobaltWolf/Bluedog-Design-Bureau#175]
![ksp_2016-09-29_00-36-55](https://cloud.githubusercontent.com/assets/19243006/18956426/037488f2-8621-11e6-9ad5-68e24c2b8c93.png)
![ksp_2016-09-29_00-36-36](https://cloud.githubusercontent.com/assets/19243006/18956435/08492824-8621-11e6-884b-a5a4a94e7a81.png)

Not to mention the two hydraulic braces on the opposite side, which I can't seem to locate my screenshot of... The black top part stays stationary even when the silver bottom section is moving.

**Comment by CobaltWolf** [comment]
I forgot to add the module...

**Comment by VenomousRequiem** [comment]
It's not _that_ big of a deal, but aesthetically it's not very pleasing.

**Comment by CobaltWolf** [comment]
I need to fix the arms, at least.

**Comment by CobaltWolf** [comment]
fixored
