### ISSUE TITLE
Reminder to Remove Saturn 1 Text

### ISSUE THREAD

**Issue by Sgt-Shutesie** [CobaltWolf/Bluedog-Design-Bureau#177]
Do it boi, even though I don't want you to. Plez.

**Comment by Modsojoy** [comment]
That would require a texture rework, Unless the text is on its own layer that would be a bit of a pain to rework.

**Comment by Sgt-Shutesie** [comment]
Everything is done in layers, text will be easily removed. I am just sad to see it go.

**Comment by Modsojoy** [comment]
Sure bout dat?

**Comment by Sgt-Shutesie** [comment]
Yeah, he taught me his texturing style. As long as he has the photoshop images, he can take away the layers without touching anything below it.

**Comment by Modsojoy** [comment]
Oh. damn.

**Comment by VenomousRequiem** [comment]
I think I know Cobalt well enough to speak for him when I say: oh, fuck you

**Comment by CobaltWolf** [comment]
@VenomousRequiem I asked him to remind me. I want the Saturn series to have matching styles. I will replace it with the now-standard red stripe.
