### ISSUE TITLE
Apollo LES textures

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#181]
Need to make the new textures for the Apollo LES.

**Comment by Modsojoy** [comment]
I would say i could do it - depending on what Details you want in it

**Comment by Modsojoy** [comment]
Oh nvm just saw - "Cobalt Self assigned"

**Comment by CobaltWolf** [comment]
The we really need help with the cfg side right now. Like I said, tech tree placement, making sure everything has a description, etc. All the little polish things.

**Comment by Modsojoy** [comment]
Ah. Oh btw - im Getting ready to start on the Apollo IVA But the .collada (dae)file you sent me does not import, Blender does not even throw an error.

**Comment by CobaltWolf** [comment]
https://www.dropbox.com/s/exqouffz3i44oso/Apollo_Block2_Capsule_NewRCS.dae?dl=0

**Comment by Modsojoy** [comment]
Thanks.

**Comment by Modsojoy** [comment]
Still a nope,hmm.

**Comment by CobaltWolf** [comment]
https://www.dropbox.com/s/o839uhc2idmra6f/Apollo_Capsule.fbx?dl=0

**Comment by Modsojoy** [comment]
That seems to work, to the extent of crashing blender with an unsaved project open, Still better then nothing. Thanks cobalt, Sorry for bothering ya.

**Comment by CobaltWolf** [comment]
shit, forgot to recheck on this. Do you want to try and OBJ?
