### ISSUE TITLE
Saturn IVB APS description is wrong.

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#185]
The "Sarnus-SIVB-APS Auxilary Propulsion System" description says that it "feeds directly from your fuel tanks, negating the need for separate RCS fuel.", however it does not feed from your tank, nd uses separate RCS fuel. It should either be changed to use LHO, or the description should change.

**Comment by jsolson** [comment]
Didn't see you self assigned this. Already got it.
