### ISSUE TITLE
Kerbals slide down Hermes pod ladder

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#188]
There's some kind of phantom force that pushes Kerbals down the ladder on EVA.

**Comment by jsolson** [comment]
Press [F] Grab and he won't slide.
The ascent module/ladder/ground interface is imperfect. I have to grab the ladder after eva-ing.
Right now I'm having difficulty stepping up over the landing leg foot to get to the ladder from the ground.

**Comment by IronCretin** [comment]
This is the Mercury pod, not the LEM. Though that may have problems too, I'm not sure.

**Comment by CobaltWolf** [comment]
They all suck. The ladder/airlock collider system is FUBAR.
