### ISSUE TITLE
Some experiments don't work

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#191]
These experiments don't work. the only option in the right-click menu is "Aim Camera"
- Micrometeoroid Detector
- Geiger Counter
- "Zufar" Film Camera
However, the Hermes Goo and the Ion Trap do.
![screenshot102](https://cloud.githubusercontent.com/assets/708770/19017394/c6c69f1c-8805-11e6-9d46-3e501323ce89.png)

**Comment by CobaltWolf** [comment]
They use the generic version of DMagic's animation plugin. We'll have to wait for him to update it. Leaving it open until we have the update version. 

Alternatively, @jsolson, if you wanted to make that your next project. I believe the only thing they need from it is making it so they only animate one way. If you can get that working we'd be free of that dependency.

**Comment by jsolson** [comment]
The cameras use it because they hold multiple results.

I'm sure the others can be converted to ModuleAnimateGeneric without trouble.

**Comment by CobaltWolf** [comment]
at long as the one way tag is fixed. 

and weren't you going to code your own custom behavior for cameras when you had time?

**Comment by jsolson** [comment]
#88 
No. I never came up with a system I was happy enough with to run with. The new part upgrades and science containers may open some doors.

**Comment by CobaltWolf** [comment]
hrmm, I think it's definitely something to go back to. In general I think we should see what sort of cool stuff we can do with probes, especially when I start to push through those parts I made
