### ISSUE TITLE
Apollo RCS effects are broken

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#192]
The Apollo capsule RCS jet effects are stuck on. I launched the ship before the jets were added if that's relevant.
![screenshot107](https://cloud.githubusercontent.com/assets/708770/19017545/7eeba1a0-880b-11e6-9447-765becff4e5d.png)

**Comment by jsolson** [comment]
I have not observed this. Make sure everything's up to date, both KSP and BDB.

**Comment by CobaltWolf** [comment]
yeah like your engine mounts probably still have fuel. You need to build it from scratch every time we update.
