### ISSUE TITLE
LES model-texture issue

### ISSUE THREAD

**Issue by Araym-KSP** [CobaltWolf/Bluedog-Design-Bureau#194]
I just noticed during a ride on 1.1.3 (you know I'm cross-testing still on the old version, depending on what I'm feel to play):

the latest LES tower model (when the new textures were released), when placed on top of the Kane assembly, rotates counterclockwise at 90° respect the new textures.

During handling it after part selection it behaves regularly, but when placed, the model itself shifts, BUT the textures stays as they should be (so, for example, the hatch coverage texture is still above the Kane pod hatch correctly, but the model is 90° turned).
Even rotating the model during handling, before placement, does not correct the issue (Model and textures still switched at 90°, in the new placement).

For my 1.1.3 version I "partially" resolved the problem reverting just the model from an earlier release, but not completely:
during handling (not placed to the pod) the model is shifted 90° clockwise in respect to the textures, but then goes alligned when connected to the craft. (so basically it shows the same behaviour to turn 90° counterclockwise when placed, but being already shifted to the other side, it makes it right with the textures on a full build craft)

Check the behaviour in KSP 1.2 (model took by github beta version, not eventually later changes on the master version here)

**Comment by IronCretin** [comment]
This is fixed in 1.0 beta for 1.2.

**Comment by jsolson** [comment]
That's the old plugin.

**Comment by Araym-KSP** [comment]
Ok... in fact just noticed on 1.1.3, where, anywhay, I found a sort of fix for it (a previous LES model)
