### ISSUE TITLE
Apollo LES wobbles

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#197]
Unless it's autostrutted, the Apollo LES tower wobbles all over the place.
![screenshot143](https://cloud.githubusercontent.com/assets/708770/19024398/c5abd662-88d0-11e6-8d87-857824484de9.png)
![screenshot142](https://cloud.githubusercontent.com/assets/708770/19024400/ca644c98-88d0-11e6-8fc0-396c149079a6.png)

**Comment by VenomousRequiem** [comment]
It works fine if you auto-strut it to something. This is more of a KSP bug than a BDB bug, sorry. :)
