### ISSUE TITLE
Add new docking rules to Gemini, Apollo ports.

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#213]
I'd like to add the new docking module parameters to all our docking ports (The Apollo, Gemini, and MOL ports for now).

animCaptureOff: if true, will disable anim toggle when enter state Captured
animDisabledEnter: if true, will set enable toggle on enter state Disable
animDisabledExit: if true, will disable toggle when exit state Disable
animDisableIfNot1: if true, will force node to enter state Disable when anim.Progress is not 1
animDisenageEnter: if true will enable toggle on enter state Disengage
animDisengageExit: if true will disable toggle on exit state Disengage
DockedEnter/Exit don't do anything. Wonder what I meant for them.
animEnableIf1: if true will go to Enable state when anim.Progress == 1
animReadyEnter: if true will enable toggle on enter state Ready
animReadyExit: if true will disable toggle on exit state Ready
animUnockOn: if true will enable toggle on run event Undock

**Comment by jsolson** [comment]
All I've ever managed to do with these is make it not work right. It seems fine to me as is.

**Comment by CobaltWolf** [comment]
Can you at least try and configure the angle snapping? Look at the APAS configs; it's a different set of values.

**Comment by CobaltWolf** [comment]
https://kerbalspaceprogram.com/api/class_module_docking_node.html
Hrmm.

**Comment by jsolson** [comment]
Still no luck doing anything useful with this stuff.

**Comment by CobaltWolf** [comment]
Aight I'll handle it.

**Comment by jmrd98** [comment]
Some valuable hints are seen [here](http://forum.kerbalspaceprogram.com/index.php?/topic/94352-12-mark-one-laboratory-extensions-mole-v129-mk1-cmd-pod-station-extensions-more/&do=findComment&comment=2804232) from our good friend Angel-125. Not as much with the animations, but it might help with the angles.

**Comment by jsolson** [comment]
That post got me to give it another shot. While I got the Gemini port to at least still be able to dock using these settings, I think when the agena port model was rotated 90 degrees a long time ago is screwing with things. Or maybe not. I'm at the throwing things point with this stuff.

**Comment by CobaltWolf** [comment]
yeah don't worry about it, I assigned it to myself. I think I already got some of the new functionality built into the Apollo ports.
