### ISSUE TITLE
APAS port CADS 0.9375 Docking port bugs

### ISSUE THREAD

**Issue by Araym-KSP** [CobaltWolf/Bluedog-Design-Bureau#218]
![screenshot4](https://cloud.githubusercontent.com/assets/16553106/19219311/203e891e-8e10-11e6-8f3a-02accad0286c.png)
![screenshot5](https://cloud.githubusercontent.com/assets/16553106/19219318/35634992-8e10-11e6-8c5c-b0ddb38ce969.png)

KSP 1.2-pre v.1576 (latest pre-release)

The new APAS docking port (the one that should animate, as seeing in the cfg) have some model problem, probably related to the animation itself:
- it hovers above the capsule when placed
- it does not animate in VAB and neither in the actual active scene
- (related to the above) looking at it in the VAB, as it hovers, probably the model stay at the level of the upper node, where the animation (it's a ring moving up, isn't it?) should end when extended.

Check the model and if the animation is properly addressed.

**Comment by CobaltWolf** [comment]
CXG sent me a new one that was shorter to fit better. @jsolson the CADS port doesn't fit under the LES unfortunately. I don't know why it doesn't animate tho.

**Comment by jsolson** [comment]
It needs the correct animation name.
animationName = Default Take

**Comment by CobaltWolf** [comment]
He thinks it wasn't set as legacy export. He is giving me the new node height tonight.

**Comment by CobaltWolf** [comment]
Needs to be tested

**Comment by jsolson** [comment]
It still doesn't animate. It throws a NullRef exception.

**Comment by Modsojoy** [comment]
Animation marked as Legacy?

**Comment by jsolson** [comment]
I don't know anything about "marked as Legacy", but the animationName in the config is either a typo or has a space in it which is always cause for concern.

**Comment by Modsojoy** [comment]
Ay cobalt/Whoever made the part Check if A - The animation is marked as legacy in unity and Double check the Animation name, If it has spaces remove them.

**Comment by CobaltWolf** [comment]
whoa whoops. Didn't mean to close it. CXG says that this for sure works for him with the same .mu.
