### ISSUE TITLE
Bug with Sarnus-IV-2200 tank

### ISSUE THREAD

**Issue by Araym-KSP** [CobaltWolf/Bluedog-Design-Bureau#219]
... there a strange issue building the S-IV not starting from the top:
example here:
![screenshot13](https://cloud.githubusercontent.com/assets/16553106/19220112/a93da492-8e25-11e6-8b36-3969e1df87fa.png)
... start with the central part...
![screenshot14](https://cloud.githubusercontent.com/assets/16553106/19220115/b9efd332-8e25-11e6-8ae9-6175b8e07d32.png)
... add the engine mount...
![screenshot15](https://cloud.githubusercontent.com/assets/16553106/19220116/cc420870-8e25-11e6-802d-547160db5488.png)
![screenshot16](https://cloud.githubusercontent.com/assets/16553106/19220117/d1bcb21e-8e25-11e6-9d47-d7d10fa2b547.png)
... then I added the mentioned Sarnus-IV-2200 tank.

NOW anything picked from the part menu goes automatically to the upper node, free, of the Sarnus-IV-2200 tank. It is impossible to move around the VAB, it could be mounted ONLY on the top node, could be clicked over like to demount, but any part does not move untill dropped back in the part selection menu (like always) even if the part itself stay clipped above the tank (once released on the part menu, the game play the sound of dropping it) but then anything selected goes straight ONLY to the top node.

Noticed when I tried to add 6 engine below the assembly, but the Inon goes ONLY above:
![screenshot9](https://cloud.githubusercontent.com/assets/16553106/19220141/818a5bec-8e26-11e6-9ae9-e4adc9337f75.png)
![screenshot10](https://cloud.githubusercontent.com/assets/16553106/19220142/86a280e6-8e26-11e6-9868-7b9fc598875b.png)

... but the behaviour is consistent with ANY part picked from the menu, if it has a "bottom" node free...

![screenshot8](https://cloud.githubusercontent.com/assets/16553106/19220148/b68cbb5a-8e26-11e6-976b-72ed89d0ea0d.png)
![screenshot7](https://cloud.githubusercontent.com/assets/16553106/19220147/abcb1efa-8e26-11e6-8412-3a6d193c8df3.png)
... notice here (even if the mouse pointer is not shown in the screenshot because KSP eliminate it when picking an image) that the label of the Rhino engine follow the mouse when the part is "locked" above the S-IV-2200:
![screenshot18](https://cloud.githubusercontent.com/assets/16553106/19220170/4d22deb4-8e27-11e6-975e-b244459a2fd4.png)
and could be ONLY attach the engine there:
![screenshot19](https://cloud.githubusercontent.com/assets/16553106/19220186/a8a05276-8e27-11e6-9da7-e7789af8ed4b.png)

Only parts that have not any "bottom" definited node (example here: a "Panther" jet engine) could be moved freely and eventually attached below:
![screenshot20](https://cloud.githubusercontent.com/assets/16553106/19220200/ed94e9d2-8e27-11e6-8b06-7d19f7b2c8a7.png)
![screenshot21](https://cloud.githubusercontent.com/assets/16553106/19220202/f80225a6-8e27-11e6-8ea4-7821b3b69457.png)

The behaviour is definitely an issue with the tank, because it works too if it's the "root part", not only a part added above anything else:
![screenshot22](https://cloud.githubusercontent.com/assets/16553106/19220212/52078ca8-8e28-11e6-8daa-b462194d934c.png)
![screenshot23](https://cloud.githubusercontent.com/assets/16553106/19220220/6c4b3db2-8e28-11e6-95b1-3c0993a009e1.png)
![screenshot25](https://cloud.githubusercontent.com/assets/16553106/19220259/6f7f220e-8e29-11e6-8d65-9dfa1ff5b1ba.png)

... generally not noticed because we generally build "from top to bottom" (so we use the top node first), I checked back from older relases on 1.1.3 too, and it does the same "bug", so there is something wrong that is it keep going since it was released but went unnoticed up to now????

**Comment by jsolson** [comment]
The node size is 200. It's been like that since day 1. Nice catch.
