### ISSUE TITLE
Dipole issue

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#220]
Can't make this edit right now

Hi CobaltWolf

I don't have a git account, so thought I'd message you.

Was running down exceptions in my 1.2 setup, and ran across this:

PartLoader: Compiling Part 'Bluedog_DB/Parts/Antennas/bluedog_dipoleAntenna/bluedog_dipole'
 
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Cannot parse Enum value. Field antennaType, value v on object of type ModuleDataTransmitter: System.ArgumentException: The requested value 'v' was not found.
  at System.Enum.Parse (System.Type enumType, System.String value, Boolean ignoreCase) [0x00000] in <filename unknown>:0
  at System.Enum.Parse (System.Type enumType, System.String value) [0x00000] in <filename unknown>:0
  at BaseField.ReadPvt (System.Reflection.FieldInfo field, System.String value, System.Object host) [0x00000] in <filename unknown>:0

Sure enough, in the config file,

MODULE
    {
        name = ModuleDataTransmitter
        antennaType = v
        packetInterval = 0.6

Looks like a paste gone wrong.  I assume RELAY was the intended value?

Hope this is useful, and thanks much for the great mod.  It's a "must have" in my load order.

--Foozle

**Comment by jsolson** [comment]
Already fixed.
https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/6ecec0503f64b2dafc094e5114700b17c8733a93#diff-3c48a8d1c675afeefd7d2886d944d632
