### ISSUE TITLE
S-Ic engine mount retro rockets give roll torque

### ISSUE THREAD

**Issue by VenomousRequiem** [CobaltWolf/Bluedog-Design-Bureau#225]
The thrust transform on the S-Ic engine mounts are improperly aligned and roll the spent S-Ic around. It's not that big of a deal as they're only used after you're done with it, but it's a visual issue and some people are nitpicky(like myself :b)

**Comment by IronCretin** [comment]
I thought it was supposed to do that?

**Comment by VenomousRequiem** [comment]
No, they're supposed to fire straight out. No rolling.

**Comment by CobaltWolf** [comment]
Does this still happen or did I fix it?

**Comment by jsolson** [comment]
It still happens

**Comment by CobaltWolf** [comment]
Aight shouldn't be too hard to fix
