### ISSUE TITLE
Ayy matt?

### ISSUE THREAD

**Issue by Modsojoy** [CobaltWolf/Bluedog-Design-Bureau#233]
Ayy matt, 1.2 Has dropped.

**Comment by CobaltWolf** [comment]
k

**Comment by Modsojoy** [comment]
Lol sorry about the Useless post, Would've Emailed you but i cant find an Email on your Github page.

**Comment by CobaltWolf** [comment]
well, I mean, either I'm a) working on BDB, in which case I'd be watching for 1.2 to drop. Or b) I'm busy and an email wouldn't help :P

**Comment by Modsojoy** [comment]
Or c - Drinking.

**Comment by CobaltWolf** [comment]
that is done with both a or b

**Comment by Modsojoy** [comment]
God damnit Cobalt. XD.
