### ISSUE TITLE
HLR-P1 "Ramo" Probe causes issues

### ISSUE THREAD

**Issue by pike82** [CobaltWolf/Bluedog-Design-Bureau#241]
For some reason this probe (I have tested a few of the others and they are ok) causes the staging menu to disappear around 10 seconds after engine activation (from launch) and then the Nav ball and the ship commands (including right click on parts) to freeze/not work. The physics engine still runs but seems stuck on the point when the freezing occurs. 

An example is launching the probe on a Solid Rocket booster. The booster will accelerate until the freeze point. The ship will continue to run after the freeze point with the SRF still burning fuel as normal, however after the freeze point the velocity of the craft will remain and all controls become inactive.

I am halfway through career mode so it is not a random event caused by another mod (game runs fine for every other part I have tried). I have also tried restarting KSP and reloading this probe into two different saves half a dozen times, so it is not a one off event.

**Comment by pike82** [comment]
I have added the Ckan export of the mods installed.

[Unstable 2 .txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/531574/Unstable.2.txt)

**Comment by CobaltWolf** [comment]
Can you confirm whether it happens on a clean install of KSP 1.2 with BDB 1.0.1 installed? Our process for hunting the bug will differ significantly. That's very strange tho. I've never heard of something like that.

**Comment by jsolson** [comment]
I can't duplicate it. Can you upload a ksp.log?

**Comment by pike82** [comment]
I will try to get the files and test in a fresh install tonight (if the kids allow me to).

**Comment by pike82** [comment]
A test run with the probe on a clean install in v1.2 works fine. 

I did a test run again on my current v1.1.3 setup with a fresh Ksp log and was able to replicate the issue again with the same probe (note first launch was with another probe). I have attached the files requested.

[ModuleManager.ConfigCache.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/533213/ModuleManager.ConfigCache.txt)

[KSP.log.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/533215/KSP.log.txt)

**Comment by pike82** [comment]
Furthermore from a quick glance [WRN 21:48:53.921] and [EXC 21:49:08.498] appear to be two keys locations in the log for your reference.

**Comment by jsolson** [comment]
This
`[WRN 21:48:53.921] [Part]: PartModule ModuleRTDataTransmitter at bluedog.Pioneer1, index 21: index exceeds module count as defined in cfg.
Looking for ModuleRTDataTransmitter in other indices...`

would occur when your save file is different from the part config. There's a ModuleRTDataTransmitter in the save, but in the part config, it's a ModuleRTAntenna.

Try building it from scratch and see if it still occurs. If you are building from scratch, then I don't know what to say, that shouldn't happen. I would say remove remotech and see what happens, but that will really screw up your save.

That's an extensive list of mods, so make sure they're all up to date. There's a newer version of remotetech for 1.1.3, version 1.7.1.

**Comment by pike82** [comment]
Thanks for your efforts. I am guessing it may be a corrupt file my end as I moved the ksp directory last weekend in preparation for an upgrade to an ssd. 

Main thing, it appears not to be an issue with your file. I will put it down to a "random computer thing" as everything else plays fine when I don't use that probe and I will start a new v1.2 career install soon anyway.

**Comment by CobaltWolf** [comment]
No problem, thanks for bringing it to our attention. :)
