### ISSUE TITLE
X-15?

### ISSUE THREAD

**Issue by Modsojoy** [CobaltWolf/Bluedog-Design-Bureau#246]
an X15 Would be a good addition.

**Comment by VenomousRequiem** [comment]
It's being worked on by a friend of ours. This is more of a post for the forums, not an issue. :)

**Comment by Modsojoy** [comment]
Oh, i was going to say i'm half way through modeling one, And im working on making Landing gear.

**Comment by VenomousRequiem** [comment]
Oh, let's see it! Though I don't think we she is include on in BDB in respect for Shute's efforts on his.

**Comment by Modsojoy** [comment]
Ah, Was un aware that there was one in the works, Perm b& from the forums so i dont(cant) follow Threads.

**Comment by VenomousRequiem** [comment]
I'm curious what you did to ge banned from the forums, but that's not a discussion for here. :b

**Comment by Modsojoy** [comment]
Lol.

**Comment by Modsojoy** [comment]
"VenomousRequiem commented 42 minutes ago:Oh, let's see it"
![ayy](https://cloud.githubusercontent.com/assets/21351692/19422108/fa925042-93dc-11e6-9395-fe6f06df0d0b.PNG)

**Comment by VenomousRequiem** [comment]
That... Is... Not X-15.

**Comment by Modsojoy** [comment]
CockpitWIP.

**Comment by Modsojoy** [comment]
Also its meant to be kerbalised.

**Comment by Modsojoy** [comment]
![ayy](https://cloud.githubusercontent.com/assets/21351692/19422166/e63cf3e4-93dd-11e6-8b65-6ddb8bb89d16.PNG)

**Comment by CobaltWolf** [comment]
X15 (and anything aircraft based) is outside the scope of this mod.
