### ISSUE TITLE
A vague Idea: Unshielded LES

### ISSUE THREAD

**Issue by Araym-KSP** [CobaltWolf/Bluedog-Design-Bureau#254]
This is not any bug-problem.

Just an idea for @CobaltWolf:

... could it be an iper-mega problem do a "generic LES" from your Apollo one?

Cut the Shield, just end the LES itself with a white cone that ends in 0.675m diameter. It could be a great "LEGO-alike" LES to be mounted on infinite generic payloads ___

Pretty please <3 WITH LOVE <3
Araym (:P)

**Comment by Araym-KSP** [comment]
p.s.: I admit: it's a shameless self-request.
I'm not done yet to settle my mod packages (I'm probably going to build a modded career with modded tech tree, as basis for my upcoming "comic-reprise") and I was just wonderig to find an advanced "generic LES tower", big enough to fit the use for any pod from 2.5m onward. Your one, @CobaltWolf, is the best actually :D 

😼 ppprrruuuuu-etty pleeeeease -puuuuurrrrr 😸

**Comment by CobaltWolf** [comment]
I think we would have to ask Kurld about that. It's certainly possible. I think that in his official mod PEBKAC he has such things, but he'd have to see about getting the textures. I believe he is rebuilding it to be single part style that he and Jso developed for the Kane one. If he has something like that in his mod we can see about including it in BDB too.

**Comment by jsolson** [comment]
Kurld has the exact part you're asking for in his pack, and it's a pretty lightweight part pack, no biggie to install. We have our own version because it's fitted to the Kane capsule and decoupler - and he was nice enough to make it. I don't see the point of adding a generic version that just duplicates his.
