### ISSUE TITLE
Prometheus-T-RTB RCS Translate BUG

### ISSUE THREAD

**Issue by FoxxoniusAugustus** [CobaltWolf/Bluedog-Design-Bureau#255]
The Prometheus-T-RTB Reaction Thruster Cluster has no graphic/sound and no thrust forward.
Tested disabling and enabling RCS and individual RCS actuation toggles. Throttle-able engine mode also has no graphic/sound or thrust.

Crap diagram below. Ignore dots.

ok<--->ok
..........I
..........V
   not ok

**Comment by CobaltWolf** [comment]
Fuck you I fixed this on the master. Prove to me that it's broken there

**Comment by FoxxoniusAugustus** [comment]
nvm, I'm an idiot. To be fair that had been broken forever and you only fixed it 3-4 comit's ago.

**Comment by CobaltWolf** [comment]
Fuck you I fixed it in the master

-----Original Message-----
