### ISSUE TITLE
Tech Tree Balance

### ISSUE THREAD

**Issue by minepagan** [CobaltWolf/Bluedog-Design-Bureau#266]
With the addition of new parts, many with temporary tech tree placements, the mod needs a rebalance. Current issue is - should the tree be condensed, or should Sat-V be endgame?

**Comment by minepagan** [comment]
Leaning to condensed, to give space for ETS, Comet, ect. without needing CTT.

**Comment by CobaltWolf** [comment]
Please keep tech tree discussions on issue #189
