### ISSUE TITLE
Hydrolox Titan engine 1.875m butt is too small

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#268]
The 1.875m base for the cryogenic Titan engine is slightly too small.
![screenshot11](https://cloud.githubusercontent.com/assets/708770/20010640/4d2fdcc4-a27f-11e6-8eb3-48d4882cf109.png)

**Comment by CobaltWolf** [comment]
Oh dammit. You know what happened? I multiplied it by 4/3 instead of 3/2. Ante the other ones correct?

-----Original Message-----

**Comment by IronCretin** [comment]
Yeah.
