### ISSUE TITLE
Apollo IVA fails to load on a clean install with RasterPropMonitor

### ISSUE THREAD

**Issue by demib84** [CobaltWolf/Bluedog-Design-Bureau#269]
Hello,

I am having issues with the IVA for the Kane module, it is simply missing. I had thought perhaps it was other mods conflicting, so I deleted all of them with the exception for BDB. Still had the same issue with it missing. So I am at a lost for what this issue is. I tried to keep the logfile at a minimum by just putting the capsule on the launch pad and then exiting out of the game. Thank you for your time!

[output_log.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/573056/output_log.txt)

**Comment by jsolson** [comment]
@Daelkyr13 could you look at this, I've been told you know a thing or two about INTERIORs (I don't).

This error appears to be the source of the problem:
`LoadInternalPart 'Bluedog_DB/Compatibility/RasterPropMonitor/KP0110internalRPM/KP0110internalRPM' FAILED: Cannot find model`

The interior is being changed to `KP0110internalRPM` by [this compatability file](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Compatibility/RasterPropMonitor/KP0110internalRPM.cfg).
He has RasterPropMonitor installed.

**Comment by demib84** [comment]
I tried deleting the RPM mod and the game was still looking for KP0110internalRPM. 

[output_log.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/575611/output_log.txt)

**Comment by jsolson** [comment]
This likely has something to do with it.
`LoadInternalPart 'JSI/RPMPodPatches/PatchesMod/kp0110-remade-internal/KP0110internalRPM' FAILED: Cannot find model`

There's some RasterPropMonitor files still in GameData\JSI

**Comment by jmrd98** [comment]
RPM ships configs for the original capsule we borrowed the IVA from, I think. 
Looking at it, we could get away with something like 
``@INTERNAL[KP0110internalRPM]:BEFORE[Bluedog_DB]:NEEDS[JSI]
``{
``    {
``        @model = (Insert our model path here)
``    }
``}
... actually that would be exactly what we would need.

**Comment by jmrd98** [comment]
Initial pass at the above patch failed to solve the problem... I'm hoping it is a order of patch application issue, as I can't think of a reason it would faIl.

... No, I know why this doesn't work: I need to find the parts it reconfigures and alter their configs directly. By the time this patch fires, the pods have already been altered. Arhghggggg.

**Comment by jsolson** [comment]
I haven't taken the time to figure out how INTERNALs work beyond the obvious but... I would think KP0110internal would need to be renamed bdbKP0110internal to avoid name collisions if  we were to encounter it installed through other means. It would also prevent an outside patch from accidentally modifying our version.

**Comment by jmrd98** [comment]
This is the best/fastest solution. The RPM patch is a little clumsy in the way it goes about things.
