### ISSUE TITLE
Sargent 11x decoupler

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#27]
The one with the hole in the middle. Decouples in wrong direction - flys off forward.

**Comment by CobaltWolf** [comment]
@jsolson could this be due to the same issue the interstages had long-ago with being offset? Or do you think it's a collider issue?

**Comment by jsolson** [comment]
Probably is. The fix would be to shift the coordinates on the 3x part so it's entirely below the 0,0,0 position (I think). This part combination used to work. It may have been colliding before and bouncing backwards making it look correct, then somehow the collision got fixed. I can't look at this till tomorrow.

**Comment by CobaltWolf** [comment]
I'll try and figure it out.

**Comment by CobaltWolf** [comment]
@jsolson this does not occur in the intended behavior (ie staging the 3x cluster with the decoupler). What do you think?

**Comment by jsolson** [comment]
Confirmed. Sienno + Vicenza 1x / HLR-VD3 Decoupler / Vicenza 3x / HLR-VD11 Decoupler attached to upper "bottom" node on 3x / Vicenza 11x. The HLR-VD11 + 11x detaches forward over the probe. No evidence of clipping.

**Comment by VenomousRequiem** [comment]
Had i been paying attention to this, i could have confirmed it when the issue was opened. I noticed it and forgot to log anything a couple weeks ago.

**Comment by jsolson** [comment]
I'm pretty sure I've got this fixed. Same problem as the interstages, just on the 3x engine rather than the decoupler. The center coordinates of the engine needs to be forward of the decoupler's center when it's attached.

It's going to be totally save/craft file breaking.

**Comment by CobaltWolf** [comment]
Alright I'll see what I can do. I've set a goal of getting the final release out by this coming Tuesday

**Comment by CobaltWolf** [comment]
So is it the 3x cluster that needs changing, or is it the decoupler itself?

**Comment by CobaltWolf** [comment]
It's fixed! Awesome.
