### ISSUE TITLE
Atlas tanks fuel switching

### ISSUE THREAD

**Issue by minepagan** [CobaltWolf/Bluedog-Design-Bureau#276]
The Atlas tanks only have the baloon/ regular switching (which does nothing but affect mass). However, they don't have any options to switch fuels (hydrolox, for instance).

All other tanks (of that size) have the option, why not them?

**Comment by jsolson** [comment]
At >= 3 rescale they get the Balloon tank option, and I'm just switching the LH2 option to Balloon. There's no reason it couldn't have three options.

I was just sitting here pondering eliminating the LH2 option from smaller tanks, and making it monoprop instead. Small LH2 tanks are useless, while small (large by monoprop standards) monoprop tanks are useful.

There's no reason you can't have every conceivable option on every tank. I just like to reduce interface clutter.

**Comment by minepagan** [comment]
I think it would be good to have every tank greater than size 1 to have an LH2 option, and every tank less tham size 1 to have a monoprop option. Size one should probabally be based on volume, and a few other pankake tanks too.

**Comment by jsolson** [comment]
You've got me thinking maybe we should reduce complexity a bit and just install the balloon tanks always. I didn't want to put them in stock 1x, but they weight about the same as the LH2 tanks, and we're op in 1x balloon tanks or not.

So every non service module tank would have:
LF/O Standard or Balloon
LH2/O
MonoProp

**Comment by minepagan** [comment]
@jsolson it appears that it is not an issue in the stock game - it only appears when the >=3 rescale patch is active. So apparently the balloon option is overwriting it? I say this because tanks that did have an LH2 option in stock (like the Vega tanks) don't have that option in a rescale.

**Comment by jsolson** [comment]
This should be addressed now. I did change it so balloon tanks show up in stock.

**Comment by minepagan** [comment]
Yeah, it seems to be fixed now, I think you can close it.
