### ISSUE TITLE
Sienno/Vicenza - todo

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#28]
Make roll torque same as pitch and yaw torque. Mechjeb is oscillating on the roll axis.

Add 15 kg mass to probe account for experiments and antenna.

If the Sargents stay overfueled bring Isp down to Separatron levels. Target deltav is <1500.

**Comment by CobaltWolf** [comment]
Is this for you or for me? Loving all these helpful issue reports. Keep them up!

**Comment by jsolson** [comment]
The torque and mass will take 2 minutes if you want to do them. Save me a pull request. The Isp is a wait and see item for later. Need to find creative ways to cripple this thing without just throwing a half a ton on it somewhere. No hurry.

**Comment by CobaltWolf** [comment]
I'll take care of it next time I'm going through all these issues.

**Comment by CobaltWolf** [comment]
I edited the torque (made them all 0.02) and made the mass 0.065.

**Comment by jsolson** [comment]
Reopened so I don't forget. I still want to work on these engines.

**Comment by CobaltWolf** [comment]
ohhhhh righrighright
