### ISSUE TITLE
Separate probe pack from launchers

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#282]
We want to separate the probe parts from the launchers parts.

Todo:
Decide on a directory structure. Should everything go under GanmeData\Bluedog_DB, or a new top level folder, GameData\Bluedog_Probes.

What get's moved? Everything under Parts\Probes, Parts\Science, Parts\Antennas, Parts\Explorer, Resources\ScienceDefs.cfg. Related stuff under Compatibility needs to be untangled.

What doesn't get moved? The Apollo Scimatar antenna.

What to do with Explorer and it's 1x/3x/11x boosters?

There may or may not be some crossover with misc parts like decouplers that are needed for both probes and launchers.

**Comment by CobaltWolf** [comment]
I think the explorer stuff should go with the probes. The off sizes can possible be off putting.

**Comment by minepagan** [comment]
About explorer, I would separate it, but not the Sargent rocket motors.

**Comment by jsolson** [comment]
My initial thought on explorer was it should stay put since it's more booster than probe, but the sargent's are really only used for explorer/pioneer so it should probably move. Regardless I don't think the explorer probe and sargent motors should be separated from each other.

**Comment by CobaltWolf** [comment]
I think they need to go. I think we can just make a cfg to make a 0.3125m version of the 0.625m decoupler, so we don't need to keep anything from the probes pack in the main mod. Can we keep it all on this same repo and just have separate packages in the releases section?

**Comment by jsolson** [comment]
Same repo would be easiest for everyone. Would anything less than 0.625m remain in the main mod that would even require a smaller adapter?

**Comment by CobaltWolf** [comment]
The Altair and Alcyone SRBs. But they would never be integrated into an aerodynamic stack so having just a decoupler is fine. 

-----Original Message-----

**Comment by CobaltWolf** [comment]
lol... yeah....
