### ISSUE TITLE
Check S-IVB IU attachment points

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#285]
Apparently there is some clipping - the attach points don't perfectly line up with the end of the parts. I need to fix it.

**Comment by CobaltWolf** [comment]
This *should* be fixed now.

**Comment by jsolson** [comment]
I'm seeing shimmering/z-fighting at the IU/tank interface.

**Comment by CobaltWolf** [comment]
Still???

**Comment by jsolson** [comment]
Not today. Looks good on skylab and the sivb tank. And I'm pretty sure it hasn't been touched since I last saw it.
