### ISSUE TITLE
Add standalone LFO Titan engine

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#286]
Shouldn't be too hard - we need a single mount version of the normal LFO Titan engine. Probably going to base it on the Titan IV engine with the bronze bell extension. Would take an hour or so tops. @jsolson you'll need to cook up the stats for it. Think you could just comment the values here? It'd basically just be everything halved with some adjustments I think... It's really just a flavor part.

**Comment by jsolson** [comment]
I think the one that we have (titan 1?) has stats exactly one half the parent engine. Thrust,mass,cost.

**Comment by CobaltWolf** [comment]
No, cus its Hydrolox. 

-----Original Message-----

**Comment by jsolson** [comment]
The X-300 is what I was thinking of. That needs a look at balance. Same weight as the titan 1 engine, a lot less thrust, less Isp, and more expensive. That's just wrong.

Regardless, exactly one half thrust/mass would be appropriate for a single chamber Titan engine.

**Comment by CobaltWolf** [comment]
Feel free to change it if you think it needs to be adjusted.

**Comment by CobaltWolf** [comment]
This engine is working great, but we need to push it back in the tech tree. I also fucked up the mesh and need to do some cleaning -some extra geometry got left in and its causing Z fighting

**Comment by jsolson** [comment]
Ouch, how did that slip though... it needs to go to heavyRocketry. How badly is that going to break saves?

**Comment by CobaltWolf** [comment]
Just do it, its one part.
