### ISSUE TITLE
Finish new Apollo parts 

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#289]
Finish the parts on that texture sheet so they can have normal/specular maps created.

- [x] Blok V solar panels
- [x] Blok V HGA
- [x] Blok V engine remake
- [x] Normal maps
- [x] Specular maps
- [ ] Descriptions + names
- [ ] Fix parachute texture glitchiness

**Comment by jsolson** [comment]
I'm seeing flickering on the parachute when I change the texture to white. In flight, not in the vab.

**Comment by CobaltWolf** [comment]
Someone else reported that. I'll see what I can do. Do you mean the parachute cover? Or the chute itself. There's a chance that it could be an incompatibility between the stock parachute module and the texture/mesh switching. How does B9's work? We should maybe think about converting them to that while we still only have a couple to worry about.

I'll see what I can do. do you want it with the arm or more like the stock 1x6 panels?

**Comment by jsolson** [comment]
I wouldn't be at all surprised if mesh switching completely borked a parachute. They seem to be fragile. Just switching the texture would probably work, but I don't know if B9 or WBI can do that, and we wouldn't want firespitter for just one part. Perhaps a neutral texture can be found? You could take a little creative license and draw a frame on there to hide the color transition.

[This is](https://github.com/ChrisAdderley/NearFutureConstruction/blob/master/GameData/NearFutureConstruction/Parts/Truss/truss-octo/truss-octo-01.cfg) one of Nertea's parts that uses B9 for mesh switching.

Nevermind about the solar panel. Rotating it 90 degrees works very well for a more traditional flush mount.

**Comment by jsolson** [comment]
Switching to B9 fixed the flickering parachute, and it handles the symmetry correctly - change one and it changes them all. The cap, referenced in ModuleParachute capName = cap does not jettison when you use the alternate paint though. I don't see a solution to that. Otherwise everything seems to work.

**Comment by CobaltWolf** [comment]
Alright well I'm closing this
