### ISSUE TITLE
Malhena Solar panels do not work in game

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#29]
Convert both sides of solar panel to static panels, add in transmitter, convert all animation over to ModuleAnimateGeneric.

**Comment by CobaltWolf** [comment]
I need to know whether this works.

**Comment by Cowboy-WY** [comment]
Both Panel and Antenna animate when using "Extend Panels" and "Retract Panels" options.

Only one side of the panel works for "Sun Exposure" and "Energy Flow".

"Transmit Data" functions with panels extended or retracted.

No RemoteTech configuration included for this part

**Comment by CobaltWolf** [comment]
As far as I can tell, it's impossible to get this part working on both sides with the stock modules. #JustSquadProgramming

**Comment by Cowboy-WY** [comment]
Anything left to test for this?  

I included the antenna in the latest remote tech update.

Only thing I see is the config file is a little messy and the panels are set to not breakable.  (I can fix these if you are done working on this part)
