### ISSUE TITLE
Smooth engine gimbals

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#297]
Someone pointed out to me that our engine gimbals apparently have the old 'snapping' behavior, while newer ones like the Porkjet revamp gimbal smoothly. I believe it's something in the part cfg.

**Comment by jsolson** [comment]
gimbalResponseSpeed and useGimbalResponseSpeed? I thought they've been around a while.

**Comment by CobaltWolf** [comment]
idk what ours are set as tho.
