### ISSUE TITLE
Apollo Block V service engine missing plume

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#302]
The Apollo Block V service engine is missing it's plume. Pretty self explanatory.

**Comment by jsolson** [comment]
Stock effects missing. I don't a cfg issue. Probably a missing transform. The LEM descent engine effects work ok.

**Comment by CobaltWolf** [comment]
I'll have to see, I'm not sure what it could be.

**Comment by jsolson** [comment]
My guess is [fxTransfrom](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Apollo/bluedog_Apollo_Block5_ServiceEngine.cfg#L59) is missing. The effects are just copied from the decent engine which does work.

**Comment by CobaltWolf** [comment]
I don't know how that's possible since the descent engine is missing it too, but it should be fixed now.
