### ISSUE TITLE
BDB Mirrored Solar Panels Not Working Correctly

### ISSUE THREAD

**Issue by Daelkyr13** [CobaltWolf/Bluedog-Design-Bureau#315]
While the new plug-in does correctly (and easily) mirror the solar panel textures as intended, it does not mirror the actual  suncatcher  portion of the solar panel.

**Comment by jsolson** [comment]
Try it now. I really did test that. Then I got cute and cleaned up the code without testing again.

**Comment by CobaltWolf** [comment]
@jsolson this appears to be working now? I'm closing it
