### ISSUE TITLE
Saturn SLA w/ Saturn_Rescale

### ISSUE THREAD

**Issue by thunder175** [CobaltWolf/Bluedog-Design-Bureau#317]
When using the Saturn_rescale.cfg optional MM patch, all Saturn parts are rescaled to 6.375m and 4.25m. This includes the Saturn Lander Adapter Module. However the top node increases in size as well as the base, and no longer is compatible with the Apollo CSM which remains at 2.5m. Does this need a new 4.25m to 2.5m adapter or is there a scaling option I am missing?

**Comment by jsolson** [comment]
It needs a new adapter since we can't rescale just one end of the part.

**Comment by jmrd98** [comment]
If it's not in the rescale somewhere, one of us has the MM patch to convert the appropriate fairing base to a PF interstage. I'll hunt it down tonight/tomorrow if it's not present.

**Comment by jmrd98** [comment]
Ok, so tonight/tomorrow turned into 3 days, but the fix is in! (After a ****load of git dusting off, whew. I still exist, but work is challenging at the moment.)

I will leave the issue open for feedback on the patch. @thunder175 , could you give it a look and see if it will work for you?

**Comment by thunder175** [comment]
Seems to work! Although can you check the node placement for the fairings? There is a slight gap between the fairings and the fairing base. I can see daylight in the stack.This will definitely work though until we get a 4.25 petal adapter.

**Comment by jmrd98** [comment]
If you check the config, there is an @extraNodeShift value which controls that spacing. I left it be for the moment, as as you say, there is a small gap, but I don't know how tight it can get before weird collision things pop up with PF. Try playing with it and see what the results are. I don't know if it works for PF, but check out [NodeHelper](http://forum.kerbalspaceprogram.com/index.php?/topic/115700-122-nodehelper-tool-used-to-edit-node-positions/), its a godsend for things like this.

Glad it's working for you, though!

**Comment by CobaltWolf** [comment]
Oh shit did you do a thing?

**Comment by jmrd98** [comment]
Sometimes I do in fact do a thing.

**Comment by CobaltWolf** [comment]
Donezo
