### ISSUE TITLE
Real names update

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#321]
Progress tracker on updating the real names config.
 - [x] Agena
 - [x] Antennas
 - [x] APAS
 - [x] Apollo
 - [x] Atlas
 - [x] Centaur
 - [x] Delta
 - [x] Diamant
 - [x] Early Rockets
 - [x] Engines
 - [x] Explorer
 - [x] Gemini
 - [x] Juno
 - [x] Launch Clamps
 - [x] Mercury
 - [x] Probe Expansion
 - [x] Saturn
 - [x] Science
 - [x] Skylab
 - [x] Titan
 - [x] Vega

**Comment by IronCretin** [comment]
WIP patches are available on https://github.com/IronCretin/Bluedog-Design-Bureau/tree/realnames

**Comment by jsolson** [comment]
Cool. Somebody's been reading up on regular expressions.
