### ISSUE TITLE
bluedog_Algol (no thrust)

### ISSUE THREAD

**Issue by Anvh87** [CobaltWolf/Bluedog-Design-Bureau#323]
Hello, 
I found this little problem with the Dioscuri-MGU27 "Persei" Solid Rocket Booster.
The Radial version works, but not the inline version.

When activated there is no thrust coming out and no plume, it seems like the "node" for the thrust is inside the model and it is colliding with itself since when you look at the stats while running it does generate the thrust.

**Comment by jsolson** [comment]
Yeah, there appears to be an issue with the thrust transform.

**Comment by CobaltWolf** [comment]
@Anvh87 yes, it appears that the transform names in the model changed last time it went through Maya, meaning that there wasn't a thrustTransform in the model at all! Uploading a fix in a minute.

**Comment by Rodg88** [comment]
The MGU27A radial version seems to have some problems too, the thrust is coming out at a 90° angle, instead of the 1 or 2° it should be. I'm using a version direct from the GitHub where the MGU27 is fixed.

**Comment by CobaltWolf** [comment]
@Rodg88 should be fixed now. I don't know how, but when I reexported them from Maya the one thrustTransform was rotated 90 degrees, the other was missing entirely.

**Comment by CobaltWolf** [comment]
@Rodg88 should be fixed now. I don't know how, but when I reexported them from Maya the one thrustTransform was rotated 90 degrees, the other was missing entirely.
