### ISSUE TITLE
PDC-L Lateraltron symmetry

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#332]
The small Lateraltron sideways separation rockets have weird symmetry... If you want to place them on a radial booster, you can't place two in mirror symmetry to get them pointing the same way (eg both pointing inwards). They just are placed in the same orientation as in radial symmetry mode.

**Comment by CobaltWolf** [comment]
I'm not sure, but this sounds like something that might be a stock bug. 

By the way Rodg, what's your forum username. Someone I know?

**Comment by Rodg88** [comment]
Yeah maybe, it could just be because it's an asymmetrical sideways part to begin with. I'll check if there's other asymmetrical parts that do the same thing.

I'm Rodger on the forum, but I don't think I've posted much in the BDB thread

**Comment by Rodg88** [comment]
Yeah, looks like the only way to fix it would be to rotate the part to have the engines pointing down or up initially. That way mirror symmetry could be used to rotate them to both point sideways in the same direction. Not that critical though, you can just place them individually.

**Comment by CobaltWolf** [comment]
I gotta say Rodg I used them tonight and had no issues with them. :/

-----Original Message-----
