### ISSUE TITLE
Null Ref - Light of the Kane-11-5 Always "ON"

### ISSUE THREAD

**Issue by AstroWell** [CobaltWolf/Bluedog-Design-Bureau#333]
The Light of the Kane-11-5 Advanced Command Pod "bluedog_Apollo_Block3_Capsule" are always "ON".

Cause a null Ref when the Caspule is loaded in the VAB.

```
[ERR 22:06:56.708] Module ModuleAnimateGeneric threw during OnStart: System.IndexOutOfRangeException: Array index is out of range.
  at ModuleAnimateGeneric.OnStart (StartState state) [0x00000] in <filename unknown>:0 
  at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 
```

The Folder contain 2 variant for the Apollo Capsule "bluedog_Apollo_Capsule" and "bluedog_Apollo_Capsule_New" The setup in unity are maybe not correct ?

**Comment by Araym-KSP** [comment]
Found that issue too:

it's basically the 5 seat pod having as light transform reference for the "old" from the previous pod in the cfg (or the other way around... I forgot :P) for the light transform

Noticed when I was trying to make working back in my game the old Kane version too (even if Cobalt does not like it anymore, I was looking for the changing color white/grey old ones, and noticed the old behaviour on the new couple)

3 seat variant lights module animation call:
animationName = bluedog_Apollo_Capsule_light

5 seat variant:
animationName = bluedog_Apollo_Capsule_WindowAnim

... i think that in the new Apollo capsule, should be both the first...
