### ISSUE TITLE
SARNUS SIVB LAM doors do not open in VAB.

### ISSUE THREAD

**Issue by SlainteMaith** [CobaltWolf/Bluedog-Design-Bureau#334]
Steps To Reproduce:
1) Open KSP
2) Select a Sandbox Game
3) Enter the VAB
4) Build Sarnus V rocket, down to adding the SIVB LAM for the LM.
5) Right-click on the LAM
6) Select "Toggle Doors"

Observed Result:
Doors do not open.

Expected Result: 
Doors should open to more easily insert a payload.

**Comment by SlainteMaith** [comment]
Notes: 
Workaround is to build the Sarnus Rocket starting with the Sina Ascent Stage.

**Comment by CobaltWolf** [comment]
Can you confirm if you're using the Saturn Rescale MM config?

-----Original Message-----

**Comment by SlainteMaith** [comment]
Sure!  Where would I find this?

**Comment by CobaltWolf** [comment]
I'm not sure. Ctrl+F your KSP directory for Saturn_Rescale.cfg

-----Original Message-----

**Comment by SlainteMaith** [comment]
Can confirm it is -not- present.

**Comment by SlainteMaith** [comment]
Do I need the rescale?  I'm using stock sized RSS.

**Comment by CobaltWolf** [comment]
No, I forgot to configure the animations for both versions when I did some mesh fixes...

-----Original Message-----
