### ISSUE TITLE
IMPROVEMENT: Title Standardization

### ISSUE THREAD

**Issue by IronCretin** [CobaltWolf/Bluedog-Design-Bureau#336]
cobalt ur part titles are inconsistant

- Rocket parts
  - Rocket & stage
  - Engines
    - Reference real name?
    - Types:
      - LFO: "Liquid Fuel Engine"
      - Cryo: "Cryogenic Engine"
      - Monoprop: "Monopropellant Engine"
      - SRB
        - Booster: "Solid Rocket Booster"
        - Inline?/Upper: "Solid Rocket Motor"
  - Fuel Tanks
    - Fuel capacity - LFO Units total
    - Fuel type
      - LFO: "Liquid Fuel Tank"
      - Cryo: "Cryogenic Fuel Tank"
      - Monoprop: "Monopropellant Tank"
      - Service Module: "Service Module"
    - Diameter?
  - Structural
    - Adapters: `<name>-<larger>-<smaller> Structural Adapter`
    - Fairings: `<name>-F-<size> Fairing Base`
    - Engine Mounts/Fairings: `<name>-EM-<# engines> Engine Mount`
    - Decouplers: `<name>-D-<size> Decoupler`
    - Interstages: `<name>-I-<larger>(-<smaller>) Interstage`
    - Launch Clamps: `<name>-LC(-<size>) Launch Clamp`
    - Heatshields: `<name>-HS-<size> Heatshield`
Are some of these changes too much? Should I just make sure the terminology is consistent and sizes and roles are mentioned in titles or descriptions?

**Comment by jsolson** [comment]
The fairings with the radius instead of the diameter in the title make me crazy.

**Comment by Pappystein** [comment]
RE Solid Rockets.   SRM is the specific name applied to the entire family of Solid Rockets for Titan.   most all of the SRMs refer to the UA-120 family of Rockets but the Hercules SRMU is un-related (other than diameter and... well Titan.) 
All Solid Rockets Pre Space Shuttle appear to be labeled as SRMs.  Only with the Space Shuttle era do we see the term SRB (Solid Rocket Boosters.)   By that nomenclature all of the BDB Solid Rockets should be classified as SRMs.
