### ISSUE TITLE
Disable LHyd boiloff pre-launch

### ISSUE THREAD

**Issue by MOARdV** [CobaltWolf/Bluedog-Design-Bureau#341]
Prior to launch, when the vessel is sitting on the launch pad and connected to launch clamps (and presumably fuel lines), LHyd shouldn't boil off, since I'd assume the tanks are being topped off.  There are a couple of ways of implementing it -

* Simple way: if the vessel has any launch clamps (a part has module LaunchClamp), don't boil off.
* Fancy way: Add a module (ModuleBdbTopoff?) to selected launch clamps (the FASA umbilical tower, but not the Saturn hold-down clamps, for instance).  If any launch clamp has that module, don't boil off.  The top-off module could have a switch to disable it, if someone really wanted to allow boiloff on the launch pad.

I plan on implementing this on my own branch of the plug-in, but I thought I'd offer it as a pull request if it is of interest.

**Comment by CobaltWolf** [comment]
Or, just turn on the generators on the umbilical clamps. :D

-----Original Message-----

**Comment by MOARdV** [comment]
That works if your tank is topped off.  If you're launching with a reduced fuel load, the generators will fill the tank.

**Comment by jsolson** [comment]
Is there a way of determining if you're attached to launch clamps without walking the vessel part tree every update? That would seem to be expensive.

**Comment by MOARdV** [comment]
Subscribe to GameEvents.onVesselWasModified.  When the vessel changes, you see if there are still launch clamps:

```        
private void CheckTopoff()
{
    var lc = vessel.FindPartModuleImplementing<LaunchClamp>();
    topoffAvailable = (lc != null);
}
```

That's how I implemented it locally.  You walk the part list once in Start(), and then every time the vessel changes (basically, when it stages and the part count changes).
