### ISSUE TITLE
Pioneer1 geiger experiment not working

### ISSUE THREAD

**Issue by davy79** [CobaltWolf/Bluedog-Design-Bureau#344]
The pioneer1 probe lists an internal geiger experiment in the VAB, but it can't be run during flight.
It's not available from the right click menu nor is it run by [x] science for example.

The standalone geiger experiment works fine and so do the build-in geigers of explorer probe.
compared the explorer configs vs. pioneer 1 and they look the same, so not sure what could be the problem...

running release 1.3.0 on KSP 1.3

**Comment by jsolson** [comment]
Works for me. Try without the [x]Science mod.
