### ISSUE TITLE
BUG: "BSA-0150-0120 - MOS-LA Large Structural Adapter" missing icon

### ISSUE THREAD

**Issue by Vollinger** [CobaltWolf/Bluedog-Design-Bureau#345]
switching to any of the three choices does nothing, the adapter keeps its default size

hopefully relevant logfile moonspeak:
`[WRN 02:34:02.744] Warning on PartSubtype 0.9375m on module ModuleB9PartSwitch (moduleID='meshSwitch') on part bluedog.MOL.Adapter.1875.15(Clone): No transforms named Adapter_1875_9375 found
[WRN 02:34:02.744] Warning on PartSubtype 1.25m on module ModuleB9PartSwitch (moduleID='meshSwitch') on part bluedog.MOL.Adapter.1875.15(Clone): No transforms named Adapter_1875_125 found
[WRN 02:34:02.745] Warning on PartSubtype 1.5m on module ModuleB9PartSwitch (moduleID='meshSwitch') on part bluedog.MOL.Adapter.1875.15(Clone): No transforms named Adapter_1875_15 found`

**Comment by CobaltWolf** [comment]
Gotcha, must've messed that one up somehow. I'll make sure to fix it before the next release now that you've logged it. Thanks!

**Comment by Vollinger** [comment]
Howdy, thanks for looking into this!

Good news is, end cap switching works great and Gemini-related orbiting monstrosities are much more aesthetically pleasing.
Bad news: [The partconfig file uses the old, duplicate model,](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Gemini/bluedog_MOL_Adapter_1875_15.cfg#L9) instead of `bluedog_Adapter_1875_15`
Weird news: New model doesn't have the lil rotating thumbnail picture in parts list, but I'm not sure if that isn't just a local issue with my install.
![1875](https://user-images.githubusercontent.com/19734375/34305249-7601bcae-e73d-11e7-9626-bc8a16597e6b.png)

Merry Christmas!

**Comment by CobaltWolf** [comment]
Gah, @Vollinger could have sworn I replied to you! I did upload a fix for the filenames and stuff, not sure why it doesn't have a preview when you mouse over it though... will have to check the part in Unity (again!)
