### ISSUE TITLE
Wrong dependency for GeigerCounter

### ISSUE THREAD

**Issue by Phiido** [CobaltWolf/Bluedog-Design-Bureau#348]
When playing using Bluedog Design Bureau parts and Kerbin Enviromental Institute, KEI gives an error for wrong id for science GeigerCounter.
When looking in sciencedefs_compatibility.cfg in BDB folder, the Pioneer 1 part is checking for dependency from Dmagic science experiments.
Though it rather looks like compared to the rest of the modules that it should check for FASA.
When changing out dependency from Dmagic to FASA, KEI works again.
I'm using several other mods but not FASA.
As I'm not a programmer I'm not sure if it is as intended or mislabeled.

**Comment by jsolson** [comment]
Looks like a typo. Fixed.
