### ISSUE TITLE
Apollo Sub Sat unable to transmit

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#349]
New bluedog_Apollo_Subsatellite_Core
Has too high of EC consumption to transmit data packets.

	MODULE
	{
		name = ModuleDataTransmitter
		antennaType = DIRECT
		packetInterval = 1.44
		packetSize = 2
		packetResourceCost = 5.0
		requiredResource = ElectricCharge
		//DeployFxModules = 0
		antennaPower = 500000
		antennaCombinable = True
	}

PacketResourceCost of 5.0 likely the issue (Suggest 0.5??)
If attached to the Apollo SM when transmitting it will deplete most of the Apollo's reserve of EC.

Alternatively could be set to EVA retrieve.

**Comment by Pappystein** [comment]
Suggested Realnames.cfg data:

@PART[bluedog_Apollo_Subsatellite_Core]:AFTER[BlueDog_DB]
{
	@title = Apollo PFS subsatellite 
	@description = Apollo subsatellite to measure plasma and magnetic effects in Lunar orbit.   Launched from the Apollo Blk-II Service module in lunar orbit.  Can not be re-used without a Scientist present  

}

**Comment by jsolson** [comment]
Addressed in https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/7ada2bcfad376e81ea3935d55aa7551c7002a6f3
Probably should bump the cost on this part a lot. It gets a lot of science.

**Comment by CobaltWolf** [comment]
Strange, pretty sure I used the config for the Pioneer 1 as a basis? 

Isn't it just a gravioli experiment @jsolson ?

**Comment by debaker02** [comment]
I had the same issue when I tried the part.  It runs out of charge before it can transmit.

**Comment by CobaltWolf** [comment]
Hrmm, alright. We'll have to give it a transmitter like the Pioneer 1. Really low power/bandwidth. (Which I thought was already what it was using...)

**Comment by jsolson** [comment]
I fixed the Apollo sub sat already. It just needs sunlight.

Pioneer is a geiger counter experiment, and it's fine. It runs entirely on batteries so you have to remember to put it in hibernate while coasting.

**Comment by CobaltWolf** [comment]
@jsolson does that mean this issue can be closed?
