### ISSUE TITLE
J-2 New Upgrade

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#356]
Hey @jsolson , found some stats for a new upgrade to the J-2 engine from Eyes Turned Skywards. 
https://www.alternatehistory.com/wiki/doku.php?id=timelines:eyes_turned_skyward_spacecraft_and_launch_vehicle_technical_data#saturn_multibody_iip

The Multibody Interim Improvement Program's J-2A-2, which is a late-90s update to the design. 2% increase in thrust, 10 more ISP compared to the existing J-2-S upgrade. I'm not sure how to add upgrades, can you handle that?

**Comment by jsolson** [comment]
It needs to be positioned in the tech tree. It's with the J-2-S now.

**Comment by CobaltWolf** [comment]
Does it require the J-2S upgrade first?

Sent from my Windows 10 phone

**Comment by Pappystein** [comment]
Also not mentioned in ETS that I am aware but a RW proposal.  J-2T-400K  Toridal is slightly larger than standard J-2T-200/250K engine with 400kpf thrust...   I have a MM patch for it but can't figure out how to perform the pull request.

+PART[bluedog_J2_Toroidal]:AFTER[Bluedog_DB]
{
	
	@name = bluedog_HE2JT400K
	@title = Sarnus-HE2JT-400K "Tohces" Cryogenic Aerospike
	@description = A development of the Dnoces engine, the Tohces reuses a number of components such as turbopumps, while exchanging the bell-shaped thrust chamber for an annular aerospike. The result is a slightly lighter engine, with higher ISP. The 400K subvariant, is able to perform gimbaling using a hydraulic thrust structure.
	
		@MODEL
		{
			%scale = 1.150,1.100,1.150
		}
	@entryCost *= 1.5
	@cost *= 1.5
	@mass *= 1.2
	

	@MODULE[ModuleEngines*]
	{
		@maxThrust *= 2.0
		@atmosphereCurve
		{
			@key,0 = 0 447
			@key,1 = 1 385
		}
	}
	@MODULE[ModuleGimbal]
	{
		@gimbalRange = 4.5
	}
}

**Comment by Pappystein** [comment]
Followup on the J-2A-2 variant.  It sounds like it is a POST J-2S development of the standard bell engine.  So Cobalt I would say YES it comes after the J-2S (if that is any help)

**Comment by CobaltWolf** [comment]
@Pappystein the issue being that if they're in the same node, it's fine if the latter upgrade requires the former.

And generally I am not a fan of adding too many parts that are just rescaled meshes and such. If you can get it into the extras folder that's cool.
