### ISSUE TITLE
HLR-ZOID Solar Panel sun orientation 90 degrees off

### ISSUE THREAD

**Issue by icedown** [CobaltWolf/Bluedog-Design-Bureau#358]
The HLR-ZOID solar panel only generates EC when its end is pointed to the sun, not the panel itself.

Panels facing the sun
![screenshot48](https://user-images.githubusercontent.com/9828412/33302431-fabf2de6-d3c9-11e7-8130-e983b8bb9265.png)

End facing the sun
![screenshot49](https://user-images.githubusercontent.com/9828412/33302441-14d63238-d3ca-11e7-9280-0f39495255b8.png)

**Comment by CobaltWolf** [comment]
@icedown why is it so tiny? xD

Also, I *cannot* figure out what it wrong with it. I've rotated the sunCatcher transform every which way and it refuses to change the orientation that the part receives sunlight from. Will experiment more tonight hopefully,

**Comment by CobaltWolf** [comment]
Fuck this part. Just saying.
