### ISSUE TITLE
Apollo Block V Solar Panel default attachment point incorrect

### ISSUE THREAD

**Issue by icedown** [CobaltWolf/Bluedog-Design-Bureau#359]
This may not be a bug and as intended.

The default attachment point on the Block V SP appears to be set to the wrong side.
I think it is off because I would expect it to start flat and extend out but I may not be correct on it's intended use.

Default attachment
![screenshot52](https://user-images.githubusercontent.com/9828412/33302533-d1d0a332-d3ca-11e7-8db6-7502f2c07084.png)
![screenshot51](https://user-images.githubusercontent.com/9828412/33302544-e194e88c-d3ca-11e7-9c03-5ba5f9c1ee5b.png)

**Comment by CobaltWolf** [comment]
That is intended behavior. The panel is supposed to stick down from the bottom of the service module and then swing out when deployed. 
https://www.alternatehistory.com/wiki/lib/exe/fetch.php?w=750&tok=430418&media=timelines:blockv_ortho.png
