### ISSUE TITLE
Add BDB tab for VAB / SPH part menus

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#36]

**Comment by CobaltWolf** [comment]
I just added this to the repo, I need confirmation that it actually works.

**Comment by jsolson** [comment]
Is this the manufacturer tab? It displays correctly when selected. Just a black bar when not. Coatl Aerospace is the same way. Bloeting Aerospace appears to work fine.

**Comment by CobaltWolf** [comment]
no, a custom tab like what MOLE or USI have. Tabs in the main VAB menu. I accidentally added it, it works if you have Angel-125's mods installed. Without them nothing happens. I'm not going to worry about it for now. :P
