### ISSUE TITLE
1.4.0 Release S1 Messed Up

### ISSUE THREAD

**Issue by debaker02** [CobaltWolf/Bluedog-Design-Bureau#363]
Hi,

I pulled the 1.4.0 release and the S1 is missing the bottom textures, has see through spots when viewed from the bottom, and the attachment points are high on top/bottom.  It is also the case on the current head of the master.  

I think it was the last commit.

**Comment by CobaltWolf** [comment]
Alright, thanks for the heads up. Serves me right for trying to push out a release while exhausted and not properly testing it...
