### ISSUE TITLE
bluedog_Pioneer6_BottomAntenna description (mildly) borked.

### ISSUE THREAD

**Issue by jmrd98** [CobaltWolf/Bluedog-Design-Bureau#365]
This one is quite minor, but I noted it when trawling configs for the RT patches. The description for this part abruptly cuts off.

[See link to line for reference.](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/c68ac3d0322590b103f2224bae2c4f3e2c454b5b/Gamedata/Bluedog_DB/Parts/ProbeExpansion/bluedog_Pioneer6_BottomAntenna.cfg#L20)

**Comment by CobaltWolf** [comment]
Thank Komodo!
