### ISSUE TITLE
Saturn 1F Tankage and Atlas Adapter B9 fix

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#368]
Need some sort of override to make the Saturn 1F tankage and Atlas 1.25m adapter work with B9 fuel switching, they currently do not because the existing config excludes them.

@jsolson are you still around? Can you fix this?

**Comment by jsolson** [comment]
Yeah... I'll look into it. Worst case we just put the fuel switch module
directly in the config.

**Comment by CobaltWolf** [comment]
Gah, this new phone is killing me. I don't feel like I get any notification emails.
