### ISSUE TITLE
QUESTION: Real Solar System Compatibility

### ISSUE THREAD

**Issue by HooHungLow** [CobaltWolf/Bluedog-Design-Bureau#372]
I've recently installed the RSS mod which is working fine, and BDB is not giving me any issues. The only problem I am having now is the BDB rockets lack the real-world DeltaV needed to get to orbit. Are there any CFG's available or anything else I can do to get the stock performance scaled up to 1:1?

**Comment by CobaltWolf** [comment]
@HooHungLow Hey man, there's a couple things you can do. Personally, I use Sigma Dimensions to rescale Stock Size Real Solar System to 2.5x, which makes the BDB rockets just about perfectly balanced. Alternatively, you could try SMURFF but I don't know much about that.

**Comment by HooHungLow** [comment]
Thanks for the advice, I will definitely try that out.

**Comment by HooHungLow** [comment]
Ok, so I tried out SRSS at 2.5x and I couldn't get it to scale up for some reason, I guess I should have just stuck with RSS and used Sigma to scale down. Instead I ended up just scaling the stock solar system to 2.5x, including atmosphere. I noticed the vanguard rocket (which was my test vehicle) didn't have enought DeltaV to make it into orbit. So I scaled down from 2.5 to 2.0x and 1.5x atmosphere and that seems to be perfect. The vanguard now has just enough DeltaV to make it into LEO.

**Comment by CobaltWolf** [comment]
I really don't know how well the Vanguard is balanced, the rockets that have gotten a lot of work have been mostly the ones for manned stuff. With that said, please let me know if there's anything that you think needs to be changed. :)

**Comment by HooHungLow** [comment]
Thanks for the info. I started to realize that yesterday, I guess my default shouldn't be a rocket that never actually made it off the pad in real life anyway. I've been using gravity turn to help optimize things and it seems to be working combined with SMURFF, which basically lowers the dry mass of the fuel tanks. It seems to be a nice balance, I am finding the sweet spot is around 5k DeltaV with a 2x scale. The Vanguard is just a tad short, I can get it all the way to a circularization Burn and its lacking about 20% of the fuel needed.

**Comment by CobaltWolf** [comment]
@jsolson anything we can do to buff Vanguard? Buffing the AJ-10 maybe but idk...

**Comment by CobaltWolf** [comment]
Actually, @HooHungLow are you including the SRB? I believe it's called the Aquilae. Vanguard's orbital version was a 3 stage rocket.

**Comment by HooHungLow** [comment]
I wasn't actually sure about the real life third stage but I actually have tried it with the Aquilae SRB as the final booster, the only issue is the second stage doesn't have enough TWR in that scenario. Basically the second stage is under powered with any additional stages, with the SRB I'm showing .85 TWR after stage 1 sep. 

Although the first stage is great IMO.

**Comment by CobaltWolf** [comment]
Well you don't need a positive TWR on your upper stage, right?

**Comment by jsolson** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/wiki/Launch-Vehicle-Technical-Data

Vanguard is 3 stage above 1X. It's payload to orbit is only 100 kg at 3X - 10 times more than real life.

@HooHungLow SMURFF is disabled in this mod. We have an internal script that does what SMURFF does but is designed specifically for these parts. It will auto detect your rescale and adjust accordingly if it's a Sigma based rescale.

**Comment by HooHungLow** [comment]
@CobaltWolf Thats true regarding the TWR, I am not doing a great job of explaining what I mean, basically in the SRB 3rd stage scenario, after 1st stage sep I always felt like the 2nd stage was under powered until it made it out of the atmosphere, by which time it burned off a lot of fuel trying to bring the AP high enough, by the time I hit circularization burn she didn't have enough fuel. But I have to try it again and see if I forgot something. 

I will try it again with the SRB 3rd stage and report back, I am using the TV3 probe as the only payload so i don't think it's a weight issue. Perhaps if you give it a go in your 2.5x scale system you would get an Idea of what I am talking about. I am by no means an expert. 

@jsolson regarding SMURFF, that is good to know, It runs in the background anyway and I never looked deep enough in the cfg files to see that you guys have your own script.

**Comment by HooHungLow** [comment]
Just on a side note, are the fairings supposed to be plain grey? I noticed in the manual they have textures but for me they are all the same, I use CKAN for installation.

**Comment by HooHungLow** [comment]
Ok, so I did a full test with the correct 3 stages, 1st stage is good, 2nd stage makes it to about 58km and then starts to dip until it crashes. I've attached screenshots below with all of the details I could get. Maybe this will help. 

![vessel info](https://user-images.githubusercontent.com/28848369/35357508-c767a4ac-0121-11e8-96a6-fe180eee1de6.PNG)
![craft](https://user-images.githubusercontent.com/28848369/35357509-c77803c4-0121-11e8-85e3-536d200f8568.PNG)
![deltav stats](https://user-images.githubusercontent.com/28848369/35357510-c786f988-0121-11e8-8d88-4b4948341342.PNG)
![gravity turn stats](https://user-images.githubusercontent.com/28848369/35357511-c794c234-0121-11e8-958c-1cca2ca4f686.PNG)
![launch map](https://user-images.githubusercontent.com/28848369/35357512-c7a99358-0121-11e8-989c-ceb91a2ea58d.PNG)

**Comment by jsolson** [comment]
I don't know what a TV3 probe is, but it looks like you have discovered that more is less.

The third stage solid motor looks like a tweakscaled up Star 20. Just use the normal size Star 20 or Star 10 and put it inside the fairing with the probe.

The second stage has an unnecessary extension. Just use the long 100 tank. Your second stage engine can't push all that weight upwards as you're finding out.

If you find yourself just barely not making orbit, lower the destination height to just above the top of the atmosphere. The margins are very tight on this rocket. Gravity turn may not be able to deal with the solid motor stages. The flight plan for this rocket is stages 1 and 2 push your apoapsis up to orbital height, then coast and the solid stage circularizes - to be authentic you don't circularize, just burn it out and hope for the best. These early birds ended up in all kinds of crazy orbits. Consider a 100x2000km orbit a success. 

Hint: Right click on the first stage engine and set Shroud to Disabled. You'll get a cleaner liftoff (the shroud clips a little on the launch clamp).

**Comment by HooHungLow** [comment]
I meant Vanguard TV3 Probe, "Vanguard 1", "Flopnik", you guys call it "Narly". 

Thanks for helping me with this. I realize now the manual textures have since changed from the current parts and that threw me off during assembly, also I see now the Star20 was scaled up, I couldnt figure out if it was supposed to be under the fairing or not in the manual. 

I'll try it out now with your changes.

**Comment by jsolson** [comment]
I can see how that would be confusing, the manual is out of date in a few places. You should be fine with the Narly probe, it's well within weight limits.

**Comment by HooHungLow** [comment]
What about the fairings? I noticed they are all grey but in the manual they are textured. Also, Vanguard has a black fairing IRL.

**Comment by jsolson** [comment]
Mine are grey.

**Comment by HooHungLow** [comment]
Ok, is there any way to change that? Not really that important, but I am just curious. Also, is there a way to DM? I didn't want to flood the issue forum with unimportant questions.

**Comment by jsolson** [comment]
You would have to edit the texture, which is probably shared with something
else.

Asking questions here is fine.

**Comment by HooHungLow** [comment]
Not sure if its a mod issue on my part but the Narly probe has a "select tracking body" in the menu for each solar panel. It also mentions absolute exposure or relative exposure.

**Comment by jsolson** [comment]
It's not a mod, I see it too. Not sure what that stuff is for.

**Comment by CobaltWolf** [comment]
I have zero idea what that does. On that subject @jsolson , Nertea said we could include his curved solar panel module if we'd like. Would be really useful for Pioneer 6, Vanguard, Explorer 7... there may have been one or two more parts that would benefit significantly, can't remember which. I know the Pioneer 6 parts have their right click menus go off the edge of the screen.

@HooHungLow fairings are a complete crapshoot right now. On the texture they are the same color as the white painted parts of the rockets, but in game they appear darker. I have no idea why. The next KSP update should have some great stuff for fairings - better mapping, texture switching - and I'm planning on putting some work into fairings then. 😄 

Making a new fairing texture would be easy - I actually think there is a black fairing already, used by Titan. In Bluedog_DB/Parts/EarlyRockets/, open the bluedog_625mFairing.cfg and replace line 53 with: 	TextureURL = Bluedog_DB/Parts/Aero/bluedog_Titanfairing

**Comment by jsolson** [comment]
> Not sure if its a mod issue on my part but the Narly probe has a "select tracking body" in the menu for each solar panel. It also mentions absolute exposure or relative exposure.

It comes from Kopernicus. See Gamedata\KopernicusConfig\SolarPanels.cfg
