### ISSUE TITLE
BUG: AJ-260 General issues

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#373]
Posted as a way to track issue.

- [x] AJ-260 Inline short has only one Vernier effect (needs 2)
- [x] AJ-260 Long Inline is MIA (Reported by JSO)
- [x] Check top rims
- [ ] Angled upper rim needs texturing
- [ ] Equipment packages on flared mounts need to be touched up.
- [x] Thrust curves

**Comment by jsolson** [comment]
There's obvious daylight at the top nodes

**Comment by CobaltWolf** [comment]
Gotcha, I know what that would be.
