### ISSUE TITLE
BUG: Saturn IVC twin engine mount appears to cause intermittent failure at seperation

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#375]
Tested with both the Saturn IB Inter-stage adapter and the Saturn II inter-stage adapter.

9 tests with a 33% failure rate.
Failure mode = failure to separate  OR S-IVC engine mount explodes

Given some tests the rocket was turning when separation happened and some it was not...  I believe the collider is now too small of a tolerance to allow the inter-stage to separate if the discarded stage and the separating rocket have any sort of torque applied (like when performing a gravity turn.)   Dose the Colider cover the Helium spherical tanks on the mount?

I did not have this issue with the earlier version (1st release) of this mount (not talking the hacked MM file version)

**Comment by jsolson** [comment]
You beat me to it. I can confirm. The S-IVC engine mount with the straight interstage goes splody on separation.

**Comment by CobaltWolf** [comment]
y tho

**Comment by jsolson** [comment]
It may be the collider on the tandem J2's catching on the interstage rather than the mount. Check both.

**Comment by CobaltWolf** [comment]
@jsolson I was thinking the same thing. 😄  J-2s might need their colliders tightened up a bit.

**Comment by CobaltWolf** [comment]
@Pappystein @jsolson it was just the colliders glitching out. The 'base' (wider part of the angled collider that extends down to the engines) on the engine mount was too wide and was intersecting the interstage.
