### ISSUE TITLE
NEW PARTS: Large Diameter Core Titan / Titan Barbarian - 3.125m Launch Vehicle

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#377]
PARTS:
- [x] 3.125m First stage 1x engine mount
- [x] 3.125m First stage 2x engine mount
- [x] 3.125m First stage 3x engine mount
- [x] 3.125m First stage 4x low profile mount
- [x] 3.125m First stage 4x engine mount
- [x] 3.125m First stage 5x engine mount
- [x] 3.125 First stage 9x engine mount
- [x] 3.125m First stage LFO tank - Long
- [x] 3.125m First stage LFO tank - Medium
- [x] 3.125m Straight Interstage (compatible with S-IV)
- [x] 3.125m Short Interstage
- [x] 3.125m Second Stage 1x engine mount
- [x] 3.125m Second Stage 2x engine mount
- [x] 3.125m Second Stage 4x engine mount
- [x] 3.125m Second Stage 7x engine mount
- [x] 3.125m Second stage LFO tank - Medium
- [x] 3.125m Second stage LFO tank - Short
- [x] 3.125m-1.875m Interstage
- [x] 3.125m stack decoupler
- [x] 3.125m fairing base
- [x] 3.125m avionics core
- [x] 3.125m > 2.5m adapter
- [x] 3.75m > 3.125m adapter
- [x] 3.125m nose cone
- [x] 3.125M Stage and a half tank
- [x] 3.125 stage and a half skirt

EXTRA TASKS:

**Comment by CobaltWolf** [comment]
WIP screenshot for the tanks https://i.imgur.com/7EJLhdm.png I'm not sure what I meant by the 'short' tank for the second stage, any guesses?

**Comment by jsolson** [comment]
You used a medium and a short tank on the Titan II second stage model.

**Comment by CobaltWolf** [comment]
I suppose, but my model that I made... uhm, the day after the election actually. I skipped class and day drinked in my apartment and modeled it. And in the Maya scene, there is no model for a short upper stage tank. :P

**Comment by jmrd98** [comment]
Should that tank have an ethanol fueled tank config easter egg in honor of that?

**Comment by CobaltWolf** [comment]
We have a couple ways we can handle this. I can try and just polish up the parts as they exist right now (I think the biggest thing is making sure they all have proper endcaps) and include what we have in the release, with the understanding that the rocket will finish being fleshed out in the Titan update.

OR

We can remove the folder from the release so that people don't ask us why there's a new partial rocket in the mod.

@jsolson thoughts?

**Comment by jsolson** [comment]
Leave it out and leave to door open for changes.

**Comment by CobaltWolf** [comment]
Sounds good

**Comment by longlong2002** [comment]
> Sounds good

all LDC part is finished
