### ISSUE TITLE
NEW PARTS: Saturn MLV - Upgrades and additions to the Saturn parts

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#379]
PARTS:
- [x] S-II-7X Engine Mount
- [ ] 5.625m extension tank for S-1C
- [ ] 5.625m extension tank for S-II
- [ ] 3.75m Nose Cone for Multibody and AJ-260
- [ ] Extra large (3.75m) radial decoupler - make size agnostic unlike Titan’s
- [ ] 5.625m Instrument Unit
- [ ] 4x Engine Mount for S-1B / E-1

EXTRA TASKS:
- [ ] Clean up Saturn 1B engine mount

**Comment by Pappystein** [comment]
Possible suggestion (would save balancing new parts a bit.)  Copy and Cut the existing S-IC and S-II stages and just insert additional space as needed.   

Reasoning is artistically it would look "more correct" with the heavy structural parts at the top not in the middle. The texture files would need to be updated in either way...

Also I am unsure of how this would be delineated but given the E-1 came before the S-IB I would hazard that is where the missing S-IA stage went (and or it was S-I and the original big fin 8 engine stage was S-IA but they dropped the A after S-I was fully canceled.    Don't know there Pure supposition.

**Comment by CobaltWolf** [comment]
There was no "A" Saturns once the official naming scheme came into being (as in, Saturn C5 was Saturn V). Just "B". The Saturn S1 stage was supposed to be 4 E-1s but the engine was cancelled and 8 H-1s used instead, being based more or less on existing and proven hardware. That's all there really is to it. 

RE: tankages there's no easy solution to it owing to the way I built them originally... idk.
