### ISSUE TITLE
REVAMP: Juno / Chryslus

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#381]
**REVAMP:**

Tank texture sheet:
- [x] Juno First Stage Tank 1
- [x] Juno First Stage Tank 2
- [ ] Juno Engine Mount
- [x] Juno Adapter 1 (probably doesn't need anything since it gets textures from other parts)
- [ ] Juno Adapter 2 (probably doesn't need anything since it gets textures from other parts)
- [ ] Juno 2nd Stage Fuel Tank
- [x] Juno 3rd Stage Fuel Tank

Engines texture sheet:
- [ ] First stage engine
- [ ] First stage vernier
- [ ] 2nd stage engine
- [ ] 3rd stage engine
- [ ] RCS boom

**Comment by raveloda** [comment]
yay!
