### ISSUE TITLE
REVAMP: Delta II / Daleth II

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#382]
**REVAMP:** 
First stage:
- [x] Engine
- [x] Tank 1
- [x] Tank 2
- [x] GEM-40
- [x] GEM-40-Inline
- [x] GEM-46
- [x] GEM-60
- [x] GEM-60XL

Second stage:
- [x] Interstage
- [x] AJ-10
- [x] Lower Fuel Tank
- [x] Long Fuel Tank
- [x] Fairing Base Fuel Tank
- [x] Short Fuel Tank
- [x] Delta-III Fuel Tank (made because of the leftover space on the Delta K sheet)

CLEANUP:
- [x] Ribs on Delta III tank need to be updated to new color
- [x] Intertank ribs on Delta II core tanks
- [x] End caps/rims on Delta II core tanks need touchups
- [ ] GEMs need longer struts, make them switchable because that's how we roll

**Comment by CobaltWolf** [comment]
@jsolson I'd like to convert the 'DeltaK short fuel tank' to be the avionics core it should be IRL (probably going to try and make it like an upgraded Agena core?). As a result, i'd like to try and spread the fuel that was previously in there around the other tanks. is that doable? Or will it break them completely.

**Comment by jsolson** [comment]
Daleth-K-1-30 Liquid Fuel Tank, the thin one that sits on top?

Works for me. It's 30 fuel, we can add 10 to the other three tanks. It will max them out volume-wise but we can do it. Do what with the core? Bump the ec to 2 or 300?

**Comment by CobaltWolf** [comment]
I'm not sure. It would be another 0.9375m probe core though, like the Agena one, but the Delta K essentially replaced the Agena's lower end payloads (the upper end being taken by Atlas-Centaur) so I feel like it should be more advanced in some way. More powerful reaction wheels maybe, maybe more efficient on ec usage... idk.

**Comment by jsolson** [comment]
In having second thoughts as to the wisdom of this. The short tank is a
useful standalone part. I've used it building probes.

Perhaps we could put the probe core in the fairing part or the butt (engine
mount) tank. Or something else.

In the past if I felt the need for brains on the Delta K I stuck the Agena
core up top under the decoupler.

**Comment by CobaltWolf** [comment]
b-but I already remodeled the tank T.T

It's find, it just has a cross bar instead of a tank but on the top/bottom.

**Comment by jsolson** [comment]
Go with the avionics core.

**Comment by CobaltWolf** [comment]
ok

**Comment by jsolson** [comment]
The stock plume for the RS-27A main engine is way off.

The struts on the new GEM 40 models don't reach the fuselage when used with the BDB mini decoupler.

Regarding the extra fuel: The Delta III should have the same amount of fuel as the Delta II so that tank will need an upgrade as well.

**Comment by CobaltWolf** [comment]
1) thanks
2) I can lengthen them, but I intended it to be that you use the fine translation gizmo to butt them up against the ribs on the engine.
3) Alright, can we justify that without a model change?

**Comment by jsolson** [comment]
I've never messed with the old style effects. Are the first three parameters here the X Y Z? Or is this something you have to fix?
`fx_exhaustFlame_blue = 0.0, -5.74338, 0.0, 0.0, 1.0, 0.0, running`

grr... Somebody tried to get one by the accounting department and typed over a formula in the spreadsheet. The lower tank should be 2300, not 2700, and the upper tank 1700, not 1900. (The previous numbers were 2200 and 1500).

It will be overstuffing a bit but we'll just put the same fuel amount for the upper main tank into the Delta III tank. Don't change the model if the proportions are correct.

How about we just move the surface attach node for the GEM's so they don't need to be translated. Could you either do that, or post a screenshot of what it's supposed to look like?

**Comment by CobaltWolf** [comment]
Hrmm. I think we could. Here's a .craft, need to convert the extension. Sorry about the spreadsheet, must've been my fault.

The fx should be moveable... you can edit line fxOffset = 0, 0, 1.2 in the ModuleEngines.

[Delta 2.txt](https://github.com/CobaltWolf/Bluedog-Design-Bureau/files/2036885/Delta.2.txt)

**Comment by jsolson** [comment]
Got the RS27A plume fixed. Getting a little OT here but how do we fix this massive plume for the LO engine?

![screenshot0](https://user-images.githubusercontent.com/16825376/40523328-15622e7c-5fa3-11e8-8f51-5306fdc750c4.png)

**Comment by CobaltWolf** [comment]
I don't remember. I am not sure how solvable it is.

**Comment by CobaltWolf** [comment]
Reminder to myself to make it so the verniers only rotate on one axis (they are only for roll and wouldn't have a second axis like the Atlas ones... which, btw, I do have diagrams showing both rotation axes)
