### ISSUE TITLE
BUG: LR-101 vernier fuel consumption

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#387]

**Comment by SlainteMaith** [comment]
*Note remember not to forget to use the FAR fix.

**Comment by CobaltWolf** [comment]
Wait, the fuel consumption issue only occurs with FAR?

**Comment by SlainteMaith** [comment]
That is correct--but only with those engines.  The deprecated version doesn't have the same problem.

**Comment by MikeOnTea** [comment]
@SlainteMaith any details about the higher consumption? Is the burn time of your rocket's engines really reduced when you install FAR? That sounds really weird.

**Comment by CobaltWolf** [comment]
@MikeOnTea I assume you're Mike' on the forum?

No, burn time didn't decrease. He just didn't make orbit. So there is just an excess of drag or something.

**Comment by Pappystein** [comment]
I was trying to post this in forum when they crashed 404&502 style.  

Likely cause is interfearance drag + parasitic drag that was being covered up on the original LR-101 by the Aerodynamic shield.   Cobalt, as much as it pains me, if you leave the old LR-101s in the main game I can give you a MM file that will, upon detecting FAR depreciate the new LR-101s and use the old ones and if FAR not found it would use the much nicer looking LR-101s.
