### ISSUE TITLE
BUG: Engine upgrade name mismatch

### ISSUE THREAD

**Issue by raveloda** [CobaltWolf/Bluedog-Design-Bureau#389]
The Advanced Rocketry engine upgrade node is still call "Muo" even though the Atlas changed to "Bossart." Why did Atlas change anyway?

**Comment by CobaltWolf** [comment]
Are you sure? I just checked and they were changed. Is this in an existing career save?

**Comment by jsolson** [comment]
Just description in the part upgrades was changed. The part upgrade names are the same for the old and new parts, sort of like having two parts with the same name. KSP is confused.

**Comment by jsolson** [comment]
~~I'm not seeing the upgrade applied to the new engine part. The description says it it's applied, but the thrust is the same.~~
NM, now I see it. This might be somewhat savebreaking.

**Comment by raveloda** [comment]
Yes, it is referenced in the title, although since the old engine is still in the mod it is mentioned in the list of affected parts. No big deal there since the title says its deprecated. I would've fixed it for you but I cannot find the file for your part upgrades anywhere. Only the Early Rockets one, which does not include Atlas engines

**Comment by jsolson** [comment]
I already fixed it. I think the weirdness I saw was from the MM cache needing a refresh. The part upgrades are at the bottom of the part file. They were copied from the depreciated part to the new part, but with a syntax error. I removed it from the old part and fixed the error (and title) on the new part.

**Comment by CobaltWolf** [comment]
@jsolson is this safe to close?

**Comment by jsolson** [comment]
I suppose
