### ISSUE TITLE
Probe Core balance

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#39]
Probe cores need some differentiation in terms of balance, to make them feel distinct. Each core should be looked at in regards to:
-Mass
-Cost
-EC units
-Other resource storage
-Experiments onboard
-SAS

Cores to be looked at:
-Pioneer 1
-Pioneer 4
-Asterix
-Diapason
-Ranger core
-Explorer 7 (Suomi)
-Venera/Pioneer (Pog)

Make sure their VAB descriptions are edited appropriately.

**Comment by CobaltWolf** [comment]
@jsolson I know you have a lot on your plate, I'll try and pull someone else on to this.

**Comment by CobaltWolf** [comment]
**Ideas:**
Ranger core: Very small amount of EC, and instead contains monopropellant for the engine. You'd have to attach the Ranger batteries to get power. @VenomousRequiem we need to move on that engine and possibly another part, I think there's room for two new parts on that texture sheet.

Pioneer 1: No SAS? Possibly remove from Explorer 1 as well. Hard to differentiate from Pioneer 4 except for the differing experiment.

Pioneer 4: No SAS? Possibly remove from Explorer 1 as well. Hard to differentiate from Pioneer 1 except for the differing experiment.

Asterix: Biggest of the 'baby probes'. Heavier, more electric charge. No science equipment. Makes a good early comms satellite body.

Diapason: Once the Ranger core is changed, this can slot in as a sort of 'normal' probe core for early game, with a decent amount of charge.

**Comment by jsolson** [comment]
They should all have at least an attitude hold SAS.

**Comment by CobaltWolf** [comment]
What setting in the cfg do you use for that?

**Comment by jsolson** [comment]
MODULE
{
name = ModuleSAS
SASServiceLevel = 3
}

SASServiceLevel can be 0 to 3. I'm not certain what exactly you get in each level. 0 is minimum, 3 is everything. Take a look at Coatl's star trackers. All they do is add this. They're neat parts too.

**Comment by CobaltWolf** [comment]
made some changes. Going to merge them tonight.

**Comment by CobaltWolf** [comment]
Probe balance needs to be looked at more, especially with the new probes that will be added.
