### ISSUE TITLE
LEM IVA & NFProps

### ISSUE THREAD

**Issue by 7ranceaddic7** [CobaltWolf/Bluedog-Design-Bureau#390]
Has this always been a requirement?  Or, is this new?

If yes, then CKAN is requiring.

If no, then CKAN is not requiring NFProps on the update.

**Comment by CobaltWolf** [comment]
NF Props are required for the new LEM IVA that was made last week. We decided to make it a dependency because we want future IVAs (Skylab and MOL, specifically) to be able to use the props since there's a lot of good stuff.

**Comment by 7ranceaddic7** [comment]
I discovered that CKAN forces you to remove BDB; then reinstall with dependencies.

**Comment by CobaltWolf** [comment]
weird
