### ISSUE TITLE
Bossart-Inon Fairing issue

### ISSUE THREAD

**Issue by TJCizadlo** [CobaltWolf/Bluedog-Design-Bureau#391]
The 1.875m Bossart Fairing does not fit under the Inon ACS Avionics and Control System probe core with straight fairings. The prior 1.875m Muo fairings did. The Inon Fairings do however, but this leaves BDB with two different 1.875m fairing parts.

**Comment by jsolson** [comment]
Isn't that by design? The centaur fairing is a hair wider at the base so it can be placed under the IU.

**Comment by CobaltWolf** [comment]
yes, that is intentional.
