### ISSUE TITLE
REQUEST: Little Joe I & II

### ISSUE THREAD

**Issue by HooHungLow** [CobaltWolf/Bluedog-Design-Bureau#396]
More of a request for future releases: It would be great to have the Little Joe I & II, Mercury and Apollo Rocket Boosters. https://en.wikipedia.org/wiki/Little_Joe_(rocket)
![800px-little_joe_on_launcher_at_wallops_island_-_gpn-2000-001883](https://user-images.githubusercontent.com/28848369/35785831-76596b8a-09f1-11e8-9bf5-0c35c264dc25.jpg)
![apollo-_little_joe_ii_liftoff_ december_8 _1964 _-_cropped](https://user-images.githubusercontent.com/28848369/35785836-83b32050-09f1-11e8-9687-d884d1b758c8.jpg)

**Comment by CobaltWolf** [comment]
They're definitely cool, there's even a proposal for a satellite launcher consisting of a Minuteman 1 on top of a Little Joe 2.

https://i.imgur.com/gEjZAB6.jpg

Unfortunaetly, they're very minor compared to some of the cooler stuff I have planned. :)

**Comment by jsolson** [comment]
It's kind of a novelty part. When I was testing the Apollo LES I used a tweakscaled Diamont solid and some stock fins. Worked pretty well.

**Comment by HooHungLow** [comment]
In it's historical iteration I agree, but for use in KSP it would be a great first stage for small-medium size payloads.
