### ISSUE TITLE
NEW PART: Skylab 0.9375m Radial Attachment Point

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#398]
Keep forgetting to make this damn thing. It won't take longer than an hour or two to make.

**Comment by CobaltWolf** [comment]
Need to fix the 45 degree rotation on this part.

**Comment by HooHungLow** [comment]
When are you planning on releasing the next update?

**Comment by CobaltWolf** [comment]
@HooHungLow uhhhh... eventually? idk. There's no release schedule but I'm not going to schedule a release for just one or two parts. I'm going to try to cut a new release sooner rather than later, though.
