### ISSUE TITLE
NEW PART: Atlas II Roll Control System

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#399]
Another easy part I've forgotten about, and one that is preventing the Atlas II, IIA, and IIAS from being made. This one should be pretty easy, and the model is already done.

**Comment by jsolson** [comment]
It works. Plenty of roll control authority.

The booster skirt got retro rockets. Is that accurate?

The booster itself should have them. You can read "Retarding Rockets" in the high res.
![Retarding Rockets](https://forum.nasaspaceflight.com/assets/16540.0/1118693.jpg)
https://forum.nasaspaceflight.com/index.php?topic=16540.0

**Comment by CobaltWolf** [comment]
the 'retarding rockets' from what I understand were only present on the missile versions. The booster skirt had retros, but they weren't much more than a bunch of model rocket motors. The IRL Atlas separation is way safer than in KSP, since the skirt rode on rails until it was pretty much completely clear. Can't really do that in KSP.
