### ISSUE TITLE
Interstages need to be fixed

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#4]
Interstages need to be fixed, seen Jso's post for info.
http://forum.kerbalspaceprogram.com/index.php?/topic/122020-wip-105-bluedog-design-bureau-v009a-prometheus-3112016/&page=50#comment-2396838

**Comment by jsolson** [comment]
Moving the nodes fixes the Delta K and Centaur straight interstage. The Centaur 2.5 meter interstage is also clipping on the Centaur engine mount.

**Comment by CobaltWolf** [comment]
Applied the fixes.
