### ISSUE TITLE
Gemini parts no longer tagged as "Leo" for part search

### ISSUE THREAD

**Issue by VenomousRequiem** [CobaltWolf/Bluedog-Design-Bureau#40]

**Comment by CobaltWolf** [comment]
Yes, the parts don't have the leo tag in the tags section. Also add 'trails', 'beale', 'bread' and 'loaf' to all the TRAILS parts.

**Comment by CobaltWolf** [comment]
@jsolson venom made the changes on her PC, how does she merge it? Does she have to start a branch, upload / replace them, then make a pull request?

**Comment by jmrd98** [comment]
From memory, if you edit a file via the site here, it auto-forks it for you, and offers either a straight PR on the spot, or you can make one later after testing and whatnot. No git install needed locally. (also, i'm not dead, I swear...)

**Comment by CobaltWolf** [comment]
@jmrd98 yeah I think she figured it out. There's a branch for the files now. Also, do I know you on the forums?

**Comment by jmrd98** [comment]
Doh, I forget this is my 'semi-work' account, this one is attached to komodo on the forums.

**Comment by CobaltWolf** [comment]
ahhhhh nice!
