### ISSUE TITLE
REVAMP: Solid Launch Vehicles

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#403]
Peacekeeper
- [x] Castor 120
- [x] Castor 30
- [x] SR-119
- [x] SR-120
- [x] Castor 30 XL
- [x] Decoupler
- [x] Fairing Base

Liquid uppers:
- [x] HAPS
- [x] Super HAPS
- [x] PBV
- [x] OAM

Solid Uppers:
- [x] Alcyone
- [x] STAR-20
- [x] STAR-37BV
- [x] STAR-37FMV
- [x] STAR-48BV
- [x] Burner 2 kit (guidance and rcs for any 0.625m stage)

Scout:
- [x] Algol Inline
- [x] Algol Radial
- [x] Castor Inline
- [x] Castor Radial
- [x] Algol Fin
- [x] Antares Advanced
- [x] Antares Basic
- [x] Scout texture pass - same updates that were made to the Peacekeeper stuff

Perfectrons:
- [x] Retrotron
- [x] Perfectron
- [x] Lateraltron

**Comment by jsolson** [comment]
Peacekeeper stage three to four interstage is wrong. Should be short and full height, not 3/4 and full height. Though not a real option, short, 3/4 and full height would work (short can not accommodate Star 37FM, full is overkill). In the real Minotaur what is the short bottom extension on the present version is always present as the stage three to four interstage, regardless of what if any fourth stage is used.

**Comment by longlong2002** [comment]
why no Castor-2 boosters
