### ISSUE TITLE
NEW PART: E-1 Rocket Engine - H-1, but bigger. 

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#405]
New model already made, just need to unwrap it and get it textured. Have a pretty good feeling about it.

**Comment by CobaltWolf** [comment]
@jsolson this part is mostly done. Want to throw together some stats for it so I can plug them into the cfg for the beta release? 😄

**Comment by jsolson** [comment]
TechRequired = dunno
mass = 1.6
cost = 3520

maxThrust = 471
Isp = 290 260

There's a slightly different set of numbers here with an upgrade.
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/BD_Extras%20(No%20Warranty)/GameData/Bluedog_DB_Extras/Pafftek/Saturn%20INT%20series%20Parts/E1_W_Upgrade.cfg

**Comment by CobaltWolf** [comment]
Oh, the description is done already... schweet.

**Comment by CobaltWolf** [comment]
@jsolson Hey, I saw this just now. In Kolyma's Shadow (alt-history by the guy who did the art for Eyes, the Eyes authors consulted on the rocket designs) they have an E-1A because that is used as the main lifter engine by the US. It would have 562.5 kN in KSP (vs the current's 471) and 310s of ISP (vs 290s current). The round numbers for the ISPs make me think they are estimates.

This jives with the general impression I've gotten that the published numbers for the E-1 were fairly conservative. The few documents I have on it make references to performance increases, either via upthrusting or increasing the ISP or both. They seemed to think that there was a lot of growth for it. 

By the way, if you ever saw a 2.5m part family labeled 'Minerva' in the old roadmap, this is what those were. 

https://www.alternatehistory.com/wiki/doku.php?id=timelines:kolyma_vehicles

**Comment by jsolson** [comment]
20 seconds of Isp is a hell of an upgrade.

**Comment by CobaltWolf** [comment]
Where did we land on this? I still am in favor of including it. It's not that different than the type of improvements we've seen on some of the other engine families, and yeah it is from an alt history but it was judged plausible by the people I spoke to.
