### ISSUE TITLE
NEW PART: Stock Wet Workshop

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#406]
Two experimental new parts using B9's inflight fuel switching need testing.

Hokulani-WWS Wet Workshop
Hokulani-LWWS Light Wet Workshop

The WWS is the OWS model with wet workshop capability added. The LWWS is a lighter version using the S-IVB tank model, and stock 2.5m lab specs. Both may be launched full of fuel (cryo or LFO), then switched to Lab once in flight. This is one way, you may not switch back to fuel in flight. Remaining fuel is dumped on the switch, but a warning will be given first.

Limitations:
~~I don't think you can change crew capacity on the fly, so you can put crew inside while fuel is on board. Don't cheat.~~ Thanks Nertea!

Crew may not board in the VAB, even when starting in Lab configuration.

While in a fuel configuration, the lab will be set to zero data storage, (hopefully) preventing lab usage while it's a fuel tank.

**Comment by TJCizadlo** [comment]
Works well so far.

**Comment by TJCizadlo** [comment]
If we had to keep only one of the two, I'd suggest that the LWWS be the one that is kept. I may pull the other one out of my install.

**Comment by jsolson** [comment]
Because of the weight? I think I accidentally hit the sweet spot there.

I'm pondering what to do with the WWS (I'd prefer not to make it functionally identical to the LWWS). Bare bones it can just do a TLI and Mun injection, but boiloff makes that iffy.

**Comment by CobaltWolf** [comment]
In Baxter's _Voyage_,  Moonlab was a wet workshop because it did the TLI burn. Once they got to Lunar Orbit they used almost all the fuel of an Apollo (docked to the reinforced axial docking port) to brake it into an elliptical orbit. Each subsequent mission lowered the orbit using the excess deltaV from the CSM. So, there's that to think about.

**Comment by jsolson** [comment]
I have a stranded crew with a WWS/Apollo Blk II sitting in a 100x4000km orbit of the Mun. It took every drop of fuel and most of the mono propellant to get there. The WWS had fuel left to contribute to braking though. Not sure if the CSM can do it by itself. I doubt it can do it while retaining enough fuel to return without rescue. It might be possible to do a higher dV TLI cutting the transit time and avoiding some boiloff.

The situation is an excellent exercise in real rocket science.

**Comment by jsolson** [comment]
I've reduced the weight (and nerfed the lab) on the WWS so with either the Spacelab adapter or the Fly-by module it's:
a. Capable of being launched to orbit with an S-IB stage. Or
b. Capable of doing a Mun TLI with a Block II CSM attached, and with the CSM able to do the capture burn without being stranded. Or
c. Capable of doing an Eve or Duna transfer burn with a Block III CSM attached.

I'm wondering if we should keep the LWWS.

**Comment by CobaltWolf** [comment]
I don't see any particular reason to have two of them, if I'm being honest. This is really neat stuff though John, you should mention it on the forum thread again to get more eyes on it.

**Comment by CobaltWolf** [comment]
What's going on with this? Are they all good to be kept in the next release?

**Comment by jsolson** [comment]
Yes. We're keeping all of them as-is.
