### ISSUE TITLE
NEW PARTS: Inline Titan SRBs

### ISSUE THREAD

**Issue by TJCizadlo** [CobaltWolf/Bluedog-Design-Bureau#407]
- [ ] Inline UA1202
- [ ] Inline SRMU (standard 2.5 seg)
- [ ] Inline short SRMUs (1 and .5 seg)

**Comment by CobaltWolf** [comment]
Alrighty. @jsolson , some updates on this:
- I wound up not making an inline SRMU (listed, poorly, in BDB as SRB_3Seg). The real life ones are more or less vertically aligned.
- I did however, add the pairs of hydraulic tanks visible on the outboard sides of the tanks. That actually pretty much was the missing link for these parts to look correct.
- Those new tanks *should* have mesh switching, but I was pretty tired and didn't get to test it. Mesh switching would make it possible to switch between them both being aligned together, and having them be on opposite sides.
- I added two new boosters, representing a full segment and the top 1/2 segment of these SRMUs. The white noticeably doesn't match up, the bastards. Need to fix. These new parts were fairly low effort to make, and allow you to build the Alliant EELV proposal (which obviously lost to the Delta IV and Atlas V), which would have been derived from these Titan IV solids. https://forum.nasaspaceflight.com/index.php?topic=19248.0 Very interesting stuff. You can think of the 1 segment and 1/2 segment as 1.875m versions to the Castor 120 and Castor 30, respectively.
- I am really unhappy with the final result of these SRMUs from a modeling/texturing perspective, I spent at least a good two hours trying to mess with them with very poor results. I am pretty tempted to just make a new 512px texture sheet and make them from scratch, which means the aft skirt would also be correct. I'd also be able to make bigger, rectangular block 3x sepratrons that more closely match the IRL ones, and would have more fuel than the existing ones.
- With all that said, these need some significant work balance wise. I had Pappy throw some numbers at me but they feel pretty incorrect. The TWR was way too high on both the new boosters, and the fuel loads seem suspect. Unfortunately I don't believe there are any published numbers for these proposed cut down versions. If things seem really screwy maybe that is an additional reason to remake the SRMUs from scratch.
- The 2 seg inline still needs to be added, but its niche is already maybe covered by the SRMU-1. From my POV, it makes sense for the SRMU parts to be a straight upgrade over the UA120X derived solids. In general for late game (ie stuff from the end of the 90s / early 2000s) part I'm kind of ok with them being straight upgrades and perhaps making older parts obsolete.

**Comment by TJCizadlo** [comment]
Full SRMU hydraulic tankage is offset 90 degrees from 'outboard' when placed radially.

**Comment by jsolson** [comment]
Can we rename the SMRU parts bluedog_Titan_SMRU_XYZ so I can tell them from the 1200 family. (Or USRM according to Wikipedia and Astronautix, which is it?) Didn't you want to move solids to another directory? Maybe bluedog_UA120X_XYZ and bluedog_SMRU_XYZ. Break stuff, we've already crossed that bridge.

I assume these are napkin proposals and I can guess on fuel and thrust numbers? 1/3 and 1/6th seem to make sense - or something like that, I guess the full one is really 2.5 segments?

**Comment by CobaltWolf** [comment]
SRMU is the correct name. That would be great honestly if you're willing to make the break. Go nuts with the numbers. No rush.

**Comment by longlong2002** [comment]
add UA1206

**Comment by CobaltWolf** [comment]
Need to roll back the changes to these SRBs before release

**Comment by CobaltWolf** [comment]
Ok, I'm also going to remove the 3 new SRMU parts, and revert the models + textures back to the last release.

**Comment by jsolson** [comment]
Keep the SMRU config, but rename it if you want. It's had fixes we want to keep.

**Comment by CobaltWolf** [comment]
I'll make them .txt files or something. I know, I don't want to lose them. I'll replace the models + textures with the olds ones and make sure everything still works.

**Comment by CobaltWolf** [comment]
Moved to #519
