### ISSUE TITLE
Missing Interior Overlay to Hokulani-FRM Foreign Research Module.

### ISSUE THREAD

**Issue by HaullyGames** [CobaltWolf/Bluedog-Design-Bureau#408]
![image](https://user-images.githubusercontent.com/34033348/36118718-0294bb20-100c-11e8-8b85-ca3538d0b325.png)

**Comment by CobaltWolf** [comment]
Indeed, it does not have an IVA. Most of the BDB parts do not, we don't have an IVA artist.
