### ISSUE TITLE
IMPROVEMENT: Add single version of Inon engine mount

### ISSUE THREAD

**Issue by TJCizadlo** [CobaltWolf/Bluedog-Design-Bureau#409]
engine caps/shrouds on the Inon engine mount do not currently work.

**Comment by CobaltWolf** [comment]
@TJCizadlo so, if i understand it, B9PartSwitch actually allows enabled/disabling nodes when you do mesh switching. That means that I'd be able to have them both be a single part, but hopefully would be able to have a bespoke / better quality version of the single mount than we had before? Idk.
