### ISSUE TITLE
ART: Atlas Adapter Tank

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#412]
The tank at the bottom where the sustainer goes. The graphic on the top is junk. Looks like it's the roll control thruster part of the sheet.

**Comment by CobaltWolf** [comment]
Oh dear. Sounds like I unwrapped it, forgot to texture it, then used that space for the RCS without knowing. Thanks for the heads up!

**Comment by HooHungLow** [comment]
Slightly off topic, but It would be great if we could get white Atlas V Booster tanks, the ones that go below centaur on the first stage, above the orange "MUO" tank. 

http://www.spaceflight101.net/uploads/6/4/0/6/6406961/1620413_orig.jpg

**Comment by CobaltWolf** [comment]
@HooHungLow something to keep in mind if I ever get around to remaking the Atlas V (it very much needs it). For a while someone else was going to take ownership of it and split it into another mod, they finished making a very very nice RD-180 model but I don't think they ever got past that. I have the model so in theory I could use it to start remaking the Atlas V, but it's just a lot of work and there's never enough time for everything. :)

**Comment by jsolson** [comment]
@CobaltWolf if you were unaware B9 added plain old texture switching to a recent update. Something you might be able to make use of in the future. Orange Centaur comes to mind.

**Comment by HooHungLow** [comment]
@jsolson You mean like this? 
![centaur tank orange](https://user-images.githubusercontent.com/28848369/36711327-cb415570-1b50-11e8-8a0f-bd27d9621beb.png)

**Comment by jsolson** [comment]
> You mean like this?

That's the spirit!

**Comment by HooHungLow** [comment]
Yeah, I found that buried in the centaur parts folder, I guess it was an old unused texture?

**Comment by CobaltWolf** [comment]
The two long Centaur tanks were made by a friend and I've continuously forgotten to do something about them, considering the textures don't match at all. I didn't realize he never added B9 to them.

In any case, the stock game is getting mesh/texture switching in the next update. If the functionality is the same I'd probably move our model/texture switching to that. We'd have to keep B9 for the other functionality.
