### ISSUE TITLE
ART: Apollo textures

### ISSUE THREAD

**Issue by Rock3tman** [CobaltWolf/Bluedog-Design-Bureau#413]
- [ ] Address/look into concerns listed below in the original issue report
- [x] fix vents on the SM - they are not correct and look bad
- [ ] SM interior bays need work, possibly a slight remodel, reminder to consider supporting the profile for US2
- [ ] SM in general might need some work, it wasn't given the same level of overhaul as the capsule
- [ ] LEM descent stage foil
- [ ] Apollo docking alignment indicator part (just greebling I guess?)
- [ ] Fix UVs on the LEM antennas
- [ ] Standalone LEM legs
- [ ] SPS shroud sucks butt

Original issue post below: 

In comparison to the rest of the Saturn parts and many of the new parts in general, the Apollo partset looks pretty grimy and dirty. This level of grease is especially present on the Block 3 SM and engine. While the Apollo is an adaptation since reflective textures don't match the style of the mod, it might also be worth considering brightening the colors on the Apollo parts as well.

**Comment by HooHungLow** [comment]
I actually like the Apollo, It would be nice if we could have options when it comes to textures. It would be nice if we had a white painted texture for an Orion feel. The service modules are hard to pair with other parts as well with the Apollo texture as-is.

**Comment by jsolson** [comment]
We _(you)_ really should give metallic/reflective textures a shot on Apollo and Atlas. The new Atlas models are fantastic, but the new tank textures are just so-so. They have a repeating pattern to them.

**Comment by CobaltWolf** [comment]
@jsolson just because I didn't reply here - there aren't any reflective shaders available. The Apollo and (well, not really) the Atlas are already about as good as I can make them.

**Comment by friznit** [comment]
Making a note here as a reminder ref the issue with BDB in Colors mod.  Drakenex provided a fixed texture file for the Apollo CSM parachute mount, which was preventing In Colors working.

Thought: given that shiny textures are now a thing, do you think it would be worth merging In Colors textures and adding a shiny metal option to Apollo  (and maybe Atlas & Centaur too)?
