### ISSUE TITLE
REQUEST: Inertial Upper Stage (Titan/Shuttle)

### ISSUE THREAD

**Issue by HooHungLow** [CobaltWolf/Bluedog-Design-Bureau#416]
Inertial Upper Stage

Two stage solid-fueled rocket upper stage developed by Boeing for the United States Air Force beginning in 1976 for raising payloads from low Earth orbit to higher orbits or interplanetary trajectories following launch aboard a Titan 34D or Titan IV rocket, or from the payload bay of the Space Shuttle. -[Wiki](https://en.wikipedia.org/wiki/Inertial_Upper_Stage)

![image](https://user-images.githubusercontent.com/28848369/36777301-0415becc-1c37-11e8-84dc-a9b9a8fae5c8.png)

![image](https://user-images.githubusercontent.com/28848369/36777319-1866aeae-1c37-11e8-9516-a41255deed8a.png)

**Comment by CobaltWolf** [comment]
I believe Pak over at Cormorant Aeronology has been working on one. :)

**Comment by CobaltWolf** [comment]
@HooHungLow Pak posted a new screenshot of his IUS. If I know him it'll be easy to delete the rest of the mod once it's out. https://forum.kerbalspaceprogram.com/index.php?/topic/119951-141-cormorant-aeronology-mk3-space-shuttle/&page=67&tab=comments#comment-3323381

He has shown more to me in private and I'm pretty excited, I'm not sure how much else he posted to the forums.

**Comment by HooHungLow** [comment]
Really cool! I already have his mod so it will be a nice addition for the shuttle and BDB's Titan.

**Comment by CobaltWolf** [comment]
@HooHungLow closing this issue to keep the issues list clean :)
