### ISSUE TITLE
IMPROVEMENTS: MikeO09's feedback

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#420]
There's probably some stuff worth considering in all this:
https://forum.kerbalspaceprogram.com/index.php?/topic/122020-131-bluedog-design-bureau-stockalike-saturn-apollo-and-more-v142-%D0%B0%D1%82%D0%BB%D0%B0%D1%81-1feb2018/&page=413&tab=comments#comment-3309093

**Comment by jsolson** [comment]
I was able to reproduce the RCS bug by cheating to orbit with a CSM+LEM. Undocking the LEM and leaving physics range, then returning. On return the CM thruster effects are firing. A scene change clears the issue.

It does not happen when I change the root part from the CM to the service module. This looks like yet another stock root part related bug.

**Comment by CobaltWolf** [comment]
Well it's the same as https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/366

I'd be interested in looking into the plumes, maybe there are custom effects we can take+use ourselves. Do you have any thoughts on the 'jerkiness' he described? It sounds like he's trying to say that the decoupler forces and reaction wheels are too strong which wouldn't surprise me, and makes me think it's worth thinking about.

**Comment by CobaltWolf** [comment]
Just checked, FASA uses stock (ancient, actually) FX and sounds for their engines, except for one thing - they have a custom sound file for the Titan SRB noise which is also used on the F-1. Interdasting...

**Comment by jsolson** [comment]
FASA might not have a reaction wheel in the LEM. Ours are probably OP across the board.

Switching the CM to use ModuleRCS instead of ModuleRCSFX might kill the CM effects bug.

I've no doubt our stock engine effects are lacking in places.

**Comment by CobaltWolf** [comment]
I'm seeing about having the guy that fixed up our F-1 and J-2 do the same for the CSM and LM engines. Doesn't ModuleRCS look a lot worse?

**Comment by jsolson** [comment]
>Doesn't ModuleRCS look a lot worse?

It looks fine and seems to cure the bug. Could you take a peek at the LEM Ascent stage model. I'm seeing RCS effects firing through the docking port. I may have just wonked something out messing around.

The CM really needs it's roll control thrusters separated from the rest. They fire on any pitch or yaw movement and throw everything off (mainly yawing they induce a spin).

The F1 looks ok except for the big smoky plume. J-2s looks like long blue afterburners - Vector engine effect I think. The LEM engines look fine (for stock). The CM engine is underdone (it's not ModuleEnginesFX), though a plume that matches the oversized bell would look silly too.

I want to look at the behavior of the SLAs. It's inconsistent. The fixed petal adapter stages the petals and has a payload decoupler, the jettonsonable petal adapter stages the petals with no payload decoupler, the full covering doesn't stage the petals at all, and has a stageable payload decoupler.

LEM extraction is fine. Handling is fine. If someone thinks it's too spunky that's what toggle torque and the rcs thrust slider are for.

**Comment by CobaltWolf** [comment]
I wish Squad would let us arbitrarily override/rename the entries in the right click menu, that would make it easy to distinguish multiples of the same module.

**Comment by HooHungLow** [comment]
Please don't get rid of realplume effects. They are much better than stock.

**Comment by CobaltWolf** [comment]
@HooHungLow we'd never get rid of them, but a lot of people don't like using them (or can't due to their PC). But, I don't really do any work with them so they are pretty lacklustre.
