### ISSUE TITLE
Mostly CobaltWolf's ToDo list...

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#423]
...as best I can remember

Must have parts
LDC 1st stage engine mount. Do this first.

Art
Atlas vs Vega "metal" textures. Vega looks better. Does 1.4 use a shader that helps?
Titan IV "bronze" bell. The color from the VFB dish might be better.

Future stuff maybe
Old school fairings for certain very distinctive fairings. (needs plugin support written)

**Comment by CobaltWolf** [comment]
I looked into the Atlas issues, I think I got at least part of it. I will need to approach Benjee10 for help.

We still don't have part tools for 1.4.1 but apparently the shaders did change.
