### ISSUE TITLE
REVAMP: Atlas V

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#428]
First, thanks to PickledTripod for the awesome RD-180 to start from. He even UV unwrapped it. Now...
- [x] RD-180 (Naked)
      - 
- [x] RD-180/Atlas 3 Shroud
      - [ ] Finish detailing texture
- [x] RD-180/Atlas 5 Shroud
      - [X] Add detail to the connector box
      - [X] Better texture where the cloth connects to the engine bells
      - [X] Fix lobes on Atlas V shroud
- [x] RD-180 Setup
- [x] Atlas V main tank
      - [ ] Detailing on the avionics package, tank butts, pipe, intertank
- [x] AJ-60 Solid Booster
- [x] 4XX Centaur Interstage
- [x] 5XX Centaur Fairing Base
- [x] Centaur Truss Interstage
- [x] 4XX Centaur Fairing Base
- [x] 2.5m decoupler?
- [x] Revamp for long centaur tanks
     - [x] white and orange
- [x] Single Engine Centaur Mount

**Comment by longlong2002** [comment]
RD-180/noShroud

**Comment by CobaltWolf** [comment]
- [ ] Shrouded RD-180 variants need better colliders
- [ ] [Fix seams at bottom of raceway of the lower tank and under the connector block on the Atlas V RD-180 shroud](https://user-images.githubusercontent.com/10545461/42297186-6e444d66-7fb2-11e8-98da-a2922326ea83.png)

**Comment by CobaltWolf** [comment]
[ ] Add RCS to Centaur V engine mount

**Comment by jsolson** [comment]
You're gonna kill me...

The straight portion of the 4xx Adapter is too tall. The red and orange lines on the image should be aligned. Centaur sits at the same height on both the 5xx and 4xx versions.

The Centaur is slightly too deep in the 5xx adapter (the top of the engine mount should be at the flair), but even accounting for that the 4xx adapter is too tall. The 4xx adapter should be the same height as the straight part of the 5xx adapter.

![atlas 400 interstage](https://user-images.githubusercontent.com/16825376/51028457-7296b080-1561-11e9-9b51-ef8004857730.png)

**Comment by CobaltWolf** [comment]
I think this is firmly a "ah well, fuck it" type issue. :)
