### ISSUE TITLE
Fairing Base scaling

### ISSUE THREAD

**Issue by Kerbal01** [CobaltWolf/Bluedog-Design-Bureau#431]
almost every fairing base (except the 1.25,1.5 and 1.875m) is scaled bigger or smaller than the tank of its diameter.

**Comment by CobaltWolf** [comment]
Got anything else? Mod lists? KSP.log files? These parts have been in game for over a year and this is the first issue I'm hearing of it. Are you even certain you're using the right fairing base..?

**Comment by Kerbal01** [comment]
Sarnus Multibody, 3.125M fairing is too small for the S-IVC.

**Comment by CobaltWolf** [comment]
mmhmm
