### ISSUE TITLE
Science Experiments nonfunctional.

### ISSUE THREAD

**Issue by Kablob** [CobaltWolf/Bluedog-Design-Bureau#432]
Added science experiments (magnetometer, Geiger counter, ion trap, etc) cannot be performed in flight.

**Comment by CobaltWolf** [comment]
Any other info? Not a lot to go on. They have all worked in the past and havne't been touched in over a year. Can you confirm it happens on a clean install of just BDB and its dependencies, for example? 

(Sorry for the delay, have been AFK for a bit here)

**Comment by CobaltWolf** [comment]
@Kablob do you have any confirmation on this?
