### ISSUE TITLE
Model Bluedog_DB/Parts/ProbeExpansion/bluedog_Xenon_RadialSingle does not exist

### ISSUE THREAD

**Issue by blowfishpro** [CobaltWolf/Bluedog-Design-Bureau#438]
Referenced by https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/3b2b54a9dd514ea1d4c7463cf99d33be7a376101/Gamedata/Bluedog_DB/Parts/ProbeExpansion/bluedog_Xenon_RadialSingle.cfg#L8

**Comment by CobaltWolf** [comment]
Apparently I changed the name of the part prior to release but had already uploaded an incorrect config. Should be fixed now.
