### ISSUE TITLE
Exception on bluedog_Saturn_VFB_MissionModule

### ISSUE THREAD

**Issue by blowfishpro** [CobaltWolf/Bluedog-Design-Bureau#439]
```
IndexOutOfRangeException: Array index is out of range.
ModuleAnimateGeneric.AssumeDragCubePosition (System.String name)
...
```

This probably means that the animation `VFB_Window_Anim` does not exist

**Comment by CobaltWolf** [comment]
Do the window lights work? In that case the animation does certainly exist

**Comment by blowfishpro** [comment]
The toggle does not show up, and I see additional NREs from the module when I interact with it.

**Comment by blowfishpro** [comment]
This is on KSP 1.4.3 I'll add, it's possible something in the handling changed

**Comment by CobaltWolf** [comment]
I'll look at it, sounds like I just made an oops and never actually tested that functionality.
