### ISSUE TITLE
BUG: NRE at BDB.ModuleBdbBoiloff.sunExposure

### ISSUE THREAD

**Issue by blowfishpro** [CobaltWolf/Bluedog-Design-Bureau#441]
```
[EXC 20:09:58.422] NullReferenceException: Object reference not set to an instance of an object
	BDB.ModuleBdbBoiloff.sunExposure ()
	BDB.ModuleBdbBoiloff.Update ()
```

Only happens for a few frames, best guess is that `part.pdt` is null initally

**Comment by jsolson** [comment]
I don't get that error here. I've seen that function spam exceptions once before but it was such a heavily modded and unrelated NRE filled log it wasn't worth pursuing. I'll try wrapping part.ptd around a null check.

**Comment by jsolson** [comment]
I added a null check. Should be fixed.

**Comment by blowfishpro** [comment]
I don't see it anymore, thanks!
