### ISSUE TITLE
BUG: Old Atlas parts still appearing in game

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#449]
The old Atlas parts are still visible in the VAB parts list. Did we do something wrong when we deprecated them? Whatever the solution is, it should also be applied to the existing Atlas V and Delta II first stage (+ GEMs) parts since they're getting replaced soon.

**Comment by jsolson** [comment]
I don't see deprecated parts. The extra fairing is Procedural Fairings.

![untitled](https://user-images.githubusercontent.com/16825376/41722286-0624aa72-7536-11e8-8d17-c8e3a4a1f600.png)

FWIW Squad deprecated the Mk1-2 like this (note TechHidden):
~~~
	TechRequired = commandModules
	TechHidden = True
	entryCost = 0
	cost = 3800
	category = none
	subcategory = 0
~~~
We've been doing variations of this:
~~~
	TechRequired = LOLNOPE
	entryCost = 15300
	cost = 3170
	category = none
	subcategory = 0
~~~

**Comment by jsolson** [comment]
Update your files. I fixed this in Feburary.

https://github.com/CobaltWolf/Bluedog-Design-Bureau/commits/master/Gamedata/Bluedog_DB/Parts/Atlas/bluedog_atlas1AdapterTank.cfg

**Comment by CobaltWolf** [comment]
Gotcha. They showed up in RocketPCGaming's BDB highlight stream but looking at the date, the last release was before your fix.
