### ISSUE TITLE
ModuleBdbBoiloff added to non-tank parts

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#450]
GameData\Bluedog_DB\Compatibility\B9PartSwitch\B9PartSwitchTanks.cfg
```
@PART[bluedog*,Bluedog*]:HAS[@MODULE[ModuleB9PartSwitch],!MODULE[ModuleBdbBoiloff]]:NEEDS[!RealFuels]:FOR[Bluedog_DB_8]
{
	MODULE
	{
		name = ModuleBdbBoiloff
		CRYOGENICRESOURCE
		{
			name = LqdHydrogen
			boiloffRate = 8
			outputResource = Hydrogen
		}
	}
}

@PART[bluedog*,Bluedog*]:HAS[@MODULE[WBIResourceSwitcher],!MODULE[ModuleBdbBoiloff]]:NEEDS[!RealFuels]:FOR[Bluedog_DB_8]
{
	MODULE
	{
		name = ModuleBdbBoiloff
		CRYOGENICRESOURCE
		{
			name = LqdHydrogen
			boiloffRate = 8
			outputResource = Hydrogen
		}
	}
}
```
these 2 patches are also adding ModuleBdbBoiloff to parts which are no tanks, like for example the bluedog_rangerDish.

Using a patch like this will crash the game then:
```
@PART[*]:HAS[@MODULE[ModuleBdbBoiloff],!MODULE[ModuleCryoTank]]:NEEDS[Bluedog_DB,CryoTanks]:AFTER[Bluedog_DB_8]
{
    !MODULE[ModuleBdbBoiloff] {}

    MODULE
    {
        name =  ModuleCryoTank
        CoolingCost = 0.09
        CoolingEnabled = False
        BOILOFFCONFIG
        {
            FuelName = LqdHydrogen
            // in % per hr
            BoiloffRate = 0.05
        }
    }
}

```

**Comment by Gordon-Dry** [comment]
I don't think that ModuleCryoTank likes it to be in a comm dish without fuel or even volume to hold fuel.

The  ModuleB9PartSwitch has to be checked if it even is a fuelSwitch and not a meshSwitchFairing or whatever.

**Comment by Gordon-Dry** [comment]
I suggest to change line 336
from
`@PART[bluedog*,Bluedog*]:HAS[@MODULE[ModuleB9PartSwitch],!MODULE[ModuleBdbBoiloff]]:NEEDS[!RealFuels]:FOR[Bluedog_DB_8]`
to
`@PART[bluedog*,Bluedog*]:HAS[@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[fuelSwitch]],!MODULE[ModuleBdbBoiloff]]:NEEDS[!RealFuels]:FOR[Bluedog_DB_8]`

**Comment by Gordon-Dry** [comment]
I don't know if line 350 also needs a special treatment like this.

**Comment by jsolson** [comment]
Yeah it needs an update since we use B9 for other things now. ModuleBdbBoiloff does nothing if no LqdHydrogen is present so it's harmless.

Nertea may be interested if ModuleCryoTank is crashing with no resource present. Though I would definitely try to isolate to a very simple test case before reporting it.

**Comment by Gordon-Dry** [comment]
So that first patch, the BDB one, works.

Together with fixing some CryoTanks patches there are no weird issues anymore in Kerbalism, especially when I add my patch that replaces ModuleBdbBoiloff by CryoTanks.
