### ISSUE TITLE
Agena active docking port is -90° relative to passive docking port regarding indexing key

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#454]
When using MechJeb to dock, I have to set the target relative rotation to 90° to have the indexing key fit into the shape.

**Comment by Gordon-Dry** [comment]
^inserted "target relative" into the sentence to give it proper sense.

**Comment by jsolson** [comment]
Another weird rotation issue. As seen from the the Gemini craft, the game sees the "top" of the Agena docking port at the 3 o'clock position, where the notch is at 12 o'clock.

It's not the Gemini port. Against a stock docking port Gemini orients as expected.

**Comment by CobaltWolf** [comment]
Good thought - I'll try that. Makes sense - I could have sworn I fixed a bug like this a long time ago. I probably only checked that they were visibly aligned.

**Comment by CobaltWolf** [comment]
@Gordon-Dry @jsolson I just uploaded a possible fix - let me know if it fixed it or I need to rotate it 180 the other way.

**Comment by CobaltWolf** [comment]
Thanks for checking that - I had a 50/50 shot :P I'll re-fix it tonight.

**Comment by CobaltWolf** [comment]
Alright, try again! :)

**Comment by Gordon-Dry** [comment]
It's fine now.

**Comment by CobaltWolf** [comment]
Nice. _*dabs*_

**Comment by Gordon-Dry** [comment]
It's at 180° offset again - with rls.
