### ISSUE TITLE
ART: Make the Able/Ablestar interstage ribbed

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#457]

**Comment by jsolson** [comment]
There's an interstage for Able/Ablestar?

**Comment by CobaltWolf** [comment]
The autoshroud. Just a thought that had occurred to me, it would be one of those '1 hour max' type things. I have a few like it on this list, would just be a Saturday morning or something to get through them.

**Comment by CobaltWolf** [comment]
These parts are just going to get redone probably...
