### ISSUE TITLE
Marquart changes

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#46]
Marquart got rescaled to 0.3125m. @VenomousRequiem the RP config needs a quick fix, as well as the Tweakscale config.

**Comment by jsolson** [comment]
This probably needs a mass adjustment and fuel checked. What should it be capable of? Right now it gives a probe core about 850 dv.

**Comment by CobaltWolf** [comment]
It needs to be able to get a small probe injected into an elliptical lunar orbit, I suppose. It's based on Lunar Orbit so there's your reference on how big of a probe you should be able to run relative to it. Prolly needs to get hit with the nerf bat. OTMikhail will be sad. He was loving it last night when we were talking.
https://upload.wikimedia.org/wikipedia/commons/b/bb/Lunar_orbiter_1_%28large%29.jpg
http://images.spaceref.com/news/2011/EL-2002-00496.jpg

**Comment by jsolson** [comment]
I thinking just cut the mass in half. It's just an Ant with a little tank. Gonna leave the fuel alone. It will have 400+ dv with 200 kg on it. Plenty for Munar capture. Enough for maneuvers if you're mass conscious.

**Comment by CobaltWolf** [comment]
really? sweet

**Comment by jsolson** [comment]
What happened to the antenna like the one on that lunar orbiter?

**Comment by CobaltWolf** [comment]
So what was happening was that windows doesn't update the capitalization of files, and neither was github. I made a change to it to bring it in line, and github wasn't updating. So I removed it and added it back. But the model is messed up now, cus I didn't update that.  Can you log that?

-----Original Message-----

**Comment by CobaltWolf** [comment]
were these changes made?

**Comment by jsolson** [comment]
The mass and I think RP changes are in. My agena died before I had a chance to test this engine on an acutal mission.

**Comment by VenomousRequiem** [comment]
I fixed the RP config, yeah. Was i supposed to look at the TweakScale config too?

**Comment by CobaltWolf** [comment]
I fixed the TS config. If it's all good then someone can close it.
