### ISSUE TITLE
RT compatibility: Probe cores got no ModuleSPUPassive

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#460]
I just recognized that the GameData\Bluedog_DB\Parts\ProbeExpansion\bluedog_Sputnik3_Core.cfg had no connection at all...

Quote from the info from https://remotetechnologiesgroup.github.io/RemoteTech/modders/modules/#modulertantennapassive

> ### ModuleSPUPassive
> 
> This module allows any vessel with an antenna to participate in a RemoteTech network, even if it does not have a ModuleSPU. It should be included in all RemoteTech antennas. Unlike ModuleSPU, it does not filter commands or provide a flight computer.

GameData\Bluedog_DB\Compatibility\RemoteTech\remotetech_Probes.cfg

**Comment by jsolson** [comment]
Just fyi, neither CobaltWolf or myself use remotetech so someone who uses it will need to issue a PR with a fix.

**Comment by jmrd98** [comment]
That would have normally been me, but I’m very unable to at the moment/near future :/

**Comment by Gordon-Dry** [comment]
Well, for my personal convenience I just added a generic patch to my setup:
GameData\zFinal\zzz_RemoteTechAddMissingModuleSPUPassive.cfg
```
@PART[*]:HAS[ModuleRTAntenna|ModuleRTAntennaPassive,!ModuleSPUPassive]:NEEDS[RemoteTech]:FINAL
{
	MODULE
	{
		name = ModuleSPUPassive
	}
}
```
This can be used as a base for a BDB specific patch then.

**Comment by Gordon-Dry** [comment]
I guess it has to be changed to this because of the weird and/or ordering in MM:
```
@PART[*]:HAS[ModuleRTAntenna,!ModuleSPUPassive]:NEEDS[RemoteTech]:FINAL
{
	MODULE
	{
		name = ModuleSPUPassive
	}
}

@PART[*]:HAS[ModuleRTAntennaPassive,!ModuleSPUPassive]:NEEDS[RemoteTech]:FINAL
{
	MODULE
	{
		name = ModuleSPUPassive
	}
}
```

**Comment by Gordon-Dry** [comment]
Oh well, I guess at least it should look like this ;)
```
@PART[*]:HAS[@MODULE[ModuleRTAntenna],!MODULE[ModuleSPUPassive]]:NEEDS[RemoteTech]:FINAL
{
	MODULE
	{
		name = ModuleSPUPassive
	}
}

@PART[*]:HAS[@MODULE[ModuleRTAntennaPassive],!MODULE[ModuleSPUPassive]]:NEEDS[RemoteTech]:FINAL
{
	MODULE
	{
		name = ModuleSPUPassive
	}
}
```

**Comment by jmrd98** [comment]
The most “consistent” solution/the way I fix them is a copy paste in the RT extras file with the new probe cfg. 

I agree that a wildcard here would be most ideal, but I wouldn’t recommend it at this juncture without a closer look, and separately that FINAL is intended to be a user reserved option, not one mods set. 

In theory, It shouldn’t muck anything up, but if the patch above is used i would make it AFTER[BDB] just to cover our behinds.

**Comment by Gordon-Dry** [comment]
ofc, this was just my personal generic fix.
