### ISSUE TITLE
RT compatibility: remotetech_Antennas.cfg misses some commas

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#461]
GameData\Bluedog_DB\Compatibility\RemoteTech\remotetech_Antennas.cfg

says in all instances:
NEEDS[RemoteTech!SETIRebalance]
should be
NEEDS[RemoteTech,!SETIRebalance]

**Comment by jsolson** [comment]
Thanks!
