### ISSUE TITLE
Update RCS FX (Sounds and visuals)

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#463]
Currently acquiring a new visual effect from Beale that gets pretty close to [IRL RCS ](https://i.ytimg.com/vi/scGc1NS_IV8/maxresdefault.jpg). 

@jsolson compared to the new sound fx in 1.4.5, do any of the [ones from here stick out to you](https://i.ytimg.com/vi/scGc1NS_IV8/maxresdefault.jpg)? We have permission to use them if you like any in particular. 

I figure we can do a temporary master RCS MM patch to test things out then move to the cfgs themselves when we find what we like.

**Comment by CobaltWolf** [comment]
@jsolson how do I make this into a MM patch? I'm uploading the FX now.

MODEL_MULTI_PARTICLE
            {
                modelName = Tantares/FX/FX_Alnair_Engine_1_RCS
                transformName = attitudeTransform
                emission = 0.0 0.0
                emission = 0.1 0.0
                emission = 1.0 1.0
                speed = 0.0 0.8
                speed = 1.0 1.0
                localRotation = -90, 0, 0
            }

**Comment by jsolson** [comment]
I just got a giant non directional ball of white gas. Can you get this working on one part, on a clean install - or without Beales stuff anyway. And give me a screen shot of what it should look like. I can take it from there.

There's a patch already for global RCS adjustments where this can go.

**Comment by CobaltWolf** [comment]
Sure - I'll see if I can do it tonight. I think I know why that would happen.

**Comment by CobaltWolf** [comment]
Didn't work for me either. He's looking into it. Thinks it might be a 1.4 problem.
