### ISSUE TITLE
Missing Texture for atlas control engines/RCS

### ISSUE THREAD

**Issue by djreonic** [CobaltWolf/Bluedog-Design-Bureau#464]
There seems to be a missing texture for the bluedog_Atlas2_RollControlSystem. It appears flat gray in game. Also there seems to be a similar texture issue with the bluedog_Atlas_LR101_Inline.

**Comment by CobaltWolf** [comment]
You probably still have the old DDS compressed textures in the folder and they're overriding the uncompressed MBM texture files. Compressing to DDS is one of the last things I do before I publish a release, though I don't know why yours are overriding the MBMs when they aren't on mine. I think the easiest way to deal would be to use DDS4KSP to DDS compress everything, hopefully that overwrites the old DDS files.

**Comment by CobaltWolf** [comment]
Closing since this isn't a bug :)
