### ISSUE TITLE
Screwed up thrustTransform's on PIBS

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#465]
All but one thruster is in the wrong place on both.
![screenshot7](https://user-images.githubusercontent.com/16825376/44311569-cf79aa80-a3b7-11e8-9784-1d60f58b5bbd.png)
![screenshot8](https://user-images.githubusercontent.com/16825376/44311574-d4d6f500-a3b7-11e8-83d5-6181ae6bd52c.png)

**Comment by CobaltWolf** [comment]
alright, they're getting redone anyways
