### ISSUE TITLE
BUG: No payload decoupler on the SLA-base

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#467]
https://www.reddit.com/r/KerbalSpaceProgram/comments/9d0fz8/ksp_has_been_fun_lately_recreating_some_early/e5g4n3s

Need someone to confirm, might be that the SLA helper module isn't working on 1.4.5?

**Comment by jsolson** [comment]
I think I'm still on 1.4.3 but I'll check when I get a chance. Though I doubt it doesn't work. The Apollo/SIVB needs documentation, both on how to build and how to use.

**Comment by jsolson** [comment]
I wonder if the guy is running the last release on 1.4.5. Or he found some sequence of actions to make it fail. I can't make it not work.

**Comment by CobaltWolf** [comment]
Best to just ignore it and see if it comes up again

**Comment by OrbitalManeuvers** [comment]
Being the guy, I can tell you for certain that I'm not certain. Just tonight I looked at the top-level of this github, and realized that I have the Bluedog_DB files (Bluedog_DB_142.zip) and now I'm seeing this one. Have I been on an old release this whole time?

**Comment by OrbitalManeuvers** [comment]
Update: So I downloaded this repository, and compared it against the zip file that I previously downloaded - from somewhere - probably spacedock? Anyway, the zip I have has the exact same Bluedog_DB.version file, but has MANY missing folders for other things like Parts. E.g. AtlasV, LDC, Solids are all missing from what I previously had. Also, more important things like BDB.dll are out of date, mine was 9/2/18, this repo has 9/9/18.

So I dunno how I have the same version file but not the same rest of the package, but clearly at this point what I need to do is wipe out the previous download, and install this one and try the LEM fairing again. Will do that today.

**Comment by CobaltWolf** [comment]
We have not published a new release since the date listed on the thread - February 1st, I think. Downloading the repository is basically downloading the current development build of the mod.

**Comment by OrbitalManeuvers** [comment]
Hmm, OK ... so the missing folders I mentioned are basically work in progress stuff? If so then great, I'm happy to run on the bleeding edge. Things that don't work yet won't bother me, and hopefully I can even contribute a little testing.

**Comment by OrbitalManeuvers** [comment]
Well this build definitely has the Decouple menu item on it, and it worked great (on 1.4.5).

**Comment by CobaltWolf** [comment]
Alright, I think we can close this then :)
