### ISSUE TITLE
Stockish BDB fairing bases not openable by RemoteTech?

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#469]
I cannot open the bluedog_125mFairing - I just get this single line in the log then:
`[RemoteTech] BaseEvent invokeException by 'Open all bays' with message: Object reference not set to an instance of an object
`

**Comment by CobaltWolf** [comment]
???

**Comment by Gordon-Dry** [comment]
Well, the staging of that fairing did not work, just wrote that line to the log.

But decoupling the payload was working without issues, like the still closed fairing was non-existant.

The PF variant works, though.

**Comment by CobaltWolf** [comment]
Sounds like its Remotetech's issue since it's a bog standard fairing.
