### ISSUE TITLE
MM error sources found

### ISSUE THREAD

**Issue by JadeOfMaar** [CobaltWolf/Bluedog-Design-Bureau#471]
Something is wrong with the 5 insert nodes at [this config file](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Compatibility/B9PartSwitch/StockWetWorkshop.cfg#L134). I was told this is a matter explicitly for @jsolson to address.

**Comment by jsolson** [comment]
Those lines copy the nodes from the other part. You've stumped me, what's going wrong?

**Comment by CobaltWolf** [comment]
The best form of communication, copying lines from a Discord conversation:
[10:32 AM] blowfish: Not sure, probably had something to do with the variable search
[11:36 AM] JadeOfMaar: @CobaltWolf you'd have to share your logs and check if your wet workshop part has all the modules it's expecting in-game.

**Comment by jsolson** [comment]
Try turning it off and back on again. If that doesn't work change the batteries. I could try reversing the polarity of the neutron flow, or maybe we can reconfigure the phase decoupler, but I'm not sure if that will work since I have no idea what the problem is.

**Comment by CobaltWolf** [comment]
I think the second part of the last message has the first step here: Can we confirm that all the modules that should be on the part, are?

#@PART[Large_Crewed_Lab]/MODULE[ModuleScienceContainer] {}
#@PART[Large_Crewed_Lab]/MODULE[ModuleScienceLab] {}
#@PART[Large_Crewed_Lab]/MODULE[ModuleScienceConverter] {}	#@PART[Large_Crewed_Lab]/MODULE[ModuleKerbNetAccess] {}
#@PART[Large_Crewed_Lab]/MODULE[ModuleExperienceManagement] {}

**Comment by jsolson** [comment]
First thing I did. It's all present. Couldn't find any related log errors either.

These Wetlabs have been getting used for a few months now without complaints. I was going to change them to proper config files rather than MM scripts anyway.

**Comment by CobaltWolf** [comment]
y'know, people noticed they were throwing errors on my stream and started talking about it in the Discord, but I probably don't even have updated files for them. Ignore it, sorry for the fuss.

**Comment by jsolson** [comment]
A mod that modified labs could easily cause errors here.
