### ISSUE TITLE
bluedog_Peacekeeper_FairingBase

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#472]
I have a really heavy suspicion that the part
GameData\Bluedog_DB\Parts\Solids\Peacekeeper\bluedog_Peacekeeper_FairingBase.cfg
is the reason for
https://forum.kerbalspaceprogram.com/index.php?/topic/50911-13-kerbal-joint-reinforcement-v333-72417/&do=findComment&comment=3467698
because PF parts are picky ...

**Comment by CobaltWolf** [comment]
What do you mean? Any reason in particular? It's a bog standard fairing base copied from another one, all I did was change the name and node positions.

**Comment by Gordon-Dry** [comment]
It seems that these tiny decouplers from BDB were the reason for that issue - I should avoid them.
