### ISSUE TITLE
RealPlume and Realnames not applyitng to the F-1A and J-2A

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#473]
From Marcelo Silveira
"I noticed that the realnames and Realplume patches are not applied to the F-1A and J-2A engines. This happened because Module Manager wasn't loading the files in the correct order..."

**Comment by CobaltWolf** [comment]
I'm not sure what that means. Do you know what we need to do?

**Comment by jsolson** [comment]
Yes. Those are +PART MM patches making those parts. I'll either make them proper full config files or add a First to the patch so the order is correct.
