### ISSUE TITLE
Blank preview in VAB for bluedog_MOL_Adapter_1875_15

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#475]
![untitled](https://user-images.githubusercontent.com/16825376/47082498-bc2e6400-d1db-11e8-93de-c5156c6eaf42.png)

**Comment by blowfishpro** [comment]
This is because the first (default) subtype's mesh has the `Icon_Hidden` tag on its GameObject.  `Icon_Hidden` should not be necessary on subtypes - icon setup is handled by B9PartSwitch.

**Comment by CobaltWolf** [comment]
Yup, an easy enough fix at least
