### ISSUE TITLE
Telstar VHF Antenna: says it's stack mountable but it got no upper node ...

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#478]
Just to mention it is not stack mountable.

**Comment by CobaltWolf** [comment]
Yeah, it's only meant to be stacked on top of stuff

**Comment by Gordon-Dry** [comment]
Well, derivied from the look of the antenna it should be designated to be stackable on each other ...

I guess this idea went to the cupboard drawer long time ago?
