### ISSUE TITLE
TRAILS/Leo/Vinci mainchute rips craft apart

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#48]
The entire craft comes apart when the main chute fully deploys. Need to determine if this is pilot error or a config issue.

**Comment by CobaltWolf** [comment]
Any updates on this?

**Comment by jsolson** [comment]
Still needs testing. My impression is it needs a little more drag before the main chute opens. Could be wrong.

**Comment by VenomousRequiem** [comment]
I have never once had an issue with this. I usually drop my periapsis to 20KM from any orbit to keep G forces down and that slows me down just fine, no parachute issues.

**Comment by CobaltWolf** [comment]
Well, I think I'm going to close this so we can make the release.

**Comment by CobaltWolf** [comment]
People keep saying that it's happening. I don't know why.

**Comment by CobaltWolf** [comment]
@jsolson I am trying to upload a possible fix for this issue but after making the commit and syncing it won't appear on the repo online. Any idea why?

**Comment by CobaltWolf** [comment]
Hrmmmmmm, here's something. [Sumghai's SDHI mod is having similar issues.](http://forum.kerbalspaceprogram.com/index.php?/topic/48073-112-sdhi-service-module-system-v311-23-april-2016/&page=62#comment-2596771) I'm starting to wonder if this could be a 1.1.2 issue if we aren't the only ones experiencing some issues. It's not 'gamebreaking' but there might be something behind the scenes with the forces the parachute modules apply to the craft, causing it to break.

**Comment by jsolson** [comment]
Declaring this fixed. Reopen if necessary.
