### ISSUE TITLE
GEM40 Inline glitch

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#481]
~~~
Warning on PartSubtype None on module ModuleB9PartSwitch (moduleID='meshSwitchStripe') on part bluedog.Delta.GEM40.Inline: No transforms named NoStripe found
~~~

Something wrong with the NoStripe transform. Selecting leaves a graphical glitch up top. The radial model is fine.

Edit: Also the bluedog_LR87_SingleChamberB is giving `No transforms named BareEngine found` though it looks fine since there's nothing supposed to be there.

**Comment by CobaltWolf** [comment]
Does that mean the LR87 is broken? Or it works but spits errors. If its the second I won't kill myself over it.

**Comment by jsolson** [comment]
It appears to work but spit errors.

**Comment by CobaltWolf** [comment]
The GEM-40 is fixed, the NoStripe version looks like it was named wrong in Maya and I didn't correct it in Unity.
