### ISSUE TITLE
Star 48BV ModuleJettison

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#482]
There are 3 ModuleJettison's in [the Star 48 file](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Solids/UpperSolids/bluedog_UpperSolids_Star48BV.cfg). What are the last two at the bottom of the file for? They don't appear to do anything.

**Comment by CobaltWolf** [comment]
Nothing to worry about, it looks like I just didn't realize there was all that stuff past that stupid stock test contract thing that bloats every cfg.
