### ISSUE TITLE
Agena D unbalanced RCS effect

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#483]
![agenadrcs](https://user-images.githubusercontent.com/16825376/47892250-1579d280-de2d-11e8-8fdd-f71172101bfd.png)

The top half is the pitch thrusters, and the bottom half the yaw thrusters. I'm pitching/yawing and translating at the same time to get them to fire in opposition. The one pitch thruster has a much larger effect than the others.

Could you check the magnitudes of the `rcsTransform`. I can't imagine what else would cause this.

**Comment by JadeOfMaar** [comment]
Experience tells me there may be a "limitation" somewhere to the number of RCS ports on a single part where scaling a plume works. I discovered this while testing an engine plume once. The scaling worked on 3 of the nozzles but did not work on the 4th one. If this BDB part has all these nozzles builtin then let me know how many. I tested this on the stock 4-nozzle RCS block but I didn't think to test any mod RCS and look out for this.

**Comment by JadeOfMaar** [comment]
I've confirmed it. It happens at the 6th RCS transform and may be tied to a legacy problem I heard of way back where you couldn't have 6+ RCS transforms on a single part for unknown reasons.
If you'd like, I'll export pre-scaled plumes for you to use, multiplied by the scale numbers you've used in the configs.

**Comment by jsolson** [comment]
I see it now, only the 6th transform is effected. Well that is just... I'm speechless.

We do have a few parts with 6+ transforms (vega has 12), but on the bright side they're all tiny thrusters in the 0.1 to 0.3 Kn range. Maybe go with half size? I was attempting to scale by multiplying the scale by the thruster power but 0.1 scale is just way to small. I may be able to do something with speed and emission to tone down the intensity a bit.

FWIW I had originally thought we'd use Hot Flash for the many tiny jets we have, but Whiff is really growing on me. The lingering effect is really nice. I've yet to try Soyuz on the small ones, but I have a feeling that will work well too.

**Comment by CobaltWolf** [comment]
"...I'm speechless"

Holy smokes I'm snorting coffee in a diner reading that. 

Good news is we can probably get by with just a couple sizes. And it wouldn't really hurt our ram usage since the textures for the puffs are reused.
