### ISSUE TITLE
New RCS Plumes - Feedback wanted! 

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#487]
Please leave your feedback on the new RCS plumes here. @jsolson converted them using a couple blanket patches and we need to know what plumes need individualized adjustments to look right. Keep an eye out for parts with more that 5 thrusters on a single part - they're susceptible to bugs that leave one plume scaled wildly different than the others.

**Comment by CobaltWolf** [comment]
The Soyuz one is the one I originally was asking after. It's nice to be able to integrate this sort of polish/quality increase without much work. 

On a vaguely related note to my previous statement, [this guy seems interested in, among other things, improving the sounds for RealPlume, and was open to my request for trying to get the Titan II "bwoooOOOP" sound on ignition.](https://forum.kerbalspaceprogram.com/index.php?/topic/179579-dev-rocket-sound-enhancement/ )

**Comment by debaker02** [comment]
Looks like the ion thrusters use the new could vs the ion effect.

**Comment by CobaltWolf** [comment]
Thanks I'll fix that
