### ISSUE TITLE
BUG: LEM Ascent Module RCS transforms

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#491]
The direction of thrust is correct on all transforms.

All RCS transforms except one are rotated 180 degrees off, causing RCS effects to move in the wrong direction.

There is an RCS transform in the docking port position that should not exist.

![lemrcs](https://user-images.githubusercontent.com/16825376/48970669-18578580-efdd-11e8-863a-267a415a5db9.png)

**Comment by CobaltWolf** [comment]
fukkin weird, I'll look into it

**Comment by CobaltWolf** [comment]
Fixerino-ed
