### ISSUE TITLE
bluedog_Explorer1 bd_GeigerCounter xmitDataScalar should not be 0.4

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#494]
Nobody wants to send a manned mission to get the data ...

And Explorer 1 is not intended to do a reentry and safe landing.

So xmitDataScalar should be plain 1.0

**Comment by Gordon-Dry** [comment]
Same goes for

bluedog_Pioneer1
bluedog_Pioneer4
bluedog_Vanguard
bluedog_Sputnik3_Core

**Comment by jsolson** [comment]
xmitDataScalar = 0.4 transmits 40 percent of what's available, correct? Leaving something for Explorer 2, 3, 4, etc to do.

**Comment by Gordon-Dry** [comment]
Okay, I'm too much in Kerbalism ...
