### ISSUE TITLE
J2 Upgrades?

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#497]
For consistency, should the J2S, J2A2, and J2 Toroidal 250K be changed to upgrades? The three are +PART patches now. The Atlas Booster and RL10 variants are all upgrades.

I maintain patches in Extras\Sandbox that eliminates the upgrades and splits the Atlas and RL10 engines into separate parts and I could do the same with these.

**Comment by CobaltWolf** [comment]
Yeah sounds fine by me. I didn't realize they weren't implemented as upgrades.

**Comment by jsolson** [comment]
Forgot to mention the F1A as well.

**Comment by CobaltWolf** [comment]
We good to close this?
