### ISSUE TITLE
Kerbalism compatibility configs

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#50]

**Comment by CobaltWolf** [comment]
... did we ever get these?

**Comment by Maxzhao1999** [comment]
Hi! I'd like to help with kerbalism compatibility but I'm very new to mod configuring, is there any specific thing I can help with?

**Comment by minepagan** [comment]
You'd need to start by learning how to make an MM config, there is a good wiki on the MM forum page.

**Comment by minepagan** [comment]
If nothing else, you could always just make a chart or table or something with the resources that should go on each pod, thats actually the hard part.

**Comment by dieDoktor** [comment]
I'm not sure to what extent this is being worked on or needs to be done, but I thought I would just bring attention to the thread/future visitors that Kerbalism does have a .cfg for Bluedog. It looks to primarily allow antenna parts to function as antennas, but it seems to exclude probe body antennas. Depending on input from this thread, I may go open an issue in the Kerbalism repo to help expand on that.

Like I said, I'm not sure what that .cfg encompasses versus what the original issue intends to get done, but it does exist.

**Comment by Maxzhao1999** [comment]
Kerbalism excludes all probe antennas, stock or otherwise, it's the default setting, if you'd like antenna to be added to probes you need to manually edit the config.
