### ISSUE TITLE
Atlas V lower tank fuel flow priority

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#502]
Undesirable behavior: When you move the Atlas V lower tank retros to stage with the decoupler, it lowers the fuel flow priority of the tank. Fuel flows from the upper tank first, then the lower tank if you don't change it.

Short of putting the retros in a separate part I don't think we can do anything about this. KSP seems to adjust priorities based on staging order.

**Comment by CobaltWolf** [comment]
That's annoying as shit.

**Comment by CobaltWolf** [comment]
Does this actually change anything? Or can we just close the issue with it noted.

**Comment by jsolson** [comment]
The real solution here is a flush mount retro part so the retros can be removed from the tank part.

I discovered this using smart parts when it staged halfway through the core stage burn when the upper tank ran out.

The presence of the AJ-60s had probably concealed the bottom heavy effect of burning though the upper tank first.

**Comment by CobaltWolf** [comment]
Ok well... I'm not remaking the tank at this point. Tell KSP to stop being a broken piece of shit.

**Comment by CobaltWolf** [comment]
Actually, it wouldn't be toooooo much work... but I'd honestly probably just comment out the SRBs instead of wasting more time.

**Comment by jsolson** [comment]
We'll just remove the SRB's.

If your inclined in the future a flush mount 45 degree retro would probably get heavy use as a general purpose part.
