### ISSUE TITLE
Centaur engine mount clipping

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#507]
The old twin engine mount (this used to work):
Clips with or without rcs on the straight interstage.
Clips with rcs on the 2.5-1.875 interstage

The new single mount:
Clips badly and explodes with rcs attached.
Does not clip without rcs.

**Comment by CobaltWolf** [comment]
So if I remember, we had decided that the Centaur V mount would just have integrated RCS and the older, dual-mount would eventually receive the same?

Should I maybe just bash it together on the old one too for this update?

**Comment by jsolson** [comment]
I'm not sure the best way to proceed. I assume you want to keep the mounts separate parts, rather than a mesh switch. I think I'd prefer the integrated RCS on both. The old mount has nodes for single and dual engines. The new mount only can accept singles. From a gameplay perspective dual engines on the new mount would be preferred since that's a 6+ minute burn with one engine and the big tank, so a dual mount option there would be a big plus.

Centaur parts are organized a little weird. Some are under Centaur, some are under AtlasV.

**Comment by CobaltWolf** [comment]
Well, I had a lot of space left on the Atlas V texture sheet and needed to use it *for something*... but yeah it's a horrible mistake and I have no idea how to dig myself out of it... at least, none that don't delay this release a few more months...

Similarly, I wish I could make them into one part but I can't because of how they're organized.

**Comment by CobaltWolf** [comment]
@jsolson closing this now that RCS has been added.

**Comment by jsolson** [comment]
The twin mount still clips on the straight interstage. It's got a 3 rpm spin and a slight pitch or yaw rate.

**Comment by CobaltWolf** [comment]
seriously? ok...

**Comment by jsolson** [comment]
It's probably the interstage. It didn't used to do it, and you added the truss mesh. The spin rate is less with the truss mesh.

Another issue is the middle engine node. It floats slightly. There's a ModuleJettison that does nothing. It think that used to do some sort of twin single mount switch?

**Comment by CobaltWolf** [comment]
The two interstage variants used the same colliders. 

The middle engine thing should just be removed.
