### ISSUE TITLE
Wiki needs to be updated for v1.5.0

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#512]
Need to finish updating the wiki for release with the new stuff. Off the top of my head:

- [x] Athena needs to be added to the MX page
- [ ] Scout needs to be added
- [x] would be nice to have both Atlas V 401 and 551 in the Atlas page
- [ ] Delta 2 needs to be added once I finish the texture pass - hold off for a couple more days

**Comment by jsolson** [comment]
How exactly to document Scout has been bugging me. Built historically it's probably got enough dv to work in RSS. In my mind it's not a Scout at all, it's a Scout-XL.

**Comment by CobaltWolf** [comment]
Why's that? Shouldn't matter, it is what it is. Still the smallest useable lifter in 2.5x

**Comment by CobaltWolf** [comment]
Yeah, I already started sketching out revamped parts for Thor and Vanguard.

**Comment by SilveiraMarcel** [comment]
Should the updated wiki contain the delta v curves for the rockets? Those will be quite simple to calculate, given that most rockets use a stack design, unlike Atlas with its stage and half.

**Comment by CobaltWolf** [comment]
I think they would be helpful for the most common builds! :)

**Comment by CobaltWolf** [comment]
Delta 2 stuff is done and ready to be put in, methinks
