### ISSUE TITLE
Tech tree issues

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#513]
Centaur parts all appear at the same time. Need to spread them out a bit.

**Comment by CobaltWolf** [comment]
I'll look at it tonight, I'll take a second pass at the tech tree. When should the E-1 unlock do you think?

**Comment by jsolson** [comment]
Centaur needs to follow the four nodes from General Rocketry to Precision Propulsion. And I need to add an upgrade for the A3 engine.

The E-1 unlocks at General Rocketry with Titan 1. It's fine there till we get on the same page with what to do with it.

**Comment by CobaltWolf** [comment]
re: Centaur really? It needs that many? I'll take a look, I need to see where the other stuff lives...

E-1 is fine there I think, it *was* supposed to be available in the late 50s...

**Comment by jsolson** [comment]
Centaur tanks go D-1, D-1A, II, and V. The A1 engine goes with the D1. The A3 that I want to add goes with everything including Saturn, then the A4 goes on Centaur V (It also went on later Centaur II's).

The more I look at the tree the more I want to throw everything out and start over.

**Comment by CobaltWolf** [comment]
Oh, I created a branch for tech tree updates. Check that out: 
https://github.com/CobaltWolf/Bluedog-Design-Bureau/tree/techTree

**Comment by jmrd98** [comment]
Would it be worthwhile/interesting to create a squad-free/total conversion tech tree for the optional folder? I suspect there exist enough parts to easily do that at this point.

**Comment by jmrd98** [comment]
Emphasis on the 'optional folder'. My inclination is to not, but it was a thought I had a while back, and this seemed a reasonable venue to offer it up.

**Comment by jsolson** [comment]
Officially adopting CTT has crossed my mind. We could lobby for some additional nodes and branches.

We've been very lazy with tech tree placement though so I'd like to see where this goes.

**Comment by CobaltWolf** [comment]
Did you have any more edits you wanted to make on that branch Jso? Or should we merge it in?

**Comment by jsolson** [comment]
I still want to do Centaur, but go ahead and merge it.

**Comment by CobaltWolf** [comment]
I could swear that I spread them out, or were you thinking of spreading them further than just the propulsion nodes?

**Comment by CobaltWolf** [comment]
Completely unrelated but while I have you... if you want to poke at the switching a bit, check here https://github.com/blowfishpro/B9PartSwitch/pull/100
