### ISSUE TITLE
bluedog_Gemini_Service_B RCS Transform Rotated Incorrectly.

### ISSUE THREAD

**Issue by jmrd98** [CobaltWolf/Bluedog-Design-Bureau#514]
The RCS on this module should thrust forward. This isn't working. The actual transform on the part is rotated 90 degrees to point up instead.

On a tangentially related note, what is the intended use for this part, historical or otherwise? I'm trying to figure out the difference beyond fuel cell from the larger part. Similarly, is there an intended/suitible engine to mate with the 1.5m cylindrical SM? I'd use it all the time but for that.

**Comment by jsolson** [comment]
I don't think I ever noticed this part.

![untitled](https://user-images.githubusercontent.com/16825376/51084541-8248fd00-16f9-11e9-858f-1c8b72f84fbc.png)
