### ISSUE TITLE
NullReferenceException Error

### ISSUE THREAD

**Issue by Mangmod** [CobaltWolf/Bluedog-Design-Bureau#515]
Hello, I have thought of sending this report due to the game stopping loading after it encounters a "Exception:NullReferenceException: Object reference not set to an instance of object" error. I tried removing the mod and it loads fine without issues. The loading is stuck at this specific part: Bluedog_DB/Parts/Apollo/bluedog_Apollo_Block2_LES/bluedog_Apollo_Block2_LES.

Is it any way of fixing this manually?

**Comment by CobaltWolf** [comment]
Can you share your ksp.log and what version of the mod you're using? 

I have an idea of what it might be - that's probably the first BDB part to load that requires our custom plugin, which might not be compatible with your game version?

**Comment by StoneBlue** [comment]
@Mangmod You have *tons* of texture loading errors, for like, everything...
also tons of PartDatabase issues
First, I would try re-verifying KSP install thru Steam... alo delete PartDatabase.cfg ... dont worry, KSP will regenerate a new one on next restart

**Comment by Mangmod** [comment]
I followed your instructions, but without success. I checked for dependencies, but they are up to date. 
I am also wondering why all the texture errors occur.

**Comment by jsolson** [comment]
The error's not likely related to that part, it's just timing. If you want you can rename the bluedog_Apollo_Block2_LES.cfg to bluedog_Apollo_Block2_LES.txt so it doesn't load. You'll probably still get the error on some other part.

Something called AntiSubmarineWeapon is throwing errors starting early on. That may or may not be the real issue.

Texture errors aren't likely causing crashes.

I need a clean or nearly clean install to try to reproduce a problem. BDB loads without issues on 1.6.1 for me.

**Comment by Mangmod** [comment]
I found the culprit. The issue was with BetterBurnTime mod Ver. 1.8, which luckily has been fixed.
I do not know how that could affect this and other parts pack, but I am glad the issue has been solved.

Thank you for your patience and keep up this great work!

**Comment by CobaltWolf** [comment]
Thanks for tracking it down, had me worried there :)
