### ISSUE TITLE
Parts cannot be decoupled from Agena target docking port

### ISSUE THREAD

**Issue by jmrd98** [CobaltWolf/Bluedog-Design-Bureau#518]
This one is fun, and by fun I mean, I don't understand why it doesn't just work. (3am troubleshoot==terrible plan)

Docking ports allow for arbitrary parts to be attached to them in the VAB, and used as decouplers. They even have a staging option if you want. This part though, does not have this behavior. If a part is attached to the agena target docking port in the VAB, there that part will stay forever. A stock port (I used the dockotron jr) allows for a simple right click/decouple node as expected.

I ran into this once before, but I thought I botched it up with a very non-standard design (the target port was attached directly to the bottom node on a gemini SM, so I figured the game got confused as that part ALSO had a docking node on another node...) But I just ran into it as well with an escape tower being welded to the front of my ship.

Setting an action group does not seem to affect anything one way or another, the parts are just stuck.

If used as a docking port, everything works great, though, so at least the main function is working.

**Comment by jsolson** [comment]
>3am troubleshoot==terrible plan

Yup. Just tested, it works fine.

There are two nodes, top and dock. Dock is the inner node and works with the docking port. Top is an ordinary top node, but it has a shroud like an engine's bottom node that covers the port when the nose cone is attached. The nose cone has a decoupler to separate.

![untitled](https://user-images.githubusercontent.com/16825376/51107121-e16f4600-17bb-11e9-8f9c-2ae2925b2aa4.png)

~~~
	MODULE
	{
		name = ModuleDockingNode
		referenceAttachNode = dock
		nodeType = gemini
		acquireForce = 0.75
		acquireTorque = 1
		gendered = true
		genderFemale = true
	}

	MODULE
	{
		name = ModuleJettison
		jettisonName = fairing
		bottomNodeName = top
		isFairing = True
		jettisonedObjectMass = 0.1
		jettisonForce = 5
		jettisonDirection = 0 0 1
	}
~~~

**Comment by jmrd98** [comment]
Ah. The “I don’t see what’s broken because it isn’t” trick. Sorry about that... i guess I’m going to have to do something creative on my station, then.
