### ISSUE TITLE
REVAMP: Titan Part Revamp

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#519]
ENGINES:
- [x] LR-87-AJ3
- [x] LR-87-AJ5/7
- [x] LR-87-AJ9/11
- [x] LR-87-AJ11 Single
- [x] LR-87-AJ11 Single, Vacuum Optimized 
- [x] LR-87-LH2 Single
- [x] LR-87-LH2 Single, Vacuum optimized
- [x] LR-91-AJ3 (1.875m shroud?)
- [x] LR-91-AJ5/7
- [x] LR-91-AJ9/11

TITAN 1:
- [x] First stage lower tank
- [x] First stage upper tank
- [x] Second stage normal length tank
- [x] Second stage shorter length tank
- [x] Short adapter
- [x] Medium adapter
- [x] Long adapter (doubles as autoshroud)
- [x] Separation 'bottles' (big fat sepratrons, they're kinda cool looking)
- [x] Standalone engine shroud

TITAN 2: 
- [x] First stage lower tankage
- [x] First stage upper tankage
- [x] Second stage tankage
- [x] Engine decoupler
- [x] Gemini decoupler
- [x] Titan 2 1.875m>1.5m adapter
- [x] Titan 2 1.5m>1.25m adapter
- [x] Missile nose cone
- [x] Titan 2 vernier solids?
- [x] Small retro solids
- [x] Titan 23G ACS pack

TITAN 3:
- [x] Lengthened first stage
- [x] Second stage Avionics
- [x] 1.875 - 2.5m Titan IIIE fairing base adapter
- [x] 1.875 - 2.5m Commercial Titan 3 fairing base
- [x] Standalone engine shroud

TITAN IV:
- [x] First stage tankage
- [x] Second stage tankage
- [x] 1.875m > 3.125m fairing base adapter 

SRMS:
- [x] SOLTAN
- [x] SRM decoupler
- [x] UA1202
- [x] UA1203
- [x] UA1204
- [x] UA1205
- [x] UA1206
- [x] UA1207
- [x] UA1208
- [x] Nose cone (1.875m)
- [x] Nose cone (1.5m)
- [x] Sepratron pack

SRMUS:
- [x] SRMU (Titan IV)
- [x] SRMU (3 seg)
- [x] SRMU (Inline, single segment)
- [x] SRMU (Inline, half segment)

TRANSTAGE:
- [x] Transtage (engines + tanks combined in one part this time)
- [x] Transtage linear ACS
- [x] Transtage 3-way ACS
- [x] Transtage 2-way ACS
- [x] Transtage ACS quad
- [x] Transtage radial ACS
- [x] Transtage engineering antenna

INERTIAL UPPER STAGE:
- [x] Orbus 21
- [x] Orbus 6
- [x] IUS interstage
- [x] IUS Avionics/Control Block
- [x] TOS Avionics/Control Block

GENERIC PARTS:
- [x] New 1.875m generic decoupler
- [x] New 1.875m generic fairing base
- [x] 1.875m > 1.5m adapter (two lengths like before?)

**Comment by Pappystein** [comment]
Since I don't see an existing part...  MkIV RV and hopefully you will consent to a Mk 6 RV.  I use the Mk IV for gathering all sorts of Impact science on whatever planet I am launching it from.   set to be highly survivable (no parachute needed here!) and set to NOT allow science to be broadcast from it (Recovery is the only option.)    Preferably these things would SINK and not float

**Comment by Pappystein** [comment]
Also recommend that the adapters to RVs have a basic Control system in it (no SAS just basic pilot function.)  D/L range should be 2/3rds planet based broadcast antenna range (I don't remember km distance off the top of my head.)

**Comment by CobaltWolf** [comment]
The emissive on the engines needs to be adjusted so the interior is a deep red instead of the yellow/white, it looks weird as it fades in an out. The white>yellow>orange gradient will be moved, probably just elsewhere on the Titan engine texture sheet, so that the two effects are more separated. That will look a lot better.

The AO on the gimbal struts (at least on the LR-87) needs to be removed so you can't see the blackened tip appearing and disappearing constantly.

I'm getting super bad z-fighting on the engines at low altitude but apparently that might be a side effect of me apparently still running 1.5.1.

I have only found evidence of flight LR-91s flying with the brown/orange bell and not a white one. I am thinking of making it brown, and then using a white strip around the bottom edge of the LR-91-AJ11 to make it seem a bit more visually... idk, perky? and thus seem a little better than the AJ5.

@Pappystein I'm not planning on making RVs this time around. After I made the original parts I took a class on the aftermath of nuclear war (I don't know why I consented to that, guess I wanted an easy credit in exchange for mild PTSD) and now the idea of people making nukes with my stuff throws me off a little. I'm still considering making all the little SRBs for the Titan II just to have them... I feel like having more complicated staging isn't necessary in KSP but it's certainly fun.

**Comment by jsolson** [comment]
Titan IIIE Centaur Fairing adapter. On the real one the boattail fits over the Centaur interstage. I don't see how we can do that. We're going to need to fit the 1.875m interstage inside a fairing adapter with an 1.875m trunk. I'm thinking it could taper from 1.875 to 1.9 or something. It needs to be just wide enough so the interstage doesn't bleed through.

The 14 foot fairing works out to 2.62m in KSP. It's an odd size, but it should fit 2.5m parts inside. Since it doesn't interface with anything I don't see any reason the fairing width needs to be a standard size.

Dimensions here are taken from the real adapter and scaled for KSP. The top of insterstage sits higher than the top of the boattail.

![Untitled](https://user-images.githubusercontent.com/16825376/55031826-dc154f80-4fe5-11e9-8d16-82231bb7b41d.png)

**Comment by CobaltWolf** [comment]
On the real one there is sort of a conical interstage that comes up/inwards from the point the angled comes out, I think.

**Comment by CobaltWolf** [comment]
more notes for myself...

Apparently FX are fine for switching, I can add nodes for exhaust plumes on the LR-87 variants if you'd like. I already bounced it off Zorg a little.

You wore me down Jso, I'm definitely going to chop up the second stage a bit... I'll see what I can do.

**Comment by CobaltWolf** [comment]
Just saw your edit:

I'd like Transtage to just stay as a 1.875m decoupler and autoshroud. I don't know what to do with Agena because I don't want to go down a rabbit hole of fixing stuff right now. For IUS see below. Extra nodes are definitely doable.

By common straight simple fairing, you mean just a 1.875m fairing base? Yeah I want to make a new generic one. The Atlas stuff isn't quite what I want from generic 1.875m parts.

It's no big deal to get the Centaur to fit inside a fairing base like that. It's ok to have slightly overhangs on parts when it fits. The Ablestar is going to have to have an inverse - the top won't be perfectly 0.9375m but it looks much more accurate. There are overhangs like that on some of the IRL Titan fairing bases.

Yeah, the fairing base diameter can just be like 2.65m or something.

Thank you for the dimensions.

I'm not sure what you mean about the CT-3 fairing.

Yeah, aside from a wider fairing diameter (I guess it should be more like 3.2m or something otherwise it can't really carry a bigger payload, huh?

The IUS-Titans were all for spook work, so pics of the IUS in the Titan configuration are hard to find. Here's the best reference I have, from Raidernick's mod. The Centaur truss is what broke my art block. I say just give the Orbus 21 a straight 1.5m autoshroud and an angled 1.875m autoshroud and call it a day?

http://i.imgur.com/ZJGGMbT.png

**Comment by jsolson** [comment]
Yes, Transtage is just decoupler and autoshroud. If you don't want to muck with Agena, we can get away with using the 1.875 fairing base as an interstage. It works well. Just requires a little more work from the user.
![Untitled](https://user-images.githubusercontent.com/16825376/55247587-6811bc00-521e-11e9-8251-951cf293b517.png)

Yes, common straight simple generic 1.875m fairing base. Just a ring or flat plate, nothing fancy.

'We can reuse the Titan IIIE fairing for CT-3 if you want. Best I can tell from pics the CT-3 fairing does not have that lower 1.875m straight section the centaur fits in. It's just the boattail.

The Titan IV fairing works out to be a hair less than 3.125, so it would fit 2.5 with stuff hanging off. I don't think we need to go bigger. Centaur might start to look funny.

**Comment by CobaltWolf** [comment]
@jsolson I got some more progress done on the Titan IV upper stage tank and got some texturing work started on the T3E fairing base and T4 fairing base. I hate the textures I have so far for all of them. 😛 That's in addition to getting the AJ11 engines in game.

I'm still not happy with the second stage tank textures if I'm honest. They still feel like just a cylinder with a bunch of disconnected greebles slapped on.  I'm kinda just trying to push stuff through and then the stuff with the worst textures can be looked at again. I didn't mean to push that variant texture into the github so ignore it for now.

I kinda want to try and model the internals of the avionics truss, but it might not be worth the effort especially if we can't find more reference for it.

I don't think there is enough different in the Titan IV first stage tanks to justify making new tanks/textures from scratch - what do you think? I could basically do the same stretch as the Titan IIIM tank (basically stretch the middle areas that don't have any real variation so the stretch isn't noticeable) but it would apply to both the first stage tanks and not just the top one. That also means we don't have to have another set of texture sheets for those parts - that'll be a big savings on memory/download size. I also say it because having to do all the texture work for the second stage over again for the upper stage has been miserable and I don't want to have to do it for the first stage too.

I wanted to ask about the SRB decoupler. Do you have any feelings on how to design that? I kind of want to do it the way I've seen some others do theirs - sort of a long, thin stick that would sort of be hidden once attached, and then the top and bottom would have the struts like on the real rocket. That means I don't have to include the struts in the models of the SRBs themselves (which will save me a lot of room on the texture sheets due to not having to bake that AO into the texture, means I can be more efficient with how I re-use that space). And then I can make a switcher, kinda like how Modular Launch Pads works, that would let us set a bunch of different lengths (or rather, spacings between the top struts and bottom struts) for the different booster lengths. It wouldn't be especially lego-friendly but it would be great for dedicated 1.875m > 1.875m attachment, which it's already specialized in anyways. If that doesn't make sense I can mock it up for you.

I am getting burnt on these cores, I think I need to switch to starting the SRBs for a bit if that's ok with you. If only just to start getting a better feel for how it all fits together.

**Comment by jsolson** [comment]
The SRBs actually need the struts though, and they're not hard to place nicely.

![Untitled](https://user-images.githubusercontent.com/16825376/55354340-7e747d80-5493-11e9-87dc-8fac63cba5a0.png)

Length issues aside I think stage 2 looks good.

Other than the two racks on either side of the interior of the Avionics bay I don't think you need to worry about details. It looks like the kind of place someone might try to stuff something into.

**Comment by CobaltWolf** [comment]
Yeah but it would be nicer to have it be guaranteed that the struts would be nicely horizontal and symmetric every time. Autostruts are the standard nowadays anyways, you don't need to allow for the actual struts. It's not without precedent, mods like Tundra have decouplers built like that. There's enough of a strip to make it placeable and such.

**Comment by CobaltWolf** [comment]
I'm going to play around with the SRBs next time I sit down to work, so I'll be able to mock it up for you.

**Comment by jsolson** [comment]
Position of upper and lower SRB struts. Upper struts attach at the Stage 1/2 sep point (top of the LR-91 shroud). Applies to UA1205 on normal first stage and UA1206 with stretched first stage. The UA1207's attach higher, midway up the Titan IV second stage.

![Untitled](https://user-images.githubusercontent.com/16825376/55800649-36acb200-5aa2-11e9-9bfc-38480b784a56.png)

**Comment by longlong2002** [comment]
missile adapter/fairing base for titan ii rockets you can make blok upper stage

**Comment by Pappystein** [comment]
Answering a question posted in inital post.    LR87-AJ-11A engine... is it worth doing?  Yes as a Part upgrade late in the tree.

HOWEVER I do think the LR87-AJ-9 should be separate from the AJ-11 (they can use the same model as they look almost exactly the same.)  There is a rather large performance disparity between the two of them due to the different pumps and engine bells.   

So that means first stage Titan II/III/IV rockets.
choice of 3 engines (LR87-AJ-5/7, LR87-AJ-9, or LR87-AJ-11)   

The AJ-5/7 is name only change so should be one part with mention of both versions

-9 is tough because it only flew on all but 3 of the 1st generation Titan IIIs and was not used after.... 

AJ-11 should be the mainstay Titan 23 and later engine.

**Comment by Pappystein** [comment]
Adding post for the LR91 as it is significantly different than how the LR87 was evolved:

Titan II/GLV fly the LR91-AJ-5 or AJ-7 engines in their second stage.   The Early Titan IIIs flew LR91-AJ-9 which is essentially identical to the -5/-7.   The Late Titan IIIs as well as the IV flew the LR91-AJ-11 which is still pretty close (<5% IRL thrust increase according to Astronautix.)

**Comment by CobaltWolf** [comment]
I'm still pretty opposed to having parts that reuse the model of something else. If it isn't visually distinct, it should be a part upgrade. Moreover, considering how nearly identical the -AJ9 is stat-wise to the -AJ7, I don't see a need to include it especially with the mesh switching to give it the Titan 3 style shroud.

**Comment by longlong2002** [comment]
almost finished Titan redux

**Comment by SilveiraMarcel** [comment]
I think the new Titan adapters could have a middle node so they could store a secondary payload or whatever. I made some changes in the cfgs to accommodate that new node.

at part Titan/bluedog_Titan1_StructuralAdapter
`MODULE
	{
		name = ModuleB9PartSwitch
		moduleID = meshSwitchLength
		switcherDescription = Length
		affectDragCubes = False
		affectFARVoxels = False
		
		SUBTYPE
		{
			name = Long
			transform = Long
			NODE
			{
				name = bottom
				position = 0.0, -0.75556, 0.0
			}
			NODE
			{
				name = middle
				position = 0.0, -0.70556, 0.0
			}
			NODE
			{
				name = top
				position = 0.0, 0.75556, 0.0
			}
		}	
		
		SUBTYPE
		{
			name = Medium
			transform = Medium
			NODE
			{
				name = bottom
				position = 0.0, -0.4, 0.0
			}
			NODE
			{
				name = middle
				position = 0.0, -0.35, 0.0
			}
			NODE
			{
				name = top
				position = 0.0, 0.4, 0.0
			}
		}	
		
		SUBTYPE
		{
			name = Short
			transform = Short
			NODE
			{
				name = bottom
				position = 0.0, -0.2, 0.0
			}
			NODE
			{
				name = middle
				position = 0.0, -0.15, 0.0
			}
			NODE
			{
				name = top
				position = 0.0, 0.2, 0.0
			}
		}	
	}`

at part Titan/bluedog_Titan2_S2_1p25mAdapter
`
	node_stack_top = 0.0, 0.32986, 0.0, 0.0, 1.0, 0.0
	node_stack_middle = 0.0, -0.28986, 0.0, 0.0, 1.0, 0.0
	node_stack_bottom = 0.0, -0.32986, 0.0, 0.0, -1.0, 0.0`

Another change I made is to the old Titan I RV (or nose probe). I added some lead to it so it could be used to test and "calibrate" launch vehicles.
at part Titan/Old/bluedog_Titan1_NoseProbe

'
	RESOURCE
	{
		name = Lead
		amount = 0
		maxAmount = 300
	}'

**Comment by SuchIlluminati** [comment]
Not sure if this is the correct place to post this, but the top and bottom attachment nodes on the Titan III-3080 fuel tank (the extended 1st stage one) are a bit too high up. Anything attached to the bottom of it clips into it and anything attached to the top floats above it. Picture: https://i.imgur.com/DGMNV5J.png

**Comment by CobaltWolf** [comment]
Yeah I accidentally re-exported it slightly offset trying to fit *another* bug the other night. I need to fix it, should be easy. Thanks for reporting. :)

**Comment by CobaltWolf** [comment]
@jsolson @Pappystein  do you think we could add an abort mode to the UA120s? It would blow open the two holes on the SRB nose cone but we can just make it come out the top of the UA120 from two directions. I think it would be both cool and useful.

**Comment by Pappystein** [comment]
I am all for an Abort mode.  I just crashed my Gemini 23C-6 + Lander single rocket :(
The SRMs ended up causing most of the destruction... an abort mode would have reduced the damage and I could have completed the 2nd stage as an Abort to Orbit

**Comment by longlong2002** [comment]
all Titan revamp is done
