### ISSUE TITLE
probe core validation

### ISSUE THREAD

**Issue by JadeOfMaar** [CobaltWolf/Bluedog-Design-Bureau#521]
@jsolson It's been discovered that all probe core parts need to have the ship type key in them in order to operate correctly (this may be new to KSP 1.6 and part of the change to `ModuleSAS{}` in the changelog for the relevant version of KSP).
Its layout is like this:
```
PART
{
    name = x
    VesselType = y
    ...
```
Where y is any one of these: `Probe, Relay, Base, Lander, Plane(?), Station, Rover, Debris, Ship(?)`

**Comment by jsolson** [comment]
Everybody has a vessel type. Found a bunch of missing bulkead profiles though.
