### ISSUE TITLE
Delta II interstage top node

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#525]
The top node hovers above the part. Other interstages have the top node flush with the top of the part. This makes mix and match awkward.

**Comment by CobaltWolf** [comment]
I'll check, it might have shifted during all the re-exporting. Thanks for catching it.

**Comment by jsolson** [comment]
It's probably like that because the two bottom nodes on the fairing base would be in exactly the same location otherwise, but I can't see the harm in that.

**Comment by CobaltWolf** [comment]
is that where it attaches? I don't think I've thought about how that model goes together in a long time...

**Comment by CobaltWolf** [comment]
gotcha

**Comment by jsolson** [comment]
I got it

**Comment by CobaltWolf** [comment]
Thanks
