### ISSUE TITLE
Add support for an unmanned, Apollo 5-style LM

### ISSUE THREAD

**Issue by sundhaug92** [CobaltWolf/Bluedog-Design-Bureau#536]
Minimum version: Add probe module to the LM cockpit
Medium version: + Probe-only version unlocked earlier than crewed version (to emulate Apollo 5)
Full version: + Separate, legless version of the descent module

**Comment by sundhaug92** [comment]
This would also add support for de-orbiting the LM after a crewed mission

**Comment by jmrd98** [comment]
Options one and two can easily be done as a MM patch, for the extras folder at the very least. I just don’t have the time to do it at the moment. @sundhaug92 , an opportunity knocks!

**Comment by sundhaug92** [comment]
@jmrd98 I'm looking into doing it now, perhaps have the bells-and-whistles version as an upgrade as I'm not sure if variants can be unlocked separately and in other ways be more than "just" graphical

**Comment by jsolson** [comment]
While it would be useful, I'm a little hesitant because you can make the case that every manned craft had an unmanned test.

The LEM is battery powered. Do we know if the probe core would draw power while it's manned?

**Comment by sundhaug92** [comment]
@jsolson Fair point, though it does mean the LM gains the ability to be used in realistic impact-experiments (and cleaning up save-files). The simplest solution would be to say the probe-core doesn't draw extra power, and just _is_.

To do this, it seems to me the change would be to set minimumCrew to 0 for ModuleCommand, as well as adding the SAS upgrades. I'm not sure it's possible to have a "If this part is crew, EC-draw should be this, otherwise it should be this" without making a DLL, but I must admit my experience in making mods for KSP is severely lacking.

**Comment by jmrd98** [comment]
It looks like the part variant system may be able to do this, but I’ve not tried. You’d end up with something like a manned variant with a probe core that had no draw, but needs a pilot, or a seatless variant with a “working” probe core.

I’m entirely guessing from the variant example that google-fu rendered.

**Comment by jsolson** [comment]
>The simplest solution would be to say the probe-core doesn't draw extra power, and just is

>To do this, it seems to me the change would be to set minimumCrew to 0

No need for more variants, that solution would suffice. The LEM already has lunar and orbital variants.

**Comment by sundhaug92** [comment]
@jsolson You mean the CSM has lunar and orbital variants? I think the LM should have a SAS, but perhaps only the very basic stuff (maybe pro/retro hold, probably not anything fancier)

**Comment by sundhaug92** [comment]
@jsolson Huh, just didn't find a reference to it. 

Have begun on a branch, just not sure if it's possible to disable Crew Reports while it's unmanned

**Comment by sundhaug92** [comment]
Found ref now, it's using B9 partswitch

**Comment by sundhaug92** [comment]
After research, it seems these are the options:
* Upgrades: Enables support for a separate Apollo 5-style no-crew LM. Choice between no remote-control of the crewed LM or crew-reports without crew. No support for using an uncrewable LM after the upgrade.
* Variants: More or less just graphical changes, can't be unlocked.
* B9 fuel switcher: More or less "just" different tanks, can't be unlocked
* ModuleManager: Pros: Separate part based on the original, can be unlocked and have no experiment. Cons: Separate part.

It should be possible to have a separate assembly which essentially says "If there's crew in this module, it should have crew reports, otherwise not", but that requires more work. For now, my work just ignores the crew-report issue.
