### ISSUE TITLE
LEM / Full SLA catastrophic separation

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#538]
When attached to an S4B with a Full SLA, decoupling the LEM causes the S4B to explode and the LEM tumbles away.

When attached to the other two SLA bases, with zero decoupler force, the LEM is pushed away indicating some small amount of clipping. It might be clipping into the top of the tank, I didn't check without the tank. _Edit: It's the IU, and maybe the tank a little. With just the SLA it hardly moves at decoupling._

The LEM legs hang below the bottom of the SLA bases into the IU. Check colliders.

**Comment by CobaltWolf** [comment]
the IU might have a pancake collider instead of a ring. I'll have to look at it
