### ISSUE TITLE
Tweakscale for retrotrons

### ISSUE THREAD

**Issue by SilveiraMarcel** [CobaltWolf/Bluedog-Design-Bureau#540]
The PDC-L Lateraltron and the PDC-P Perfectron solids do not have tweakscale compatibility. It can be fixed by adding this to the Compatibility/TweakScale/tweakscale_Engines.cfg

`@PART[bluedog_Lateraltron|bluedog_Perfectron|]:NEEDS[TweakScale]
{
    #@TWEAKSCALEBEHAVIOR[SRB]/MODULE[TweakScale] { }
    %MODULE[TweakScale]
    {
        type = free
    }
}`

Atlas V retro could use some tweakscale;
`@PART[bluedog_AtlasV_Star5F]:NEEDS[TweakScale]
{
    #@TWEAKSCALEBEHAVIOR[SRB]/MODULE[TweakScale] { }
    %MODULE[TweakScale]
    {
        type = free
    }
}`

And the Mercury kick motor could have _free_ tweakscale type instead of _BluedogStack_ type with a diameter of .10m
`@PART[bluedog_mercury_posigradeMotor]:NEEDS[TweakScale] //Hermes M-PM "Zoot" Kick Motor
{
    #@TWEAKSCALEBEHAVIOR[SRB]/MODULE[TweakScale] { }
    %MODULE[TweakScale]
	{
		type = free
	}
}`

**Comment by jsolson** [comment]
Fixed, Thanks!
