### ISSUE TITLE
Re-Implement Realnames/Tweakscale

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#547]
Original discussion: https://github.com/CobaltWolf/Bluedog-Design-Bureau/pull/533#issuecomment-460066898

Realnames:

- [x] APAS
- [X] Agena
- [x] Antennas
- [x] Apollo
- [x] Atlas
- [x] AtlasV
- [x] Centaur
- [x] Delta
- ~~Diamant~~
- [x] EarlyRockets
- [x] Engines
- [x] Explorer
- [x] Gemini
- [x] Generic [ left as is]
- [x] Juno
- [x] LDC
- [x] LaunchClamps
- [x] Mercury
- [x] ProbeExpansion
- [x] Saturn
- [x] Science [decided to leave these as is]
- [x] Skylab
- [x] Solids
- [x] Titan
- [x] Vega

**Comment by zorg2044** [comment]
I'll also be contributing to this effort whenever I can get some time. After discussion with CobaltWolf I have changed the patch condition to ``:NEEDS[BDB_RealNames]`` and I've moved the patch into a folder named the same in ``BDB_Extras/Gamedata``

RealNames for B9 engine switch subtypes are also being implemented in a similar manner. A ``real_title`` and ``real_descriptionSummary`` field is being added to each subtype.

**Comment by friznit** [comment]
@zorg2044 

Realname for Thor Interstage is incorrect.  _Thor Short 1.25m to 0.9375m structural adapter_ - should be _Thor 0.9375m Interstage_

https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/8bb9df46c4874924e75d8f4febcd231818a7f5f7/Gamedata/Bluedog_DB/Parts/Thor/bluedog_Thor_0p9375mInterstage.cfg#L22

Also the realname of _BSA-0100-0050 - Fenris-80 Structural Adapter_ is a bit confusing (Thor _Long_ 1.25m to 0.9375m structural adapter) given it's shorter than the Able adapter and the only one in it's class (unless new ones are going to be added, I was looking for the short & medium ones...) - maybe just remove the word _long_.

**Comment by zorg2044** [comment]
Thanks, made the corrections
