### ISSUE TITLE
Vernier/LES Engines not showing plume effects

### ISSUE THREAD

**Issue by Redleg1** [CobaltWolf/Bluedog-Design-Bureau#549]
Wondering if anyone has the issue with numerous engines including Vernier engines and Launch Escape System motors not displaying exhaust plumes with RealPlume?

**Comment by jsolson** [comment]
Installed realplume to check. It's working fine for me. There was a change that had to be made for the LES plume for KSP 1.4. If you've got an old version of BDB running on KSP 1.4+, or the latest BDB running on KSP 1.3.1 you'll probably have an issue with the LES plume.
