### ISSUE TITLE
Mis-aligned thrust vectors

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#555]
Agena SPS and Juno 6K verniers have screwed up positioning on the thrust vectors.

![](https://user-images.githubusercontent.com/39182212/55303247-6fbfa380-545e-11e9-8190-32cf7a99d1db.png)

**Comment by CobaltWolf** [comment]
is it positioning or...?

**Comment by jsolson** [comment]
nm
