### ISSUE TITLE
LH2 only tank option [request]

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#558]
Having an LH2 only option in the tank switcher would be quite a nice addition to enable the use of nuclear engines with BDB tankage (nuclear SIV-B/C anyone?).

It would be a trivial addition and open up some interesting alt-history concepts :)

**Comment by jsolson** [comment]
The tank type is in there, it's just unused. Something I've considered doing is replacing the MonoProp type with LH2 only in tanks larger than X. Small LH2 tanks are about as useless as large MonoProp tanks.

**Comment by SilveiraMarcel** [comment]
I would suggest to keep both, regardless of tank size. It's easy to change between tank types using B9PartSwitch, it doesn't clog the part menu to add an extra tank type and it gives more uses (exotic ones) to the part. If the user wants to add 150 small LH2 tanks, well... I'm okay with that, it's their craft

**Comment by CobaltWolf** [comment]
I agreed with @SilveiraMarcel , if it's trivial to add (you don't have to define the numbers for every individual variant of every part right? it's all ratios based on the default stats in the part cfg?) then it's not us to say what players can and can't do.

**Comment by jsolson** [comment]
It's trivial enough.
