### ISSUE TITLE
Titan II LR87-AJ5 attach node issue [dev branch]

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#561]
All variants of the Lr87-5 currently clip into the tank. 

Issue is confirmed to be with the engine and not the tank. LR87-11 is fine.

![Screenshot 2019-04-24 21 39 08](https://user-images.githubusercontent.com/39182212/56677382-de98c100-66d9-11e9-933a-da63f8ec519e.png)

![Screenshot 2019-04-24 21 39 16](https://user-images.githubusercontent.com/39182212/56677386-e0628480-66d9-11e9-8c1d-899d54a35fdc.png)

![Screenshot 2019-04-24 21 39 23](https://user-images.githubusercontent.com/39182212/56677400-e5273880-66d9-11e9-987e-8edda33c7cfe.png)

![Screenshot 2019-04-24 21 41 12](https://user-images.githubusercontent.com/39182212/56677409-ee180a00-66d9-11e9-9581-fd62c66fefae.png)

**Comment by jsolson** [comment]
Confirmed

**Comment by CobaltWolf** [comment]
I'll take a look. it probably got shifted vertically and I didn't notice when reexporting to fix something else.
