### ISSUE TITLE
Fuel cells

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#57]
Suggestion. An inline fuel cell for Agena.

**Comment by CobaltWolf** [comment]
Did Agena have fuel cells?

**Comment by jsolson** [comment]
No. But ksp doesn't simulate electric use realistically at all. We need alternatives to long term battery use.

I ran out of juice in less than an orbit last night, thus something must be done! Agena seems to use it fast, not sure why, maybe reaction wheels.

**Comment by VenomousRequiem** [comment]
Yeah, i second this. Plus it'd make Agena longer so you wouldn't have to put a second probe core down to make it its actual scaled length.

**Comment by CobaltWolf** [comment]
@jsolson I can look into it. I think in general the large 'instrument unit' cores should have their EC buffed. 

I will see how much texture room I'll have. I'll likely have a little to spare on that second Agena texture sheet once the ADTA RCS is done.

**Comment by jsolson** [comment]
Want to close this or try something different? I kind of like it on the D engine. It makes it special and hi tech since we can't add restarts.

**Comment by CobaltWolf** [comment]
Yeah I think this is fine now.

**Comment by CobaltWolf** [comment]
I'm going to try and make the changes to the D engine I mentioned in the other post.

**Comment by CobaltWolf** [comment]
[Just through it together real quick. ](http://i.imgur.com/7jYzB53.png)Thoughts?

**Comment by jsolson** [comment]
I like that a lot. Just make sure the fuel cell is on the bottom. That pair of tanks on top is an extremely prominent feature.

**Comment by CobaltWolf** [comment]
You mean top as in farther from the bell?

**Comment by jsolson** [comment]
The skyward side if you launched from the runway. I don't mean closer to the pointy end.

**Comment by VenomousRequiem** [comment]
Why can't we just resort to actual side names. Port, starboard, aft, forward, zenith and nadir. Spit it out man! :b

**Comment by jsolson** [comment]
My starboard usually faces zenith in orbit, and forward faces it at launch. Either way you've got gimble lock!

**Comment by CobaltWolf** [comment]
I have no idea what y'all are saying

**Comment by CobaltWolf** [comment]
iirc the new mesh was added in the commit I pushed last night.
