### ISSUE TITLE
Gemini Lander Bugs

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#576]
- [x] Legs don't default to being part of the gear group
- [x] No animation on the mini goo
- [x] All parts still need name and description
- [x] RCS on the saddle tanks is broken for forward/backwards
- [x] Saddle tanks don't have proper fuel distribution
- [x] Low profile port doesn't work
- [x] Leg mass too low?
- [x] Make ladder on frame toggleable

**Comment by roryyamm** [comment]
Also, nullref errors. Specifically this one over and over again:
```
    ModuleDockingNode.FixedUpdate ()
[EXC 10:43:14.012] NullReferenceException: Object reference not set to an instance of an object
    ModuleDockingNode.CheckDockContact (.ModuleDockingNode m1, .ModuleDockingNode m2, Single minDist, Single minFwdDot, Single minRollDot)
    ModuleDockingNode.FindNodeApproaches ()
    ModuleDockingNode.<SetupFSM>m__1 ()
    KerbalFSM.FixedUpdateFSM ()
    ModuleDockingNode.FixedUpdate ()
```

**Comment by CobaltWolf** [comment]
Decided it will be called the Dona Mini Lander

**Comment by Sgt-Shutesie** [comment]
IVA is Backwards
