### ISSUE TITLE
Engine Ignitor Compatibility

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#580]
There is an existing patch for BDB but it would be cool if someone ever took the time to either submit a PR to them or fold them into our own compatibility files. The current patch is just thrown together. Finding restart info for most of the engines in BDB should be doable, and you can assume that pretty much any SL engine cannot be restarted. 

https://github.com/linuxgurugamer/EngineIgnitor/blob/master/GameData/EngineIgnitor/MM_Configs/MM_Bluedog.cfg

**Comment by Rock3tman** [comment]
Past couple of commits have been these revisions. At some point LGG needs to be contacted about those so the BDB configs can be taken out of engineignitor mod

**Comment by IronCretin** [comment]
Once the configs are in BDB make a pull request to engineignitor

**Comment by zorg2044** [comment]
- [ ] Configs for LR91 alternate variants.

**Comment by zorg2044** [comment]
Everything needed for this update is now complete. Just changed most SL engines to use external ignition capability (except Titan and such). This means a launch clamp is needed to ignite them. BDB's own clamps have been patched to have the external ignitor module added. Engines will ignite if clamp is placed within 30m of the engine.

Modular Launch Pads do not have this capability at time of writing but a PR has been opened to Engine Ignitor which will add that module.
