### ISSUE TITLE
Kane Docking Adapter - 0.9375m adapter messes up placement of LES

### ISSUE THREAD

**Issue by blowfishpro** [CobaltWolf/Bluedog-Design-Bureau#581]
The offset tool is enough to deal with it for now, but it would be great if it had an alternate node (or something else) that put it in the correct position.
![image](https://user-images.githubusercontent.com/10545461/62428334-6ae15980-b6b5-11e9-9fd3-3446f08087e0.png)
![image](https://user-images.githubusercontent.com/10545461/62428337-70d73a80-b6b5-11e9-82c9-3390a99ea246.png)

**Comment by jmrd98** [comment]
I think I've looked at this. Don't you get clipping in some way shape or form no matter what? Adding a node wouldn't be hard though.

**Comment by blowfishpro** [comment]
I haven't looked at how much clipping happens inside with the LES offset.  It's certainly not visible externally though.

**Comment by CobaltWolf** [comment]
This should be fixed but I need confirmation.
