### ISSUE TITLE
REVAMP: Probe Parts

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#584]
LUNAR ORBITER:
- [x] Probe Core
- [x] Propulsion section
- [x] Solar Panel (side fold)
- [x] Solar Panel (under fold)
- [x] Camera (replaces existing medium tech camera)
- [x] Omni Antenna
- [x] Dish

RANGER/MARINER 2 SHARED:
- [x] Ranger/Mariner Core
- [x] Ranger Solar Panel
- [x] Course Correction Motor
- [x] Battery
- [x] Dish
- [x] Omni Antenna
- [x] Cosmic Dust Detector Experiment
- [x] Decoupler
- [x] Payload deck
- [x] Bare core

RANGER BLOCK 1:
- [x] Truss
- [x] Electrostatic Analyzer Experiment
- [x] Electrostatic Analyzer Device 1
- [x] Electrostatic Analyzer Device 2
- [x] Lyman Alpha Telescope

RANGER BLOCK 2: 
- [x] TV Experiment (worse version of the Ranger Block 3 experiment?)
- [x] Radar Altimeter Experiment
- [x] Gamma ray spectrometer Experiment
- [x] Rough Lander
- [x] Omni Antenna
- [x] Decoupler / thermal shroud

RANGER BLOCK 3:
- [x] RCA TV Experiment

MARINER 2:
- [x] Mariner 2 Truss
- [x] Mariner Solar panel (basic)
- [x] Mariner Solar panel (antenna)
- [x] Microwave/Infrared Radiometer Experiment
- [x] Combined Ion trap / particle flux Detector Experiment

MARINER B:
- [x] Mariner B Truss
- [x] Mariner B Solar Panel
- [x] Mariner B Bus

Pioneer Venus:
- [ ] Main bus / probe core
- [ ] Equipment Deck - Orbiter
- [ ] Equipment Deck - Multiprobe
- [ ] Orbiter High gain antenna
- [ ] Orbiter Magnetometer 
- [ ] Orbit insertion solid motor
- [ ] Orbiter UV Spectrometer
- [ ] Orbiter Photopolarimeter
- [ ] Orbiter Retarding Potential Analyzer
- [ ] Orbiter Mass Spectrometer
- [ ] Orbiter Thermometer Extending Probe
- [ ] Orbiter Thermometer Fixed Probe
- [ ] Orbiter Electric Field Detectors
- [ ] Orbiter Radar Altimeter
- [ ] Low Gain Antenna
- [ ] Small probe
- [ ] Large probe
- [ ] Multiprobe Horn Antenna
- [ ] Multiprobe Forward Omni

Mariner 10:
- [x] Probe Core
- [x] Solar Panels
- [x] Low gain antenna
- [x] Course correction engine
- [x] deployble sunshade
- [x] High gain antenna
- [x] Magnetometer
- [x] Science pallete
- [x] Charged particle telescope
- [x] UV Spectrometer
- [x] Plasma science experiment
- [x] Star Tracker ?
- [x] Camera system (best? TV experiment in the mod)
- [x] Standalone camera
- [x] Spacecraft adapter

RCS ADDON:
- [x] Linear Probe RCS
- [x] Double Linear Probe RCS
- [x] Radial Probe RCS
- [x] Two Way Probe RCS
- [x] Two Way 45 Degree Probe RCS
- [x] Three Way Probe RCS
- [x] Three Way 45 Probe RCS
- [x] Three Way Probe RCS
- [x] Three Way Radial Probe RCS
- [x] Four Way Probe RCS
- [x] Four Way 45 Degree Probe RCS
- [x] Small Pill Mono Tank
- [x] Triple Pill Mono Tank
- [x] Radial Spherical Tank

OGO:
- [x] Core
- [x] Solar Panel
- [x] Solar Panel with Antenna
- [x] Attitude Boom
- [x] Payload Adapter
- [x] High Gain Antenna
- [x] Tri-axial search coil magnetometer (hoop)
- [x] Gamma ray spectrometer (ball)
- [x] OPEP
- [x] EP 1 (includes omni antenna)
- [x] EP 2
- [x] EP 4

SCIENCE:
- [ ] Micrometeoroid Detector
- [ ] Geiger Counter
- [ ] Ion Trap
- [ ] Low Tech Camera
- [ ] Infrared Spectrometer
- [ ] Mass Spectrometer
- [ ] Hydrometer
- [ ] Photometer

EARLY PROBES:
- [x] Explorer 7
- [x] Explorer 8
- [x] Explorer 11
- [x] Crossed Dipole Antenna
- [x] 0.125m Probe Decoupler
- [x] Explorer S-45
- [x] Explorer S-46
- [x] Pioneer 1
- [x] Pioneer 1 vernier solids
- [x] Pioneer 4

IMP AND AIMP:
- [x] IMP/AIMP Core
- [x] IMP/AIMP Antenna
- [x] IMP/AIMP Solar Panels
- [x] IMP/AIMP Magnetometer Boom
- [x] IMP Rubidium Magnetometer
- [x] AIMP Star-13
- [x] AIMP Star-13 Decoupler
- [x] Mini Flipping Solar Panel (Texture revamp, uses space leftover on the AIMP texture sheet)
- [x] Mini Static Solar Panel (Texture revamp)

EARLY COMMUNICATIONS SATELLITES:
- [x] Telstar core
- [x] Telstar Antenna
- [x] Relay Core
- [x] Relay Antenna
- [x] Courier

NIMBUS:
- [x] Payload Torus
- [x] Payload Deck
- [x] Truss
- [x] Early control section
- [x] Early command antenna
- [x] Late control section
- [x] Late command antenna
- [x] Solar Panel
- [x] Decoupler
- [x] THIR Instrument
- [x] S-Band Antenna
- [x] ERB Experiment
- [x] SAMS Experiment
- [x] SCMR Experiment
- [x] Nimbus 5 ESMR Experiment
- [x] Nimbus 7 ESMR Experiment
- [x] Satellite Infrared Spectrometer

PIONEER P3
- [x] Pioneer P3 Solar Paddles
- [x] Pioneer P3 Core
- [x] Pioneer P3 VLF Antenna
- [x] Able 4 Engine

OAO
- [x] OAO probe core
- [x] OAO 2 UV telescope block
- [x] OAO 2 TV camera block
- [x] OAO 3 UV telescope block
- [x] OAO 3 lower block (extended service module?)
- [x] Star tracker large
- [x] Balance boom
- [x] Upper solar panel B9 switch for with (OAO 2&3) and without extension (OAO1)
- [x] Lower solar panel
- [x] straight variant of solar panels (b9)
- [x] Antenna
- [x] Spacecraft adapter

MISC:
- [x] Solar Battery Panels
- [ ] Small Klaw
- [ ] Big Solar Panels, big enough for the ion engine
- [x] OFO Experiment
- [x] OFO Antenna
- [x] OSO Spin weight
- [x] OSO Experiment (with sail)
- [x] OSO Experiment (standalone)
- [x] OSO Core

**Comment by zorg2044** [comment]
btw did you want to add an independent photometer to the science section? (using the Vanguard 2 experiment)

**Comment by CobaltWolf** [comment]
yeah I should

**Comment by longlong2002** [comment]
after Probe Parts compled should make revamp centaur parts

**Comment by friznit** [comment]
Minor bug: OGO-EP2 Gravimetric Scanner won't retract once deployed.

**Comment by Morphisor244** [comment]
Found a small issue of interaction between the Burke A27 C antenna and the Wayfarer 2 ETS radiometer. Turns out, the combination of the microwave experiment data size and the antenna packet size leads to a stock science bug where the science won't complete by transmission, even when it's all perfectly legit otherwise. 
Any other antenna works fine with the experiment.
I'll quote DRVeyl who explained it to me:

"Re: microwave experiment.  Stock science bug.  Floats incrementing from 0 in one counter and decrementing from <total data> in a separate method, you can get 0.0000001 remaining.  Very unpredictable when it will happen, depends on the combination of packetSize of your transmitter and the data size."
