### ISSUE TITLE
B9 Upgrade Conversions

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#591]
Existing upgrades that need conversion:
- [x] Able/Ablestar upgrade
- [x] Redstone upgrade        
Plume switch for Redstone upgrade between alcolox and hydyne [save for BDB 1.7]
- [x] Atlas upgrades
- [x] RL10 upgrades
- [x] E-1 upgrade
- [x] J-2  upgrades
- [x] H-1 upgrade
- [x] F-1 upgrade
- [x] LR-87-LH2 upgrades
- [x] Transtage upgrade
- [x] Deprecate sandbox patches.

New upgrades / option
- [x] Altitude optimized Castor 120
- [x] SR-118
- [x] Single and half seg SRMU altitude/SL variants. 
- [x] Incremental upgrades for the kick solids (Upgrade Altair to FW-4S for instance)[upgrades for Altair, Star 37BV, Star37FMV and Star 48]
- [x] RS27/RS27A switch
- [x] GEM 40 and GEM 46 ground lit + air lit 
- [x] Castor 4, Castor 4A

mesh switches to be combined with module switches for the future
- [x] GEM 40 and GEM 46 bigger nozzle for air lit 
- [x] SR118 - shorter length, less solid fuel.
- [x] Castor 120XL

If possible
- [x] Kerolox switch for hypergolic LR91s and 87s
- [x] support for new realnames patches for the B9 subtypes. (should be doable).

**Comment by zorg2044** [comment]
Need to redo RL10 upgrade stats.

**Comment by zorg2044** [comment]
RS-56 OSA upgrade to the Atlas sustainer for Atlas II? The booster engine has the RS56 OBA upgrade but not the sustainer.

**Comment by zorg2044** [comment]
Castor 120 switching:

Current config
-Thrust curve: steady drop 66. A dedicated but unused Castor 120 prefab exists.
- KSP stats: 280s/229s | 565kN/
- Corresponding IRL stats: 2,260kN/

Castor 120
-Thrust curve: currently uses steady drop 66. A dedicated but unused Castor 120 prefab exists.
-IRL stats: 280s/??? | 1957kN/??
- KSP stats: 489.25 kN

https://www.northropgrumman.com/Capabilities/PropulsionSystems/Documents/NGIS_MotorCatalog.pdf

Peacekeeper SR118
-Thrust curve - 
-IRL stats
- KSP stats

Castor 120 altitude optimised (For ETS Carrack)
-Thrust curve - 
-IRL stats
- KSP stats

**Comment by jsolson** [comment]
Atlas sustainer is already the RS-56. It would need to be downgraded then an upgrade added to get it to the current numbers. The differences are minor.

This is all probably breaking the sandbox patches a lot of people are using. They need to be depricated.

The thrust curve prefab code doesn't know about the B9 upgrade blocks. That needs to be sorted out. Preferably in a manor where the actual thrust curve is coded once and inserted where it's needed.

**Comment by CobaltWolf** [comment]
I dont really have a floor but I think there should be a minimum for performance increases. At least a 10% thrust change or at least 5 second ISP adjustment. Otherwise no point in spamming users with such minor upgrades

**Comment by zorg2044** [comment]
> Atlas sustainer is already the RS-56. It would need to be downgraded then an upgrade added to get it to the current numbers. The differences are minor.
> 
> This is all probably breaking the sandbox patches a lot of people are using. They need to be depricated.
> 
> The thrust curve prefab code doesn't know about the B9 upgrade blocks. That needs to be sorted out. Preferably in a manor where the actual thrust curve is coded once and inserted where it's needed.

Hi @jsolson :) Good news is that the sandbox patches don't seem to break critically (at least with the parts I've tried so far). Its redundant but users can transition by having the sandbox patches installed, then removing the sandbox parts in their craftfiles and replacing with the originals with module switch.

The way the B9 module switch works is also quite nice, it doesnt replace the entire EnginesFX module entirely for instance, it just swaps the specified values. So an engine with a a thrust curve applied via the existing MM patches can still get swappable ISP and thrust upgrades for instance.

For the Castors I am inserting the values from the prefab curves individually into each subtype. The Castor subtypes are not upgrade linked though.

Any thoughts on a dedicated version for the ETS Carrack second stage? I have a preliminary config for it following some discussion with Cobalt but that was before we saw the existing Castor 120Air config. I'll push that shortly but let me know if you have any thoughts on it or if it feels redundant with the Athena II second stage config (or if its too out there).

**Comment by CobaltWolf** [comment]
I had a brain fart. There's zero reason to have separate variants for the Carrack upper stage and Athena upper stage. I can't imagine they are that different, and it's not like E of Pi ever even came up for stats for the improved version. I also don't recall seeing numbers for the Athena second stage, implying it might be more or less unmodified. 

Luckily there probably isn't a reason to ever have to have thrust curves (which are mostly just for SRBs) on parts with upgrades, since there usually isn't a reason to have those be an "upgrade" in a separate node.

**Comment by zorg2044** [comment]
Oh ok cool, I'll remove the Carrack variant.

**Comment by zorg2044** [comment]
Initial configuration for the single and half seg SMRUs. Please let me know if any changes need to be made.

Currently they both have have 286s/259s for ISP. For the altitude optimised version I am giving them 296s/180s. For comparisons sake the SR119 has 309s/100s

I've also given each a roughly 10% thrust reduction for the AIR versions.

Neither of them seemed to have a thrust curve by default. I am configuring them as follows:
Single seg - steady drop 105% to 66% for both versions
half seg - steady drop 66 for booster, steady drop 105% to 30% for AIR.

**Comment by zorg2044** [comment]
Gem 40 and Gem 46 are done. Got the vac ISP from the grumman catalogue and had to guess at SL isp.

https://www.northropgrumman.com/Capabilities/PropulsionSystems/Documents/NGIS_MotorCatalog.pdf

Thrust difference is very minor and proportional to the differences in the catalogue (Gem 40 air is 3% more powerful, Gem 46 is 2% less)

**Comment by zorg2044** [comment]
@CobaltWolf I've pushed the Able/Ablestar upgrades as well as the star ones. As discussed added an upgrade for the Star 48 to enable it to keep pace and moved the final upgrade into heavyRocketry. You probably want to take a lot at the descriptions and subtype names though for everything in that commit.

@jsolson I think for the Star upgrades and in particular the Altair since it involves thrust changes, it probably needs a closer look from you when you have the time. I couldn't quite get the hang of the solids balancing in the spreadsheet so I went with % changes from the baseline values based on the IRL values given by Cobalt.

**Comment by jsolson** [comment]
They look ok. As long as your not changing fuel loads, you can mess around with thrust and isp without worry about cost and mass balance.

**Comment by CobaltWolf** [comment]
Generally speaking things are getting nerfed and then boosted back up to or slightly past their current levels slightly further down the tech tree.

**Comment by Pappystein** [comment]
LR87AJ-9 as a variant of the AJ-5

@MODULE[ModuleEngines]
    {
    @maxThrust = 577
        !atmosphereCurve {}
        atmosphereCurve
        {
            key = 0 300
            key = 1 252
            key = 5 0.001
        }
    }    
}

**Comment by zorg2044** [comment]
hi @jsolson when you have a moment would like to get your thoughts on this:

Cobalt would like to have a Castor 4 to Castor 4A upgrade (for the radial one). I was looking at the stats of the one in game and I assume you had to downscale the thrust to fit the in game model and that its based on 4 rather than 4A?

In which case does an upgrade to 4A that gives it 10-15% more thrust and 267/237 isp make sense? thanks.

![Screenshot 2019-10-07 17 06 35](https://user-images.githubusercontent.com/39182212/66310445-ab638a80-e925-11e9-97de-50760b3e8db6.png)

**Comment by jsolson** [comment]
The Castor 4 numbers came from Astronautix so I would stick with the same source, unless we prefer another source for both. I've been using Ed Kyle's numbers lately.

http://www.astronautix.com/c/castor4aengine.html

There's a ton difference in fuel, so the dry mass and cost would need to change with the switch.

**Comment by zorg2044** [comment]
Ok after double checking everything I think we can go with this page here:
http://www.b14643.de/Spacerockets/Specials/ATK-Thiokol/index.htm

The reference seems to be the old ATK catalogue and the IV-A figures match up with whats in the current NGIS catalogue too (and are close to the RO figures as well).

The SL thrust on that page for Castor IV actually matches up exactly with the Vac thrust on the current config which makes me think there was an error there.

In any case will include the prop mass, dry mass and cost differences between the two subtypes.

**Comment by jsolson** [comment]
Works for me!

**Comment by zorg2044** [comment]
Added the LR87 AJ9 as a patch in BDB extras. Looks like this project is done for BDB 1.6
