### ISSUE TITLE
Rational Resources mod breaks resupply tanks

### ISSUE THREAD

**Issue by jmrd98** [CobaltWolf/Bluedog-Design-Bureau#592]
This one is annoying. The Rational Resources mod (included with JNSQ system mod) gets to the resupply tanks before the BDB patches can/overloads the contents with its own, leaving me no way to drag snacks up to orbit.

I think it's able to be worked around, but let me have a go at some MM wizardry...

I also would wonder if anyone else has seen this, or if it's a local install issue. Staring at the patches, it doesn't seem like there should be a problem, but the incorrect result ends up in the MMCache/in game.

**Comment by CobaltWolf** [comment]
ngl I see people reporting issues with RR on a daily basis it sounds like more trouble than  its worth

**Comment by jmrd98** [comment]
Fair enough. It looks to be conquerable, but who wants to be making workaround fixes of another mod. I'll leave it to you to leave this issue open or not.

**Comment by jsolson** [comment]
We're you able to identify the patch causing the problem? I don't see anything in RR.

**Comment by jmrd98** [comment]
Yes, that I was able to do. It's in [RationalResources\CRP\zOreTanks.cfg](https://github.com/JadeOfMaar/RationalResources/blob/master/GameData/RationalResources/CRP/zOreTanks.cfg).

...

Oh, I think I see what occurs now. JNSQ may bundle an older version, as what I have on my machine and what is on that repo don't match. Mine has the following for the patch: `@PART:HAS[@RESOURCE[Ore],!MODULE[ModuleB9PartSwitch]]:NEEDS[B9PartSwitch,CommunityResourcePack]`

Looks like it was updated on Jul 15th on their end. I'll update my RR and see if it resolves the issue.

**Comment by zorg2044** [comment]
This has been resolved on the RR side. The initial release of RR had a lot of clashes with various mods but most have been resolved since. The problem is that JNSQ itself has not released an update in a while so a lot of people are still using the old packaged bundle of RR instead of the GitHub master of JNSQ (which has the updated RR).

**Comment by zorg2044** [comment]
Actually should leave this open in case some else checks here until JNSQ gets another full release.

**Comment by zorg2044** [comment]
Resolved since the 0.8 release of JNSQ
