### ISSUE TITLE
IR Spectrometer not Re-runable

### ISSUE THREAD

**Issue by raveloda** [CobaltWolf/Bluedog-Design-Bureau#60]
I do not know if this is intentional, but  you can only run the BDB IR-Spectrometer experiment once (Like the Mystery Goo)

**Comment by VenomousRequiem** [comment]
That seems a little silly, no? It should totally be re-runnable.

**Comment by CobaltWolf** [comment]
I need to take another look at this. I looked and didn't see anything in the config that would make it do this.

**Comment by raveloda** [comment]
I sent you a pull request with the fix :)

**Comment by CobaltWolf** [comment]
I'm going to assume this is fixed then.
