### ISSUE TITLE
DEVELOPMENT: Able and Ablestar engines -ve mass = kraken

### ISSUE THREAD

**Issue by syscryp** [CobaltWolf/Bluedog-Design-Bureau#606]
The new upgrade switching on the Able and Ablestar engines reduces the mass by an absolute value, instead of by 50%. This doesn't play well with rescaled systems, as BDB automatically reduces the base mass values for these engines, so a further absolute mass reduction takes them into negative mass and summons the kraken.

**Comment by jsolson** [comment]
Fix unploaded. Please test.

**Comment by syscryp** [comment]
Seems to be fixed now. Thanks.
