### ISSUE TITLE
H-1D has a gap in the struts

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#608]
![Screenshot 2019-09-10 14 49 56](https://user-images.githubusercontent.com/39182212/64604074-edf37f00-d3da-11e9-8683-bee463956ae2.png)

**Comment by CobaltWolf** [comment]
lmao, looks like they're getting pointed at each other. I'll see if I can fix it using the web editor

**Comment by zorg2044** [comment]
Fixed now.
