### ISSUE TITLE
New MOL 1.875m ring docking port autoshroud overlaps attached parts

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#609]
Problem with attach node positioning perhaps?

**Comment by zorg2044** [comment]
Shroud for both versions not visible in flight even when enabled.

**Comment by zorg2044** [comment]
![screenshot1271](https://user-images.githubusercontent.com/39182212/64886532-d7218680-d67f-11e9-9dab-ab79a6efc581.png)

Seems like theres definitely a node issue.

**Comment by CobaltWolf** [comment]
@zorg2044 I believe the first two issues are fixed. Going to start a new one for the third.
