### ISSUE TITLE
MOL fork docking port animation issue

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#614]
Throws index out of range log spam when the forks deployed in flight. Causes the the game screen to blink while animation plays. Log spam continues after animation done. Will try to find out more.

**Comment by CobaltWolf** [comment]
Had it happen to me when I was animating the ring docking ports. Did we have confirmation on what this was?

**Comment by zorg2044** [comment]
No I havent been able to figure it out yet. That procedural drag cube message (on a lighter install) I mentioned is normal according Alpha since it stops once the animation is done playing. I'll see if I can find a clue.

**Comment by zorg2044** [comment]
fwiw I've not seen this happen since mid september.

**Comment by CobaltWolf** [comment]
Lets just close it then. Fuck it.
