### ISSUE TITLE
Convert all engines to 25% thrust scaling

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#615]
All engines to use consistent 25% thrust scaling. Most upper stage engines would simply need to be halved from their current 50% scaling. Need to identify and convert (upper/lower) engines which use 37% scaling. [with noted exceptions below]

Agena

- [x] Agena A/B
- [x] Agena D
- Agena SPS (very low thrust, leave unscaled)

Apollo (Leave at realworld TWR)
- Block II SPS
- LMDE/Block III
- LMAE/Block V

Centaur
- [x] RL10A
- [x] RL10A41N
- [x] RL10B2

 Delta
- [x] Delta K AJ10

Early Rockets
- [x] Able AJ10
- [x] Ablestar AJ10

Gemini 
- SM A (Leave be as ultra low thrust engines)
- SM B (Leave be as ultra low thrust engines)
- lander (keep same for lander TWR reasons)

Juno
- [x] 6K
- [x] 45K

Saturn
- [x] J2
- [x] J2S
- [x] J2X
- [x] J2SL
- [x] J2T

Solids (Very low thrust engines, leave overscaled)
- Post Boost Vehicle
- Athena OAM
- HAPS
- Super HAPS

Titan

- [x] LR91-3
- [x] LR91-5
- [x] LR91-11
- [x] LR87 LH2 SL
- [x] LR87 LH2 V

Vega
- [x] Vega engine

**Comment by zorg2044** [comment]
@jsolson I will be contributing to this effort alongside realnames passes. Just wondering if the upper stage solids will need any special consideration?

**Comment by jsolson** [comment]
Solids should all be 22.42%. I remember where that number came from but it seems to be working out so I would leave them alone. Apollo and the LEM are a special case. They were balanced to give real world thrust to weight ratios. The very low thrust engines like HAPS and the verniers are at over 100% real world thrust.

**Comment by CobaltWolf** [comment]
Honestly @jsolson I think the solution is to just throw out the stock balance for stuff like RCS and roll our own

**Comment by zorg2044** [comment]
@jsolson Having followed @CobaltWolf 's suggestion to get feedback from users (via Blowfish's thrust nerf patch in extras) it looks like there arent any vehement objections. I can prepare the thrust changes on a seperate branch and do a PR to DV so its easy to review. I presume mass needs to be scaled by the same factor the engines are being adjusted to maintain the same engine TWR?
