### ISSUE TITLE
BALANCE: New Gemini station parts

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#619]
I've been going through and getting these in game but they have yet to receive any sort of balancing. Could really use help tightening these up and trying to diversify them a little.

Things to look for:
Tech tree placement (maybe this needs to be a separate issue?)
Costs
Mass
Efficiency (for labs)
Crew capacity
Resource capacity
Electrical generation (for solar panels, I can measure the surface area in Maya if it helps)
Antenna power/capabilities (For... antennas)

**Comment by jsolson** [comment]
Yeah, I'm looking at it.

**Comment by CobaltWolf** [comment]
Cool, let me know if you have questions. A lot of this is getting made more for lego-ability rather than because a niche is strictly needed.
