### ISSUE TITLE
SUGGESTION (RealFuels): Add the new engine switching subtypes as engine configs for real fuels.

### ISSUE THREAD

**Issue by KerbalKore** [CobaltWolf/Bluedog-Design-Bureau#624]
Ex: the able engine could have switches between AJ10-37, AJ10-101, AJ10-138, etc.

**Comment by CobaltWolf** [comment]
I don't believe we handle real fuels on our end, do we..?

**Comment by KerbalKore** [comment]
In BDB_Extras, there is a folder called RealFuels Dev. this is more of a suggestion to the people who make that, but it has no separate github.

**Comment by jsolson** [comment]
Realfuels has it's own mechanism for switching. It doesn't use ModuleEngines.

**Comment by KerbalKore** [comment]
Yes, but the changes made by the B9 switching can still be translated into The ModuleEnginesRF, as engine configs. I was not proposing using the B9 switching for real fuels. I was proposing making realfuels engine configs for realfuels users, because the b9 engine switching doesn’t work on real fuels

**Comment by jsolson** [comment]
Sorry I misunderstood. Yes, if someone wanted to add those that would be fine. The people who maintain those files are the real fuels users, so feel free to dive in if you like. They have a tendency to lag behind since none of the regular contributors here use it.
