### ISSUE TITLE
Titan IIIM tank has nodal positioning error

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#630]
Only since the updated model (holes/no holes) has been in place.   include.
![20190930215859_1](https://user-images.githubusercontent.com/7834967/65929102-b58a0400-e3ce-11e9-9e01-381797a34740.jpg)
![20190930215918_1](https://user-images.githubusercontent.com/7834967/65929105-b753c780-e3ce-11e9-8bb6-47e391d1f318.jpg)

**Comment by CobaltWolf** [comment]
Easy enough to fix.
