### ISSUE TITLE
LR91 new variant data issue

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#635]
The new LR91 Variants all are named the same with the same data plaque in game.   
Could possibly be named LR91-AJ-x (4) or LR91-AJ-x(1)  With updated notes about madmen and altered engines?  :)

**Comment by zorg2044** [comment]
The realnames hadn't been updated. Fixed now with updated tags too https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/8994399b5f49fcc1ac144f6d35abf4b997e5c50b. Thanks
