### ISSUE TITLE
Native CWPT Integration | Current: THOR/SATURN

### ISSUE THREAD

**Issue by DeltaDizzy** [CobaltWolf/Bluedog-Design-Bureau#638]
TBA

**Comment by zorg2044** [comment]
By family is probably easier to review for merging.

**Comment by DeltaDizzy** [comment]
Agena family is ready for fact-checking

**Comment by DeltaDizzy** [comment]
Starting to wonder if I'll be able to get everything in by the 25th (or is the BDB 1.6.0 due date just a vain hope?)

**Comment by DeltaDizzy** [comment]
@KerbalKore did you do the lander parts as well?

**Comment by KerbalKore** [comment]
I did *everything*

**Comment by DeltaDizzy** [comment]
What about MOL, as it is in a different folder?

**Comment by KerbalKore** [comment]
Also tagged, as it’s a Gemini subfolder @DeltaDizzy

**Comment by KerbalKore** [comment]
Wait it’s not a separate folder, the parts are all in Gemini. I tagged them, but huh

**Comment by DRVeyl** [comment]
Should these tags come with a :NEEDS[CWPT] to avoid spamming the KSP log with eg:
```
[LOG 14:55:01.489] PartLoader: Compiling Part 'Bluedog_DB/Parts/Explorer/bluedog_Pioneer4/bluedog_Pioneer4'
[WRN 14:55:01.494] PartLoader Warning: Variable techtag not found in Part
```

To avoid touching all the files again, consider a separate clean-up patch in one place:
```
@PART[bluedog*]:HAS[#techTag]:NEEDS[!CWPT]:LAST
{
  !techTag = DEL
}
```
This at least cleans everything up on the way out if the tag won't be used.  If some other tech tree mod comes about and wants to use techTag, it's a single place to change.

**Comment by DeltaDizzy** [comment]
Well the idea is for the techtags to be available for any mod to use, regardless of if BDB has updated to let them use it, especially since BDB updates so rarely. What is causing that error?

**Comment by DRVeyl** [comment]
That is -the- KSP PartLoader that runs after all MM patching is complete, when it builds the prefab/availablePart parts, warning that it found a parameter for a `PART` that doesn't belong.  So I suggested a patch that runs in :LAST, such that any mod that wants the tag has had access to it before BDB cleans it up.

Since I suggested :LAST, you could actually just delete the NEEDS and not worry about tracking it.

**Comment by DeltaDizzy** [comment]
What I may do is add a patch in the Compatibility folder that deletes all techtags in BDB parts duringthe LAST[Bluedog_DB] pass. (for LAST you input a modname)
