### ISSUE TITLE
add life support tank and KIS/BG Inventory

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#646]
Life support

- [x] Big G 69 SM

KIS inventory

- [x] Big G SM
- [x] Ferry?

BG Inventory

- [x] Big G SM
- [x] LEM descent module
- [x] Ferry?

**Comment by friznit** [comment]
And maybe a bit of KIS/BG inventory too?

**Comment by zorg2044** [comment]
Oh yeah why not. Speaking of should probably add BG inventory to the LEM descent module (if KIS is not installed)

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/a6f2de8757e4ee39eaaef5327deb8b6c79a64c2e

BG inventory added to parts with KIS inventory.
