### ISSUE TITLE
Old transtage RCS cfg still lurking with new Titan parts

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#647]
bluedog_Titan_TranstageACS.cfg is in the main Titan folder instead of the ``old`` folder. I presume this was meant to be deprecated once the new Transtage RCS blocks were produced.
 
It references this model ``Bluedog_DB/Parts/Titan/Old/bluedog_Titan_TranstageRCS``

**Comment by jsolson** [comment]
Another place holder that didn't get overwritten with the new part. It can be deleted.
