### ISSUE TITLE
Atlas CELV should allow side attachment

### ISSUE THREAD

**Issue by GoldForest383** [CobaltWolf/Bluedog-Design-Bureau#649]
The real CELV has srb boosters that need to be attached. 

With the CELV as it is right now, I have to attach the decoupler to the sustainer tank and then move the SRBs using the translate tool.

**Comment by zorg2044** [comment]
As with the old Atlas II in BDB, the SRBs need to be attached to the booster skirt. Since the attachment point is going to be quite below the CoM of the SRB, you will probably need to add a small sep motor to the nose of the solids to ensure a clean separation.

**Comment by GoldForest383** [comment]
Oh, didn't think of that.

**Comment by zorg2044** [comment]
No worries. No surface attach helps balance lightweight balloon tanks against regular tanks.
