### ISSUE TITLE
Early Rocket Revamp

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#658]
This list is by no means exhaustive, I'm adding stuff to it as I think of them

Vanguard:
- [x] GE-405 (With toggleable shroud)
- [x] Vanguard first stage fuel tank
- [x] Vanguard adapter interstage
- [x] Vanguard Able tank
- [x] Vanguard Able guidance compartment
- [x] AJ10 Able engine
- [x] 0.625m Fairing base
- [x] 0.3125m spin-decoupler
- [x] 0.125m Payload decoupler (short)
- [x] 0.125m Payload decoupler (long)
- [x] Vanguard retro rocket
- [x] Vanguard 1
- [x] Vanguard 2
- [x] Vanguard 3

Thor:
- [x] LR-79 engine
- [x] Thor boattail (any difference in UBT?)
- [x] Thor type LR-101 vernier
- [x] Thor lower tank (Base Thor, includes the intertank)
- [x] Thor 1.25m long adapter tank (used for original Thor stage)
- [x] Thor 1.25m medium adapter tank (for legoing)
- [x] Thor-Able adapter (long .9375m)
- [x] Thor-Ablestar adapter (medium 0.9375m)
- [ ] Thor .9375m adapter (short, for legoing)
- [x] Long Tank Thor tank (long 1.5m smooth tank)
- [x] ELTT lower tank (straight 1.5m, longer than base tank, includes the intertank)
- [x] Medium Thor tank (two tank segments, for legoing)
- [x] Short Thor tank (one segment, for legoing)

Able / Ablestar / Delta
- [x] Thor-Able Tankage (0.625m basically a white Vanguard-Able)
- [x] Delta B Tankage (IRL was a 36 inch stretch to the Thor-Able)
- [x] Thor-Able guidance compartment (0.625m)
- [x] Thor-Able interstage  (0.9375m to 0.625m adapter)
- [x] Thor-Delta interstage (breaks at different point than T-A, merged with Thor-Able interstage)
- [x] Thor-Ablestar tankage (has recessed engine mount, not as legoable as I'd like)
- [x] Thor-Ablestar interstage (0.9375m straight)
- [x] AJ10-Ablestar engine
- [x] 0.9375m generic fairing base
- [x] 0.9375m generic decoupler
- [x] Delta E tankage (stretched Ablestar tank)
- [x] AJ10-118F engine (basically a single Transtage AJ10-138 with a 26:1 extension instead of 40:1)
- [x] Delta interstage (1.5m, multiple lengths?)

Castor:
- [x] Castor 1
- [x] Castor 2 (merged into one part with the Castor 1)
- [x] Castor Radial Decoupler

HOSS:
- [x] HOSS tank
- [x] HOSS engine mount 
- [x] HOSS interstage

Redstone:
- [x] A7 engine
- [x] A7 tail unit
- [x] Juno/Redstone fuel tank
- [x] Ctrl surface fin
- [x] Basic fin
- [x] Air Vane
- [x] Control Jets
- [x] Juno Guidance Core
- [x] Juno Nose
- [x] 11x Sergeant Cluster
- [x] 11x Sergeant Decoupler
- [x] 3x Sergeant Cluster
- [x] 3x Sergeant Decoupler
- [x] 1x Sergeant
- [x] Explorer 1
- [x] Sparta Guidance
- [x] Sparta 0.625m Adapter
- [x] Sparta 0.625m Interstage
- [x] WRESAT
- [x] Medium Fuel Tank
- [x] Short Fuel Tank

Jupiter:
- [x] S-3D (Mesh/performance switch for LR-79, no start tanks)
- [x] Juno Vernier
- [x] Engine Shroud
- [x] First Stage Fuel Tank
- [x] Juno II Guidance Core
- [x] JPL 45K engine
- [x] 0.625m generic decoupler
- [ ] 1.5m to 1.25m Interstage
- [x] 1.25m Engine Mount 
- [x] 1.25m Juno IVB Fuel Tank
- [x] 1.25m straight Interstage
- [x] JPL 6K engine
- [x] 1.25m Juno IVA Fuel Tank
- [x] 1.25m generic fairing base
- [x] 1.25m generic decoupler
- [x] Vega third stage fuel tank

Delta II:
- [x] Separate boattail from engine
- [x] RS-27 (mesh/performance switch for LR-79. no lube tank, FABU, turbine spinner)
- [x] RS-27A (mesh/performance switch for LR-79, as above but 12:1 nozzle)
- [x] Castor-IV
- [x] Castor-IVXL
- [x] AJ10-118K engine
- [x] AJ10-118K-100 (Extending nozzle for 100:1 expansion ratio)
- [x] SSPS Avionics (0.9375m)
- [x] Miniskirt fairing base 1.5m
- [x] Miniskirt fairing base 1.875m
- [x] Delta P tankage
- [x] SSPS Tankage
- [x] Delta 3 first stage fuel tank (would have to be redone, it's currently on the Delta K texture sheet)

**Comment by longlong2002** [comment]
once for Thor/Able/Delta/Vanguard Revamp done and always double check every inch see if has mistake

**Comment by CobaltWolf** [comment]
thanks for the reminder I will

**Comment by longlong2002** [comment]
Forgot add Castor-IV

**Comment by longlong2002** [comment]
also hi CW need add Green paint for fenris/Thor rocket
