### ISSUE TITLE
Titan SRB's top node is slightly too high

### ISSUE THREAD

**Issue by sslaptnhablhat** [CobaltWolf/Bluedog-Design-Bureau#661]
This only occurs after saving and reloading the craft in the VAB/SPH, the separation nosecone/upper stage will be floating slightly above the SRB.

**Comment by CobaltWolf** [comment]
Not a very helpful report... What SRB?

**Comment by sslaptnhablhat** [comment]
All Titan SRBs; UA120s, SRMUs and the newer 1.5m SRBs.

**Comment by zorg2044** [comment]
I noticed this when loading one of my saved craft, an few weeks old one. But Im not seeing it happen for a fresh build and then saving and loading.

**Comment by sslaptnhablhat** [comment]
No, I reinstalled the dev version and it is still occurring even on newly saved crafts.

**Comment by zorg2044** [comment]
Bleh it just happened to me on freshly saved subassembly. But not the others I made (craft and sub). And I cant seem to reproduce it reliably despite trying several times. I think we need to check on a clean install.

**Comment by zorg2044** [comment]
Im presuming this issue is long since gone
