### ISSUE TITLE
Need dedicated FX transform on the LR87 single

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#664]
The good news is plume switching seems to be working really well! However for the realplumes to look right I think I need a dedicated fxTransform positioned precisely at the end of the engine bell. 

Right now the realplumes are being applied to the thrust transform and that is constant between the subtypes. So if I set the plume positioning correct for the AJ3 for instance it ends up too far inside the AJ11. Stock plumes can get away with it but for realplume the expansion makes this noticeable.

![Screenshot 2019-10-21 15 41 58](https://user-images.githubusercontent.com/39182212/67199178-0adb9300-f41a-11e9-9417-a880047b9867.png)

**Comment by CobaltWolf** [comment]
Should be working now

**Comment by zorg2044** [comment]
Yup looks like its working. Just need to tweak the plumes now. Thanks
