### ISSUE TITLE
Skylab bugs

### ISSUE THREAD

**Issue by birdog357** [CobaltWolf/Bluedog-Design-Bureau#667]
Skylab parts not affected by real-names patch, the Skylab WWS that looks like a basic S-IVB tank is the sole exception.

WWS tanks do not boil off cryo fuels.

When using the Saturn rescale patch and building Skylab:
-The upper and lower nodes on the Skylab Adapter/Airlock module are recessed into the model
-The non-airlock adaptor is not affected by the Saturn Rescale patch

**Comment by CobaltWolf** [comment]
The rescale patch is basically unsupported at this point, unfortunately.

**Comment by zorg2044** [comment]
as mentioned the realnames for skylab were updated several days ago. 

closing this since the rescale patch is no longer officially maintained.

Boiloff added to Wet workshops now though https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/549629e3769dff87a75b53886e29d6c9863947e7
