### ISSUE TITLE
Fix pods with integrated heatshields

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#68]
Need to figure out a solution for pods with integrated heatshields. Either:

1) Separate them
2) Tweak their heating values to make sure they reenter properly and safely.

**Comment by jsolson** [comment]
I believe separate them is the only proper option.

I don't see how the problem with being able to reenter at any angle can be solved. There's no orientation for the ablator.

As is the interior temp exceeds 212 F. That can be likely tweaked with InternalConductionSomethingOrOther, but the entire skin temp will remain too hot and conduct heat to attached parts.

**Comment by CobaltWolf** [comment]
I will speak to Beale and see what our options are. I can't separate the Leo without his help.

**Comment by CobaltWolf** [comment]
I have acquired the Leo source files, including the Unity scenes. I should be able to cut it up and reexport it without issue.

**Comment by CobaltWolf** [comment]
The Hermes heatshield needs to be re-separated.

**Comment by CobaltWolf** [comment]
I fixed this but have not committed the changes.

**Comment by Cowboy-WY** [comment]
Is the intention to remove the Ablator resource from the pods once the heatshield is separated?

**Comment by CobaltWolf** [comment]
Yes. Was it not already removed?

**Comment by Cowboy-WY** [comment]
Still exists in Hermes pod.

**Comment by CobaltWolf** [comment]
Dammit. You've probably figured out the general state the mod is in by now :P Lot of poor/hasty config edits on my end that need to be sorted out before we can make a stable release...

**Comment by Cowboy-WY** [comment]
I still like it!  I can help with edits, but I really have no idea how to do much of anything on github.

**Comment by CobaltWolf** [comment]
I believe you make a branch, make commits to it, and then make a Pull Request. That lets you 'propose' changes to the files directly that myself or any of the other authors can accept or discard.

@jsolson @VenomousRequiem correct me if I'm wrong.

**Comment by Cowboy-WY** [comment]
Thanks,  I think I got it to work for removing the Ablator from Hermes pod.
