### ISSUE TITLE
Need fairing texture variants for all newly added fairing bases.

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#693]
Generic fairing bases texture switches

- [x] 0.625
- [x] 0.9375
- [x] 1.25
- [x] 1.5
- [x] 1.875
- [ ] 3.125

DCSS
- [ ] 2.5

**Comment by zorg2044** [comment]
er its covered by a blanket patch, didnt have the aero folder in test install. nm

**Comment by CobaltWolf** [comment]
they still need variants for the actual model which is what I thought you were reminding me about :P

**Comment by zorg2044** [comment]
Oh cool, yeah why not.
