### ISSUE TITLE
Real sizes config

### ISSUE THREAD

**Issue by IronKerbal** [CobaltWolf/Bluedog-Design-Bureau#700]
I think some people would like a Real sizes patch if they would like it, I will be working on some.
A good way to make this happen is have a ```real_size = [rescale_factor]``` in each config just like the real names. The real sizes would be activated in the same way as the real names.

**Example Real size patch**
```
// engines
@PART[bluedog*]:HAS[#real_size]:HAS[@MODULE[ModuleEngines*]]:AFTER[zzBluedog_DB]
{
   @rescaleFactor = #$real_size$
   @mass = #$real_mass$
   @MODULE[ModuleEngines*]
    {
      @maxThrust = #$real_thrust$
    }
}
// Engine Switcher
@PART[bluedog*]:HAS[@MODULE[ModuleB9PartSwitch]:HAS[#moduleID[engineSwitch]]:AFTER[zzBluedog_DB]
{
  @MODULE[ModuleB9PartSwitch]:HAS[#moduleID[engineSwitch]]
  {
    @SUBTYPE[*]:HAS[#real_mass]:HAS[#real_thrust]:HAS[#real_size]
    {
      @rescaleFactor = #$real_size$
      @mass = #$real_mass$
      @maxThrust = #$real_thrust$
    }
  }
}
// Fuel Tanks
@PART[bluedog*]:HAS[@RESOURCE[*]]:HAS[#real_mass]:AFTER[zzBluedog_DB]
{
  @mass  = #$real_mass$
  @rescaleFactor = #$real_size$
  @RESOURCE[LiquidFuel]
   {
      @amount = #$realFuel_Amount_LiquidFuel$
      @maxAmount = #$realFuel_Amount_LiquidFuel$
   }
   @RESOURCE[Oxidizer]
   {
    @amount = #$realFuel_Amount_Oxidizer$
    @maxAmount = #$realFuel_Amount_Oxidizer$
   }
}
// Other parts
@PART[bluedog*]:HAS[#real_size]:AFTER[zzBluedog_DB]
{
   @rescaleFactor = #$real_size$
   @mass  = #$real_mass$
}
```

**Comment by CobaltWolf** [comment]
Hmm... unless this is a blanket rescale, you'll run into issues with the adapters not lining up since all the sizes get rounded up/down

**Comment by IronKerbal** [comment]
Yes, that would be a issue...

**Comment by zorg2044** [comment]
If I understood the above proposal correctly, the real thrust and real fuel quantities would also need to be defined manually per part in addition to the real size?

I dont think anyone on the team has the time to maintain those fields, and if you do have the time and motivation to undertake such a project I think putting that energy towards doing actual RO configs for those parts would be of more benefit perhaps? 

BDB already has custom SMURFF configs for people who want to play in large system upscales without RO but I expect most people who want to play with real-scale parts do so with RO.

**Comment by IronKerbal** [comment]
Closed. RO Configs can take care of Real sizes.

**Comment by CobaltWolf** [comment]
That's actually a good point - @IronKerbal the balance issues with the stock game get exacerbated with larger scale parts (the high dry mass of tanks, for instance). Proper RO configs would be much better.
