### ISSUE TITLE
Thor tanks have wrong volume

### ISSUE THREAD

**Issue by blowfishpro** [CobaltWolf/Bluedog-Design-Bureau#703]
They seem to have volumes of either 1300 or 680 regardless of length

HOSS has more volume than the main Thor tanks despite being slightly shorter (1440 vs 1300)

**Comment by CobaltWolf** [comment]
I didn't have a chance to configure the volumes.

**Comment by blowfishpro** [comment]
Ahh gocha.  I would have done it myself if I had the length measurements.

**Comment by CobaltWolf** [comment]
you can take them from the attach nodes

**Comment by blowfishpro** [comment]
Ahh good point

**Comment by CobaltWolf** [comment]
this can be closed right?

**Comment by blowfishpro** [comment]
Yes
