### ISSUE TITLE
Agena performance

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#71]
Right now an Agena has significantly lower performance than an Ablestar, even an Agena D. That needs to be fixed - Agena significantly outperforms Ablestar in real life IIRC.

**Comment by jsolson** [comment]
The Agena engines are too heavy. Plus they pack monopropellant, take that out when doing comparisons. Plus Agena D adds secondary engines that are probably too heavy and also add fuel. Mass disadvantages almost always trump Isp advantages. A real Agena D weighs less than a same sized Agena B.

The upper stages in general need a balance pass. They didn't get the attention the lower stages did recently. All of the tanks as well. But I think it's the spreadsheet more than the tanks that needs cleaning up.

**Comment by CobaltWolf** [comment]
I will see if I can make some changes to the Agena D model to reflect it. I can probably reuse the battery pack from the probe core, etc.

**Comment by CobaltWolf** [comment]
This can possibly be closed and discussion moved to the newer issue I just posted covering all the upper stages.
