### ISSUE TITLE
2 Titan I-700 Fuel tanks

### ISSUE THREAD

**Issue by birdog357** [CobaltWolf/Bluedog-Design-Bureau#711]
When using the real names patch I get two Titan I - 700 fuel tanks in my parts list. They are different tanks by volume. I believe one should just be renamed to Titan I - 350 fuel tank. This is current release version.

**Comment by zorg2044** [comment]
Thanks. Fixed https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/d7d1d5f155d714e32afd971d1d565d6576b43414
