### ISSUE TITLE
Kane 11-5/11-3 IVA graphical glitch

### ISSUE THREAD

**Issue by maushacks** [CobaltWolf/Bluedog-Design-Bureau#715]
![buggg](https://user-images.githubusercontent.com/51866804/68254162-ca873200-0021-11ea-9663-2258d1451250.jpg)

It looks like something clips inside the window. Either side is affected on both capsules.
I only used BDB and its dependencies.

**Comment by CobaltWolf** [comment]
BDB doesnt have IVAs. Its currently reusing one from a much older mod.
