### ISSUE TITLE
Issues with plumes of various engines

### ISSUE THREAD

**Issue by sslaptnhablhat** [CobaltWolf/Bluedog-Design-Bureau#719]
I did some minor testing and found that the plumes of the E1, non-gimballing H1, Thor/Delta H1, Transtage, cryogenic LR87, sea-level J2 and the Thor verniers either don't function at all or only become visible at a high altitude. In addition, the turbopump exhaust plumes of the E1 and both H1s function as they should, and the cryo LR87 and Transtage produce no sound when ignited.

**Comment by zorg2044** [comment]
Is this with stock or realplume?

**Comment by zorg2044** [comment]
And is it with the dev branch or the current release?

**Comment by zorg2044** [comment]
I've been able to track down the engage sound issue (which is seemingly there with a lot more engines than just the transtage and LR87) but as for the other issues I havent been able to reproduce.

**Comment by zorg2044** [comment]
Can you send me your modulemanager.configcache?

**Comment by sslaptnhablhat** [comment]
I'm using Realplume and the dev version in 1.7.3, all dependencies are updated to this version and not 1.8.x.
I tried looking in the ModuleManager thread OP and KSP's files, and tried searching google, but can't find modulemanager.configcache.

**Comment by Gordon-Dry** [comment]
@sslaptnhablhat That file is in GameData root.
If not, it was not created - which means MM got errors.

**Comment by sslaptnhablhat** [comment]
Definitely not in gamedata... https://prnt.sc/ptw47v

**Comment by zorg2044** [comment]
The picture you showed is of the KSP root folder itself. configcache is inside ksp/Gamedata in the same level as module manager itself.

![Screenshot 2019-11-08 00 16 37](https://user-images.githubusercontent.com/39182212/68420049-4bc6fc00-01bd-11ea-8415-50431c346edd.png)

The only reason it wouldn't appear there is if there are MM errors as pointed out above in which case I will need your ModuleManager.log inside KSP/Logs/ModuleManager

**Comment by Gordon-Dry** [comment]
^ you are faster ...

**Comment by sslaptnhablhat** [comment]
Oops... It isn't present in gamedata anyway.
Here's my ModuleManager.log: https://www.dropbox.com/s/rr1v55dre3kq50b/ModuleManager.log?dl=0

**Comment by sslaptnhablhat** [comment]
I just updated BDB to the latest dev version and now the Transtage's plume is back... but still no engine sound. The aforementioned broken engines are all still broken.

**Comment by zorg2044** [comment]
You have a lot of Module manager errors. I'm not sure but I think you have an out of date version of RealPlume itself.

**Comment by sslaptnhablhat** [comment]
Do you know whether the latest version of Realplume will work with 1.7.x?

**Comment by zorg2044** [comment]
RealPlume itself will but the 1.8 dependencies (MM and Smokescreen) will not. However, A backwards compatible zip with pre 1.8 dependencies is available even for today's release of RealPlume

https://github.com/KSP-RO/RealPlume-StockConfigs/releases/tag/v3.0.1

**Comment by sslaptnhablhat** [comment]
Apologies for the late reply, I have just tested the affected engines after updating Realplume and the aforementioned issues have been resolved. Thank you for your help and cooperation.
