### ISSUE TITLE
Leo Parts Changes

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#72]
We need to look at the Vinci service module. It possibly needs a fuel cell added, and perhaps some other stuff. The balance on all the parts, including the new 'Augustus' automated capsule should also be looked at.

- [x] Balance on pods
- [x] Balance on SM
- [x] Balance on rest of parts
- [x] New texture pass
- [x] Add fuel cell to SM
- [x] Make the top of the service module concave
- [x] Re-export the service module with fixed colliders
- [ ] Small retro solids to jam into SM?
- [ ] Separate BDB RCS from the Malhena texture sheet
- [x] Separate heatshield from command pod
- [x] Replace decoupler in SM with janky docking port
- [ ] Fix texture on black adapter piece
- [ ] Add short Blue Gemini service adapter

**Comment by jsolson** [comment]
> Experiment with separate decoupler for the heatshield - this will make MJ / KER readouts actually work for the module!


I think you mean the service module. The way I like to handle combo engine/decoupler parts is remove the decoupler and make the top node a docking port. You can't stage it, but you can detach from the right click menu or use action groups, and dv readouts work.

**Comment by CobaltWolf** [comment]
@jsolson I believe that you can enable staging for docking ports using tweakables now. That would be ideal I think - you can make it a custom gendered docking port type and never put in a non-female version or whatever.

**Comment by jsolson** [comment]
We need to rename the Gemini parts. Someone could have TRAILS and BDB installed at the same time. Just the part name, everything else is fine.

And for the love of god, [please stick to the bluedog* naming convention](https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Parts/Gemini/bd_gemini_cap.cfg#L3).

**Comment by CobaltWolf** [comment]
Oops. Can just unlist/deprecate that part and add a new one with proper naming.

You mean the the name at the top of the cfg? We could do that as well - same thing, copy all the TRAILS part files, change the name for the file (add a 'bluedog') and for the part and bam, fixored.

**Comment by jsolson** [comment]
Yup, the name at the top of the config. Filenames would be nice too for finding things.

**Comment by jsolson** [comment]
The Big Leo heatshield decouples from the bottom node and stays with the craft rather than the expected behavior of separating at the top node. I'd call this a bug but I'm pretty sure it's intentional, so I didn't just fix it.

**Comment by CobaltWolf** [comment]
@jsolson I need to add a transform to the service module in order to get the docking port, don't I?

**Comment by jsolson** [comment]
I've always used the engine's transform with a negative decoupling force.

**Comment by CobaltWolf** [comment]
I need to reexport it from Unity with new colliders anyways, so I'll probably just add a dedicated one to make it less janky.

**Comment by jsolson** [comment]
Visually you can't tell if the new separate heatshield is installed or not. Can you flatten the bottom of the pod?

**Comment by CobaltWolf** [comment]
I'm aware. I'm waiting Beale to reexport it with a new model I made. 

-----Original Message-----
