### ISSUE TITLE
Tags | 0p625m Fairing Base

### ISSUE THREAD

**Issue by friznit** [CobaltWolf/Bluedog-Design-Bureau#724]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/8ee98b1e5b98f833dee667d9c2a90eb4699c7788/Gamedata/Bluedog_DB/Parts/Generic/bluedog_FairingBase_0p625m.cfg#L42

It gets used a lot for building these things so nice for it to be included with the tags:

Add 
> Easton Alpha Able Thor Delta Daleth

Remove deprecated rocket names
> viklun diamant

**Comment by zorg2044** [comment]
done
