### ISSUE TITLE
Hermes LES decoupler menu item has no effect

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#725]
The LES doesn't show a decoupler in the staging area regardless of the menu item's state.

**Comment by zorg2044** [comment]
Only 1 staging icon can be shown for a part. For the LES its a solid rocket icon.

**Comment by OrbitalManeuvers** [comment]
So ... there's no point to the menu item then?

**Comment by DeltaDizzy** [comment]
There is, but the "Solid rocket" part of the LES is generally seen as more important than the "decoupler part". One or the other can be shown in the staging view, but not both, so the solid rocket was chosen. The icon has no effect on the part's function, but the button you speak of does have an effect.

**Comment by OrbitalManeuvers** [comment]
Ah ok, that makes way more sense now ... thank you for the explanation.
