### ISSUE TITLE
Deprecate the old Vanguard 1 files in Parts/Explorer

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#726]
Affected parts:
Bluedog_DB/Parts/Explorer/bluedog_Vanguard.cfg
Bluedog_DB/Parts/Explorer/bluedog_Vanguard.mu

In favor of:
Bluedog_DB/Parts/Vanguard/bluedog_Vanguard_Satellite1.cfg
Bluedog_DB/Parts/Vanguard/bluedog_Vanguard_Satellite1.mu

To avoid making old career saves being broken these files need to be moved to a deprecated subfolder or something like that.
So people who manually install mods (like me) can see them and decide to remove them (not copy them) on a new career.

**Comment by zorg2044** [comment]
I've soft deprecated the old vanguard. They will be deleted at some point after the initial BDB 1.7 release. 

Theres probably no need to move it into another folder. Most likely the entire Explorer folder will be deprecated as they are replaced by upcoming new probe parts.
