### ISSUE TITLE
RLX81 plume always active

### ISSUE THREAD

**Issue by DeltaDizzy** [CobaltWolf/Bluedog-Design-Bureau#728]
![](https://cdn.discordapp.com/attachments/409435221977595924/643947943044448281/screenshot626.png)

This behaviour occurs constantly on both the 8048 and 8081 engine configs.

**Comment by DeltaDizzy** [comment]
The dev zip was packaged with an outdated version of B9 Part Switch. I have manually updated it to v2.11.1 (from v2.10.0) and am checking to see if the issue is fixed.

**Comment by zorg2044** [comment]
I would expect updating B9 will fix this. Plume switching was introduced with v2.11.0 (it suppresses unused plumes so they are not always playing). This is exactly what would happen with an older version.

**Comment by DeltaDizzy** [comment]
I didn't get to test it yesterday due to various IRL events, so I will consider that verification.
