### ISSUE TITLE
Convert Redstone to Hydyne

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#73]
I recently learned that some variants of the Redstone, specifically the ones used for Juno I, were powered by Hydyne/LOX rather than Alcolox. This resulted in an increase in thrust, somewhere between 20-30 kN. Thought it might be worthwhile to buff the engine slightly, if only to make it more useful. To be clear this isn't converting the in-game fuel, just the stats.

**Comment by jsolson** [comment]
Fine with me. I'd have to go recheck, but looking at my old realfuels files Hydyne runs at 111% of Alolox. It would be going from 143 to 158. I believe at that level it can lift itself with all the tanks full.

Right now it's:
Vanguard 80
Redstone 143
Diamont 160 (overscaled - ahistorical)
Juno 190

**Comment by CobaltWolf** [comment]
yeah. There isn't much I can do about the Diamant right now. It wouldn't scale very well if I made it more accurate.

**Comment by jsolson** [comment]
I want thinking about doing a 75% rescale to see what happens. Although I kind of like it the way it is. It gives us some really nice 1.25 parts to play with.

**Comment by CobaltWolf** [comment]
Yeah there aren't too many other things I can do in 1.25m and I like the variety. 0.9375m is too small to be very useful

**Comment by CobaltWolf** [comment]
Did we reach a conclusion for this? I feel as if buffing the Redstone is actually a bad idea - it'll step too much on the Vexin.

**Comment by jsolson** [comment]
I think it's good as is.
