### ISSUE TITLE
BALANCE: Antennas

### ISSUE THREAD

**Issue by DeltaDizzy** [CobaltWolf/Bluedog-Design-Bureau#731]
My aim is to diversify the antenna selection, to try and avoid the need to either use huge antennas or spam small ones. This is not meant to be offloaded purely onto any of the primary contributors (though anyone can chip in however much they want), it is only intended to serve as a checklist for which antennas have been looked at and either changed or left alone.
- [ ] bluedog_LOantenna
- [ ] bluedog_LOdish
- [ ] bluedog_dipoleAntenna
- [ ] bluedog_domeAntenna
- [ ] bluedog_mariner2Antenna
- [ ] bluedog_mariner4Antenna
- [ ] bluedog_mariner4Dish
- [ ] bluedog_rangerDish
- [ ] bluedog_scimatarAntenna
- [ ] bluedog_simpleAntenna
- [ ] bluedog_solarAntenna
- [ ] bluedog_telstarAntenna
- [ ] bluedog_Apollo_Block2_HGA
- [ ] bluedog_Apollo_Block3_HGA
- [ ] bluedog_Apollo_Block5_HGA
- [ ] bluedog_LEM_Ascent_Antenna1
- [ ] bluedog_LEM_Ascent_Antenna2
- [ ] bluedog_Gemini_DipoleAntenna
- [ ] bluedog_Gemini_DockingAntenna_Fixed
- [ ] bluedog_Gemini_DockingAntenna_Rotating
- [ ] bluedog_Gemini_DoubleXAntenna
- [ ] bluedog_Gemini_WhipAntenna
- [ ] bluedog_MOL_TrackingAntenna
- [ ] bluedog_MOL_rackDish
- [ ] bluedog_mercuryScience
- [ ] bluedog_Pioneer6_BottomAntenna
- [ ] bluedog_Pioneer6_TopAntenna
- [ ] bluedog_Skylab_DisconeAntenna
- [ ] bluedog_Titan_Transtage_Antenna
- [ ] bluedog_Helios_Dish
- [ ] bluedog_IDCSP_Probe

**Comment by DeltaDizzy** [comment]
My WIP balance spreadhseet can be found here: https://docs.google.com/spreadsheets/d/1so83W9sKCIrasM8crH6Qod4aBnqtYPU8p5oRGE-thzo/edit?usp=sharing

**Comment by CobaltWolf** [comment]
Yeah I don't think antennas have ever been balanced past fixing glaring issues that prevent historical builds

**Comment by DeltaDizzy** [comment]
Is there any way you suggest I go about it?

**Comment by CobaltWolf** [comment]
Yeah I don't think antennas have ever been balanced past fixing glaring issues that prevent historical builds.

**Comment by DeltaDizzy** [comment]
All antennas fully entered into the sheet. Now only to figure out how to go about this...

**Comment by zorg2044** [comment]
@DeltaDizzy the Ranger dish needs to work at least up to Duna and Eve since it was also used on Mariner 1 & 2, keep that in mind when balancing it.

**Comment by DeltaDizzy** [comment]
@zorg2044 then why does mariner2Antenna exist?

**Comment by zorg2044** [comment]
@DeltaDizzy The mariner 2 antenna is the omni antenna on top of the truss. Mariner 2 features both the dish and the omni. But the Omni should have less range than the dish.

**Comment by zorg2044** [comment]
![image](https://user-images.githubusercontent.com/39182212/69245897-87a08f00-0bc9-11ea-9ccb-c40a3be2ab2e.png)

**Comment by DeltaDizzy** [comment]
Ahhh, I see. In that case I will knock rangerDish back a bit in the tree and keep mariner2Antenna in the same node as it.

**Comment by CobaltWolf** [comment]
if you can push the balance adjustments to Ranger/Mariner ASAP... I guess, along with all the other stuff that is getting redone this update? That would be really useful to me - the internal part names will likely change but since I start with the old cfgs if the fixes are pushed already they'll already be in the new parts.

Delta, there's unfortunately a lot more going on than just the antennas/dishes themselves. A lot of the single-part probes need to be looked at too. Pioneer 1 and 4, Explorer... not sure what else

**Comment by DeltaDizzy** [comment]
Right... May just search the repo for ModuleDataTransmitter and throw in all the parts I see. I also still need to figure out exactly what I want to do. I'm leaning towards setting the range a bit over what it needs to fully reach the target planet's orbit with the DSN level the layer probably has. E.g. Ranger can reach a little past Eve with DSN Level 2 since Mariner 1/2 targeted Venus and players will probably not still have the Level 1 DSN when going interplanetary.

**Comment by zorg2044** [comment]
Oh re IDCSP they were deployed like at 80-90%ish of GEO altitude. So when balancing them I think GEO distance at DSN1 would be good.

**Comment by DeltaDizzy** [comment]
ok whats stock GEO distance then, ive played in rescale and JNSQ too much.

**Comment by DeltaDizzy** [comment]
Method for getting maximum distance: SMA[Target]*2+(SMA[Kerbin]-SMA[Target])

**Comment by zorg2044** [comment]
Maybe we should convert either the MOL tracking antenna or the rack dish into a relay? BDB only has a few and most of the probe ones probably are not appropriate as relays?

**Comment by DeltaDizzy** [comment]
> Maybe we should convert either the MOL tracking antenna or the rack dish into a relay?

Funnily enough someone already suggested this to me. I'll convert the tracking antenna.

**Comment by DeltaDizzy** [comment]
I am assuming `mariner4Antenna` refers to the dish?
If so that makes it need a power of 315,000,000,000 to fully maintain contact with Duna...

**Comment by zorg2044** [comment]
Sure why not. I dont see a problem with that idea.

**Comment by DeltaDizzy** [comment]
And the LO antennae are too powerful (for Mun AND Minmus) even with a power of 1.

**Comment by DeltaDizzy** [comment]
Geostationary with L2 DSN needs an antenna rating of 0.00002

**Comment by zorg2044** [comment]
oh I was having trouble getting reception with it at GEO. turns out it was a mod conflict with Commnet Constellation. It specifically doesnt like single part probes that have a non deplouyable relay as the transmitter :P

Anyway yeah something reasonable for the size class should be fine.

**Comment by DeltaDizzy** [comment]
@zorg2044 Define reasonable. A power of 1 exceeds the muns orbit.

**Comment by zorg2044** [comment]
What I mean is you seem to me on the right track so I leave it to you :)

**Comment by zorg2044** [comment]
I've tentatively done a balance of the relays (excluding apollo, not looked at that yet).

Basically set sufficient power (1M) so that the Telstar and Courier can be used to set up an early game commnet that can support the basic BDB probes with 250k antennas in low to medium orbit. So players on hard mode without extra ground stations can use these.

The max distance between a 1M relay and a 250k probe is 500km.

The MOL tracking antenna is a more expensive more powerful take on the HG5 in the same tech node with Relay falling in between that and Telstar/Courier.

![Screenshot 2020-02-17 18 46 25](https://user-images.githubusercontent.com/39182212/74659373-03ed4300-51b6-11ea-8c20-cfd77129700f.png)

**Comment by DeltaDizzy** [comment]
Alright, but is there a formula or strict algorithm to use? I put a little bit more thought in and came to the conclusion that since the parts in general are balanced for 2.5x, why not do the same with the antennas? (i.e. have the ranger omni be able to communicate to the level 2 dsn from the 2.5x mun)

**Comment by zorg2044** [comment]
> Alright, but is there a formula or strict algorithm to use? I put a little bit more thought in and came to the conclusion that since the parts in general are balanced for 2.5x, why not do the same with the antennas? (i.e. have the ranger omni be able to communicate to the level 2 dsn from the 2.5x mun.) Does this throw a wrench into the relay balance?

We talked about this earlier? Stock balance should be fine since Sigma Dimensions ups the antenna strengths and JNSQ does the same via MM.

**Comment by zorg2044** [comment]
I havent come up with a strict formula or anything yet though. I just did this pass on the relays so they will be functional (it could also use some testing in those use cases) and we can review and change them going forward.

**Comment by Pappystein** [comment]
Just a comment about the math.  IRL Radio uses a LOG10 math formula 
here is an article linked to the basic terrestrial FM transmission formula:
https://itstillworks.com/12439428/how-to-calculate-distances-of-fm-transmissions

**Comment by jsolson** [comment]
Comms in KSP bears no resemblance to real world radio transmission unfortunately.

**Comment by Pappystein** [comment]
While this is totally true we CAN at-least use the antenna type as a way to gain modifiers for Broadcast cost and Science broadcast (as well as mass)   Here is where my spreadsheet is currently  I did a lot of number crunching on the 2nd sheet to see where antennas were AT in the game...   Lots of different ways to break down the numbers side by side.   I also included my simple Antenna type should be X compared to a standard on page 3.)   Feel free to use/not use as you need

https://docs.google.com/spreadsheets/d/13YVtSihEXZNilyUDrrB4wRe9IH0Lm2O597Mcw3rR8Ao/edit?usp=sharing

**Comment by jsolson** [comment]
Yeah we could use that as a guide for tx speed.
