### ISSUE TITLE
No TAC-LS for LM

### ISSUE THREAD

**Issue by Wallum** [CobaltWolf/Bluedog-Design-Bureau#732]
There is no life support for the LM Cockpit, making only short lunar expeditions possible, and the extended J-type missions impossible; resolution in my fork.

**Comment by zorg2044** [comment]
Please make a pull request targeting the 1.6 hotfix branch. Thanks

**Comment by SilveiraMarcel** [comment]
@Wallum , you can make a patch for TAC using the USI LS one. You just have to convert Supplies/Mulch to Food/Water/Oxygen/Waste/WasteWater/CarbonDioxide. A loooong time ago when I used TACL LS, I made this spreadsheet to calculate how much resources I would need
https://www.dropbox.com/s/hqquib2gtgh840z/usi2tac.xlsx?dl=0

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/pull/734

Issue resolved in PR
