### ISSUE TITLE
Apollo Block V High Gain Antenna has incorrect real name

### ISSUE THREAD

**Issue by DeltaDizzy** [CobaltWolf/Bluedog-Design-Bureau#735]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/62e179544e6752566d41c0f731b604ee6ce4ce30/Gamedata/Bluedog_DB/Parts/Apollo/bluedog_Apollo_Block5_HGA.cfg#L21
This is the only time "Block IV" is mentioned in the part CFG.

**Comment by zorg2044** [comment]
Yup typo there. Fixed https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/48b8154a6c7e5e000be371bbb90141d83a7f344d
