### ISSUE TITLE
bluedog_DeltaE_Tank vs. MechJeb / KER

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#736]
When I use a stack of bluedog_IDCSP_Truss with attached bluedog_IDCSP_Probe each, the upper stage that is carrying it is not calculated (or even shown) in MechJeb / KER.

That means I have to make sure it will have enough deltaV before I fully assemble the lifter.

The probe control is inside the bluedog_DeltaE_Tank which is the upper stage tank / core.

The PAW of the bluedog_DeltaE_Tank looks like this on the launch pad:
![Screen-2019-11-20_22-57-30](https://user-images.githubusercontent.com/29145213/69281821-47510900-0be9-11ea-826e-fcadf3405ec5.jpg)
as you can see there are two blank entries beside those buttons.

The Player.log spams this:
```
GUIContent is null. Use GUIContent.none.
 
(Filename: C:\buildslave\unity\build\Modules/IMGUI/GUIContent.cpp Line: 23)
```
(UnityPlayer.dll)

Full log and stuff (standing on launch pad):
https://www.dropbox.com/s/3gef6kld2t9zq23/player.log%20and%20stuff%202019-11-20-01.zip?dl=1

(Yes, I know that BDB could be the screaming victim, but this specific issue appears with this 100% BDB vessel)

**Comment by zorg2044** [comment]
@Gordon-Dry I've not been able to reproduce this, I suspect its down to some mod conflict. The IDCSP + TAID combo shows up just fine for me in MJ/KER and there is no log spam. I'm unable to determine a culprit from the log so you may have to do some mod elimination to find the cause.
