### ISSUE TITLE
New Experiments and science definitions

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#739]
A few additional experiments and associated science defintions are needed. Any help would be appreciated :)

- [x] BD_reconnaisance. (for KH10 Dorian, experiment already defined but science defs could use some work. Scope to modify experiment
- [x] BD_mapping reconnaisance or something, for lower res systems.
- [x] Photometer
- [x] Skylab ATM
- [x] Ranger/Mariner TV experiment ( still needs flavour text, right now shares with the camera experiment ) 

Things to steal from Probes plus

- [x] Gamma ray spectroscopy
- [x] IR Spectroscopy
- [x] Ionization and Electrostatic Analysis
- [x] Ultraviolet and Atmospheric Analysis
- [x] Biological experiment (OFO etc)

**Comment by zorg2044** [comment]
Scansat integration of KH10 and Corona will have to be dealt with separately.

**Comment by CobaltWolf** [comment]
The Ranger/Mariner TV experiment - right now there would be three tiers I believe, the Ranger Block 2 system, Ranger Block 3 system, and the one on Mariner 10 which is getting remade at some point this update.

Would be good to be able to separate the recon experiments by "mapping imagery" and "high resolution imagery"

Needs to be stolen from Probes+:
Gamma Ray Spectrometry
Infrared Spectrometry
Ionization and Electrostatic Analysis
Ultraviolet and Atmospheric Analysis

**Comment by CobaltWolf** [comment]
Would someone be interested in organizing this a bit more? Specifically I'd like a list of all the experiments, sorted by the experiment that they use; IE:

<EXPERIMENT NAME>
   <Part name> <tech node> <xmitScalar or whatever other balance levers we have> <notes>
   <Part name> <tech node> <xmitScalar or whatever other balance levers we have> <notes>

<EXPERIMENT NAME>
   etc...

Also, I'd like to try and convert some of the new experiments to DMagicScienceAnimateGeneric. Even on parts without animations there's a ton of features it adds. I need to keep them in mind for the new experiments moving forward.
https://github.com/DMagic1/DMModuleScienceAnimateGeneric/blob/master/reference.cfg

I ported a bunch of Coatl experiments last night but they need to have compatibility stuff written for them still.

**Comment by SilveiraMarcel** [comment]
> Scansat integration of KH10 and Corona will have to be dealt with separately.

I can help with that. After Wednesday I will have some time so I can make and test a ScanSat compatibility patch

**Comment by SilveiraMarcel** [comment]
Never mind, I found the patch I made last year for Contares_SPY
`//Patch made by Marcelo Silveira, Aug-10-2018


//C-CAM Type Argon
@PART[C?CAM_2S]:NEEDS[HullCameraVDS]:AFTER[HullCameraVDS]
{
	MODULE
	{
		name		= SCANsat
		sensorType	= 24  //2^3 + 2^4
		fov		= 2.2
		min_alt		= 5000
		max_alt		= 180000
		best_alt		= 120000
		scanName	= Multispectral
		RESOURCE
		{
			name	= ElectricCharge
			rate	= 0.128
		}
	}

	MODULE
	{
		name		= SCANexperiment
		experimentType	= SCANsatBiomeAnomaly
	}
}

//C-CAM Type Gambit
@PART[C-CAM_1]:NEEDS[HullCameraVDS]:AFTER[HullCameraVDS]
{

	MODULE
	{
		name		= SCANsat
		sensorType	= 24  //2^3 + 2^4
		fov		= 2.2
		min_alt		= 5000
		max_alt		= 180000
		best_alt		= 120000
		scanName	= Multispectral
		RESOURCE
		{
			name	= ElectricCharge
			rate	= 0.128
		}
	}

	MODULE
	{
		name		= SCANexperiment
		experimentType	= SCANsatBiomeAnomaly
	}
}

//Zenit Capsule
@PART[ZENIT_1]:NEEDS[HullCameraVDS]:AFTER[HullCameraVDS]
{
	MODULE
	{
		name		= SCANsat
		sensorType	= 24  //2^3 + 2^4
		fov		= 2.2
		min_alt		= 5000
		max_alt		= 180000
		best_alt		= 120000
		scanName	= Multispectral
		RESOURCE
		{
			name	= ElectricCharge
			rate	= 0.128
		}
	}

	MODULE
	{
		name		= SCANexperiment
		experimentType	= SCANsatBiomeAnomaly
	}
}
//YNTR-T80 Telexcope
@PART[YNTR?T80]:NEEDS[HullCameraVDS]:AFTER[HullCameraVDS]
{

	MODULE
	{
		name		= SCANsat
		sensorType	= 24  //2^3 + 2^4
		fov		= 2.2
		min_alt		= 5000
		max_alt		= 280000
		best_alt		= 120000
		scanName	= Multispectral
		RESOURCE
		{
			name	= ElectricCharge
			rate	= 0.36
		}
	}

	MODULE
	{
		name		= SCANexperiment
		experimentType	= SCANsatBiomeAnomaly
	}
}
`
