### ISSUE TITLE
bluedog_telstarAntenna is not stackable (anymore)

### ISSUE THREAD

**Issue by Gordon-Dry** [CobaltWolf/Bluedog-Design-Bureau#741]
The description says
> This lightweight communications antenna is stack mountable, and provides omnidirectional coverage for sending and receiving commands.

But it is not (anymore).

A long time ago, about 2 years or more, it really was stack mountable.

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/fd0e04e42d8fdfa1ab074077e8098fbab53cf576
