### ISSUE TITLE
Excess MP on Corona retropack

### ISSUE THREAD

**Issue by MaverickSawyer** [CobaltWolf/Bluedog-Design-Bureau#758]
Was tinkering with the new Corona bucket parts and found the retropack has far too much MP for what it needs. If the thrusters are left as they are, you can halve the MP without impacting its ability to complete its mission.
The thrusters can also probably be rolled back in thrust to 0.1 kN thrust without impacting the pointing ability of the capsule.

**Comment by zorg2044** [comment]
MP quantity has been halved now 4dcf61b60b85c14a4c94d0de30f783a278f9424e
