### ISSUE TITLE
Corona cannot survive reentry above stock heating

### ISSUE THREAD

**Issue by MaverickSawyer** [CobaltWolf/Bluedog-Design-Bureau#759]
Another field report... The Keyhole bucket heat shield cannot withstand a reentry from a 105x100 km polar orbit with the ejection and deorbit burn occurring at Ap with heating at 120%. This is on stock scale, btw, so this should absolutely be survivable.

**Comment by CobaltWolf** [comment]
Hmm... I thought I increased the heat tolerance of all those parts...

**Comment by MaverickSawyer** [comment]
All I know is that it popped the heat shield at about 1600 m/s as I dropped in. The bucket survived, as did the parachute, but I don't consider that a good result.

**Comment by zorg2044** [comment]
@MaverickSawyer made a slight adjustment see if this works 734b83181b385e4f14dd49d933fd5a27ad9ac080 . It survived for me in JNSQ just barely (which also has increased heating).

@CobaltWolf the retro pack for me doesnt seem to be fully sheilded by the heatshield. Usually it explodes from overheating.

**Comment by MaverickSawyer** [comment]
@zorg2044 I'll take a look this weekend.

And isn't the retropack supposed to be ditched just before reentry? Just point the bucket in roughly the right orientation and gently spin it up and it should be just fine.

**Comment by jsolson** [comment]
Do we know what the real return capsule weighs, with and without heatshield and retropack? Little parts usually blow up because they are too light.

I can't figure out the right way to assemble this.

**Comment by zorg2044** [comment]
@jsolson previously the retro pack was attached to the bottom edge of the heat shield. But Cobalt has reorganised it since then, its a bit more intuitive now and can be assembled as a plain stack

1. pod
2. attach chute with decoupler to ditch the retro motor
3. retro motor attaches to chute
4. shield attaches to pod and has its own decoupler to ditch itself.

About the mass I havent managed to find it yet. I'm trying to balance the masses right together now with the KH cameras and the approriate launchers. I'm testing the Kh1 with Thor Agena A right now in JNSQ and  given the low capacity of the Thor Agena A I dont think there will be much room to reduce the weight of the pod much further.

**Comment by jsolson** [comment]
The return capsule is 140kg according to [this](http://www.spacelaunchreport.com/Thor-Agena-A-Card.jpg).

I put the max temps back to less than the surface of the sun values 'cause I really hate that :stuck_out_tongue_winking_eye: and played with the ablator efficiency a bit. The retro pack must be jettisoned or it won't slow down. This thing is really weight sensitive so we may be able to shift some weight between the retro pack and the rest of it to get better results.

**Comment by CobaltWolf** [comment]
Apparently the later KH-9 ones were up to a ton when they got caught due to the amount of film. I imagine the C-130 pilots felt quite a "whump!"

**Comment by zorg2044** [comment]
@jsolson ive tested with your fixes and it seems to be quite ok now from JNSQ low orbit reentry :)

**Comment by jsolson** [comment]
I'm thinking drop the weight some more so it can keep the retro assembly. It strikes me as something that would stay in place until the chutes deploy. Counter intuitively, reducing the ablator amount _might_ help. It's a large percentage of the total mass and less of it might allow the probe to slow sooner.

**Comment by CobaltWolf** [comment]
![image](https://user-images.githubusercontent.com/16356162/74051552-2b6a3180-49a6-11ea-8831-8b8efa07cb41.png)
