### ISSUE TITLE
Athena OAM drag issues

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#763]

**Comment by jsolson** [comment]
Can you elaborate?

**Comment by zorg2044** [comment]
Er continuing this very timely conversation, I think this was some 2nd hand bug report passed to me by someone. I cant remember the specifics.

**Comment by zorg2044** [comment]
I'll just close this I guess, I cant find anything about this in my messages or mentions and no one else has found antyhing
