### ISSUE TITLE
sciencedefs_compatibility.cfg missing pioneer mag boom

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#767]
Just need to add:
```@PART[bluedog_Pioneer6_Boom_Mag]:NEEDS[DMagicOrbitalScience]
{
	@MODULE[DMModuleScienceAnimateGeneric]{
		@experimentID = magScan
	}
}
```
to Compatibility/sciencedefs_compatibility.cfg

**Comment by CobaltWolf** [comment]
if/when @dmagic1 is back we need to have a discussion between me, him and @akron about just moving to something like a "community science definitions" pack. This is getting ridiculous honestly.

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/pull/769
