### ISSUE TITLE
two copies of Explorer 7

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#773]
~~In 1.7.0 dev, there's bluedog_explorer7probe.cfg in the ProbeExpansion directory, as well as bluedog_Explorer_7.cfg in the JunoProbes sub-directory.~~

It's not the bluedog_explorer7probe, but there's still somehow 2 bluedog_Explorer_7 full satellite parts
![screenshot63](https://user-images.githubusercontent.com/2611674/73588198-4bb76d80-451a-11ea-873e-04644113cf59.png)

**Comment by zorg2044** [comment]
b7576f0aeac458cc5f83204db4f3d2418decf267
