### ISSUE TITLE
1.25/1.5/1.875m standard fairings not protecting content

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#774]
The Parts/Generic/bluedog_FairingBase_1p25m, bluedog_FairingBase_1p5m, and bluedog_FairingBase_1p875m fairings don't protect internal parts. With and without PF installed, and without FAR. using 1.7.0dev

Testing:
![screenshot50](https://user-images.githubusercontent.com/2611674/73545914-67763180-4490-11ea-81ac-682449a2deec.png)
![screenshot51](https://user-images.githubusercontent.com/2611674/73545927-6c3ae580-4490-11ea-8723-caeb2a8c820d.png)
 
The 0.625m, 2.5m, and 3.125m fairings, and the named variants all work correctly.

The 1.25m one from my configcache still had ModuleCargoBay:
```
		MODULE
		{
			name = ModuleProceduralFairing
			nSides = 48
			nArcs = 2
			useClamshell = true
			ejectionForce = 300
			TextureURL = Bluedog_DB/Parts/Aero/bluedog_fairing
			panelGrouping = 3
			pivot = 0,0.031621,0
			axis = 0,1,0
			baseRadius = 0.625
			maxRadius = 1.5
			capRadius = 0.15
			snapThreshold = 0.1
			xSectionHeightMin = 0.3
			xSectionHeightMax = 3
			edgeSlide = 0.15
			edgeWarp = 0.0
			noseTip = 0.7
			UnitAreaMass = 0.01
			UnitAreaCost = 7.2
			stagingToggleEnabledEditor = True
			stagingToggleEnabledFlight = False
			stagingEnableText = Fairing Not Staged
			stagingDisableText = Fairing Staged
		}
		MODULE
		{
			name = ModuleCargoBay
			DeployModuleIndex = 0
			closedPosition = 0
			lookupRadius = 1.25
		}
```

Also noticed bluedog_FairingBase_0p625m has a very blunt tip compared to the others.

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/pull/775
