### ISSUE TITLE
Titan parts scale

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#78]
The first stage engines are too long and the bells on the second stage engines are too small. Or something.

- [ ] Titan 1 first stage mesh
- [ ] Titan 3 first stage mesh
- [ ] Titan 4 first stage mesh
- [x] Titan 1 second stage mesh
- [ ] Titan 3 second stage mesh
- [ ] Titan 4 second stage mesh
- [x] Scale down Titan 1 second stage tank mesh
- [x] Add half-length Titan 1 second stage tank
- [x] Fix rotation on the fairings for ALL engines
- [x] Implement change to tank texture - I'm shying away from the bright orange tank tops on the parts.

**Comment by VenomousRequiem** [comment]
I just want to remodel them, fam.

**Comment by CobaltWolf** [comment]
I don't want to UV unwrap them and stuff again. They're going to be fine once I get time to put an hour or two into them

-----Original Message-----

**Comment by CobaltWolf** [comment]
These already look a lot better, I'm going to put it down for now.
