### ISSUE TITLE
Vangaurd spin decoupler issues

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#780]
- staging via spacebar results in instant decoupling
- when attempting to separate events via part action window or action groups, the part refuses to decouple (although the motors can be triggered this way).

**Comment by jsolson** [comment]
In `ModuleBdbDecouplerAnimation`, `waitForAnimation` should be a value in the range 0 to 1. It's 4 now.

Clicking toggle animation the the VAB doesn't appear to do anything. Maybe `deploy` is the wrong animation name?

Regardless, I don't see any way this part will work as intended.
