### ISSUE TITLE
MIP-FMP and MIP-RMS magnetometers are too heavy.

### ISSUE THREAD

**Issue by MaverickSawyer** [CobaltWolf/Bluedog-Design-Bureau#787]
Both units tip the scales at 0.12t, which is ~20 times heavier than the similarly sized HLR-PIO6E magnetometer (0.006t).

**Comment by CobaltWolf** [comment]
I think the other question to ask - is that PIO6E magnetometer too light?

**Comment by MaverickSawyer** [comment]
No, seems pretty balanced compared to the other magnetometers, both Probes Plus! and DMOS.

**Comment by MaverickSawyer** [comment]
Went in and compiled some data...
![screenshot117](https://user-images.githubusercontent.com/12904835/73694154-256e0b00-469d-11ea-830e-8e6069ea73d2.png)
Okay, so, for comparison, we've got the following deployable magnetometers, from left to right:
BDB Bion-MFD: 0.009t (includes small reaction wheel package, so the extra mass is justified)
(back) Univ. Storage 2 - Magnetometer Boom: 0.05t (heaviest of the bunch outside of our current issue, actually)
(front) PP CAE-MG03: 0.015t
BDB MIP-RMS: 0.12t
BDB DSMAG-R: 0.009t
PP CA-MER-MAG300: 0.017t
BDB HLR-PIO6E: 0.006t
BDB MIP-FMP: 0.12t
BDB Sonne-MBM-MEB: 0.009t
DMOS Magnetometer Boom: 0.015t
PP CA-MG100: 0.015t
And in the back, there's a Stayputnik for scale.
So, given the part sizes involved, I'd wager that the PIO6E is properly balanced in terms of mass, and that the MIP magnetometers are far too dense. It's some of the booms from other packs that are too light!

**Comment by zorg2044** [comment]
@MaverickSawyer I might have made a typo when doing some mass balancing :P iirc I was going to make it 0.012t

**Comment by zorg2044** [comment]
Should be fixed here. e4d5e346ca58db4fff976b8031feb3e7031807ad
