### ISSUE TITLE
Cryo Engines compatibility

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#79]
Cryo engines compatibility for the RL-10. We don't have any other hydrolox engines right?

**Comment by VenomousRequiem** [comment]
Single chamber LR87.

**Comment by jsolson** [comment]
> Single chamber LR87.
???

Just Centaur and the Saturn upper stages.

**Comment by CobaltWolf** [comment]
The single chamber LR-87 is based on a LR-87 that they converted to use with hydrolox.

**Comment by jsolson** [comment]
> The single chamber LR-87 is based on a LR-87 that they converted to use with hydrolox.
huh. I thought you just made that up. Is the bluedog_LR87_15m something other than a titan 1 engine in a 1.5 meter base?

Does "Cryo engines compatibility" mean compatability with the Cryogenic Engines mod, or just in the general sense?
Do we know of any other mods that use LH2/LOX or Oxidizer engines in stock? Space Y possibly?

**Comment by CobaltWolf** [comment]
I meant Nertea's Cryogenic Engines. I see a lot of people that use it apparently.
I know Benjee's DIRECT mod integrates compatibility withe Nertea's Cryogenic Engines.

**Comment by jsolson** [comment]
You should install Cryogenic Engines and look at the tank switcher it puts on all tanks. It uses B9PartSwitch. I think Nertea's mod is going to be the unavoidable defacto standard. It kind of takes over.

**Comment by CobaltWolf** [comment]
I've used it before. I suppose my point was, how hard would it be to integrate compatibility that switches the Hydrolox engines over if its installed? Even just a test case with the RL-10.

**Comment by jsolson** [comment]
Not hard at all. We don't even need it installed. Which other mods to play nice with is the trick, and I'm not finding anything other than this one to worry about.

**Comment by CobaltWolf** [comment]
To be clear - I was saying to have compatibility if it is installed. I think having new fuel types in the base mod is a bit much. 

I never answered one of your questions - the 1.5m LR-87 is indeed a 1.5m mounting of the Titan 1 LR-87, based on a horribly inaccurate model I saw once while looking for reference material. It was just a little personal thing I thought looked kind of unique.

**Comment by jsolson** [comment]
Short term todo on this is find a way to default the cryo tanks to LH/O fuel.

**Comment by CobaltWolf** [comment]
Is there no way to do it with a MM config? The centaur parts are the only ones that should default.

**Comment by jsolson** [comment]
There's almost certainly a way.
