### ISSUE TITLE
BDB 1.7 General Tech rebalancing

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#791]
Using this issue to highlight various overall tech balance issues for BDB 1.7

The linked spreadsheet below shows a general overview by rocket family of the current balance as of the latest commit (it is being updated with every commit).

Thor/Delta and Keyhole balance resolved here: https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/783

Outstanding issues:

Atlas II
- [x] Centaur II is in tier 6 but Atlas II engines unlock in tier 5. Since Centaur III and Centaur T tanks are also in Tier 6 suggest moving Centaur II tank backwards to tier 5

Titan I
- [x] Soltans unlock in Tier 3 along with the Titan I base (generalRocketry). Are we happy to keep it there in view of other rockets in that tier?

Titan III
All of the UA120s unlock in Tier 4 (advRocketry)
The AJ11s unlock in Tier 5
Suggestions:
- [x] Only Ua120s upto 1205 unlock in tier 4, 1207 and 1208 go to heavyRocketry
- [x] Titan III-M extension tank goes to heavyRocketry

- This puts Titan II, Titan IIIA, Titan IIIC, Titan 23/33B (later two using Aj5 engines as AJ9 analogues) in Tier 4
- Titan 23C (IIIC with AJ11), Titan III-M, Titan 34D, Titan CT3 will all then be in tier 5

IUS/TOS
- [x] In keeping with the above progression, suggest moving IUS TOS from Tier 4 to Tier 5. Also compare to other upper stage solids

Titan IV
- [x] Are we happy to keep it in Tier 5 (same as the later Titan IIIs) or do we move the tankage and SRMU to Tier 6. Tier 6 is the same as LDC, CELV and Atlas V. decision: Titan IV to Tier 6

---- Probes Balancing ----

To be done on the basis of the LV on which they launched where possible.

https://github.com/friznit/Unofficial-BDB-Wiki/issues/43

Completed (by game folder)

Agena
- [x] KH1-Kh8
- [ ] KH9 hexagon

Probe Expansion
- [x] AIMP
- [x] Alouette
- [x] Biosat
- [x] Helios
- [x] IDCSP (in Start right now as a substitute for deprecated Asterix, can be moved if another early game relay made)
- [x] Explorer 7
- [x] Explorer 8
- [x] Explorer 11
- [x] Explorer S45
- [x] Explorer S46
- [x] Pioneer 1
- [x] Pioneer 4
- [x] Lunar Orbiter
- [x] Nimbus
- [x] OFO
- [x] OSO
- [x] Ranger 
- [x] Ranger Lander
- [x] Mariner 2
- [x] Mariner B
- [x] TIROS
- [x] Tryp
- [x] OGO
- [x] Pioneer 6 (Old pioneer 6 parts are in tier 5, Delta E is in Tier 3. Could move to basic science in Tier 4 as a compromise since it goes to solar orbit and has powerful antennas)

- Need to decide on positioning of Pioneer 6 and Mariner 2 as they go to interplanetary space. Do we go with a strict  historical positioning  and both both in tier 3? Or put them into Tier 4 as an upgrade?
- Ahistorical Mariner B and Ranger lander are in tier 4 right now.

Redstone/Juno-I/Jupiter-C
- [x] WRESAT
- [x] Explorer 1

Vanguard
- [x] Vanguard 1
- [x] Vanguard 2
- [x] Vanguard 3

Probe SAS
- [x] Review Probe SAS upgrades positioning

**Comment by zorg2044** [comment]
Atlas II and Titan issues overview

![Screenshot 2020-02-06 13 12 04](https://user-images.githubusercontent.com/39182212/73918005-76227580-48e2-11ea-9c74-edd2124c61ad.png)

**Comment by Rodg88** [comment]
The titan 1.875m radial decouplers are in the tier above the UA120s themselves too

**Comment by zorg2044** [comment]
Yeah theres a few oddities like that to be fixed like the SOLTAN nose cones.

**Comment by zorg2044** [comment]
Probes tech balance as of 3dff8f8c8534a241ac3c4af87a544e8e030f8593

![Screenshot 2020-02-06 18 00 09](https://user-images.githubusercontent.com/39182212/73939179-b3026280-490a-11ea-8288-bde1501ffbf2.png)

**Comment by zorg2044** [comment]
Nimbus commit reverted to the earlier balance. Early nimbus will be on Thor Agena B, later one on ELTT

**Comment by CobaltWolf** [comment]
Ok, thoughts:
- Alouette should be Tier 2. It's functionally similar to the other more-or-less single part probes that unlock at that level. Same with TIROS - I imagine Tier 3 as the point where things open up and you start designing both full-scale/detail rockets and payloads.
- Do we want all the Ranger stuff to unlock together? Otherwise I'd maybe put Block 1 and Mariner 2 in Tier 3, put Block 2 and 3 in Tier 4. 
- We already discussed Nimbus. Early unlocks in tier 3, mid in tier 4, the last couple parts in tier 5. 
- Why is this fucking tech tree so small.
- Just toss Ranger Lander in Space Exploration if you want to free up some space. Mariner B can probably hang in Tier 4.
- I think some of the stuff in basicScience can be moved to Flight Control.
- idk I kinda liked Lunar Orbiter being a tier further back but that's up to you.
- Pioneer 6 can be moved back to Tier 4. There's nothing really magic about it. 
- Past a certain point we're counting on things like Coatl and Near Future to fill in for late game probes.
- OGO is probably going to wind up in Tier 4 and I think that's the last of the probes I'm adding for the time being. Tier 5 will probably be Mariner 10 and Pioneer Venus.

**Comment by zorg2044** [comment]
I decided to keep ranger lander in tier 4 since tier 5 has the gemini lander.

Also im inclined to keep Lunar orbiter in tier 4 rather than 3 for no other reason than the number of probe parts we have shoved into stability and survivability is making me a little nauseous :P It also has a much more capable propulsion system compared to Ranger/Mariner.

The other suggestions have been implemented. Will check again if we are splitting reasonably between basic science and flight control. I have been doing that for most stuff I moved into that tier.

**Comment by zorg2044** [comment]
Probes balance as of a1ef196053e46b00708aa4ec004231acc347a4c6

![Screenshot 2020-02-06 22 29 48](https://user-images.githubusercontent.com/39182212/73962480-59ad2a00-4930-11ea-801a-0bb469ad1f0d.png)

**Comment by zorg2044** [comment]
Titan and Atlas balance as of 48ae9577b8b5c863c64748526d9d640a1bf48be7

![Screenshot 2020-02-07 00 03 30](https://user-images.githubusercontent.com/39182212/73969659-a9462280-493d-11ea-8ace-95fce1187f10.png)

![Screenshot 2020-02-07 00 04 43](https://user-images.githubusercontent.com/39182212/73969664-ac411300-493d-11ea-9bdd-f36c0ea09716.png)

**Comment by zorg2044** [comment]
@CobaltWolf I've moved Pioneer p3 up from tech tier 2 to tier 3. couple of reasons.

1. It lines up with Atlas Able
2. with Ranger also in tier 3 in makes sense from an in game tech level as thats where BDB MP engines begin to unlock. Tech tier 1 and 2 will be limited to spin stabilised and solids and such.

**Comment by CobaltWolf** [comment]
Alright, if I remember though the probe RCS and bottles were staggered to unlock in several different locations instead of all at once. Some of the simpler configurations unlocked earlier than we have them now. What do you think of that? I think you moved them all to Miniaturization.

**Comment by zorg2044** [comment]
@CobaltWolf they were all ahead of where they are now but we can bring some of them even earlier and split them up too.

**Comment by Pappystein** [comment]
If I could suggest,   Move AJ10-118K to Delta II (it never flew on anything else)   Currently it unlocks before the rocket it flys on.   Only parts needed for Delta P should be unlocked where -118K is currently unlocking.

**Comment by Pappystein** [comment]
For followup on the LR87AJ11.   If it is possible to unlock the [EXTRAS folder] AJ9 version earlier than the actual AJ11 please do move the AJ11 to latter in the tree.      

Oh and Cobalt,   To your question about the size of the Techtree.   It is why I have long championed a bigger tree.   Sadly I don't see a way (without some plugin dev) to make a better tree.   You can make BIGGER trees but not better trees.

**Comment by zorg2044** [comment]
@Pappystein The Aj10-118K is in tier 5 right now as like 2 weeks ago. Its in propulsionSystems (same tier as Delta II on Heavy Rocketry).

UA1202-5 is now in Tier 4, 1206-1208 in tier 5 and SRMU in tier 6 (same tier as Titan IV and LDC).

I could move the 1208 to Tier 6 but I don't think theres any value in moving the other SRMUs any further up the tree.

I think we can move the shorter AJ260s forward, right now they are 2 tiers ahead of Saturn V so theres room.

The AJ5 is in Tier 4 while the AJ11 is in tier 5. The AJ9 in extras should go into Tier 4 since theres no room to move anything in tier 5. Heres a quick summary of Titan as it stands. 

![Screenshot 2020-02-21 13 34 26](https://user-images.githubusercontent.com/39182212/75017633-3f865680-54af-11ea-8061-a5bab82d2ebf.png)

I've not been keeping the screenshots up to date but feel free to check the link to the actual doc. I've been updating following each commit.

**Comment by zorg2044** [comment]
Oh theres also no rocketry node in tier 7 so if we move the short AJ260s they will have to move into something gross like largeVolumeContainment or advancedMetalWorks but thats been par for the course with the probe expansion in the early game too :P

**Comment by Pappystein** [comment]
Yeah.  This is why I wish I could code my own Tech tree.   Fuel type is the determining factor for the branch of Rocket engine. and each fuel has sub-branches.   As you fill up one sub branch you get credit towards others (meaning possibly free unlocks later if you have done enough research in another sub-branch)     But I also think you need to purchase the items one at a time which makes things like Atlas expensive (it is a marvel ahead of it's time.  While the Titan may cost more to build it actually cost much less in research invested.)
