### ISSUE TITLE
Procedural Fairings version of Delta P/K Fairing Adaptors bottom nodes

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#793]
The bottom nodes of the 1.5 and 1.875 Delta P/K Fairing Adaptors are too low. Those parts are made proceduraly in Compatibility/ProceduralFairings/bdb_pf.cfg so I can't just fix by editing the part cfgs.

**Comment by Rodg88** [comment]
The Delta-P fairing adapter (the one that isn't green) is fine, it's bottom node is where it should be

**Comment by CobaltWolf** [comment]
It's an issue with PFairings as I understand it, even if you made them manually it would still be an issue.

**Comment by jsolson** [comment]
No it's sunken top nodes, where the top node is below the base of the fairing hat are the known issue. We just move the top node up for those. Bottom nodes should be fine. There are two bottom nodes on those fairings, one of them for the interstage. Are they both wrong? Do you have a screenshot? I can look into it.

We have 1.875m Delta P/K fairings?

**Comment by Rodg88** [comment]
It was the bottom node for the interstage, I just patched in the correct positions manually, but if you want to make them work with your MM magic that might be better
![screenshot102](https://user-images.githubusercontent.com/2611674/74002306-f1f3ef00-49c2-11ea-8f2d-837e05486a98.png)

And yeah there's a 1.875m version with the same upper diameter, both the 1.5 and 1.875 needed tuning (see the PR I made)

**Comment by jsolson** [comment]
Neither the PF script or myself knew about the new parts. Should be working now.
