### ISSUE TITLE
Upper stage balance

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#80]
Balance pass for upper stages. Already touched on in issue #71. 

- [x] Able - Not much to say here. I like the current (?) implementation where it doesn't have terrific ISP, but is very light.
- [x] Ablestar / Delta - Let me know if there needs to be an additional part for Delta stuff, to separate performance. 
- [x] Agena A ( #71 ) - Already in a good spot.
- [x] Agena D ( #71 ) - Feels far better now, needs the fuel cell mesh added ( #57 )
- [x] Delta K - Don't really know right now.
- [x] Transtage - Don't really know right now.
- [x] RL-10 - Don't know where it's at.
- [x] JPL 6K engine (bluedog_Juno_Engine6K) - I forgot about these, but I don't believe they ever were looked at. There is very little to go on here, but remember that it's for 1.25m launchers. [There is some information available on the Space Launch Report page.](http://www.spacelaunchreport.com/jupiter7.html)
- [x] JPL 45K engine (bluedog_Juno_Engine45K) - Similar engine, the more powerful twin of the 6K engine.

I don't know if the Titan second stages need a pass as well.

**Comment by jsolson** [comment]
I'm tempted to nerf the mass and Isp on Vanguard and Redstone because right now Vanguard is very nearly a better vacuum engine than Able. I don't think either has deltav issues so they should be able to take it. It occured to me last night we could adjust whatever we adjust to make the early engines overheat if run too long.

We can call the Agenas good I think.

If it was for my own personal use, I'd turn the Centaur engine mount into a probe core (the agena probe core has become my all purpose instrument unit and finds it's way on almost every rocket). But that might be a bit too much/weird. I'm leaning towards changing it's tank to monopropellant.

Delta K/Transtage/Juno upper's have not been looked at.

Titan should be ok. I did uppers with the lowers on them.

**Comment by CobaltWolf** [comment]
In reference to the Centaur, it is getting dedicated avionics in the update. The thing with the mount is, that IS the lower bulkhead of the tank. 

Redstone has TWR issues I think it's fine right now. I like the overheat thing a lot - feel free to experiment. That essentially limits the size of the stage you have running right?

-----Original Message-----

**Comment by CobaltWolf** [comment]
Also of note - bear in mind we need performance niches for Vega (short 1.875m kerolox upper) and the RL-10B (if you want to roughly divide the RL-10's performance into two distinct versions, that would work)

**Comment by jsolson** [comment]
The RL10 we have now is like all the uppers OP for gameplay purposes. It's effectively an RL10A-4. I'm not sure what your RL10 plans are.

Overheat would limit run time, assuming you don't throttle back. How long you can run it before it destroys itself, along with restarts are the major advances in early designs that we lack control over.

**Comment by CobaltWolf** [comment]
Ah, to clarify - I plan on having two variants of the RL-10. The current one (which is getting remade with @VenomousRequiem 's new model) and then one with an animated extension (which might be purely for show, if I can even make it work) that would kind of represent later variants of the engine. Any more than that and I think they'd be sort of superfluous.

You can definitely control the whole 'how long it runs before destroying itself' thing. Ven's Stock Revamp has the early engine (LVT-10 Dachshund?) with a small amount of ablator that burns itself up if it runs too long. What engines specifically did you use that on?

**Comment by jsolson** [comment]
> (LVT-10 Dachshund?) with a small amount of ablator

That's an interesting part. It burns the ablator as fuel. When it runs out, your done. hmm

I was playing with overheating. Very hard to do without crazy numbers. Though Ven is using heatProduction = 1000  so maybe not so crazy.

**Comment by CobaltWolf** [comment]
Can this be closed?

**Comment by jsolson** [comment]
Two questions remain. Should I nerf vanguard/redstone. Nerfing the vac Isp
alone would have the effect of increasing the surface thrust. I'm inclined
to go ahistorical and put these similar to vexin's 251/221 Isp. Able and
Ablestar should probably get SL Isp dropped to under 200 to put them
solidly in the vacuum engine category.

Should we use the plugin to limit engine run times on early engines?

**Comment by CobaltWolf** [comment]
I like the plugin on Navajo - it makes it interesting, because it's OP but instable. I don't feel a need for it on the Vanguard or the other engines though. Vanguard doesn't have the thrust to make it worth attaching to a large stage. I am not sure I fully understood the point of putting it on some of those engine. Care to explain again?

The rest of those changes sound fine, give them a try.

**Comment by jsolson** [comment]
The plugin (ModleEngineLife) takes two parameters.

runTime = x
runTimeEnd = y

Run time is the number of seconds at full throttle the engine can run
before failing. You can see the current run time on the right click menu.

The first time the engine is started a random time between runTime and
runTimeEnd is selected. When that time is reached the engine "fails".

Failure means the engine's heat output is increased as long as the engine
is still running.  Heat output becomes base heat output * number of seconds
past failure time. The new heat output is permanent, you can shut the
engine down and cool it before it explodes, but if you restart it it will
continue to increase.

Assuming an engine with 200 heat output:
2 seconds past failure that becomes 400.
10 seconds past it's 2000.
And so on.

Eventually it becomes so high shutting down and cooling is useless. The
engine overheats again almost immediately. The idea is something broke
inside and it's getting worse.

**Comment by CobaltWolf** [comment]
That's good to know - I didn't know the specifics of the plugin. But my question was what point does it serve from a gameplay POV. No other engines do that. What's the point of nerfing BDB engines by limiting how big of a stage they can be attached to? Unless you're going to have a way to pass that behavior on to every other engine - in which case it has to become optional, and then what do you do with the Navaho? I like the idea of having this crazy OP but instable early engine that you can take a risk with, but I don't see a point in adding it to all the other engines especially ones that should have had the kinks worked out. 

I don't understand why the Able and Ablestar engines need the nerf I guess. Especially because I thought the issue was that the Vanguard was relatively too good, to the point where the ABLE had to justify its existence somehow.

**Comment by jsolson** [comment]
This evolved from using engine heat as a nerf not working out so well, and using the ablator trick looking kooky. The plugin gives us fine control over the effect. The way it's being used on Navaho is not how it would be used on Able. Able would just fail at 120 seconds, no randomness. Ablestar 300 seconds. It's not essential, just a tool to limit very early in the tech tree engines, rather than pumping up the mass or killing the Isp, that we can use or not.

**Comment by CobaltWolf** [comment]
So, one last question about this. Can we have a tech unlock that disables the limits on the Able and Ablestar? Especially Ablestar, since that was used up until the early eighties for the Delta 1000 series. I don't want to add another engine that is essentially the exact same thing, but I would like it to not have that restriction.
