### ISSUE TITLE
Juno IV mass/prop balancing

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#801]

**Comment by jsolson** [comment]
![Untitled](https://user-images.githubusercontent.com/16825376/74491491-bc0aab00-4e99-11ea-9e37-615b60e82620.png)

**Comment by zorg2044** [comment]
I just tried the latest commit in JNSQ, 100x100km equitorial orbit with a payload of 1,008kg, new default fill levels and the LR79-NA13. Total Dv of 5,349m/s.

Using Mechjeb PVG managed to get into orbit with 275m/s spare. Another launch with sub-optimal pitch settings for the initial ascent still managed to get the payload into orbit. I tried a couple of other fill combinations like max load on the first tank and less on the uppers and got roughly similar performance to LKO.  I think its in a pretty good place now.
