### ISSUE TITLE
Science using scienceValueRatio instead of xmitDataScalar?

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#803]
scienceValueRatio in stock ModuleScienceExperiment, or totalScienceLevel in DMModuleScienceAnimateGeneric, caps the total science available, instead of just the transmission, so might make lower tech versions of science parts make more sense? Eg a low tier magnetometer just can't get as good data as a higher tech one, even if you return the experiment. Same for different tiers of camera

**Comment by zorg2044** [comment]
Ah good catch. Yeah will take this into account when rebalancing the experiments. Now that the positioning of the parts themselves have been more or less finalised Im planning on doing a review of the individual experiments, experiment parts and their returns.

**Comment by zorg2044** [comment]
Ah looks like total science level in DMModuleScienceAnimateGeneric was added only in Mar 2019. No wonder the BDB configs didnt have the field.
