### ISSUE TITLE
Science parts rebalance

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#804]
Tech tree positioning of most parts are determined by the positioning of the spacecraft they are associated with. However science returns need to be adjusted to balance properly.

Need to compare with stock and DMOS where they cross over.

Some standalone generic instruments need to be repositioned.

As pointed out in https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/803 , ``scienceValueRatio`` in stock ``ModuleScienceExperiment``, or ``totalScienceLevel`` in ``DMModuleScienceAnimateGeneric`` (added in 2019), caps the total science available.

As such we can use xmitScalar as well as science cap as balance levers. xmit scalar can represent loss of data quality while science cap can represent the improvement of the quality of the experiment itself taking into account EVA recovery as well.

Base science value of BDB experiments could also be adjusted especially considering the use of science cap to prevent early game instruments from being OP if recovered.

Tech positioning, return%, transmit % outlined in the ``science parts audit`` sheet of the document.

https://docs.google.com/spreadsheets/d/16ZpHNR2Vl1Iilr6DnV1pWhQTv2fb4__Q64CCItaeAIk/edit?usp=sharing

- [x] bd_atm (apollo telescope mount)
- [x] bd_bioexp
- [x] bd_camera
- [x] bd_gammaRay
- [x] bd_GeigerCounter
- [x] bd_hydrometer
- [x] bd_ionElec
- [x] bd_IRradiometer
- [x] bd_IRspec
- [x] bd_magScan
- [x] bd_mapping
- [x] bd_surveillance
- [x] bd_massSpec
- [x] bd_microwaveSpec
- [x] bd_oso
- [x] bd_solarWing
- [x] bd_photometer
- [x] bd_radarAltimeter
- [x] bd_rpws
- [x] logIonTrap
- [x] logmmImpacts
- [x] mobileMaterialsLab
- [x] mysteryGoo
- [x] seismicScan
- [x] temperatureScan
- [x] gravityScan

**Comment by Rodg88** [comment]
I would consider merging the TVcamera and camera, maybe tv cameras have lower transmission than the other cameras, while regular cameras get better than their current transmission. Then balance max science based on tech level.

And maybe the photometer can use the DMOS irradiance scan?

**Comment by zorg2044** [comment]
Yeah we were considering merging the camera exp since essentially its imaging data in the end just with different levels of quality. The irradiance/goresat experiment doest seem to cross over with the photometer. Although it seems to be high orbit only. Perhaps thats not an issue.

**Comment by zorg2044** [comment]
Another thing we can do is integrate BDB parts into the Dmagic contracts DMOS is installed. For instance so that BDB magnetometers can be used for DMOS magnetometer part requirement contracts.

**Comment by zorg2044** [comment]
Working basis for now. Basically costs for BDB exclusive experiments will increase substantially as they offer extra science over stock.

![Screenshot 2020-02-18 19 22 51](https://user-images.githubusercontent.com/39182212/74744570-4d0bc880-5284-11ea-8e80-9748c83790b0.png)

**Comment by zorg2044** [comment]
Formula updated as follows

![Screenshot 2020-02-19 14 32 28](https://user-images.githubusercontent.com/39182212/74821103-ec809800-5324-11ea-9340-c90ffb44b230.png)

**Comment by Rodg88** [comment]
Should the BDB IR and UV spec experiments defer to coatl's version? I thought they did, but in-game they are still separate, and it's not in the sciencedefs_compatibility cfg. They have the same descriptions, though coatl also has OPM defs.

Or maybe we keep them in BDB and see if akron wants to defer coatl's to BDB?

**Comment by CobaltWolf** [comment]
@Rodg88 My vague notion is that before making this BDB update we should press with Community Science Definitions or whatever

**Comment by zorg2044** [comment]
I've merged the TV experiment with the Camera one. TV instruments will have 100% transmission but with lower total science return.

**Comment by CobaltWolf** [comment]
Good call @zorg2044 . And then... I guess late model (do we need a new generic?) would be best of both. 100% transmission of the full science.

**Comment by zorg2044** [comment]
@CobaltWolf yeah thats how the current high tech camera is set up. Its old though :|

**Comment by CobaltWolf** [comment]
luckily @drewcassidy volunteered to redo the generic science parts :)
