### ISSUE TITLE
Atlas booster fairing is clipping

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#81]
It's got two problems. The usual interstage issue with the node positions. I'm fixing that by moving the fairing node on the tank down/aft/nadir 4mm.

It's also clipping, enough for me to notice. You can see it clearly if you hyperedit to orbit and decouple.

Using the offset tool I had to move the fairing completely clear of any visible contact around the top/bow/zenith before it decoupled cleanly.

**Comment by CobaltWolf** [comment]
The colliders aren't even close to the visible model at this point though. I don't understand how they could be clipping.

**Comment by CobaltWolf** [comment]
@jsolson would it be possible to also add something to the fairing or the adapter tank (since that is a fairly unique / useless part otherwise) to add drag / move the CoL back? That would make the Atlas easier to fly.

**Comment by jsolson** [comment]
Perhaps it's clipping on the big tanks above. Could the booster engines be clipping with the adapter tank?

I think CoM can be moved, but I can't imagine it can be moved far enough to make a difference without being ridiculous. Mechjeb flys all my gravity turns unless I'm goofing around and I haven't observed any control issues. Atlas II had some but the added gimble cured that. You have to remember to dial back the thrust on anything smaller than an Altlas II. Maneuvering through high Q will flip you, and Q rises with velocity squared. I can do some hand flying if you insist it has an issue.

**Comment by CobaltWolf** [comment]
That might be it! I never looked at the interaction between the engine colliders and the parts around them. In that case its something that will get fixed once the engines are done. They're kind of next on my 'Atlas' list after getting at least the base Centaur in-game.

I admit that I forgot about the added gimbal. It just occurred to me that the Atlas is/was significantly less forgiving than most other launchers in the pack, and that might help with the issue.

**Comment by jsolson** [comment]
While you're looking at this, attach some launch clamps to the Atlas booster fairing on the narrow side, under where the vernors go. There's a significant gap.

Everything in this thread is minor. Atlas does work.

**Comment by CobaltWolf** [comment]
That is a result of the whole 'moving the colliders away to try and minimize physics clipping' thing. I'll have to upload a screenshot of the part in Unity so you can see how effed up the colliders are now.

**Comment by CobaltWolf** [comment]
@jsolson Atlas works more or less fine for me, apart from the obvious issue of the colliders being too far from the visual mesh. I'm closing it for now.

**Comment by jsolson** [comment]
I figured this out. It's clipping on the vernier engines. If you place the verniers so the nozzle does not extend below the top of the booster fairing the clipping does not occur.

**Comment by CobaltWolf** [comment]
oh snap. alright. I should be able to fix the collider then.

Matthew Mlodzienski
3D Animation and Visual Effects
Westphal COMAD 2017
