### ISSUE TITLE
Solar panel config errors for probe cores

### ISSUE THREAD

**Issue by Morphisor244** [CobaltWolf/Bluedog-Design-Bureau#811]
The solar panel configs for several probe cores are throwing errors both in vab and after launch.
Currently affected are:

Easton-V1 'Narly' (bluedog.Vanguard.Satellite1)
OTWS Weather Satellite (bluedog.TIROS)

----

The errors in VAB are:

**Easton V1**
[ERR 17:39:21.540] Couldn't access secondaryTransform

[ERR 17:39:21.540] Could not find the pivotName, suncatcher1, in heirarchy

[ERR 17:39:21.540] Couldn't access secondaryTransform for raycasts

[ERR 17:39:21.541] Couldn't access secondaryTransform

[ERR 17:39:21.541] Could not find the pivotName, suncatcher2, in heirarchy

[ERR 17:39:21.541] Couldn't access secondaryTransform for raycasts

[ERR 17:39:21.541] Couldn't access secondaryTransform

[ERR 17:39:21.541] Could not find the pivotName, suncatcher3, in heirarchy

[ERR 17:39:21.541] Couldn't access secondaryTransform for raycasts

[ERR 17:39:21.541] Couldn't access secondaryTransform

[ERR 17:39:21.541] Could not find the pivotName, suncatcher4, in heirarchy

[ERR 17:39:21.541] Couldn't access secondaryTransform for raycasts

[ERR 17:39:21.541] Couldn't access secondaryTransform

[ERR 17:39:21.541] Could not find the pivotName, suncatcher5, in heirarchy

[ERR 17:39:21.541] Couldn't access secondaryTransform for raycasts

[ERR 17:39:21.541] Couldn't access secondaryTransform

[ERR 17:39:21.541] Could not find the pivotName, suncatcher6, in heirarchy

[ERR 17:39:21.542] Couldn't access secondaryTransform for raycasts

**OTWS Weather Sat**
[ERR 17:41:49.235] Couldn't access secondaryTransform

[ERR 17:41:49.235] Could not find the pivotName, sunCatcher, in heirarchy

[ERR 17:41:49.235] Couldn't access secondaryTransform for raycasts

----
After launch, both result in the following error spammed continuously:

[ERR 17:37:25.526] Timing4 threw during FixedUpdate: System.NullReferenceException: Object reference not set to an instance of an object
  at Kopernicus.Components.KopernicusSolarPanels.LatePostCalculateTracking () [0x00030] in <0882401b48d84227ad9c2bbcf4ce8401>:0 
  at Timing4.FixedUpdate () [0x00023] in <9d71e4043e394d78a6cf9193ad011698>:0

**Comment by zorg2044** [comment]
Fixed along with others https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/4563ca9b1378a17de91cda77fb83900663bf2055
