### ISSUE TITLE
Assorted part config errors

### ISSUE THREAD

**Issue by Morphisor244** [CobaltWolf/Bluedog-Design-Bureau#812]
Several assorted config errors I encountered in VAB. A couple parts were tagged with both the fuelswitch error and the decoupler fx error.

---

- [x] **Partswitch errors with missing parent module id:**

Belle-ERD Equipment Rack (bluedog.Agena.EquipmentRack)
Chryslus-II-AGC (bluedog.Jupiter.Guidance)
Chryslus-IVB-SIA (bluedog.Juno4.Interstage)
Daleth-K-Interstage (bluedog.Delta.Interstage)
Etoh-CS Control Surface (bluedog.Redstone.Fin.CtrlSurf)
Fenris-MCA 1.25m Structural Adapter (bluedog.Thor.0p9375mAdapter)

Error message for each of these (replace the referenced part as applicable of course):

[ERROR] [Part bluedog.Jupiter.Guidance] [ModuleB9PartSwitch 'meshSwitchEndcap'] Cannot find parent module with id 'fuelSwitch'

---

- [x] **TransmitterModule errors for various parts with antennas:**

ALTTE-D2 'Skylark' (bluedog.Alouette.Core)
Pathfinder-11 (bluedog.Explorer.11)
Pathfinder-S46 (bluedog.Explorer.S46) 
J-15-D Comm Dish (bluedog.mariner4Dish)
Sonne-MBM-LGCA (bluedog.Helios.Dish)

TransmitterModule error:

[TransmitterModule]: Part Module 0 doesn't implement IScalarModule

---

- [x] **Similar reference as the previous set, but slightly different:**

BSA-0120-0100 (bluedog.MOL.Adapter.15.125)
BSA-0150-0120 (bluedog.MOL.Adapter.1875.15)
Prometheus-III/Comm 2.5m (bluedog.Titan3.CommercialPLF)
Prometheus-IV 3.125m Fairing (bluedog.Titan4.PLF)
Sarnus-BFBM Flyby Module (bluedog.Saturn.VFB.MissionModule)

The error:

[ModuleCargoBay]: Module ModuleB9PartSwitch is not an IScalarModule

---

- [x] **Decoupler fx error, thrown by various adapters & guidance units:**

Belle 0.9375 Interstage (bluedog.Agena.StraightInterstage)
Belle-A 1.25m to 0.9375 Interstage (bluedog.Agena.AInterstage)
Bion-MPB Adapter Section (bluedog.Biosat.Adapter)
Burke-2-RLP (bluedog.Ranger.Block2.RoughLander)
Chryslus II AGC (bluedog.Jupiter.Guidance)
Dona-LTT60 (bluedog.Gemini.Lander.Frame)
Etoh-C Guidance Unit (bluedog.Juno1.Guidance)
Etoh-C Nose Cone (bluedog.Juno1.Nose)
Etoh-H Guidance Unit (bluedog.Redstone.Guidance)
Etoh-L 0.625 Interstage (bluedog.Sparta.0p625.Adapter)
Etoh-L 0.625 Interstage (bluedog.Sparta.0p625mInterstage)
Etoh-L Guidance Unit (bluedog.Sparta.Guidance)
Fenris-LCE 1.25m Structural Adapter (bluedog.Thor.AbleAdapter)
Fenris-MCA 1.25m Structural Adapter (bluedog.Thor.0p9375mAdapter)
Fenris-SFA Structural Adapter (bluedog.Thor.1p25mAdapter.Short)
Fenris-SSI 0.9375m Interstage (bluedog.Thor.0p9375mInterstage)
MOCA Satellite Truss (bluedog.IDCSP.Truss)
Prometheus-I 1.5m Structural Adapter (bluedog.Titan1.StructuralAdapter)
Prometheus-IIIB 1.875m Adapter Interstage (bluedog.Titan3B.Interstage)
SG-1 Bloodhound Camera (bluedog.Keyhole.Camera.KH1)
SG-4 Cerveza Camera (bluedog.Keyhole.Camera.KH4)
SG-DPA Dual Return Adapter (bluedog.Keyhole.DualAdapter)
SG-RCA 0.9375m to 0.625m Adapter (bluedog.Keyhole.RVAdapter)

The error:

Cannot find fx group of that name for decoupler

---

- [x] **An engine config error found in:**

Prometheus SRB1202 (bluedog.UA1202)
Prometheus SRB1203 (bluedog.UA1203)
Prometheus SRB1204 (bluedog.UA1204)
Prometheus SRB1205 (bluedog.UA1205)
Prometheus SRB1206 (bluedog.UA1206)
Prometheus SRB1207 (bluedog.UA1207)
Prometheus SRB1208 (bluedog.UA1208)

The error:

[ModuleSrfFX]: No IThrustProvider module found at index 0!

---

- [x] **And finally, complete failure with logspam in VAB:**

Etoh-AVRT Air Vane (bluedog.Redstone.Airvane)

NullReferenceException: Object reference not set to an instance of an object
	ModuleControlSurface.CtrlSurfaceEditorUpdate (UnityEngine.Vector3 CoM) (at <9d71e4043e394d78a6cf9193ad011698>:0)
	ModuleControlSurface.LateUpdate () (at <9d71e4043e394d78a6cf9193ad011698>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

---

All errors were found on a minimalist install with only the basic required mods and utilities.

Oh, and sorry :x

**Comment by zorg2044** [comment]
The Mariner 4 dish was ignored since its deprecated.
And not sure what do about the ModuleCargoBay should be set up for the VFB module.

The issues are mostly resolved except except for the Redstone fin.

**Comment by longlong2002** [comment]
99% Fuckup

**Comment by zorg2044** [comment]
Last issue fixed as of https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/27ab4ed3829e082a8b8d501e2a0e42bffdca5280
