### ISSUE TITLE
Nimbus solar panels - Part Icon shows both variants

### ISSUE THREAD

**Issue by jsolson** [CobaltWolf/Bluedog-Design-Bureau#823]
![Untitled](https://user-images.githubusercontent.com/16825376/74587223-f9685900-4fbd-11ea-998f-e2f8e574ce91.png)

**Comment by CobaltWolf** [comment]
Easy enough to fix, just need to export it with the second side set to Icon_Hidden

**Comment by zorg2044** [comment]
Took a quick look. Seems ok now
