### ISSUE TITLE
Juno-IVA 3rd stage RCS issues.

### ISSUE THREAD

**Issue by Mudwig** [CobaltWolf/Bluedog-Design-Bureau#824]
One of the four downward facing RCS thrusters on the "Chryslus-IVA-160 Liquid Fuel Tank" is inactive by default.

I played around with it a bit and it turns out it's just in the wrong actuation menu ( it's active if you set the radial RCS fore/aft toggle to 'on' ).

**Comment by zorg2044** [comment]
Confirmed fixed as of https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/43fabdd51f3e3eeff36c2b360c376bc910afba2b
