### ISSUE TITLE
Solar panels issue with Pio 6, Relay and Explorer s46, 11

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#827]
These parts seem to not generate power evenly around the cylindrical solar panels. One side in fact does not generate power at all. Tested by pointing side of panel directly at sun and rolling the craft.

Problem limited to the Pioneer 6 (SM and Core), Explorer S46, Explorer 11 and Relay. All others seem ok.

**Comment by CobaltWolf** [comment]
bluggggghhhhh so the cylindrical ones ok. Are there any others that use that type? Explorer 11 does I think

**Comment by zorg2044** [comment]
> bluggggghhhhh so the cylindrical ones ok. Are there any others that use that type? Explorer 11 does I think

I made a big ol stack of probes to test, missed out on explorer 11 that time. And yeah it does have the issue too.

**Comment by CobaltWolf** [comment]
Do we know which cylindrical ones are working? I know some are.
