### ISSUE TITLE
SMRU advanced titan SRBs thrustTransforms not centered

### ISSUE THREAD

**Issue by Rodg88** [CobaltWolf/Bluedog-Design-Bureau#828]
The thrust on the 2, 2.5, and 3 segment SMRU boosters isn't centered, even on the in-line variants. The 0.5 and 1 segment versions are fine.

**Comment by CobaltWolf** [comment]
Thanks I'll check it

**Comment by CobaltWolf** [comment]
I'm not sure what you mean they look fine to me?

**Comment by Rodg88** [comment]
Ah looks like it's because of this: CoMOffset = 0.0, 3.0, -0.041. Maybe B9PS could center the COM on the inline variant?

**Comment by CobaltWolf** [comment]
I suppose? I think B9PS does that

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/4fb9bd255f302646b7b9e399664c022f847982ef
