### ISSUE TITLE
Delta 3 upper fuel tank texture is broken.

### ISSUE THREAD

**Issue by Mudwig** [CobaltWolf/Bluedog-Design-Bureau#830]
The upper fuel tank for the Delta 3 first stage appears gray in game and has inverted shadows/shading. Only the white parts of the tank have this problem, the blue raceways look fine. The Delta 2 tank end-caps have the same graphical problem as well.
 
I noticed this a few days ago and assumed it was a mod conflict, but on a fresh install with just BDB and dependencies it's still there.

**Comment by zorg2044** [comment]
I think I borked something when I soft deprecated the old delta K files :/ (they got moved into a deprecated folder). I guess there was a shared texture. Will check on it today.

**Comment by zorg2044** [comment]
I cant check right now but that should have fixed it.
