### ISSUE TITLE
Stock fairings improvement

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#832]
Had some feedback re stock fairings:

``
I noticed with the stock fairings is that Beale's fairings seem to allow more freedom to place rings and smooth better, I should take a look at his config and see if they can be applied to BDB's
``

**Comment by Pappystein** [comment]
The LDC 3.125 Stock Fairing seems to have had settings coppied from a 1.25m or 1.875m fairing.  The Node and struts for multi payloads are significantly smaller than the maximum 3.125m diameter and do not clear most payloads you would use on a Rocket this size.   Not a major issue if new Fairings are coming but I wanted to include info here.   When I enable "show nodes" I end up with 1 node visible and usable above my current payload (COATL Vornoa probe/lander)   Was trying to boost a comm sat with Vorona on the same flight to Jool.

**Comment by zorg2044** [comment]
Oh that will need to be fixed if thats the case. We aren't getting rid of stock fairings or the proc fairings patch.

**Comment by jsolson** [comment]
@Friznit https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/842#issue-574304819

Proc Fairings | Thor Able | Atlas V | Delta II | Titan | Titan CT-3
-- | -- | -- | -- | -- | --
baseConeShape1 | 0 | 0.1 | 1 | 0.3 | 0.3
baseConeShape2 | 0 | 1 | 1 | 0.3 | 0.3
baseConeShape3 | 0 | 0 | 1 | 0.7 | 0.7
baseConeShape4 | 0 | 0.7 | 1 | 0.7 | 0.7
baseConeSegments | 3 | 3 | 3 | 3 | 7
noseConeShape1 | 0.2 | 0.1 | 0.6 | 0 | 0.2
noseConeShape2 | 0 | 0 | 0 | 0 | 0
noseConeShape3 | 0.7 | 0.7 | 0.9 | 0.7 | 0.7
noseConeShape4 | 0.6 | 0.7 | 0.8 | 0.2 | 0.2
noseConeSegments | 5 | 11 | 11 | 3 | 11
noseHeightRatio | 1 | 3.5 | 2.1 | 2 | 2.1

**Comment by jsolson** [comment]
Addressed in https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/df68048349f77a9db79e9bfe57dd27f0ab08872c

Please report if there's still issues.
