### ISSUE TITLE
Issue with TOMS and Orbital Weather Observation experiments

### ISSUE THREAD

**Issue by jackdets** [CobaltWolf/Bluedog-Design-Bureau#834]
![](https://cdn.discordapp.com/attachments/420755203134980126/682020072877064336/unknown.png)

TOMS experiment behaved as if vessel was in the atmosphere, despite craft being in low Kerbin orbit. Orbital Weather Observation experiment simply couldn't be done with no reason given. 

This picture was taken in a 1.8.1 install with JNSQ planet mod. The craft was at around 125 km above Kerbin.

**Comment by jackdets** [comment]
![image](https://user-images.githubusercontent.com/61482248/75301699-7b9c1d00-5809-11ea-8a32-0eff48d141c9.png)

The OTWS weather satellite Cloudcover experiment seems to have a similar issue to the Orbital Weather Observation experiment.

**Comment by zorg2044** [comment]
Ack! Typo in the weather experiment science definition. Basic functionality should be restored now although these experiments still need a balance pass.

f3be67c2bff455223d0348f3c76e735ddc237ab6
