### ISSUE TITLE
Titan Realnames minor issues

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#848]
This is a list of correct Titan Rocket names with associated parts.   US Military (the people who designated the liquid rocket engine names for Titan) use a 3 group naming convention of [Engine-Type/Engine-type-Model] [Manufacture Abbreviation] and [Engine subversion numbers]  Each separated by a Hyphen.   So the Titan II Missile's First stage engine should be written as: LR87-AJ-5 (not the current LR87-AJ5)

Part:   bluedog_LR91_3
real name:  LR91-AJ-3

Part:   bluedog_LR91_3_SingleVernier
real name:  LR91-AJ-3(V)1

Part:   bluedog_LR91_5
real name:  LR91-AJ-5
real name:  LR91-AJ-5K

Part:   bluedog_LR91_5_FourVernier
real name:  LR91-AJ-5(V)4        <---This version actually has TWO real names in the CFG!
real name:  LR91-AJ-5(V)4K

Part:   bluedog_LR91_11
real name:  LR91-AJ-11
real name:  LR91-AJ-11K

Part:   bluedog_LR91_11_FourVernier
real name:  LR91-AJ-5(V)4
real name:  LR91-AJ-5(V)4K

Please note the (V) in the single and four vernier is non standard but eliminates confusion with things like LR91-AJ-11A which is a real engine designation on the Titan IV

Part: bluedog_LR87_3
real name: LR87-AJ-3

Part: bluedog_LR87_5
real name: LR87-AJ-5
real name: LR87-AJ-5K

Part: bluedog_LR87_11
real name: LR87-AJ-11
real name: LR87-AJ-11K

I will attempt to work up "real" designations for the LH2 and Single combustion chamber LR87s but Currently feel the existing designations for those are OK since they were never military (and thus do not need to strictly follow the designation standards of 1962)

**Comment by zorg2044** [comment]
Thanks, will clean this up at some point.

**Comment by Pappystein** [comment]
So name suggestions (note these don't have a Real World name) for the Single Bell standard engines:

LR87-AJ-3(S)
LR87-AJ-5(S)
LR87-AJ-5(S)K
LR87-AJ-9(S)
LR87-AJ-9(S)K
LR87-AJ-11(S)
LR87-AJ-11(S)K
LR87-AJ-11A(S)
LR87-AJ-11A(S)K

I have included names for -9 and -11A variants even those are not in base BDB.

And a Stab at Hydrolox
AJ-23-142 (LR87-LH2)
AJ-23-141 (LR87-LH2)

   AJ-23 is the overall Aerojet name for the entire LR87/LR91 and derivative family.   These versions actually correspond to a slightly higher power version but they fit.   -142 is the Sea level rated and -141 is upper stage rated versions.

**Comment by Pappystein** [comment]
Whoops forgot the LR87 Vacuum non LH2 engine:

Suggest:
AJ23-128 and AJ23-129

Original LR87-AJ-3 Hydrolox singal is AJ23-127.  no known use of -128 and -129 (per Astronautix sadly)   NASA NTRS doesn't even have any AJ23 documents except for pre Challenger Shuttle II docs!

**Comment by zorg2044** [comment]
@Pappystein any suggestions for the LR87 Single vacuum optimized?

**Comment by zorg2044** [comment]
There are also upgrades for the Cryogenic engines, I guess 142/141 can be followed by 15x and 16x ?

**Comment by Pappystein** [comment]
I would say anything in the AJ23-17x is probably best fair game for the Vacuum singles (Hydrolox and Hypergolic)  That way we are moving it further away from the KNOWN list of AJ23s
