### ISSUE TITLE
Nimbus Solar Panel Mirroring Error

### ISSUE THREAD

**Issue by dbandy13** [CobaltWolf/Bluedog-Design-Bureau#849]
When the "left side" setting for the nimbus panels show in the PAW the resulting panel does not generate any EC, it tracks correctly based on texture though. Test images below show a set with symmetry disabled after placement and manually setting both panels to "right side"and then 1 to "left side". Launchpad shots show the results after launching from same perspective
![screenshot11](https://user-images.githubusercontent.com/53122188/76633238-618b6a00-657f-11ea-8380-87ecfba2a7d2.png)
![screenshot10](https://user-images.githubusercontent.com/53122188/76633241-63552d80-657f-11ea-9c49-f0baf5216ee2.png)
![screenshot14](https://user-images.githubusercontent.com/53122188/76633675-0dcd5080-6580-11ea-8687-7b7f9b582af0.png)
![screenshot13](https://user-images.githubusercontent.com/53122188/76633251-651ef100-657f-11ea-8c76-1504d31a9747.png)

**Comment by dbandy13** [comment]
@jsolson Zorg said to ping you for this. If you need logs I can grab them but I'll do a fresh launch. I've had the game running for a while at this point

**Comment by jsolson** [comment]
@CobaltWolf take a look at suncatcher2, I think it's pointed the wrong way.
