### ISSUE TITLE
Possible CFG issue LR87-AJ-11 Single Vac

### ISSUE THREAD

**Issue by Pappystein** [CobaltWolf/Bluedog-Design-Bureau#850]
The Thrust and ISP are very close to the TWIN engine LR87-AJ-11.   This is supposed to be 1/2 the Engine with a higher ISP.    IDK if this is in error or what.

Possibly this error is introduced by faulty data (a lot of older publications list performance of the LR87 as a single bell... for twin bell installations)
Again, don't know what should be "correct" here.  Just wanted to let you know it could be an issue

Double checked Single LR87 (non vacuum optimized) and it and all it's versions appear OK.

Actual cfg name is bluedog_LR87_11_Vac.cfg

================================EDIT
Correction, it is just the B9PS Data plates with the engine mode switching that need changing, the Core upgrades are correctly applied as if single bell!  Possibly Copied the LR87AJ11.cfg B9PS upgrades and didn't finish editing the text?

**Comment by zorg2044** [comment]
Fixed now, thanks for spotting it.
