### ISSUE TITLE
Saturn_Rescale doesn't change fuel level of some rescaled part.

### ISSUE THREAD

**Issue by AeJorMor** [CobaltWolf/Bluedog-Design-Bureau#851]
Some extra part from Saturn fuel tank doesn't have a sensible amount of fuel after use Saturn_Rescale. For the example Saturn S-I 14K Tank have more amount of fuel than Saturn-I-INT11, which is a stretched version of S-I tank. Similar problem have also been observe in S-II tank with they MS-II counterpart, and in S-IC tank with they MS-IC counterpart.

PS. Sorry for bad english.

**Comment by Pappystein** [comment]
I will double check but in my install these seem to be working correctly (I have an updated selection of MS-IIs to upload after I verify anyway.
