### ISSUE TITLE
Green paint for fenris/Thor rockets

### ISSUE THREAD

**Issue by longlong2002** [CobaltWolf/Bluedog-Design-Bureau#852]
green paint for the first Delta-3 rocket

![](https://i.redd.it/c1m9d7ci5hn21.jpg)

**Comment by zorg2044** [comment]
https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/cd218ae9fccfee86ab223cd3b25f286ba89cd2ef

**Comment by CobaltWolf** [comment]
its not the right green I need to do like a Delta green >.<

**Comment by longlong2002** [comment]
like a Soyuz paint

**Comment by zorg2044** [comment]
Updated with Delta K green.

https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/cfae0876ff0869ece8f1937b399b062f07fa02ab

![image](https://user-images.githubusercontent.com/39182212/80008773-9fb26c80-84e1-11ea-822e-f72b8a4c7cad.png)


![image](https://user-images.githubusercontent.com/39182212/80008747-96c19b00-84e1-11ea-8f35-033462935454.png)
