### ISSUE TITLE
Extendo-Spectrosconomenometer reports "Not suitable for atmospheric use" when above the moon

### ISSUE THREAD

**Issue by Maffif** [CobaltWolf/Bluedog-Design-Bureau#853]
.

**Comment by zorg2044** [comment]
@Maffif no idea which part specifically you mean

**Comment by CobaltWolf** [comment]
Maff why

**Comment by CobaltWolf** [comment]
In all seriousness the DMSA parts need to be audited to make sure they all work. There's a lot of stuff where I think the situations or something aren't set up right, and since they all have the "Not suitable for atmospheric use" string in the config the actual cause isn't obvious.

**Comment by DeltaDizzy** [comment]
He may mean the Ranger electrostatic boom thing (dont remember the actual name and dont have ksp open)

**Comment by DeltaDizzy** [comment]
Oh and to add to this, I think the OGO Mass Spectrometer is also affected
