### ISSUE TITLE
Current parts loading errors

### ISSUE THREAD

**Issue by Morphisor244** [CobaltWolf/Bluedog-Design-Bureau#861]
Currently the game throws the following errors upon loading. 

~~[LOG 16:33:45.260] Load(Model): Bluedog_DB/FX/PlumeParty/Engines/Generic/keroEagleLamp~~
~~[ERR 16:33:45.262] Texture 'Bluedog_DB/FX/PlumeParty/Engines/Generic/smoke1' not found!~~

~~[LOG 16:33:45.278] Load(Model): Bluedog_DB/FX/PlumeParty/Engines/Generic/keroShuttleBlaze~~
~~[ERR 16:33:45.280] Texture 'Bluedog_DB/FX/PlumeParty/Engines/Generic/smoke3' not found!~~

~~[LOG 16:33:45.497] Load(Model): Bluedog_DB/FX/PlumeParty/Engines/Turbine/subSporting~~
~~[ERR 16:33:45.498] Texture 'Bluedog_DB/FX/PlumeParty/Engines/Turbine/shock2' not found!~~

~~[LOG 16:33:48.211] Load(Model): Bluedog_DB/Parts/Mercury/bluedog_mercuryHeatshield
[ERR 16:33:48.214] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop' not found!
[ERR 16:33:48.214] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop_NRM' not found!~~

~~[LOG 16:33:48.226] Load(Model): Bluedog_DB/Parts/Mercury/bluedog_mercuryPod
[ERR 16:33:48.229] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop' not found!
[ERR 16:33:48.229] Texture 'Bluedog_DB/Parts/Mercury/bluedog_StructuralTop_NRM' not found!~~

[LOG 16:33:49.630] Load(Model): Bluedog_DB/Parts/SAF_Fairings/bluedog_Titan3_CT3_DPAF
[ERR 16:33:49.642] Tag: Icon_Hidden  is not defined.
[ERR 16:33:49.642] Tag: Icon_Hidden  is not defined.

[LOG 16:34:08.568] PartLoader: Compiling Part 'Bluedog_DB/Parts/Agena/ReturnCapsule/bluedog_Corona_Pod/bluedog_Corona_Pod'
~~[WRN 16:34:08.571] PartLoader Warning: Variable techtag not found in Part~~
[ERR 16:34:08.578] Cannot find fx group of that name for decoupler
[ERR 16:34:08.585] Cannot find fx group of that name for decoupler

~~[LOG 16:34:17.992] PartLoader: Compiling Part 'Bluedog_DB/Parts/Delta/DeltaK/bluedog_AJ10_118F/bluedog_AJ10_118F'
[WRN 16:34:17.995] PartLoader Warning: Variable techtag not found in Part
[ERR 16:34:18.005] Cannot find a PartModule of typename 'ModuleEngineIgnitor'~~

~~[LOG 16:34:18.620] PartLoader: Compiling Part 'Bluedog_DB/Parts/Delta/DeltaK/bluedog_TR_201/bluedog_TR_201'
[WRN 16:34:18.623] PartLoader Warning: Variable techtag not found in Part
[ERR 16:34:18.633] Cannot find a PartModule of typename 'ModuleEngineIgnitor'~~

[LOG 16:34:24.236] PartLoader: Compiling Part 'Bluedog_DB/Parts/Gemini/bluedog_MiniLab_Lab/bluedog_MiniLab_Lab'
[ERR 16:34:24.251] Invalid integer value! Field scienceMultiplier, value 1.5 on object of type ModuleScienceConverter

[LOG 16:34:27.280] PartLoader: Compiling Part 'Bluedog_DB/Parts/Gemini/Lander/bluedog_Gemini_Lander_Frame/bluedog_Gemini_Lander_Frame'
[ERR 16:34:27.286] Cannot find fx group of that name for decoupler

[LOG 16:34:27.292] [ModuleBdbBoiloff] Adding LqdHydrogen, 8
[ERR 16:34:27.297] Cannot find fx group of that name for decoupler

[LOG 16:34:27.301] PartLoader: Part 'Bluedog_DB/Parts/Gemini/Lander/bluedog_Gemini_Lander_Frame/bluedog_Gemini_Lander_Frame' has no database record. Creating.
[ERR 16:34:27.306] Cannot find fx group of that name for decoupler

[LOG 16:34:28.721] PartLoader: Compiling Part 'Bluedog_DB/Parts/Generic/bluedog_FairingBase_0p9375m_Static/bluedog_FairingBase_0p9375m_Static'
~~[WRN 16:34:28.724] PartLoader Warning: Variable techtag not found in Part~~
[ERR 16:34:28.727] Cannot find fx group of that name for decoupler
(repeated 4x)

[LOG 16:34:28.736] PartLoader: Part 'Bluedog_DB/Parts/Generic/bluedog_FairingBase_0p9375m_Static/bluedog_FairingBase_0p9375m_Static' has no database record. Creating.
[ERR 16:34:28.740] Cannot find fx group of that name for decoupler
[ERR 16:34:28.741] Cannot find fx group of that name for decoupler

[LOG 16:34:40.227] PartLoader: Compiling Part 'Bluedog_DB/Parts/ProbeExpansion/Pioneer6/bluedog_TTS1/bluedog_TTS1'
[ERR 16:34:40.236] Cannot find fx group of that name for decoupler
[ERR 16:34:40.245] Cannot find fx group of that name for decoupler

[LOG 16:34:40.251] PartLoader: Part 'Bluedog_DB/Parts/ProbeExpansion/Pioneer6/bluedog_TTS1/bluedog_TTS1' has no database record. Creating.
[ERR 16:34:40.256] Cannot find fx group of that name for decoupler

[LOG 16:34:44.032] PartLoader: Compiling Part 'Bluedog_DB/Parts/Redstone/bluedog_Juno1_Guidance/bluedog_Juno1_Guidance'
[ERR 16:34:44.043] Cannot find fx group of that name for decoupler
[ERR 16:34:44.052] Cannot find fx group of that name for decoupler

[LOG 16:34:44.056] PartLoader: Part 'Bluedog_DB/Parts/Redstone/bluedog_Juno1_Guidance/bluedog_Juno1_Guidance' has no database record. Creating.
[ERR 16:34:44.063] Cannot find fx group of that name for decoupler

Will look into some of the ones I can actually understand and report here if I can figure anything out.

~~Edit~~
-
~~Report plumeparty errors: the referenced textures indeed do not exist at the FX/Plumeparty/ locations. Files with the same names as referenced do however exist in FX/FX_New. Are those the ones intended to be used?~~

~~Edit2~~
-
~~Report Mercury texture errors: the referenced textures don't exist at that location. Several versions of bluedog_structuraltop exist in a multitude of other locations however. Only 1 version of bluedog_structuraltopNRM exists, in the Apollo parts map.~~

Edit3
-
Icon Hidden not defined is actually a missing definition in the bluedog_Titan3_CT3_DPAF.mu file.

Decoupler fx errors: all these parts are missing an "XXX = decouple" line in the part config.

bluedog_MiniLab_Lab: the scienceMultiplier value needs to an integer, which right now it isn't. So either it goes up or it goes down (it's 1.5 currently).

Couldn't quite figure out the ModuleEngineIgnitor problem :/

**Comment by jsolson** [comment]
Mercury texture errors: https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/ae4326fe23d1cc6834af5917f0c055abcec26206

**Comment by Morphisor244** [comment]
> Mercury texture errors: [ae4326f](https://github.com/CobaltWolf/Bluedog-Design-Bureau/commit/ae4326fe23d1cc6834af5917f0c055abcec26206)

Then this is the old stuff still there and complaining I guess?

**Comment by jsolson** [comment]
Yeah those are deprecated parts and the textures were deleted.

**Comment by DRVeyl** [comment]
```
[ERR 20:08:53.171] FloatCurve: Invalid line. Requires two values, 'time' and 'value'
	UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogFormat(LogType, Object, String, Object[])
	UnityEngine.Debug:LogError(Object)
	FXCurve:Load(String, ConfigNode)
	MultiInputCurve:Load(ConfigNode)
	ModelMultiShurikenPersistFX:OnLoad(ConfigNode)
	EffectList:LoadEffect(ConfigNode)
	EffectList:OnLoad(ConfigNode)
	Part:LoadEffects(ConfigNode)
	PartLoader:ParsePart(UrlConfig, ConfigNode)
	<CompileParts>d__56:MoveNext()
	UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
``` 
RealPlume config errors, I believe.

`[LOG 20:08:53.130] PartLoader: Compiling Part 'Bluedog_DB/Parts/Apollo/bluedog_Apollo_Block2_ServiceEngine/bluedog_Apollo_Block2_ServiceEngine'`
also
'Bluedog_DB/Parts/Atlas/bluedog_Atlas_LR101_Inline/bluedog_Atlas_LR101_Inline
'Bluedog_DB/Parts/Atlas/bluedog_Atlas_LR101_Radial/bluedog_Atlas_LR101_Radial'
'Bluedog_DB/Parts/Centaur/bluedog_Centaur_RL10/bluedog_Centaur_RL10'
'Bluedog_DB/Parts/Centaur/bluedog_Centaur_RL10A41/bluedog_Centaur_RL10A41'
'Bluedog_DB/Parts/Centaur/bluedog_Centaur_RL10B2/bluedog_Centaur_RL10B2'
'Bluedog_DB/Parts/Delta/bluedog_Delta2_RS27/bluedog_Delta2_RS27'
(... others...)

I am very unfamiliar with plume configs, and my uneducated guess is that in eg <https://github.com/CobaltWolf/Bluedog-Design-Bureau/blob/master/Gamedata/Bluedog_DB/Compatibility/RealPlumes/BDB_Delta.cfg#L101-L138> you define a value for `energy` and `speed` and also attempt to define nodes with the same name, and RealPlume dislikes this?

Minimal test install: BDB + dependencies, + RealPlume.
