### ISSUE TITLE
REVAMP: Gemini/Leo Spacecraft

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#864]
# HISTORICAL
Covers the historical spacecraft as flown for Gemini 3-12
- [x] Capsule
* Would like to have a mesh toggle to add the portholes to the hatches, some designs feature these
* Would like to have texture variants for the shingled areas, will try to UV unwrap appropriately
- [x] 1.5m Heatshield
* Includes some sort of switch for hatch
- [x] Reentry RCS
- [x] Main Parachute
* Would like to include variant that is capable of two-point suspension like the real one
* Need to figure out - would Rogallo wing ever be possible in BDB?
- [x] Docking Cone
* Would like to include non-docking variant maybe?
- [x] ~~Pilot Chute~~ Cut, unneeded
- [x] Drogue Chute (maybe combine these two... there's no need for both)
- [x] Nose Cap
- [x] Horizon Scanner (goes on left side of capsule, right where the slope meets the reentry RCS. Need to figure out what this does)

- [x] Decoupler
- [x] Retro Section
* NEED TO DECIDE: Will the RCS modules be integrated into the Retro and Equipment sections?
* NEED TO DECIDE: How does the retro section decouple from the equipment section?
* Would like to have mesh switch on the canon retro section for crew tunnel
- [x] Retro motors
* NEED TO DECIDE: Are these going to be separate? Connect via nodes? Baking them into the parts will cause issues with variants down the line.
- [x] Equipment Section 
* NEED TO DECIDE: How will Equipment Section variants work? There are many combinations of batteries and fuel cells. One thought I had was to make the[ "crescent" sections ](https://i.imgur.com/s8Pldog.png)separate node attached parts and then have a bunch of variants of those.
* That also means there will be less stuff in the way for the pressurized SM modules.
* NEED TO DECIDE: Are the main OAMS thrusters integrated into the equipment module?
* Want to add variant to add the "pinstriped" version seen in the Gemini 6/7 rendezvous photos.

- [x] Magnetometer
- [x] Spectrometers
- [x] UHF Antenna
- [x] Radar Evaluation Pod

# GEMINI-B
The Gemini intended for MOL. Featured a cut down adapter section that matched the slope of the pod
- [x] Retro Section (includes 6 retro motors and crew tunnel
- [x] Adapter Section (short adapter, includes supplemental LES motors and short tunnel section)
- [x] LES motors? or just integrate into the adapter.

# BIG GEMINI
McDonnell studies in 1967 and 1969. 1967 gives us the conical SM that matches the S-IVB diameter, 1969 is the more cylindrical design. For now we're just focused on bringing the capsule back to working order.

- [x] Big G Crew Cabin (1.5m to 2.5m)
* I have some good reference for this, it will look a bit different.
- [x] 2.5m Heatshield
- [x] 2.5m Big G Decoupler
* I have better reference for this now and can add in the proper umbilicals etc

# LUNAR RECON GEMINI
[McDonnell study Apr 1964.](https://drive.google.com/file/d/12HtOUzkRLpHcVpzaPboI-SACdeYEvHkJ/view?usp=sharing) Variety of modifications for Gemini for circumlunar missions.
- [x] [Circumlunar Spacecraft adapter](https://i.imgur.com/fuP2Iak.png)
* This will add back the older functionality of having the retro and equipment modules in a single 1.5m to 1.875m adapter part. Seems prudent to add. 
- [x] Camera variant of Gemini nose?
- [x] Antenna
- [x] Dish

# MORL FERRY GEMINI
[McDonnell study Nov 1963. ](https://drive.google.com/file/d/1pFVEM6Dws99QIn2LV_O_0C5QX0li6DzL/view?usp=sharing)Variety of modifications for Gemini to make it into a ferry vehicle for a variety of notional space stations. Includes things like rear-docking adapter sections.

- [x] Long Ferry Service Module

# AHISTORICAL PARTS
Catch-all for the ahistorical parts that existed that must be remade to meet current functionality, as well as some low-hanging-fruit that should be doable with the new changes. The existing MOL/GMSS parts as well as the LES tower should be fine/need minimal changes. 
- [x] Augustus Resupply Pod
- [x] 1.875m "Rumble Seat"
- [x] 1.875m Heatshield
- [x] 1.875m Decoupler
- [x] Shuguang Retro Module
- [x] Shuguang Equipment Module
- [x] Shuguang Nose
- [x] Arrow Adapter (just a pressurized module?) (Morning of the Maple Leaf)

**Comment by jsolson** [comment]
Engines should be separate parts.

I lean toward integrating the rcs where possible.

**Comment by longlong2002** [comment]
and Revamp the Centaur upper stage?

**Comment by Pappystein** [comment]
Going from Memory here (my gemini book is burried ATM) but the Scanner for the Gemini Capsule was, I believe a Circular-error measuring device.  IE was the Inertial guidance accurate.  It was also used to measure the circularity of the Earth itself.    So two possible Experiments (Am I were I should be) and (Is Kerbin flat?)

**Comment by Pappystein** [comment]
I agree on Combining Pilot and Drogue.   Is there any chance however that the Drogue can actually land the nosecone safely?   That would be nice for both this and Mercury (I haven't checked if RealChutes has access to these yet)

**Comment by Wallum** [comment]
New Gemini Nose Docking Mechanism index extender animates through the low profile docking port (shown below) 
![image](https://user-images.githubusercontent.com/6353826/80554255-73f12400-89c4-11ea-91c6-74d9325758cd.png)
