### ISSUE TITLE
Give the MOL/MOS-CB RCS blocks engine configs

### ISSUE THREAD

**Issue by Delliardo** [CobaltWolf/Bluedog-Design-Bureau#865]
I think these RCS blocks would have a bit more versatility if they also had a monopropellant engine config.  Might require a new thrust transform added to the part though.

If a craft uses only these blocks to move around in orbit, this will mitigate Mechjeb not using RCS thrusters to calculate when to start burning by essentially bypassing the issue.

![screenshot186](https://user-images.githubusercontent.com/4108176/78411580-17c1fc80-75de-11ea-8451-5b75c0179bc4.png)

**Comment by biohazard15** [comment]
Single and double R-4D would also benefit from a "true" engine config and also from top/bottom attach nodes. This would make them an excellent choice for satellite main propulsion (just like IRL).

**Comment by CobaltWolf** [comment]
Sarbian says Mechjeb is compatible with Fore By Throttle

**Comment by Delliardo** [comment]
Well I have the latest version of Mechjeb and it still burns at 0 instead of something like -25 node time.  I'll ask in the Mechjeb thread if there's a certain way to get it to work.

**Comment by CobaltWolf** [comment]
If you need to, log an issue with Mechjeb. It sounded like they should be working as far as he knew.

**Comment by CobaltWolf** [comment]
And if not, its functionality worth adding/improving

**Comment by Delliardo** [comment]
See here:  https://github.com/MuMech/MechJeb2/issues/1252
