### ISSUE TITLE
Orange Spike when using the Mercury heatshield

### ISSUE THREAD

**Issue by JayTheAmazingToaster** [CobaltWolf/Bluedog-Design-Bureau#868]
Using 1.8.1 dev version of BDB, an orange spike effect appears when using the Mercury Heatshield. It has no effect on physics and is purely visual and appears regardless of whether or not F12 is enabled.
[Image:](https://media.discordapp.net/attachments/339891313971429378/696527767407165440/screenshot22.png?width=1125&height=703)

This effect disappears when using the restock heatshield in its place.
[Image:](https://cdn.discordapp.com/attachments/339891313971429378/696529745109844068/screenshot45.png)

**Comment by jsolson** [comment]
Just some debug stuff inadvertently left in.
