### ISSUE TITLE
Game uses deployed size of Mercury parachute to calculate vessel size

### ISSUE THREAD

**Issue by bfrobin446** [CobaltWolf/Bluedog-Design-Bureau#869]
Tested commit f14828b (BDB and the dependencies included in the repo) on a clean install of KSP 1.9.1 after seeing the same behavior on my heavily-modded KSP 1.8.1.

According to the base-game Engineer's Report, a 2-part vessel consisting of Hermes M-PRC pod and Hermes M-LCM nose section is 1.3 meters tall, as it appears in the editor. When I add the Hermes-MASD main parachute inside the nose section, the vessel is now 21.3 meters tall.

The capsule with parachute exceeds the height limit of the starting launch pad, making it inconvenient to use the Hermes parts when they're unlocked in early career.

**Comment by CobaltWolf** [comment]
I legit have no idea how to fix that :(

**Comment by bfrobin446** [comment]
We can hope that somebody who knows why that happens will see this issue someday. Until then, I can use a RealChute procedural chute instead of the official part.

**Comment by jsolson** [comment]
This is what it looks like in DebugStuff. That pSphere57 looks suspicious. No, other chutes don't look like this.

![Untitled](https://user-images.githubusercontent.com/16825376/79478124-02cf6b00-7fd9-11ea-8f69-5e1f0aae22e2.png)

**Comment by Rodg88** [comment]
Doesn't appear to happen anymore
