### ISSUE TITLE
No adequate replacement for HLR-VD01 tiny separator in 1.7.0

### ISSUE THREAD

**Issue by biohazard15** [CobaltWolf/Bluedog-Design-Bureau#871]
HLR-VD01 was a 0.125m separator that included optional node to make it a 0.125m->0.3125m payload adapter. This was very useful for probes that require some clearance, like Pioneer 1 or Vanguard 1. While 1.7.0 provides several decouplers in these sizes, there is no 0.125m->0.3125m adapter. The only way now is to stack tiny decouplers, which is less than optimal way.

**Comment by jsolson** [comment]
![Untitled](https://user-images.githubusercontent.com/16825376/78944761-a32f0800-7a8c-11ea-97c1-a59e0d3960b8.png)

**Comment by biohazard15** [comment]
HLR-VD03 is too short. It's barely enough for Pioneer 1 to be mounted on Star-20 (antennas still clip into SRB casing), and is not enough to be mounted directly on anything else, like fairing base:


![screenshot73](https://user-images.githubusercontent.com/62663094/78968781-79222800-7b16-11ea-9a40-aba92d1f7c28.png)
