### ISSUE TITLE
Issue with the BD-AFB-25-3.125m Fairing

### ISSUE THREAD

**Issue by jackdets** [CobaltWolf/Bluedog-Design-Bureau#875]
![image](https://user-images.githubusercontent.com/61482248/79059539-34e37480-7c49-11ea-9eb0-b305425987db.png)
The stock procedural fairing for the LDC parts has some sort of strange issue with it, here's a picture of two (nearly) identical fairings side by side. The glitched one is the LDC fairing and the normal one is the Sarnus 3.125m fairing. As far as I can tell, this issue isn't present in any other fairings.

**Comment by jsolson** [comment]
fixed thanks!
