### ISSUE TITLE
Ranger radar altimeter: doesn't work with SCANSat and BDB contracts

### ISSUE THREAD

**Issue by biohazard15** [CobaltWolf/Bluedog-Design-Bureau#880]
One of possible objectives in Ranger contract is bd_radarAltimeter. However, this experiment is replaced with SCANSat functionality if the latter is installed, making contract with this objective impossible to complete.

**Comment by zorg2044** [comment]
This issue is being dealt with in the broader context of similar problems here https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/829
