### ISSUE TITLE
HLR-OOG-EP2 gravimetric scanner: Deployment actions are bugged

### ISSUE THREAD

**Issue by biohazard15** [CobaltWolf/Bluedog-Design-Bureau#887]
- In editor, only "Deploy" is shown in PAW. When you press it, it deploys, but PAW still shows "Deploy" instead of "Retract". If you press "Deploy" again, it replays deploy animation (part blinks into retracted state and then deploys).
- In flight, both "Deploy" and "Retract" are present in PAW. "Deploy" behaves like in editor. "Retract" does nothing, even if you deployed the tool before pressing it.
- Running the experiment always behaves like it wasn't deployed before (i.e. warning message and playing deploy animation), even if it was.
- All mentioned actions behave in the same bugged way if mapped to action groups.

**Comment by jsolson** [comment]
The HLR-OOG-EP2 gravimetric scanner should be working now. Cleaned up a bunch of stuff on OGO.

The HLR-OOG-RPWS Solar Panel, the one with the experiment, doesn't work right, but it's functional as long as you deploy the panel before trying to run the experiment. The solar panel and the DMSAG experiment can not both control the animation without trouble.

**Comment by CobaltWolf** [comment]
@jsolson yeah I knew that going in. Maybe I can go back and make them explicitly separate animations/keyframes in the .mu...
