### ISSUE TITLE
Payload adapter parts

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#888]
Spin tables
- [x] Spin table 0.625
- [x] Spin table 0.9375

Dual payload adapters
- [x] Delta II Dual Payload Adapter
- [x] Delta IV

Structural payload adapters
- [ ] Structural payload adapter 0.625 to 0.3125
- [ ] Structural payload adapter 1.25 to 0.9375/0.625
- [ ] Structural payload adapter 1.5 to 1.25/0.9375/0.625
- [ ] Structural payload adapter 2.5m to 1.875m
- [x] Structural payload adapter 3.125m to 2.5m

Decouplers
- [ ] 0.3125 to 0.125 tall
- [ ] 2.5m generic

**Comment by biohazard15** [comment]
May I also suggest a 0.3125 to 0.125 "tall" adapter to mount things like Pioneer 1? #871

**Comment by zorg2044** [comment]
Sure why not, should be a simple part.

**Comment by GoldForest383** [comment]
Delta IV dual payload adapter?
