### ISSUE TITLE
New Gemini Nose Docking Mechanism index extender animates through the low profile docking port (shown below)

### ISSUE THREAD

**Issue by Wallum** [CobaltWolf/Bluedog-Design-Bureau#889]
New Gemini Nose Docking Mechanism index extender animates through the low profile docking port (shown below) 
![image](https://user-images.githubusercontent.com/6353826/80554255-73f12400-89c4-11ea-91c6-74d9325758cd.png)

**Comment by jsolson** [comment]
#864

**Comment by CobaltWolf** [comment]
Also need to rotate the port 180 degrees so the docking rotations match
