### ISSUE TITLE
Science part balance

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#90]
Need to do a balance pass on the science parts.

**Comment by CobaltWolf** [comment]
I'd like to move the hydrometer to Space Exploration, and possibly increase its value

**Comment by rasta013** [comment]
Since I just finished writing the definitions for this experiment I couldn't agree more with this idea.  It is a highly limited experiment and 2 of the 3 bodies where it has a wide range of situations open are somewhat more difficult to get to (Eve and Laythe).  With a base value of only 7 this contributes very little in the way of overall science.

**Comment by CobaltWolf** [comment]
And water is a pretty big deal... any idea what to change it to?

Matthew Mlodzienski
3D Animation and Visual Effects
Westphal COMAD 2017

**Comment by rasta013** [comment]
I'll have to do some testing with it but I've already bumped mine up to 10 and will check to see what kind of returns I get with various settings.  When balancing science I like to see what will come out of it at different difficulty settings.

**Comment by rasta013** [comment]
OK so I've been doing testing on the Hydrometer and it is definitely low considering how limited it is in the number of places it can be run.  If you total all the biomes in stock, it currently has a total of 38 different locations with the highest total (@100% science reward for a baseline) coming from Laythe/Flying Low with a science value of 90.  Just by way of comparison, the stock Barometer currently comes on the exact same tier as the Hydrometer and can be run in all situations (Space hi/lo, Flying hi/lo, landed by biome) and rewards 120 science.  Not only does it reward 25% more per run, it can be run in a vastly higher number of situations (I don't know the total but it's well over 100!)

So the question becomes, what to change it too.  The barometer is currently set to a value of 12 but as mentioned, it can be run in a lot wider range.  A comparison can sort of be made to DMagic's Bathymeter.  It must be submerged so obviously it is even more limited than the Hydrometer and has a value of 16 but makes up for it with a huge data scale of 3 making it extremely valuable to a lab.

With all these little bits in mind I can see two different courses of action (or combination of them).

1: Increase the base value of the experiment up to around 12-14 and increase the data scale to either 2 or 3 to make running it more valuable to a lab.

2: (My recommendation) Leave the value at 9 but remove the atmospheric limitation and make it a strictly landed only experiment - i.e. change the situation mask to 1.  Also, with this scenario I'd bump the data scale to 2 where it becomes worthwhile to a lab without being a gold mine.

My justification for removing the atmospheric limitation:  There is currently nothing other than the stock Surface Hydrogen Scan that is supposed to measure water when landed.  All other experiments I know of measure it from orbit.  By removing the atmospheric limitation and making it a landed only experiment it simultaneously makes it more worthwhile to carry on a regular basis without being overkill and it falls more in line with most other experiments in the number of places it can be run.  With this situation I could even see the base value being dropped to 8 if you worry about too much science too quickly.

This is my 2 cents - thoughts?  criticism?  I'm an idiot an know nothing about this game? :smiley_cat:

**Comment by CobaltWolf** [comment]
The experiment tests the air for water. There is/will/would be another experiment to test the soil, if that's what you mean for the second option. With that in mind I would favor the first suggestion, along with (as I said before) moving it to Space Exploration, since that node doesn't have enough science parts.

**Comment by rasta013** [comment]
Cool.  With the idea that another experiment is coming at some point as a soil test then I'd favor the first more anyway.  Keeping it limited but making it a little more worthwhile while helping out labs is a great way to make it more useful.  Definitely for moving it to the Space Exploration tab.  I'd have to double check but I'm about 99% sure I put it there with my CTT patch too. LOL
