### ISSUE TITLE
bluedog_Thor_AbleAdapter texture switching

### ISSUE THREAD

**Issue by Invaderchaos** [CobaltWolf/Bluedog-Design-Bureau#901]
I have been trying to make texture switching for the bluedog_Thor_AbleAdapter part. Currently, it has no texture switches, and the blue/green/cream thor boat tail textures I've added have variants for this part as they share the same texture file. However, every time I try to write a cfg for this part to add variants, the texture gets messed up. The exterior texture seems to come out just fine, however, the interior of the part appears to have no texture. It is possible that I am just writing the cfg wrong, however, it has been suggested that the meshes are not properly named for B9.

**Comment by CobaltWolf** [comment]
@Invaderchaos this should be fixed now, the relevant mesh is now named... "Mesh"
