### ISSUE TITLE
Dona Lander Can IVA is reversed

### ISSUE THREAD

**Issue by ACIsabelle** [CobaltWolf/Bluedog-Design-Bureau#902]
![screenshot13](https://user-images.githubusercontent.com/64968665/81300862-efb43600-9080-11ea-9eca-88297f8bface.png)
![screenshot14](https://user-images.githubusercontent.com/64968665/81300866-f17df980-9080-11ea-939d-5f780367d37b.png)
![screenshot15](https://user-images.githubusercontent.com/64968665/81300868-f17df980-9080-11ea-9c87-72672ffb800c.png)

**Comment by CobaltWolf** [comment]
If you are playing on the release build, it has been fixed and will be in the next update :)

**Comment by ACIsabelle** [comment]
Oh, well. Thanks!

**Comment by CobaltWolf** [comment]
@ACIsabelle Appreciate logging the issue on Git so it doesn't get lost! :)
