### ISSUE TITLE
Split BDB into three packs

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#91]
Sooner we get this over with the sooner it'll stop hurting. Splitting BDB into three packs - Bluedog_DB (main mod), Bluedog_LV (all the launchers) and Bluedog_PE (probes, antennas, science). @jsolson I think you answered this before but we need 3 separate repos right?

**Comment by jsolson** [comment]
1 repository. We need include/exclude lists for each variant.

Look at the file build.bat in the root. Run it and you will understand
(might need to adjust the path to 7zip).

The manual is not compressible and is adding 20+ mb to each download. I
suggest we link to that separately.

**Comment by CobaltWolf** [comment]
Does that mean you need to manually include everything in each list?

I will see about the manual. I think it still needs to be converted to a grayscale compressed document which would reduce it to probably under 5.

**Comment by jsolson** [comment]
Best approach is probably an include list for the science pack, and an
exclude list for the lv pack. By directory of course. I'll play with it and
see what issues come up.
