### ISSUE TITLE
Missing parts after updating to KSP 1.9.1

### ISSUE THREAD

**Issue by psychonaut25** [CobaltWolf/Bluedog-Design-Bureau#911]
Today I decided to update all of my mods to the KSP 1.9.1 versions, and when I attempt to load my save file I am asked if I'm sure I want to load the save, because several active vessels are missing certain parts.

Some of these were from NearFutureSolar, and I found [this issue](https://github.com/ChrisAdderley/NearFutureSolar/issues/77) on the Github page for that particular mod, and I solved the problem using the advice found there.  However, one of these missing parts is called bluedog.MiniRadialDecoupler, and I can't seem to find it anywhere.

Can anybody point me in the right direction here?  I just want to load my save file in the latest version of KSP, but now I'm having to hunt down multiple missing parts from multiple mods.

**Comment by jsolson** [comment]
We don't claim to support anything higher than 1.8.1, but look in `GameData/Bluedog_DB/Parts/Generic/bluedog_RadialDecoupler_Mini.cfg`

The latest release is 1.7.3/1.8.1, and what's in the development branch is 1.8.1 only. I think both will work in 1.9.1, but there are many issues with that KSP version and mods.

**Comment by psychonaut25** [comment]
Thank you... I was able to edit that config file and use the old name, and that resolved the issue.  In the future I will probably edit my save & craft files with the new name so as to avoid this issue in future updates.  Much appreciated.
