### ISSUE TITLE
1.7.0 Dev on KSP 1.10

### ISSUE THREAD

**Issue by sick13** [CobaltWolf/Bluedog-Design-Bureau#921]
Some info for feature updates

KSP 1.10 hangs with the following Message

[LOG 17:14:38.100] DragCubeSystem: Creating drag cubes for part 'bluedog.solarAntenna'
[EXC 17:14:38.134] NullReferenceException: Object reference not set to an instance of an object
	ModuleDeployablePart.AssumeDragCubePosition (System.String name) (at <c168e21ec56346b082f89043e76162e1>:0)
	DragCubeSystem+<RenderDragCubes>d__34.MoveNext () (at <c168e21ec56346b082f89043e76162e1>:0)
	UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <5aeafee3fea24f37abd1315553f2cfa6>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

**Comment by zorg2044** [comment]
Dev branch now loads on KSP 1.10.1
