### ISSUE TITLE
Galleon-L 1.5m Straight Fairing Adapter SAF colliider issue

### ISSUE THREAD

**Issue by Mudwig** [CobaltWolf/Bluedog-Design-Bureau#925]
The spacecraft doesn't separate as it seems the fairing colliders remain in place after separation.

https://imgur.com/hN8Zhtl

Edit: It's not the only one.

https://imgur.com/Exb8o7a

Edit2: It's all of the 1.5m Delta I and II style fairings
They have a very small attachable/collidible surface a few meters above the top of the default fairing.

https://imgur.com/w4oSewc

**Comment by zorg2044** [comment]
will take a look thanks

**Comment by zorg2044** [comment]
@Mudwig I wasn't able to recreate the problem but I did find a small collider problem in the file. Please see if this has fixed it thanks.

be4ac434f1caf43c0b5a649781ebd89709f6821f

**Comment by biohazard15** [comment]
Tried Delta and Galleon adapters, looks like it's finally fixed. Thanks!
