### ISSUE TITLE
Need additional science definitions

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#93]
Some of the experiments need more definitions. Specifically:
-Cameras
-Hydrometer
-Ion Trap
-Solar science

**Comment by CobaltWolf** [comment]
@rasta013 assisted with this, for two experiments that I forgot had limited configs!
https://github.com/CobaltWolf/Bluedog-Design-Bureau/pull/98

**Comment by rasta013** [comment]
I'll also take a look at the Cameras, Hydrometer and Ion Trap experiments over this next week as well and see if I can get the definition creative juices flowing again.

**Comment by rasta013** [comment]
My last PR issued today has now added in complete definitions for the Hydrometer for all situations on all stock bodies.  I've also completed the SrfLanded definitions for the camera experiment for all stock bodies out to Dres.  I still have Jool and Eeloo to complete to finish these.  

I'll be finishing the SrfLanded definitions for the camera in the next update I provide and will also be getting around to looking at the Ion Trap.

**Comment by CobaltWolf** [comment]
@rasta013 where did you leave off on this?
