### ISSUE TITLE
Delta IV

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#940]
- [x] RS-68 engine (RS 68+A, RS68B with white nozzle, RS68C with regen nozzle). Regular, Delta IV boattail, and Compact mounts.
- [x] 5m DCSS
- [x] Common Core Booster tankage
- [x] 5m DCSS payload adapter and fairing base.
- [x] Delta IV Heavy booster decouplers
- [x] Delta IV Heavy nose cone
- [x] Delta IV Heavy Interstage (3.125m)
- [x] 4m DCSS tank stretch
- [x] Delta IV Medium interstage ( 3.125-2.5m, either the current one needs a stretch or a new dedicated one needs to be made if the 4m DCSS is stretched
- [x] Delta IV small interstage  (3.125-1.5m)
- [x] Standalone version of truss from fairing base.

Known issues
- [x] surface attaching other tanks to the decoupler isnt great at the moment.
- [x] endcap material for LOX tank
- [x] fx for lox exhaust
- [x] realplume needs to fit the bell a bit better

Fairings
- [x] to be covered in SAF issue, but likely the composite fairing, a 3.75m widebody fairing stylistically suitable for both Delta IV widebody fairing and LDC, and possibly a modification to the Titan IV wallbase for a fully accurate Delta IV metal fairing texture space allowing.

**Comment by biohazard15** [comment]
Will it be possible to add a "reduced thrust" mode switch to RS-68? This would allow to control Heavy's core engine with AG instead of PAW slider.

**Comment by zorg2044** [comment]
Theres not really a way to do that due to the various variants with different stats. I believe theres a mod that lets you action group throttle settings though? The name escapes me right now.

**Comment by jsolson** [comment]
Delta IV tentative weights:

RS-68 ~2.5 tons
CCB Tankage 27,000 total fuel units. 6.75 tons dry mass. 101,250 LH2, 6,750 Oxidizer.
