### ISSUE TITLE
LR87 Titan II variant has solid grey mount texture

### ISSUE THREAD

**Issue by DeltaDizzy** [CobaltWolf/Bluedog-Design-Bureau#946]
![](https://media.discordapp.net/attachments/380515333968232456/752992533415592117/unknown.png)

It occurs regardless of whether the Chayrol paint job is selected or not. The corner "nubs"are affected in all variants that have them.

**Comment by Invaderchaos** [comment]
Yes, I am aware of this issue. Earlier, a duplicate for the GLV texture and NRM were found in the titan folder, which once discovered a little bit ago was deleted. However, it was later discovered that the titan 2 engine base were dependent on the duplicate textures. I am temporarily adding the deleted textures via PR. Eventually, the .mu of the titan 2 engine base will have to be fixed, and the duplicate textures once again removed. However for now, the engine base will appear to be fixed as soon as my PR is approved.

**Comment by DeltaDizzy** [comment]
Leaving this open until the mu is fixed, then.
