### ISSUE TITLE
Science available with Nimbus 1

### ISSUE THREAD

**Issue by OrbitalManeuvers** [CobaltWolf/Bluedog-Design-Bureau#947]
Hiya ... not sure if you want to address this in any way or not, but here's my observation...

When the Nimbus probe and its launch vehicle become friznibuildable, there's really no photographic science available that reflects what Nimbus 1 accomplished:

"Launched on August 28, 1964, Nimbus 1 sent back more than 27,000 images before its solar-power systems failed on September 22, 1964. It was the first NASA satellite to provide both daytime and nighttime images of hurricanes."
https://earthobservatory.nasa.gov/images/84542/the-legacy-of-nimbus

I believe the available cameras are the Zafar, the SG-1 and SG-4, none of which can transmit images. Anyway, just thinking it would be cool if the BDB Nimbus was able to do something along the lines of the RL mission.

**Comment by jsolson** [comment]
I guess a visual camera never got made for Nimbus. Seems like there should be one.

**Comment by Morphisor244** [comment]
Maybe give it the ability to use Neptune Camera by Beale?
