### ISSUE TITLE
Delta P/K 1.5m SAF adapter: Bugged collider

### ISSUE THREAD

**Issue by biohazard15** [CobaltWolf/Bluedog-Design-Bureau#949]
There is a collider on top, outside the mesh, which may interfere with payload separation. Stock fairing variant and 1.875m variants doesn't seem to have this bug. 
See screenshot:

![screenshot34](https://user-images.githubusercontent.com/62663094/93146938-2a01a400-f701-11ea-8207-20a751f3ad7f.png)

**Comment by zorg2044** [comment]
Looks like this: isnt totally fixed yet then, will take another look, tracking the issue there https://github.com/CobaltWolf/Bluedog-Design-Bureau/issues/925

**Comment by zorg2044** [comment]
I think its fixed now
