### ISSUE TITLE
Agena dual payload adapter

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#952]
Doesnt work as configured correctly. Needs either optional nodes on relevant fairing bases so both the first payload and the adapter can be attached to the fairing base or a custom decoupler base part for it with two top nodes. Same as above but would be fully modular.

**Comment by zorg2044** [comment]
@CobaltWolf would you have room on that sheet for a separate simple circular base for this?

**Comment by biohazard15** [comment]
IMO, a custom decoupler for it would be redundant. MPA does not work well with other 0.9375m fairing bases - its lower skirt sticks out (4900 is slightly larger and can accomodate it), and for 1.25m+ bases you can use 4900 without fairing.

**Comment by zorg2044** [comment]
a custom decoupler would make it self contained and it only has issues on the ranger base as far as I can see. If thats not feasible I'll patch in the nodes onto the relevant bases as optional nodes via B9PS

**Comment by CobaltWolf** [comment]
Yeah just put the nodes in via B9 I think.
