### ISSUE TITLE
Delta IV Engine showing plume even though its not activated.

### ISSUE THREAD

**Issue by SlapheadSte** [CobaltWolf/Bluedog-Design-Bureau#953]
RS-68 giving off Plume even without thrust being applied to the engine, seems to only happen with the Regen version for the moment being. ![image](https://user-images.githubusercontent.com/24409288/93650720-35a5e100-fa07-11ea-9a63-9927085cb0b4.png) 
![image](https://user-images.githubusercontent.com/24409288/93651487-86b6d480-fa09-11ea-90fb-e09cf9053072.png)
![image](https://user-images.githubusercontent.com/24409288/93651595-f200a680-fa09-11ea-97ad-7fefc601bcd0.png)

**Comment by zorg2044** [comment]
sounds like your B9 part switch is not up to date
