### ISSUE TITLE
Automatically generate mini-packs

### ISSUE THREAD

**Issue by CobaltWolf** [CobaltWolf/Bluedog-Design-Bureau#96]
@jsolson would it be possible to use bat files to build different releases for the mod? Like a Bluedog_DB_Lite sort of thing for people that just want a replacement for OMSK? Since that way it would automatically grab any updated files and build the update when it's ready.

**Comment by jsolson** [comment]
Yes. They would be added to build.bat, along with appropriate include/exclude files. We may or may not end up reorganizing the folder structure a little to accommodate this.
