### ISSUE TITLE
Redstone fin control surface invisible when set to green variant

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#969]
https://images-ext-2.discordapp.net/external/Ai-M0wMF3XCIgz28DxbI1qWFqlK4azCGBwF-d6zQiL8/https/i.imgur.com/78IVn9q.mp4

The flaps seem to be invisible on the green variant.

``bluedog_Redstone_Fin_Basic``

**Comment by GoldForest383** [comment]
Example/Evidence:

https://imgur.com/a/XuarRYD
