### ISSUE TITLE
S-IV interstage clips into S1 First Stage Tank

### ISSUE THREAD

**Issue by Sgt-Shutesie** [CobaltWolf/Bluedog-Design-Bureau#97]
The S-IV interstage clips into the tank below it when even just the force of gravity is applied. Not game breaking, but still an issue. Is not present in the VAB.

**Comment by CobaltWolf** [comment]
What do you want from me

**Comment by CobaltWolf** [comment]
Has anyone experienced this? @jsolson ?

**Comment by jsolson** [comment]
No but I use KJR.

**Comment by Cowboy-WY** [comment]
I see this without any joint reinforcement mod.  Sags pretty bad with Apollo attached to it.

I'm not 100% sure, but it seems to be related to hollow parts.  Looks like it is just a matter of how much weight is on something that is hollow.

Maybe just list KJR a requirement for the heavy stuff.

![saturnvab](https://cloud.githubusercontent.com/assets/20691292/17304702/1e9681c8-57e4-11e6-80c6-0f56484ed9a0.PNG)
![saturnsag](https://cloud.githubusercontent.com/assets/20691292/17304709/241914d0-57e4-11e6-9626-4e7b23894944.PNG)
![centaur sag](https://cloud.githubusercontent.com/assets/20691292/17304712/275ae236-57e4-11e6-947c-f14fcf48fe83.PNG)

**Comment by jsolson** [comment]
Yeah I think some of think the KJR requirement just goes without saying but maybe there should be a note somewhere. The I know Titan IV nearly comes apart sitting on the pad without it.

**Comment by CobaltWolf** [comment]
I've seen so many people say they like the stock wobbly joints. I don't understand it. Shit like this happens. I'll leave this open as a reminder to add the notice to the OP.

**Comment by Modsojoy** [comment]
Is there a way to change the Node Strength?

**Comment by CobaltWolf** [comment]
They're already set as strong as they can be. There might be more options in 1.2

**Comment by Modsojoy** [comment]
then go the Most kerbal route Possible - Moar STRUTS!

**Comment by jsolson** [comment]
Not a bug. Well see what happens with kjr after 1.2 is out. #166
