### ISSUE TITLE
H-1D doesn't show up during Atlas part search

### ISSUE THREAD

**Issue by GoldForest383** [CobaltWolf/Bluedog-Design-Bureau#975]
I think it should, considering it is supposed to be used on CELV.

**Comment by zorg2044** [comment]
it does come up if you search specifically for celv slv3k or slv3x

**Comment by GoldForest383** [comment]
Ah. Still think it should show up during the general atlas search, but okay, thanks.

**Comment by zorg2044** [comment]
bec281aad2a4c0291b6430bedd03e2973b72da44
