### ISSUE TITLE
Pioneer 5 / Explorer 6 Probe missing SCIENCE

### ISSUE THREAD

**Issue by CAPFlyer** [CobaltWolf/Bluedog-Design-Bureau#980]
Found this due to the Historic Spaceflight pack - the Pioneer 5 / Explorer 6 probe core does not have a Micrometeorite Impact science experiment, which is required to complete the Pioneer 5 mission.

**Comment by CobaltWolf** [comment]
@Invaderchaos what science does it have right now? We don't want to overload the probe. 

@CAPFlyer on the note above - we need to find a balance between giving historical experiments, and not overloading these little probes and making them overpowered. By Historic Spaceflight pack - do you mean @Morphisor244 's contracts?

**Comment by CAPFlyer** [comment]
Yes, I mean @Morphisor244 's History of Spaceflight contracts.  It calls for a Geiger Counter and a Micrometeorite Impact science experiment.  As of right now, it does a Geiger Counter and Magnetometer experiment.

Encyclopedia Astronautica says Pioneer 5 made Magnetic Field and Radiation measurements, so maybe the probe is correct and @Morphisor244 needs to change his mission?

**Comment by zorg2044** [comment]
> Yes, I mean @Morphisor244 's History of Spaceflight contracts. It calls for a Geiger Counter and a Micrometeorite Impact science experiment. As of right now, it does a Geiger Counter and Magnetometer experiment.
> 
> Encyclopedia Astronautica says Pioneer 5 made Magnetic Field and Radiation measurements, so maybe the probe is correct and @Morphisor244 needs to change his mission?

Encyclopedia Astronautica is a notoriously unreliable source, dont trust it! 

Anyway it does indeed have an micrometeorite experiment

https://nssdc.gsfc.nasa.gov/nmc/spacecraft/displayExperiment.action?spacecraftId=1960-001A



Experiment Name | Spacecraft Name | Principal Investigator(s)
-- | -- | --
Ion Chamber and GM Tube | Pioneer 5 | Winckler, John
Micrometeorite Spectrometer | Pioneer 5 | Dubin, Maurice
Proportional Counter Telescope | Pioneer 5 | Simpson, John
Search-Coil Magnetometer | Pioneer 5 | Greenstadt, Eugene

**Comment by Morphisor244** [comment]
The Pioneer 5 mission in HoSf was made before the Pioneer 5 parts were a thing, so I just added what experiments I deemed appropriate and the micrometeorite experiment isn't used that much at that point in the timeline, so it felt appropriate. There's a hundred MagScan parts stuff already everywhere anyway.

I don't mind changing it either way, the overall design choices of BDB should supersede any derivative work like my contracts pack.

**Comment by zorg2044** [comment]
Yeah I think swapping mag for MM just for variety is a good idea.

**Comment by CobaltWolf** [comment]
Another thing worth asking - what sort of heliocentric payloads come next? I assume they have mag scans.

**Comment by zorg2044** [comment]
Ok swapped to MM impacts
