### ISSUE TITLE
Light Wet Workshop Balance

### ISSUE THREAD

**Issue by debaker02** [CobaltWolf/Bluedog-Design-Bureau#991]
It just does not make it in JNSQ scale.  It needs mass similar to the S4B.  It set it around 3.124 (a bit more than the normal tanks), and it seems to work out.  I think this is a good balance, as it makes it earlier than the skylab and can launch on the C-1 like they proposed.

This is launching with a C-1 first stage to a 120*120 in JNSQ.

That seems to be ok, its a little extra dv if you were from a non-equatorial launch point it would have a bit extra.

**Comment by jsolson** [comment]
Saturn stuff is being completely redone. That said I'm not sure what your not able to do as-is. An light wet workshop orbits just fine on an S1 stage.

**Comment by debaker02** [comment]
Well i am using snacks; however in JNSQ i could not get it to orbit at all.  I flew the profile as prescribed, as in you need to loft a hydrolox stage like this.  But if its not a problem for you then i must be screwing up somehow.  I can share my craft, but if its all getting redone anyway.....i guess leave it.  I just changed the mass of the Light Wet Workshop to a bit more than the normal tanks and then a saturn 1b first stage flies it fine.  Thanks for looking into it!  Feel free to close out if your not gong  to change it.  No problem here.

**Comment by jsolson** [comment]
Supplies could certainly be the problem. I'd suggest just removing everything not fuel and send up a resupply mission after it's converted to a workshop. You could probably do that with the crew mission.
