### ISSUE TITLE
WaterfallFX compatiblity

### ISSUE THREAD

**Issue by zorg2044** [CobaltWolf/Bluedog-Design-Bureau#994]
Sea level SRBs will not be configured as there is no waterfall solution at time of this post. Vacuum solids can make use of these fx though.

Hypergolic Prefabs
- [x] Aerozine+NTO sea level 
- [x] Aerozine+NTO vac/NTO+MMH
- [x] IWFNA+UDMH/MON3+MMH (more white)
- [x] IRFNA+UDMH (reddish) vac hypergolic
- [x] HDA+UDMH (slightly different) vac hypergolic
- [x] Hypergolic vernier vac

SRB
- [ ] Vac solid
- [ ] Vac sep motor

Kero
- [x] Sea level
- [x] Sea level film cooled
- [x] vac
- [x] vernier vac
- [x] custom Vanguard plume
- [x] sea level vernier
- [ ] Custom F1 plume?
- [ ] exhaust?

Alcolox and HTP
- [x] Alcolox SL
- [x] hydyne SL
- [x] HTP exhaust

Cryo
- [x] Cryo ablative
- [x] Cryo Vac
- [x] Cryo SL 
- [x] Cryo SL ox rich
- [x] J2 aerospike 

Able
- [x] AJ10-37    ||37 IWFNA / UDMH || 118D IRFNA-III / UDMH||
- [x] AJ10-104  ||104, 118E IRFNA-III / UDMH||

Agena
- [x] 8096 4 different nozzle sizes (8048,8081,8096 IRFNA-III / UDMH || 8096 HDA, 9096B HDA 
- [x] 8096C MON+NTO

Apollo
- [x] SPS
- [x] LMAE
- [x] LMDE
- [x] Block 3 SPS
- [x] Block 5 SPS

Atlas
- [x] LR105
- [x] LR89
- [x] LR101

Atlas V
- [x] RD180

Centaur
- [x] RL10 (4 different nozzles including sea level version)
- [x] RL10 A4N
- [x] RL10 B2

Delta
- [x] RS68 (Ablative and Regen cryo), maybe custom exhaust fx.
- [x] AJ10 118F AZ50
- [x] AJ10 118K AZ50
- [x] AJ10 118X AZ50
- [x] TR 201 AZ50

Engines
- [x] E-1

Gemini
- [ ] Separation solids

Hexagon
- [x] Hexagon service engine

Jupiter
- [ ] Jupiter vernier
- [x] 6k
- [x]  45k

Mercury
- [ ] Posigrade motors
- [ ] Retro motors

ProbeExpansion
- [ ] AIMP - Star 13

Redstone
- [x] A7
- [x] A7 bare
- [x] A7 quad

Saturn
- [x] F1 (film cooling for earlier models, turbo for F1B)
- [x] J2
- [x] J2S
- [x] J2X
- [x] J2SL
- [x] J2 aerospike

Solids/IUS
- [ ] Orbus 6
- [ ] Orbus 21

Solids/Peacekeeper
- [x] PBV - MMH+NTO
- [x] OAM  - Vernier

Thor
- [x] LR79 (size adjustments might be needed for bell size variants)
- [x] LR101

Titan (need
- [x] LR91-3
- [x] LR91-3 sv
- [x] LR91-5 (need kero variants)
- [x] LR91-5 4v  (need kero variants) (needs better flare for hypergol version)
- [x] LR91-11  (need kero variants)
- [x] LR91-11 4v  (need kero variants)
- [x] LR87-3
- [x] LR87-5 (need kero variants)
- [x] LR87-11 (need kero variants)
- [x] LR87 single SL (need kero variants)
- [x] LR87 single vac (need kero variants)
- [x] LR87 LH2 SL
- [x] LR87 LH2 vac
- [x] Transtage

Vanguard
- [x] GE405 (need HTP exhaust)

Vega
- [x] GE405H (need HTP exhaust)

RCS (organised by full folder)
- [x] Able
- [x] Agena
- [x] Apollo
- [x] Atlas
- [x] Centaur
- [x] Delta
- [x] Gemini
- [x] Hexagon
- [x] Jupiter
- [x] Mercury
- [x] MOL
- [x] Redstone
- [x] Saturn
- [x] Skylab
- [x] Solids
- [x] Thor
- [x] Titan
- [x] Vanguard
- [x] Vega

ProbeExpansion

**Comment by computercat04** [comment]
WaterfallFX is still in WIP, so it may have some bugs.

**Comment by Pappystein** [comment]
https://i.imgur.com/c3eMR3t.jpg
I don't know if this is a Waterfall issue or an issue with the Agena8096 engine model/cfg itself (the base one not the separate 8096C)  But as you can see the Turbopump exhaust is running constantly even on a cold engine... and it is particle effects instead of waterfall
