### ISSUE TITLE
Decoupling from INON-ACS

### ISSUE THREAD

**Issue by Morphisor244** [CobaltWolf/Bluedog-Design-Bureau#995]
I have built myself a nice 3-stage Atlas-Vega craft, for sending off some probes on a far away mission.
However I ran into trouble after trying to separate the third stage from the second stage.
See these images for the build used: https://imgur.com/a/7VZsCPy

This attaches the Vejur interstage directly to the INON-ACS control unit (bluedog.CentaurD.Avionics), which is set to 0.9m mode. After failing to find a way to make this work, I tried using other decouplers/interstages instead - none would decouple from the INON-ACS when attached to it.
Note how in the second image, the interstage has already been decoupled, yet I am still applying RCS thrust from both above and below the interstage, showing that both sides are still fully attached and controllable.

Interestingly, the problem seems to disappear when changing the INON-ACS to the 1.875m node, so maybe there's some node shenanigans going on?

**Comment by jsolson** [comment]
It works fine for me. Identical build.

**Comment by dbandy13** [comment]
https://imgur.com/wi4AayY
Can also confirm no issues in release build. Didn't see any changes to that part in recent commits either

**Comment by Morphisor244** [comment]
Thanks for testing it out both. I can now confirm this is the result of a bad interaction with another mod. For some reason, the mod 'Recoupler' breaks the functionality as described. Why it does this on the smaller node version only, who knows. Nothing shows up differently in the cfg either, I only found out by removing it on a hunch. I'd never had issues with it before, but oh well that's another one off the list.
I'll close the issue.
